### ISSUE TITLE
Replace all default value usage with values from KVStore

### ISSUE THREAD

**Issue by rahulghangas** [celestiaorg/celestia-app#1032]
### Summary

Currently, the default values for min/max square size are hardcoded in `appconsts` module and these hardcoded values are used throughout the codebase as is

### Proposal

After #893 , these hardcoded values should be replaced with KVStore reads, specifically by caching them in a transient store and using them across all transactions in a block

**Comment by evan-forbes** [comment]
closing as this is outdated
