### ISSUE TITLE
QGB update internal contract ABI

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1047]
Currently, in the state machine, we're hard coding the QGB internal ABI to be able to pack and encode the data to be submitted to the QGB contract correctly:

https://github.com/celestiaorg/celestia-app/blob/8604be960b0565df66a6c4da79371f713ca62798/x/qgb/types/abi_consts.go#L16-L122

Doesn't it make sense to replace it with: 
```
qgbwrapper.QuantumGravityBridgeMetaData.ABI
```
?

cc @evan-forbes

**Comment by evan-forbes** [comment]
yeah that makes sense. I'm unsure of the reason why this added in the first place

**Comment by SweeXordious** [comment]
I guess it was added before we had the wrappers generated. I will make the changes, thanks a lot :+1:

**Comment by SweeXordious** [comment]
Aaah, it is for the private functions. These are not included in the ABI, thus, we need to add them manually. 
Issue no longer relevant, will close.
