### ISSUE TITLE
Consider deleting `AllSquareSizes`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1059]
## Context

After implementing square size independent commitments, it seems like celestia-app no longer needs:

https://github.com/celestiaorg/celestia-app/blob/24626ff8d00854d7e0027abcfdf50de1a2aee6a3/x/blob/types/square_sizes.go#L25-L27

## Proposal

Investigate if `AllSquareSizes` is still used. If not, remove it and related tests.

**Comment by evan-forbes** [comment]
:axe:
