### ISSUE TITLE
specs: update non-interactive default rules

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1063]
## Context

[ADR 006](https://github.com/celestiaorg/celestia-app/blob/24626ff8d00854d7e0027abcfdf50de1a2aee6a3/docs/architecture/adr-006-non-interactive-defaults.md) simplified the non-interactive default rules so the specs currently describe an outdated iteration of the non-interactive default rules.

## Proposal

- [ ] Align on non-interactive default rules post ADR 006 (see https://github.com/celestiaorg/celestia-app/pull/1003#discussion_r1031594488)
- [ ] Update the `specs-staging` branch

**Comment by evan-forbes** [comment]
moving the [convo](https://github.com/celestiaorg/celestia-app/pull/1003#discussion_r1031594488) from ADR009 here

> based on the above, my interpretation of the non-interactive default rules post ADR006 are:

If the message length is > k, then it must start on a new row.
If the message length is <= k, then it must begin at a location aligned with the largest power of 2 that is <= the message length.

@rootulp yeah, but to clarify I do think we should keep it to a single rule if possible, but perhaps that's just an opinion

> Messages must begin at a location aligned with the largest power of 2 that is not larger than the message length or k.

**Comment by rootulp** [comment]
I've re-read this statement several times and find it really difficult to grok:

> Messages must begin at a location aligned with the largest power of 2 that is not larger than the message length or k.

I think it may help readability if we articulate the scenarios as multiple statements. When written as one statement, the reader has to apply the rule to multiple scenarios (what happens when a message spans multiple rows? what happens when a message spans multiple rows only if placed after a message that occupies N shares at the beginning of the row? etc.)

I'm not strictly opposed to the one statement or strictly in favor of the two statements above but I find the previous and proposed non-interactive default rules really difficult to grok so would appreciate if we made them really explicit.

**Comment by evan-forbes** [comment]
can close with #1905
