### ISSUE TITLE
specs: `x/blob` module

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1067]
## Context

In a call with Informal, a takeaway from the audit was that we could have reduced the time for auditors to on-board if we had a specification for the `x/blob` module.

## Proposal

Write a spec with constraints, invariants, and properties for `x/blob`. Such a specification can be written in English. [`x/blob/README.md`](https://github.com/celestiaorg/celestia-app/blob/24626ff8d00854d7e0027abcfdf50de1a2aee6a3/x/blob/README.md) can be used as inspiration for such a spec but the README currently doesn't contain constraints, invariants, or properties which need to be investigated, understood, and documented.

**Comment by evan-forbes** [comment]
can close with #1906
