### ISSUE TITLE
rename `wrapper` package to `nmtwrapper`

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1069]
To emphasize that the wrapper used in trees generation is the NMT wrapper, we can rename the `wrapper` package to `nmtwrapper` so that it is obvious that the underlying tree is an NMT.

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/1039#discussion_r1031803820_

**Comment by Mihai22125** [comment]
Hello @SweeXordious, I'd like to work on this item. Can you assign it to me please?

**Comment by SweeXordious** [comment]
Sure, let me get a confirmation.
@evan-forbes should we start working on this now?

**Comment by evan-forbes** [comment]
I'm still undecided on this. tbh it feels not worth breaking everything downstream. Adding more docs feels like it would add more value imho

**Comment by SweeXordious** [comment]
Agreed, I checked closely, and the files are already reflecting that they're for NMT. Thus, more docs make sense :+1:
