### ISSUE TITLE
celestia-appd keys list error

### ISSUE THREAD

**Issue by VegeBun-csj** [celestiaorg/celestia-app#1075]
### Summary of Bug

1. when i run : `celestia-appd keys list`, it meets error.

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/39252213/204126225-adfa1032-4a7d-4b4f-8cd5-7b63b80af713.png">

2. Also，i have noticed the pr and issue in [448](https://github.com/celestiaorg/celestia-app/issues/448) and [553](https://github.com/celestiaorg/celestia-app/issues/530) and the suggestion in it. I followed it with https://github.com/celestiaorg/celestia-app/commit/ff2d92a98584b5f3f0fef0bdf595e21fdd808a97. 
the above error has been fixed with the same genesis file, but it meets new error:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/39252213/204126619-25fc78a1-5715-4199-894f-2045dee73c8e.png">

3. So, i think the first key list error is the binary bug. How can i solve all errors? Now, i can't select a correct version.

### Version

**celestia version**: v0.6.0
**os**: ubuntu 22.04
<img width="639" alt="image" src="https://user-images.githubusercontent.com/39252213/204126241-ca39957d-731a-4dec-80f1-fe2121ff9026.png">

### Steps to Reproduce

only need to git clone the celestia app repo, and checkout to v0.6.0 and get the binary.Run the binary

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mindstyle85** [comment]
you need to use --keyring-backend=test flag to list accounts

as for the error, you are not on v0.6.0 anymore if you tried that fix, so i suggest you rebuild the original v0.6.0 and clean up your data folder, make sure youre on the right genesis and it will work

**Comment by VegeBun-csj** [comment]
Are you sure the `--keyring-backend=test` exists?

**Comment by VegeBun-csj** [comment]
So, i want to know how can i fix the first bug? I need to run which command

**Comment by mindstyle85** [comment]
yes i am sure, you should import the key again, or create a new one and just add the `--keyring-backend=test` to the command, if you cant see if when you try to list the keys with: `celestia-appd keys list --keyring-backend=test`

**Comment by VegeBun-csj** [comment]
ok, it returns null with `[]`. But i have account in my local node
<img width="562" alt="image" src="https://user-images.githubusercontent.com/39252213/204523153-4d0a342f-5865-47a6-ad4d-0dbada191eaf.png">

**Comment by mindstyle85** [comment]
you dont have it in keyring named test, where it should be (thats the only one that works right now on mamaki). So as i said, import/create a key again and add the keyring flag to that command too...

**Comment by VegeBun-csj** [comment]
OK，thanks. I have solved it.

**Comment by VegeBun-csj** [comment]
Also, i want to know whether the celestia can be run on M1 Mac book pro with arm?

**Comment by mindstyle85** [comment]
i think it can but dont attempt it if youre not well versed in Mac's terminal and commands (plus you need to install the right packages to be able to build, like those we have in our docs for Linux)

**Comment by liamsi** [comment]
Looks like this was resolved and can be closed. Feel free to reopen in case this is not right.
