### ISSUE TITLE
Consider removing `EvidenceNamespace`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1081]
## Context

See https://github.com/celestiaorg/celestia-app/issues/1068#issuecomment-1331330996

Evidence was removed from the data square so we no longer need a reserved namespace for it. If we choose to remove the const in the `appconsts` package, we also need to update the specs.

**Comment by evan-forbes** [comment]
we should definitely still be able to do this, and we should before mainnet imo
