### ISSUE TITLE
Refactor creating the minimum square size to its own function

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1101]
this may benefit from an extracted helper so that it can be independently unit tested 

```go
// MinSquareSize returns the minimum square size that can contain shareCount
// number of shares.
func MinSquareSize(shareCount uint64) uint64 {
	return RoundUpPowerOfTwo(uint64(math.Ceil(math.Sqrt(float64(shareCount)))))
}
```

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/1089#discussion_r1041183072_

**Comment by noelukwa** [comment]
@evan-forbes  I would like to take this up.

**Comment by rootulp** [comment]
@noelukwa thanks for expressing interest! It looks like we have an extracted helper for this:

https://github.com/celestiaorg/celestia-app/blob/843a63f0d27470e2c34f6b7e70d5e0cff225e603/x/blob/types/payforblob.go#L178-L182

but there aren't unit tests in https://github.com/celestiaorg/celestia-app/blob/843a63f0d27470e2c34f6b7e70d5e0cff225e603/x/blob/types/payforblob_test.go so if you're interested, you could work on adding unit tests.
