### ISSUE TITLE
Test that we are only removing txs from the block at the max square size

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1102]
ideally we should only be hitting this if we're at the max squaresize. that might be something we want to add a test for in the future

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/1089#discussion_r1042916298_

this test could be as simple adding an additional check to an existing test that creates square not the max square size, and ensure that each transaction is getting included in the block.

**Comment by cmwaters** [comment]
Closing this as I believe it has been solved through this test: https://github.com/celestiaorg/celestia-app/blob/c121c285005c0b5d47542fd955fc5be688905e1a/pkg/square/builder_test.go#L86
