### ISSUE TITLE
Run fuzz tests on every PR

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1112]
we should have longer running fuzzing tests that run after a PR is merged to hopefully catch bugs such as that found in #1108

**Comment by evan-forbes** [comment]
consolidating #695 into this issue

**Comment by rootulp** [comment]
Is the proposal to change `make test-fuzz` to run after every PR instead of just nightly?

**Comment by evan-forbes** [comment]
yeah, just to hopefully help pinpoint any changes that might have caused the issue. If the fuzzing tests are too long however, we  can revert to running them locally

**Comment by rootulp** [comment]
Alternative idea with a similar outcome: run the fuzz tests on every PR as an optional check. Optional checks don't block the PR from merging and we'll get signal on whether the fuzz test passes on a per PR basis.

**Comment by evan-forbes** [comment]
sgtm
