### ISSUE TITLE
Proposal: make the namespace in PFBs optional

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1115]
The namespace selected by the user is already committed to in share commitments, because it is a commitment over encoded shares. The namespace is also already included in the blob transaction. This means that we don't actually need to include it in the PFB itself. However, teams have already expressed interested in having it included. 

Therefore, we might be able to make it optional. While this wouldn't have that much improvement in various different metrics of efficiency, it is compounded per blob posted. In the future, we could have a single PFB post many different blobs, so removing the namespace might actually be appealing depending on how many different blobs are posted per PFB.

**Comment by evan-forbes** [comment]
see relevant comment to the downside of doing this https://github.com/celestiaorg/celestia-app/pull/1154#discussion_r1063318450

**Comment by adlerjohn** [comment]
If the namespace ID isn't in the transaction then it would require an additional proof attached to each tx to prove that it pays for a blob in a particular namespace.

**Comment by evan-forbes** [comment]
> If the namespace ID isn't in the transaction then it would require an additional proof attached to each tx to prove that it pays for a blob in a particular namespace.

do you mind elaborating more on this? specifically on how this new proof is different from the message inclusion proof

**Comment by adlerjohn** [comment]
It wouldn't be different. But e.g. a partial node only downloads transactions, not blobs.
