### ISSUE TITLE
QGB endpoints MsgValsetConfirm and others showing in v0.10.1

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/celestia-app#1117]
### Summary of Bug

When running celestia-app with rosetta api running on port :8080, and then running `rosetta-cli view:networks`, some interesing operations are shown as accessible from Rosetta, including:

"/qgb.MsgValsetConfirm" and "/qgb.MsgDataCommitmentConfirm"

Can share a repo where this can be reproduced accurately. @evan-forbes requested I write up a ticket.

### Version

v0.10.1

### Steps to Reproduce

Message me for private repo

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
cc: @rach-id

**Comment by rach-id** [comment]
I kept looking where would this come from but then realised it's an issue from 2022. I don't think this is still the case, as those endpoints no longer exist. Closing.
