### ISSUE TITLE
Add test for address validation for account emitted in event

### ISSUE THREAD

**Issue by rahulghangas** [celestiaorg/celestia-app#1129]
### Summary

Add test to validate the signer's address' encoding emitted in a pay for blob tx

Linked - #1030

**Comment by rootulp** [comment]
OMG how did I miss this. This test would've caught [this bug](https://github.com/celestiaorg/celestia-app/issues/2781) pre-mainnet. Fortunately [this PR](https://github.com/celestiaorg/celestia-app/pull/2793) includes a test.
