### ISSUE TITLE
Proposal: Remove the gas limit arg from the canonical `SubmitPayForBlob` api

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1133]
We are currently including the gas limit as an argument to the `SubmitPayForBlob` function. While specifying the gas limit is important, it differs from how we modify other equally important transaction options. I'm suggesting that we use the same mechanism for changing a transaction option for everything, which is to use the `types.TxBuilderOption` variadic arg in the same function.

https://github.com/celestiaorg/celestia-app/blob/c16d6e7fd984184d2aba44c1e8c4a5aadfe36aef/x/blob/payforblob.go#L16-L27

kinda related: in the release that includes the upcoming refactor to include multiple blobs per PFB, we are going to have to change the canonical interface for submitting data on chain. While we're at it, I figured we might want to include other breaking changes.

cc @renaynay @distractedm1nd

**Comment by rootulp** [comment]
We already have a [TxBuilderOption](https://github.com/celestiaorg/celestia-app/blob/b6e265133788dc45e94284dcf72be4b0ca4b04c0/x/blob/types/builder_options.go#L12) so it seems safe to remove the [`gasLim`](https://github.com/celestiaorg/celestia-app/blob/b6e265133788dc45e94284dcf72be4b0ca4b04c0/x/blob/payforblob.go#L22) parameter.
