### ISSUE TITLE
How to determine if a share is namespaced padding?

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1136]
## Context

Unlike tail padding or transaction tail padding shares, a client can't use the namespace of a namespaced padding share to determine that the share is padding. In order for a client to determine if a namespaced padding share contains significant data, it must download and parse all of the preceding shares in the data square until it reaches the first share of the preceeding blob. The client can then use the sequence length in that share to determine which bytes of data are part of the blob and which are part of namespaced padding and can therefore be ignored.

## Proposal 

If we want clients to be able to download and parse a namespaced padding share without the need for downloading additional shares, we may consider: reserving one bit in the info byte to indicate if this is a namespaced padded share. If the bit is set to `1`, all remaining bytes are guaranteed to be `0`. The client can then treat the share as padding. For completeness: the sequence start indicator in the info byte would be set to `0`. The sequence length would be zeroed out.

**Comment by rootulp** [comment]
Tagging @evan-forbes @adlerjohn @musalbas for feedback

**Comment by rootulp** [comment]
I'm going to spin out an issue to update the specs with the implemented design of namespaced padding shares and modify this issue to contain the proposal a revised design of the namespaced padding share format.

**Comment by musalbas** [comment]
Can't the client also know that a share is a padding share by pre-computing the hash of padding shares within a namespace?
cc @adlerjohn

**Comment by musalbas** [comment]
>The client can't unless it knows which shares are not-padding, since there's nothing in the padding shares to indicate they're padding. This requires information that's not in the padding shares in question.

Can't they know which shares are not-padding if the share hash does not match the pre-computed root for padding in that namespace?

**Comment by musalbas** [comment]
>If we want to support rollup nodes that don't look at PFB transactions at all, then yes I think you'll need to add metadata at the beginning of the padding to say how many shares are padding.

I don't think you do. Consider a model where a full storage node does not send padding shares to a rollup light node over the wire, but simply tells them "hey, shares between index x to y are padding, and here's the sub-tree root of those shares". The light node can then recompute the sub-tree root of those padding shares itself, to authenticate that statement. Do you agree?
