### ISSUE TITLE
Rename wirepayfordata.go file

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1138]
I think this was review feedback, but we forgot to incorporate it when refactoring to remove the malleation step and `WirePayForBlob`. This [file](https://github.com/celestiaorg/celestia-app/blob/main/x/blob/client/cli/wirepayfordata.go) is still name `wirepayforblob`. We should rename it to something else.

**Comment by rootulp** [comment]
Proposal to rename: x/blob/client/cli/wirepayfordata.go => x/blob/client/cli/payforblob.go

This has the downside that it introduces a naming collision so it's harder to <kbd>CMD</kbd>+<kbd>P</kbd> to the file of based on filename:
- x/blob/client/cli/payforblob.go
- x/blob/payforblob.go
- x/blob/types/payforblob.go

**Comment by evan-forbes** [comment]
that works for me, or if we don't want to add to the collisions, then we can simply name it pfb_command, payforblob_command, or I'm even okay with just command. whatever works

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/1288
