### ISSUE TITLE
Proposal: make `MsgPayForBlob.Size` the number of shares used instead of bytes used

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1139]
We almost exclusively measure in terms of shares instead of bytes, so we might want to switch to shares used instead of bytes used for the `.Size` field of `MsgPayForBlob`. 

It would have the benefit of saving a byte or two per size per PFB and save a few calculations in the implementation, but might make things more confusing.

**Comment by rootulp** [comment]
Pros:
- may save a few bytes in the message sent over the wire

Cons:
- it is possible to determine the # of shares needed from the original blob size. However, it is not possible to determine the original blob size from the # of shares used. In other words, number of shares used is a less precise value than # of shares needed.

**Comment by adlerjohn** [comment]
If we don't know the exact number of bytes, then the reader of the share doesn't have any immediate way of knowing which bytes are padding zeroes vs which are actually supposed to be zero, at the end of the blob.

**Comment by rootulp** [comment]
I don't think this proposal is possible to implement without a resolution to the problem @adlerjohn pointed out so closing as won't do.
