### ISSUE TITLE
Validate square size in PrepareProposal and ProcessProposal

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1150]
## Proposal

- [ ] Add a check to ProcessProposal  that validates the proposed block's square size is within the bounds acceptable for a square. https://github.com/celestiaorg/celestia-app/blob/1b80b94a62c8c292f569e2fc576e26299985681a/app/process_proposal.go#L24
- [ ] [optional] add the same check to PrepareProposal: https://github.com/celestiaorg/celestia-app/blob/1b80b94a62c8c292f569e2fc576e26299985681a/app/prepare_proposal.go#L16 This check is optional because it is already performed in https://github.com/celestiaorg/celestia-app/blob/1b80b94a62c8c292f569e2fc576e26299985681a/pkg/da/data_availability_header.go#L54 but it may be beneficial to explicitly add the same set of checks in prepare and process proposal

**Comment by evan-forbes** [comment]
to clarify a bit, this would simply be adding an explicit check, as the square size is already being enforced in both prepare and process proposal

**Comment by evan-forbes** [comment]
closing because the square size is deterministic

**Comment by rootulp** [comment]
Square size is deterministic but the checks proposed in this issue still seem helpful for clarity.
