### ISSUE TITLE
uint32 for BlobSize

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1153]
changing to uint32 makes sense to me and is more efficient, iirc, it was uint64 just to mirror the specs

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/1147#discussion_r1055618331_

**Comment by evan-forbes** [comment]
this should be a simple change, and creates a maximum message size of 4GB, which should be plenty for a long long time.

However, it is breaking, so perhaps we should try to fit this in before the next major upgrade or the feature freeze at the end of the month
