### ISSUE TITLE
Put all PFBs in a reserved namespace

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1173]
Per synchronous discussion, we have agreed to put all PFB transactions in their own namespace. This is mainly to make parsing the PFB transactions significantly easier due to them otherwise requiring to be decoded using both gogoproto and proprietary cosmos-sdk code.

There are a few different ways that we could do this, but ideally we would be able to remove the the typeID tag from the index wrapped transactions. However, that might not be possible without doing something similar to #1105, but removing the metadata before sticking it onchain (unsure of this atm)

**Comment by rootulp** [comment]
> ideally we would be able to remove the the typeID tag from the index wrapped transactions

What is the motivation behind removing the typeID tag from index wrapped transactions? One benefit I see is reducing one byte per PFB transaction but that seems like a marginal benefit.

**Comment by evan-forbes** [comment]
> What is the motivation behind removing the typeID tag from index wrapped transactions? One benefit I see is reducing one byte per PFB transaction but that seems like a marginal benefit.

yeah, pretty much. It might avoid some duck typing, but can definitely be separated from the main change

**Comment by rootulp** [comment]
There are two compact share sequences: one for ordinary transactions and one for PFB transactions. The last share of ordinary transactions contains padding to fill the last share but there are no padding shares between the share sequences. There is padding after the PFB transactions share sequence and before the first blob.
