### ISSUE TITLE
Duplicate `tailPaddingShare`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1176]
## Problem

There exist two slightly different implementations of a tail padding share

https://github.com/celestiaorg/celestia-app/blob/b1113f8ac55edf0466904e8922b5dd77e8e0d89b/pkg/shares/share_splitting.go#L127-L133

https://github.com/celestiaorg/celestia-app/blob/b1113f8ac55edf0466904e8922b5dd77e8e0d89b/pkg/da/data_availability_header.go#L168-L173

## Proposal

Align on one implementation (related: https://github.com/celestiaorg/celestia-app/issues/1175) and then remove one implementation

**Comment by evan-forbes** [comment]
woah nice catch, I'll defer to you as to which should be the correct one. I can see reasoning for both, but can't see a benefit of one over the other

wdyt?

**Comment by rootulp** [comment]
I think we should include the share version format in the tail padding share so https://github.com/celestiaorg/celestia-app/blob/b1113f8ac55edf0466904e8922b5dd77e8e0d89b/pkg/shares/share_splitting.go#L127-L133 seems correct to me. The rationale for including the share version format is so that we can make a breaking change to the tail padding share and signal the change via a new share version format number. A change to the tail padding share seems unlikely but I don't see a downside to including the info byte.

**Comment by evan-forbes** [comment]
:judge: it is decided then
