### ISSUE TITLE
Consider removing constants: `MinShareCount` and `MaxShareCount`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1183]
to generate the minimum data availability header, but we could probably just remove and calculate the value there if we want to remove one constant.

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/1177#discussion_r1062909867_

**Comment by Chirag018** [comment]
Hey @rootulp, if it is not assigned to anyone, would like to work on this
