### ISSUE TITLE
Remove Estimate Square Size

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/celestia-app#1186]
### Summary

Instead of estimating the square size and then building the square in that square, you could build the square in `MaxSquareSize`and then reduce the square until it is small enough. 

One reduction of square size can happen if the square is only filled to 1/4th of the square. Then you can divide the row in half and iterate. The resulting square should still be a valid square. without changing the shares. The commitments, for example, are square size-independent, so they will not change. The index of the blobs, for example, will stay the same as well.

Here is an example of how a square of 16x16 might reduce to 4x4. The middle step can be skipped computationally and is only here for visualisation purposes. 

![image](https://user-images.githubusercontent.com/99758629/211039684-01c91062-6073-4f4f-ae36-f45823ebd585.png)

### Problem Definition

- Code Reduction 
- The Validators do not need to know which square to build as they will deterministically pick the smallest one given an indexed list of txns 

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Would it be possible to use some bisection method to approach the smallest square size?

**Comment by rootulp** [comment]
I like the idea! `estimateSquareSize` is currently used to get the index of the start of non-reserved shares. Without this estimation, we encounter a feedback loop where: adding one more blob to the square => adds one more transaction to the reserved namespace => which pushes the nonreserved share start => which modifies the index in the shares already written to the reserved namespace.

https://github.com/celestiaorg/celestia-app/blob/5f8b39b4cb7ab0a9083b97f2a20cae7a2cc1a1c5/app/estimate_square_size.go#L11-L18

**Comment by nashqueue** [comment]
> Would it be possible to use some bisection method to approach the smallest square size? 

You can do that via a formula.

You need to know how many rows are filled. If the square is of size k and r rows are started, then you can reduce the block size by x.
x := log_4(RoundUpToTheNextPowerOf4( k / r )

**Comment by nashqueue** [comment]
Ok new idea to combat the feedback loop. 
As I understand correctly, the problem lies in the fact that if you add a new PFB Transaction shares and Blob shares will move, and you will need to update all the indexes that follow those shares. Changing the initial inclusion. 
To combat this, instead of saving the index, you could save the spacing to the next blob. Happy to change the name "spacing" for better context. 

As I mentioned in ADR 13 in the first table, each range of blob sizes has a maximum possible padding that comes before it. In other words, each range shares the same `index multiple` where the blob starts. For context this `index multiple` is currently `MinSquareSize`. 

Now having an ordered linked list of blobs will be sufficient to generate a valid square, as we can derive the structure from the length of the blobs. 

The problem now is the function `FitsInSquare` as we don't know if the square is already full or not. Summing up all the indexes derived from the linked list will tell us if the block can be added. 

The Feedback loop does not exist in this case, as we don't move any share index. We only reference the next blob.

**Comment by cmwaters** [comment]
If we constrain the amount of transactions by the block size and not square size, we know up front how many transactions there are and thus we just need to calculate what the lowest square size is that fits these transactions.

I'm still unsure what the best direction to take is though. If you constrain by block size then you could have a scenario where there are transactions that take up 1025 shares which means you need a square that is 64 x 64. This is 3071 worth of tail padding. It would be far more efficient then if the proposer was to remove the lowest valued transactions so there was 1024 or less of shares and it could fit in a 32x32 block

**Comment by evan-forbes** [comment]
to add to the feeback loop issue, (more details in the non-interactive defaults [ADR006](https://github.com/celestiaorg/celestia-app/blob/main/docs/architecture/adr-006-non-interactive-defaults.md#detailed-design)), the original reason of picking a compact share start index when estimating was not just for the reasons Rootul mentioned, but also because of the rampant usage of varints by protobuf. when we try to add the share index after the fact, the number of bytes used depends on the index, so calculating an exact starting point requires recursively adjusting and recalculating share indexes (totally doable, just didn't include in the original PR https://github.com/celestiaorg/celestia-app/pull/1089)

**Comment by cmwaters** [comment]
One of the problems we have at the moment is that we haven't yet decided on the non-interactive defaults. What I mean by that is that there seems to be 2 or 3 current proposals for how the layout of the squares should be done

**Comment by nashqueue** [comment]
> One of the problems we have at the moment is that we haven't yet decided on the non-interactive defaults. What I mean by that is that there seems to be 2 or 3 current proposals for how the layout of the squares should be done.

This must be a confusion as I did 4 Proposals in quick succession. Maybe we should add the Status at the top of the file. 
- ADR 008 Status accepted
- ADR 009 Status accepted (current non-interactive default rules) 
- ADR 010 Status declined of the things core-app would be affected on
- ADR 013 Status proposed

**Comment by nashqueue** [comment]
> but also because of the rampant usage of varints by protobuf. when we try to add the share index after the fact, the number of bytes used depends on the index

Thinking out loud: 

A varint can be of size between 1 and 10 bytes. Each byte can hold 7 bits of information, meaning you can fit in 2⁷ numbers.
2⁷ = 128. The biggest index currently is 128*128 = 2⁷ * 2⁷, which means we will at a maximum of 2 bytes for the index. If we increase the block size more, let's say three more times, we will have 2¹⁰ * 2¹⁰, which is 2²⁰ < 2²¹, so it will fit in 3 bytes of the varint.

Napkin math: let's say to have the biggest impact of varints in a block would be 1/2 half PFB txns and 1/2 1-sized blobs. Meaning we have 128 * 64 = 2¹³  possible varints bytes as one is the minimum. That in shares is 2¹³ / 512 = 2¹³ / 2⁹ = 2⁴ = 16 shares. 
Hm, seems quite a bit to keep in reserve. 

I think if we keep a reference from the blob to the pfb in the linked list, there is a way to overcome those 16 shares of reserve in an iterative way.

**Comment by evan-forbes** [comment]
> I think if we keep a reference from the blob to the pfb in the linked list, there is a way to overcome those 16 shares of reserve in an iterative way.

if I'm understanding correctly, I think we do this already when preparing the proposal. Mind elaborating how this is different from our "[parsedTx](https://github.com/celestiaorg/celestia-app/blob/9707ef0930260d6d2730119cf8ecc49c59711160/app/parse_txs.go#L11-L20)" and "[trackedBlob](https://github.com/celestiaorg/celestia-app/blob/9707ef0930260d6d2730119cf8ecc49c59711160/app/write_square.go#L12-L37)" structs here and here?

**Comment by cmwaters** [comment]
There is additional overhead in proto encoding than just the varint for the share index. For example, the `bytes` field in the `IndexWrapper` is length prefixed.
