### ISSUE TITLE
Reduce estimated padding 

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/celestia-app#1200]
### Summary

Currently, we estimate the padding by 2 fold. 

https://github.com/celestiaorg/celestia-app/blob/5f8b39b4cb7ab0a9083b97f2a20cae7a2cc1a1c5/app/estimate_square_size.go#L32-L35

We can reduce this estimation to 0,375 as this is the maximum amount of padding that can be created without tail padding following the current non-interactive default rules. This was shown in my calculations of [ADR 009 ](https://github.com/celestiaorg/celestia-app/blob/main/docs/architecture/adr-009-non-interactive-default-rules-for-reduced-padding.md#5-what-is-the-worst-constructible-block-with-the-most-amount-of-padding-with-old-and-new-non-interactive-default-rules). 

### Proposal

	totalSharesUsed := float64(txSharesUsed + blobSharesUsed)
	totalSharesUsed *= 1.375
	minSize := uint64(math.Sqrt(totalSharesUsed))
	squareSize = shares.RoundUpPowerOfTwo(minSize)

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Nice! Wouldn't it be 1.375 though?

**Comment by nashqueue** [comment]
Yes that's correct I changed it in the proposal.

**Comment by evan-forbes** [comment]
nice!

this issue can supercede #682 https://github.com/celestiaorg/celestia-app/issues/682#issuecomment-1369082136

**Comment by rootulp** [comment]
I'm concerned 1.375 isn't guaranteed to be the worst case padding given it was arrived at based on observation. Is there a formal method to prove the worst case padding? If not, is it also 1.375 in square sizes other than 32?

**Comment by nashqueue** [comment]
Ok let me try to prove it to you.
What we are looking for is a sequence of blobs and padding to create the most amount of padding. 
Given a blob of size b there will be padding p that can come before that. p is bounded by the size b. 
The max worst padding is $${p_{b}}_{max} = 2 ^{\lceil{\log_4{b}}\rceil} - 1 $$

![image](https://user-images.githubusercontent.com/99758629/212061225-2765c605-a5ec-4f84-95f1-8622fa7ccfa1.png)

You can verify this by looking at the ranges in ADR 13 and confirming the upper and lower bounds of the ranges.

The biggest ratio of padding to blobs + padding is for the blob size 5. You can see this graphically or in ADR 13 in the table. 

![image](https://user-images.githubusercontent.com/99758629/212063652-43856b57-43b1-4acb-a97b-e0eea591019b.png)

We now know that 0.375 is the worst ratio for a single blob. But maybe if we combine blobs, then this ratio will increase.
This can't be true, as that would mean that another blob has a bigger ratio which would contradict the previous observation. This sets 0.375 as the upper bound. 

Now we can also show that in the other direction, maybe it will **decrease** and the maximum ratio is smaller than 0.375 in the worst case. 

This in fact, could be true for different seqeunce lengths. But for all square sizes > 2, you can show this by the construction of the sequence [1b][3p][5b]...[3p][4b] . By adding [3p][5p] in the middle of the sequence, you will have a sequence length that is a multiple of 8. All square sizes > 2 are dividable by 8, so you can construct such a sequence for every square. 

Here are some examples: 

![image](https://user-images.githubusercontent.com/99758629/212069136-e57c9409-c8d7-42ae-a4f8-8a99a69d2975.png)

**Comment by rootulp** [comment]
Thanks for the detailed walkthrough. Can you please help me understand the example below where

T = transaction share
B = blob share
_ = padding

```ascii
T___BBBB
B___BBBB
B___BBBB
B___BBBB
B___BBBB
B___BBBB
B___BBBB
B___BBBB
```

squareSize = 8
sharesInSquare = 64
txSharesUsed = 1
blobSharesUsed = 39
txSharesUsed + blobSharesUsed = 40
padding = 24

40 * .375 = 15 but 15 is less than the number of padding shares in the square

**Comment by nashqueue** [comment]
So .375 is the **ratio** of padding / (padding + blob), the percentage of the block that is padding. In this case, the ratio is 24 / 64 = 0.375. 

txSharesUsed + blobSharesUsed * **1**.375 = 55 is with how many total shares we will end up. This should have been >= 64. 

Very good that we are going through this, as we mixed up the percentages. It's not 1.375, but to get to a ratio of 37.5%, we actually need to multiply by 1.625. 

The formula should be txSharesUsed + blobSharesUsed * 1.625 + 3 = 67,375

Seeing that the fuzzer did not break in the average case, we are still overestimating.

**Comment by evan-forbes** [comment]
> Seeing that the fuzzer did not break in the average case, we are still overestimating.

see comment on fuzzer https://github.com/celestiaorg/celestia-app/pull/1211#issuecomment-1384701620 also #1102

**Comment by nashqueue** [comment]
I did some basic tests regarding blob + worst case padding and the average ratio of worst-case padding looks around to be 1.312 % . The current new change assumes it at 37.5%. I think that there is no point in going for the worst case. As this would mean that the validator wants this code to overestimate. (less reewards) . As he wants to maximize the reward, there is no point in him doing that and censoring other transactions that would decrease the padding in between, to get the specific construction of [3]5[3]5[3].... If he wants to censor transactions he can send a small block. So in general, I think this function should be estimating rather than overestimating, so we would get the nice property that if we only have ~ 1/4 of `SquareSize` we don't go over it, even though we can but stay in the block size lower to reduce blocksize at the cost of rarely kicking out some Txs.

**Comment by nashqueue** [comment]
Interestingly I just saw that the constructions of the squares had a tiny mistake. This does not make a huge change to the formula or the proof. Before the last blob, as it is only size 4, will create padding of size 1, as the MinSquareSize of this blob is 2.
