### ISSUE TITLE
Block producer will not include any blobs in the block if there are over 20,000 txs in their mempool

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1209]
As pointed out by @nashqueue, the mechanism that estimates the first compact share will begin to pick a value that attempts to fit all of the transactions in the block. The current estimation algorithm has no way of changing the first compact share value, and will continue to layout the square using that value. While this is not a critical issue for "normal" conditions (<10000 transactions per block), this starts becoming an issue if we have tens of thousands of transactions in the block, because the first compact share will be so large that we are unable to pack the square efficiently. 

While unlikely given the mempool default value for max txs is 5000, if we have over 20,000 txs in the mempool, then this becomes a critical issue, as we will not be able to fit any blobs in the square at all. This means that no PFB transaction will be allowed in either, only normal cosmos-sdk transactions. There could be a scenario where all validators have >20,000 PFB transactions in their mempool, and the chain would cease putting blobs on the chain!

The best solution to this issue would be to refactor the square layout process, to be able to change the initial index picked for the first compact share. This would allow for a more consistently efficient packing of square under extremely high loads.

A quick temporary solution would be to limit the number of transactions included in the block. If we set the value to roughly a quarter of the current max square size (roughly 5000 PFB transactions), then we will avoid the worst scenario described above.

**Comment by evan-forbes** [comment]
can close with #1210

**Comment by nashqueue** [comment]
I think you could recreate the same issue if the first blob of the list of PFBs is very big. You will not get empty blocks, but you will get as much empty space as the limited amount of Txns * MaxOverhead. For maximum Damage, the first PFB should maximise the content of (nonreserveStart to end of Square).

**Comment by evan-forbes** [comment]
yeah, the current mechanism of only estimating the non reserve start once is far from perfect, but the goal for this issue was to add extra protections against the worst case scenario of no blobs being included.
