### ISSUE TITLE
Adopt a deterministic square construction mechanism

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1214]
### Summary

Have some function `square.Construct(...` that takes an ordered list of transactions and builds a square (`[]Share`) such that all processes performing that function with the same ordered list of transactions would produce the same square.

### Problem Definition

In the current design, the proposer is at liberty to design a square in whatever way they like and all other validators simply interpret it from the block. This gives the proposer the ability to create unnecessarily large squares which may only contain 1 or 2 transactions and puts unnecessary strain on light clients. This is a part of the protocol that should be behind the curtain and that block proposers don't need to be aware of. They should only be concerned with transaction inclusion and ordering. 

### Proposal

The block data over the wire should just be an ordered list of transactions. Both the proposer and all other nodes deterministically build the same square using a method like `square.Construct(txs)` and then compare using the data root. This means that both `ProcessProposal` and `PrepareProposal` use this function and validators will prevote nil if the block does not follow the square construction rules.

This does not effect how blocks are persisted to disk nor the wrapping process for PFB transactions. That remains the same. 

This also has the added benefit that it makes compact blocks far easier and more effective because now a block can be communicated as simply an array of hashes. 

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
very related to https://github.com/celestiaorg/celestia-app/issues/935 (also [specific comment](https://github.com/celestiaorg/celestia-app/issues/935#issuecomment-1377823587) discussing some of the reasoning behind the original design)
