### ISSUE TITLE
maxWrappedTxOverhead overestimation 

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/celestia-app#1216]
### Summary

The Function `maxWrappedTxOverhead` overestimates, creating a `nonreserveStart` which is far into the block. 

https://github.com/celestiaorg/celestia-app/blob/5f8b39b4cb7ab0a9083b97f2a20cae7a2cc1a1c5/app/estimate_square_size.go#L76-L90

A better estimation will be more complicated. This could also have an effect on https://github.com/celestiaorg/celestia-app/issues/1209

### Problem Definition

While doing napkin math in https://github.com/celestiaorg/celestia-app/issues/1186#issuecomment-1377438879 I looked at `maxWrappedTxOverhead`. Putting in 128 as square size, the function gives us 15 bytes of overhead per transaction. 

This means that using the napkin math above, where I only did 1 byte for the overhead and got 16 shares, we would get 16*15 = 240 shares that we postpone `nonreserveStart` if we have 128 * 64 transactions ( half the block). 

This could overestimate the `nonreserveStart` as that many transactions with `maxWrappedTxOverhead` are clearly not possible. 

On another note, as I was reading the comment, the function might take so long because of the huge slice creation. Maybe a quick table could be enough if it creates performance issues. 

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nashqueue** [comment]
Given a blob index and the transaction bytes, the additional wrapping bytes will always be the same, right?

**Comment by cmwaters** [comment]
> Given a blob index and the transaction bytes, the additional wrapping bytes will always be the same, right?

Yes (so long as the proto definition also remains the same)

This is my source: https://developers.google.com/protocol-buffers/docs/encoding

**Comment by nashqueue** [comment]
Thinking out loud : 
Assumption: We do this wrapping, because we send the Tx over the wire to the other validators so they know the index in advance.
If we have a determenistic block building process 
-> You don't need to send the index
-> You don't need to wrap it
-> You can add a fixed length byte position before PFB transactions in the DataSquare
-> You save bytes (proto overhead) and you don't have the feedback loop issue anymore (fixed length bytes)
-> You can build the square more efficient / determenistic / better estimation
