### ISSUE TITLE
Should `genOrigRowShares` consider padding between the last transaction and the first blob?

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1226]
Currently, it looks like `pkg/proof/proof.go` doesn't account for padding between the last transaction and the first blob. Since the first blob must start at an index that is aligned with its BlobMinSquareSize, I expect there to be padding in-between the last transaction and the first blob.

https://github.com/celestiaorg/celestia-app/blob/7ad3df7248b406ffb5d22a36628c3455d2f9b78a/pkg/prove/proof.go#L161-L173

**Comment by evan-forbes** [comment]
yes, it needs to, but I'm not sure we will use that implementation in the future. ref https://github.com/celestiaorg/celestia-app/issues/703
