### ISSUE TITLE
Document token filter middleware

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1267]
I would also add here: documenting of IBC's token filter middleware

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/issues/1257#issuecomment-1397043029_

in #1219, we added a token filter to prevent tokens outside of the native one to be transfered via IBC, this change needs to be documented in:
- [ ] the specs
- [ ] developer focused documentation such as our doc site
- [ ] internally, such as readme for https://github.com/celestiaorg/celestia-app/tree/main/x/tokenfilter or a small ADR

**Comment by cmwaters** [comment]
linking https://github.com/celestiaorg/docs/pull/518 as it is relevant
