### ISSUE TITLE
Should we reserve byte(s) in the namespace IDs for versioned namespaces?

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-app#1282]
Right now we have a reserved info byte in shares with version information, in case we want to change the share format in the future.

Shall we also add a reserved info byte in namespace IDs for version information, in case we ever want to have version-specific namespaces? This would be relevant for example if we wanted to change the padding scheme in namespaces, without breaking backwards compatibility with existing namespaces.

Related to https://github.com/celestiaorg/celestia-app/issues/1136

**Comment by evan-forbes** [comment]
This sounds like a good idea to me. I also don't think it would super difficult to add, at least to celestia-app, but we still likely won't be able to finish this for feature freeze. Finishing it soon after is definitely an option though.

one slight modification could be to combine the info bytes into a single one at the beginning of the share.

**Comment by musalbas** [comment]
>one slight modification could be to combine the info bytes into a single one at the beginning of the share.
This would prevent some use cases, such as reading a blob in the middle of a namespace, because the bit for the start share indicator would no longer be useful.

>+1 to the idea of combining the version information in the current info byte with the proposed version info for the namespace. I think the version in the current info byte can be used to version changes to the share format with the exception of a change to the length of the namespace.
To be clear, the idea is not to combine any version information. I'm proposing a totally separate, additive, feature of reserving bytes in namespace ids.

>If such a change doesn't involve a change to the namespace length, I think this could be handled by the current info byte. Example:

I'm not following here. How would this work for non-reserved namespaces? If you change the padding scheme for an existing non-reserved namespace, it would be backwards-incompatible.

**Comment by rootulp** [comment]
> If you change the padding scheme for an existing non-reserved namespace

I think this refers to padding in-between blob shares (a.k.a namespaced padding) and not padding at the end of a share but can you please confirm? 

If we change the scheme of namespaced padding I expect that change to be backwards-incompatible and therefore necessitate a hard fork. I don't see how a namespaced padding scheme change can be communicated in the version byte inside a share because it applies across a data square and there is no guarantee that an entire data square is composed of shares with one particular version (unless that is also part of the hard fork). In other words, can the rules related to padding scheme of the square be determined based on the block height rather than the version byte inside a share?

**Comment by musalbas** [comment]
>I think this refers to padding in-between blob shares (a.k.a namespaced padding) and not padding at the end of a share but can you please confirm?

Yes.

>If we change the scheme of namespaced padding I expect that change to be backwards-incompatible and therefore necessitate a hard fork. I don't see how a namespaced padding scheme change can be communicated in the version byte inside a share because it applies across a data square and there is no guarantee that an entire data square is composed of shares with one particular version (unless that is also part of the hard fork). In other words, can the rules related to padding scheme of the square be determined based on the block height rather than the version byte inside a share?

The proposal is to add version bytes to namespace IDs, not shares, so that different namespaces can have different inter-blob padding formats.

**Comment by rootulp** [comment]
Here's my best effort understanding of this proposal. At time `t=0` the only supported namespace version is 0

```go
blobA := []byte{
        0, // namespace version
	1, 1, 1, 1, 1, 1, 1, 1, // namespace ID
        ...  // blobA data
}
blobB := []byte{
        0, // namespace version
	1, 1, 1, 1, 1, 1, 1, 1, // namespace ID
        ... // blobB data
} 
```

then padding between blobA and blobB is guaranteed to place blobB at an index that conforms to the current non-interactive default rules (i.e. an index aligned with `BlobMinSquareSize(blobB)`). 

At time `t=1` namespace version `1` is introduced that modifies the non-interactive default rules (e.g. ADR 013). If blobA and blobB from above are published at `t=1`, the padding between them conforms to the previous non-interactive default rules. But now we also support:

```go
blobC := []byte{
        1, // namespace version
	1, 1, 1, 1, 1, 1, 1, 1, // namespace ID
        ...  // blobC data

}
blobD := []byte{
        1, // namespace version
	1, 1, 1, 1, 1, 1, 1, 1, // namespace ID
        ... // blobD data
} 
```

where the padding between blobC and blobD is potentially reduced. Notably, roll-ups that use namespace `1, 1, 1, 1, 1, 1, 1, 1` must opt-in to writing and reading from the new namespace version + namespace. 

Questions:
1. Are there scenarios where we want blocks to be constructed with two different versions of the non-interactive default rules? This may prohibit the deterministic square construction idea.
2. Are there any downsides associated with splitting up namespaces across the square? In other words, blobA and blobB will be near the beginning of the square but blobC and blobD will be placed after all shares with namespace version `0`. Does this pose a penalty for roll-ups interested in namespace `1, 1, 1, 1, 1, 1, 1, 1` regardless of the namespace version?

**Comment by musalbas** [comment]
>Are there any downsides associated with splitting up namespaces across the square?

I don't think so. For a rollup to use a new namespace version, they have to upgrade/fork, and if they do that, they might as well abandon the older namespace version.

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/1382. Will open a new tracking issue for implementation
