### ISSUE TITLE
Consider renaming package `prove` => `proof`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1290]
## Context

I'm proposing renaming https://pkg.go.dev/github.com/celestiaorg/celestia-app@v0.11.1/pkg/prove to proof

## Motivation

> Good package names are short and clear. They are lower case, with no under_scores or mixedCaps. They are often simple nouns ...

Source: https://go.dev/blog/package-names

I found it slightly confusing that the main file in this package is `proof.go` but the package name is the verb `prove`. This has the benefit that clients will use the API like:

```go
proof.NewTxInclusionProof(...)
proof.NewShareInclusionProof(...)
```

instead of

```go
prove.NewTxInclusionProof(...)
prove.NewShareInclusionProof(...)
```

The latter is a bit confusing because the proof isn't actually proven until a client calls `.VerifyProof()` on the value returned from the previous functions.

Feel free to close if other maintainers haven't been confused by the package name.

cc: @SweeXordious @evan-forbes

**Comment by SweeXordious** [comment]
I think it makes sense. I also found it not fluid to use `prove`

**Comment by evan-forbes** [comment]
I don't have a strong opinion

>The latter is a bit confusing because the proof isn't actually proven until a client calls .VerifyProof()

I'm not sure I follow this, they are still using the prove package to prove something

**Comment by evan-forbes** [comment]
fwiw, I approved the PR, and afaic we can merge. thanks for bringing this up before feature freeze/1.0!

**Comment by rootulp** [comment]
> I'm not sure I follow this, aren't they still using the prove package to prove something?

Sorry for not fully articulating. Yes this package still proves something. To me, the following conveys that this function proves that a transaction was included:

```go
prove.TxInclsuion(...)
```

But that function actually just returns a proof of transaction inclusion and that proof still needs to be verified. The proposed reads a little cleaner to me.

```go
p := proof.NewTxInclusionProof(...)
p.VerifyProof()
```

I think the verb "prove" could be used as a method on the proofs returned by these functions if desired.
