### ISSUE TITLE
"Error reconnecting to peer" on testnet full consensus node

### ISSUE THREAD

**Issue by d-wire** [celestiaorg/celestia-app#1293]
### Summary of Bug

I'm trying to run a full consensus node in the testnet, but when I run `celestia-appd --home <base-dir> start` I get constant `Error reconnecting to peer. Trying again`

It seems to just spin on that infinitely between retrying to connect to peer and failing. Are these expected output logs? If not, how can I troubleshoot what the issue is? I followed the docs at https://docs.celestia.org/nodes/consensus-full-node/ to set everything up.

### Version

0.11.1

### Steps to Reproduce

Follow the steps at https://docs.celestia.org/nodes/consensus-full-node/ to set up a full consensus node, and then try to run the node I suppose?

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
@d-wire do you have peers configured in the persistent peers and seeds portion of the config.toml?

even when that is done, often times it takes a while (few hours) to connect to those peers if those peers are full. This is a common issue using tendermint v0.34, and can be avoided by manually filling your address book

**Comment by evan-forbes** [comment]
closing due to this issue being stale.
