### ISSUE TITLE
EPIC: Specify data root construction using rsmt2d, nmt, and the nmt wrapper

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1296]
Having a spec for the construction of the data root, particularly one that is consistent with the current implementation, would be very valuable. It would help on boarding others (internally such as new engineers, and externally via auditors and research enthusiasts) on how celestia functions at a low level. Ideally, someone should be able to write a fully compatible separate implementation using such a spec.

Currently, a lot of this information is disparate or implied. We need to compile the various sources of information, make sure they follow the implementation, and then write the missing pieces.

Notably, some of the missing pieces include (incomplete list) todo: flesh out
- [x] Spec out the NMT library https://github.com/celestiaorg/nmt/pull/101
- [x] Spec out the functionality of the nmt wrapper https://github.com/celestiaorg/celestia-app/pull/1442

Other issues that are addressed or identified as part of this EPIC:
- https://github.com/celestiaorg/nmt/issues/95
- https://github.com/celestiaorg/nmt/issues/112
- https://github.com/celestiaorg/nmt/issues/99
- https://github.com/celestiaorg/nmt/issues/108
- https://github.com/celestiaorg/nmt/issues/109
- https://github.com/celestiaorg/nmt/issues/110
- https://github.com/celestiaorg/nmt/issues/111
- https://github.com/celestiaorg/nmt/issues/115
- https://github.com/celestiaorg/nmt/issues/118
- https://github.com/celestiaorg/nmt/issues/125
-  and https://github.com/celestiaorg/nmt/pull/126
- https://github.com/celestiaorg/nmt/pull/94
- https://github.com/celestiaorg/nmt/pull/92
- https://github.com/celestiaorg/nmt/pull/96
- https://github.com/celestiaorg/nmt/pull/102
- https://github.com/celestiaorg/nmt/pull/103
- https://github.com/celestiaorg/nmt/pull/113
- https://github.com/celestiaorg/nmt/pull/114
- https://github.com/celestiaorg/nmt/pull/116
- https://github.com/celestiaorg/nmt/pull/119
- https://github.com/celestiaorg/nmt/pull/120
- https://github.com/celestiaorg/celestia-app/pull/1438
- https://github.com/celestiaorg/celestia-app/pull/1420

**Comment by staheri14** [comment]
Adding some resources relevant to this EPIC: 
- NMT outdated spec: https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#namespace-merkle-tree
- NMT Implementation: https://github.com/celestiaorg/nmt
- nmt wrapper: https://github.com/celestiaorg/celestia-app/blob/a8c8849ce3bd4be6aeee728cf1b16da1a7e3e2a1/pkg/wrapper/nmt_wrapper.go#L17

**Comment by staheri14** [comment]
The status of my advancement with respect to the EPIC and its subsidiary tasks is recorded in the following [Notion page](https://www.notion.so/celestiaorg/NMT-6d31472664cb4b7889dd8df5e9dcc36b). Please be advised that this is an ongoing effort and includes my preliminary observations, inquiries, and outcomes as I review various repositories and relevant resources.

**Comment by staheri14** [comment]
The specification for the NMT wrapper is currently under development. You can find the latest version on the following Notion page: https://www.notion.so/celestiaorg/NMT-Wrapper-4ae9ee77898e4d3d80f9a9b1c5465f87#link-to-the-nmt-spec-for-the-inclusion-proof.

**Comment by staheri14** [comment]
Closing this issue as the constituents tasks are done.
