### ISSUE TITLE
Only allow a single testnode network to be spun up at once

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1299]
Currently, it is possible to spin up two testnode networks at once on the same machine, resulting in the second network always failing. This could be one reason why we occasionally see flakey integration tests in app and node. We should add a local mutex that prevents this from occurring.

**Comment by cmwaters** [comment]
Do we know what's causing the collision? Is it the p2p/rpc ports?

**Comment by SweeXordious** [comment]
yes. Also, it's not possible to run 2 nodes because the node home is the same and the db complains + the config gets sealed

**Comment by SweeXordious** [comment]
This issue, I guess, can be closed after the discussion under https://github.com/celestiaorg/celestia-app/pull/1342#issuecomment-1425944402

**Comment by evan-forbes** [comment]
was this fixed @SweeXordious since we changed which ports are used?

**Comment by SweeXordious** [comment]
I just did a small test running multiple `DefaultNetwork(...)` and the nodes started alright. I don't think they will be connected to each other, or they will be validating the same network. But, if used in separate tests, they shouldn't complain as it's running 2 independent networks.
