### ISSUE TITLE
Final audit of state machine

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1319]
We've periodically gone through the modules we are using for the app for mainnet, and we've audited celestia specific modules, but since we've had the luxury of reusing battle tested code, we haven't set aside time to fully audit our state machine. We should do this before mainnet to triple check that we do not have some unneeded or undesired functionality.

**Comment by venkat0501** [comment]
👍

**Comment by evan-forbes** [comment]
can close with the conclusion of the binary buiders, informal, and soon ottersec audits
