### ISSUE TITLE
Test share encoding using random block data using PrepareProposal

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1322]
> I'm concerned the existing "fuzzing" test that tests reconstruction doesn't actually generate pay for blob txs [here](https://github.com/rootulp/celestia-app/blob/a42b83dac1627f428201ca98cea5914205ca5bfe/pkg/shares/merge_test.go#L101)

whoops, I should have pointed to the test I was thinking of, yeah I think we should test this using blocks that are using more realistic data, like with this test.

https://github.com/celestiaorg/celestia-app/blob/main/app/test/fuzz_abci_test.go

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/issues/1298#issuecomment-1409591659_

this will hopefully provide us with enough confidence to no longer use the test data introduced in #1298, and we could then remove it

~~blocked by #1298~~

**Comment by rootulp** [comment]
This issue may not be necessary after transaction fuzzing https://github.com/celestiaorg/celestia-app/pull/1613 and/or https://github.com/celestiaorg/celestia-app/pull/1745
