### ISSUE TITLE
Seal global cosmos config outside of the cli

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1331]
to avoid breaking all the tests and increase diff from upstream in this repo, I think we should attempt a different approach where we only call the config/seal functions once in the app in some init function, then import something from that file in celestia-node. I think that will force us to only seal a single time, instead of once in the cli for app and node each.

_Originally posted by @evan-forbes in https://github.com/celestiaorg/cosmos-sdk/pull/297#pullrequestreview-1274063484_

**Comment by Wondertan** [comment]
Nice! We did almost [the same](https://github.com/celestiaorg/celestia-node/pull/1583) recently. The PR name, though does not reflect what was in the final form, but I moved this init to one place in `core` pkg. Once you move this into the app, release and update the node with a PR, it would be nice to include the removal of init on our side.

**Comment by evan-forbes** [comment]
@vgonkivs currently we are sealing here 

https://github.com/celestiaorg/celestia-app/blob/0b447adf776689cc8f14823c6ef925b8f8249b5a/cmd/celestia-appd/cmd/root.go#L51-L55

I haven't tried this, but we can probably just include that in an init function in the app package. either directly in this [file](https://github.com/celestiaorg/celestia-app/blob/main/app/app.go), or in its own
