### ISSUE TITLE
App is not buildable on OSX Big Sur 11.6

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#134]
## Summary of Bug
keyring lib is throwing errors during `make install` process

## Version
git rev-parse --verify HEAD
`d061ef0f782e062a52db16da26bfe974a544a2d9`

## Steps to Reproduce
1. git clone repo
2. `make install` 
3.  Witness 
`# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here`

Note: If updating the lib then
`../../../../pkg/mod/github.com/cosmos/keyring@v1.1.7-0.20210622111912-ef00f8ac3d76/keychain.go:136:8: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
is this still an issue?

**Comment by liamsi** [comment]
BTW, I see the same warnings in 12.2 / Monterey. But they are just warnings. Not sure the warnings deserve an issue as the app is actually buildable.

**Comment by marbar3778** [comment]
the warnings are benign, everyone has those warnings, we are working on fixing this, soon (TM)

**Comment by evan-forbes** [comment]
closing this, as this issue will be fixed upstream if it isn't already
