### ISSUE TITLE
Investigate priority for transactions and blobs

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1351]
I have a few questions regarding priority:

1. If more transactions exist in the mempool than are possible to fit into a block, are the highest priority transactions included in the block? 
2. Are transactions in the block ordered by priority?
3. Are blobs within a namespace ordered by priority of the PFB tx they are associated with? 
4. If transactions are pruned from a block, are the lowest priority transactions pruned first?

**Comment by evan-forbes** [comment]
what is meant by priority? atm, we only have fee based priority, but in the future, I think we could have an additional value that is more subjective and does not assume high fee == high priority. 

You also bring up some really good points about how far do we need to go to support priority. I'm not sure, but I would assume only a fee based mempool is required atm.

**Comment by rootulp** [comment]
> If more transactions exist in the mempool than are possible to fit into a block, are the highest priority transactions included in the block?

There are multiple mempool implementations but [tendermint docs](https://docs.tendermint.com/v0.34/tendermint-core/mempool.html) only describe v0. 
1. Regular: v0. Orders transactions based on when they were received.
2. Prioritized: v1. Orders transactions based on fee. Deprecated (see [this discussion](https://github.com/tendermint/tendermint/discussions/9772)). 
3. Content-addressable transaction (CAT): v2. Implemented on top of v1.

So the answer to this question depends on which mempool is configured on the block proposer. The celestia-core [default is v1](https://github.com/celestiaorg/celestia-core/blob/3f3b7cc57f5cfc5e846ce781a9a407920e54fb72/config/config.go#L754).

> Are transactions in the block ordered by priority?

This question becomes applicable when the square size is the max possible and more transactions than can fit in a data square are reaped from the mempool and provided to the app. Currently the highest namespace blobs are pruned first (see [this commit](https://github.com/celestiaorg/celestia-app/compare/main...rootulp:celestia-app:rp/test-high-ns-pruned)).

> Are blobs within a namespace ordered by priority of the PFB tx they are associated with?

Need to investigate.

> If transactions are pruned from a block, are the lowest priority transactions pruned first?

No. PFB transactions with the highest namespace are pruned first.
