### ISSUE TITLE
docs: Add information to the node operator's guide on amount to stake

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#139]
## Summary
We should give a recommendation in the guide on which minimum amount of tokens to add in order to not bump into issues for future node operators 

## Problem Definition
If we execute something like this `celestia-appd gentx <user_n> 100000stake --chain-id <abc> --keyring-backend <xyz>`

Then we get the error 
`Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain` This is not directly/explicitly pointing to the issue of insufficient amount of tokens for gentx.

## Proposal
In order to avoid future repeated questions from the community, we should include an info field in the guideline that recommends a minimum amount to include in order to not bump into this issue. Something like 

`celestia-appd gentx <user_n> 1000000stake --chain-id <abc> --keyring-backend <xyz>` (1mil instead of 100k)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
this was fixed at least in the readme, so closing
