### ISSUE TITLE
Clean up Docker workflows

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1399]
## Context

We have 3 Docker related Github workflows:

1. https://github.com/celestiaorg/celestia-app/blob/main/.github/workflows/docker-build-publish.yml
2. https://github.com/celestiaorg/celestia-app/blob/main/.github/workflows/amd64-docker-build.yml
4. https://github.com/celestiaorg/celestia-app/blob/main/.github/workflows/main-docker-build.yml

I think there was recently an effort to consolidate them. Do we need all 3? My impression is we only need the first one and don't need the latter two. cc: @jrmanes

**Comment by jrmanes** [comment]
Hello @rootulp 

Yes, I'm aware of it, I created a [ticket](https://github.com/celestiaorg/devops/issues/61) for deleting the old ones, but first, I need to have the common CI fully working.
I'll remove them soon

Thanks for letting me know :)


Cheers!

**Comment by rootulp** [comment]
Closed by #1401
