### ISSUE TITLE
Implement namespace version byte

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1434]
https://github.com/celestiaorg/celestia-app/pull/1382 reached the accepted status so this issue is for tracking the implementation of a namespace version byte.

**Comment by evan-forbes** [comment]
I'm still not sure how we should track the implementation issues such as this, since they weren't originally part of the q1 goals, but they defintiely feel like part of some larger block encoding refactor/epic thing... still chewing on this though

wdyt @rootulp ?

**Comment by rootulp** [comment]
I can create an epic with all the issues in [label: share encoding](https://github.com/celestiaorg/celestia-app/labels/share%20encoding) if that helps in communicating / tracking our work.

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/1529
