### ISSUE TITLE
Consider removing split-test-files

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1439]
## Context

Our current CI test workflow splits test files to run them in parallel. This parallel [example](https://github.com/celestiaorg/celestia-app/actions/runs/4197256126) took 520 seconds to complete test-race. This sequential [example](https://github.com/rootulp/celestia-app/actions/runs/4198117246) took 543 seconds to complete test-race. The sequential test (so not test-race) actually runs faster than the parallel version.

- https://github.com/celestiaorg/celestia-app/blob/6d27b78aa64a749a808e84ea682352b8b551fbd7/.github/workflows/test.yml#L60-L84

## Proposal
Remove the step to split test files from the CI workflow.

Pros:
- simpler to maintain
- `make test` is more representative of how tests are run in CI

Cons:
- in some scenarios the parallel version may be slightly faster

**Comment by Chirag018** [comment]
Hey, @rootulp would like to work on this

**Comment by rootulp** [comment]
@Chirag018 maybe it would help to look at what our current CI 

## Current

https://github.com/celestiaorg/celestia-app/actions/runs/4821189737

<img width="1278" alt="Screenshot 2023-04-27 at 11 23 35 AM" src="https://user-images.githubusercontent.com/3699047/234909843-07dd4e1a-ac6c-4393-9896-b766c8ec2fee.png">

## Proposed

- remove `split-test-files`
- remove the `matrix` from `test/tests`
- remove the `matrix` from `test/test-race`

**Comment by Chirag018** [comment]
Since we are removing the matrix, so even the matrix. part in the following cases should be removed?

**Comment by rootulp** [comment]
We shouldn't need a path here: https://github.com/celestiaorg/celestia-app/blob/4c738244bd6b1429419c3ad9ddb4e780a62e9ab7/.github/workflows/test.yml#L114 and the test.yml can probably be simplified greatly.

You may draw inspiration from https://github.com/celestiaorg/celestia-node/blob/11fea99767f549bebd1355b4c9065115af25ea91/.github/workflows/go-ci.yml#L64-L77

**Comment by Chirag018** [comment]
Hey, @rootulp using the reference below, which I figured out, is it fine?
<img width="1267" alt="Screenshot 2023-04-27 at 11 46 23 PM" src="https://user-images.githubusercontent.com/56735482/234955783-a01a2516-6033-4957-a116-ea689ac5603a.png">

**Comment by rootulp** [comment]
Ideally we retain code coverage report creation but that action can contain fewer steps because we don't need to look at multiple files

**Comment by Chirag018** [comment]
Yeap understood, modified the changes
<img width="1273" alt="Screenshot 2023-04-28 at 10 13 27 AM" src="https://user-images.githubusercontent.com/56735482/235056210-6c97a7e5-1c97-49cf-8d26-92933e683ede.png">

Does the "coverage" file name work instead of "profile"?(line no. 71, 76)

**Comment by rootulp** [comment]
I think `coverage.out` should work too
