### ISSUE TITLE
no passphrase on wallet creation

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-app#1452]
### Summary of Bug

when doing celestia-appd keys add wallet, it wont ask for any passphrase at all

### Version

0.12.0

### Steps to Reproduce

see above

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Seems like a bug because documentation states

```
$ celestia-appd keys add --help
Derive a new private key and encrypt to disk.
Optionally specify a BIP39 mnemonic, a BIP39 passphrase to further secure the mnemonic,
and a bip32 HD path to derive a specific account. The key will be stored under the given name
and encrypted with the given password. The only input that is required is the encryption password.

...

Usage:
  celestia-appd keys add <name> [flags]
```

Yet there is no encryption password in the example usage command. There also isn't a CLI flag one can use to provide a passphrase so the `--interactive` flag is the only way to provide a passphrase.

**Comment by mindstyle85** [comment]
yeah and i remember we had this before, so it got lost somewhere between 0.11 and 0.12 i guess

**Comment by mindstyle85** [comment]
not super improtant for incentivized testnet, but best next iteration has this functionality again, at least before we ask them to create mainnet wallets

**Comment by evan-forbes** [comment]
this is likely related to setting the default keyring to test https://github.com/celestiaorg/celestia-app/pull/1261

**Comment by rootulp** [comment]
> at least before we ask them to create mainnet wallets

FWIW we could recommend users create a wallet with a passphrase by instructing them to use the `--interactive` flag in docs.

```
$ celestia-appd keys add foo --interactive
> Enter your bip39 mnemonic, or hit enter to generate one.

> Enter your bip39 passphrase. This is combined with the mnemonic to derive the seed. Most users should just hit enter to use the default, ""
bar
> Repeat the passphrase:
bar
```

**Comment by evan-forbes** [comment]
@mindstyle85 pls see convo in https://github.com/celestiaorg/celestia-app/issues/1201 but also synchronously, since we're using burner keys to submit PFBs in celestia-node, this makes things easier similar to how other chains manage burner keys (such as geth). I know this is not really normal in the sdk, but the normal doesn't fit our usecase. If more security is needed, then storing the key on disk using encryption probably isn't good enough either and a hardware key should be used.

**Comment by evan-forbes** [comment]
does this resolve this issue?

**Comment by mindstyle85** [comment]
ok yeah, then we will add --interactive flag to the docs for those that will want to use passphrase
