### ISSUE TITLE
specs: clarify Q3 extended data

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1454]
## Context

https://github.com/celestiaorg/celestia-app/pull/1442#discussion_r1128035484

## Proposal

Confirm that it doesn't matter if Q3 is extended from Q1 or Q2. Then add a note to https://github.com/celestiaorg/celestia-app/blob/c09843d07d4c3842753138de96b304b4866e8f5d/specs/src/specs/data_structures.md?plain=1#L387-L391

**Comment by staheri14** [comment]
We may need to also update the link added as part of this PR https://github.com/celestiaorg/celestia-app/pull/1461 if the extension logic is explained in a different section of the data structure spec.

**Comment by rootulp** [comment]
Verified that Q3 is identical if it is extended vertically from Q1 or horizontally from Q2. See [this commit](https://github.com/celestiaorg/rsmt2d/commit/8a46d48ce469e20abd3634216e3fc0009fe95d92) and [this test](https://github.com/rootulp/rsmt2d/blob/8a46d48ce469e20abd3634216e3fc0009fe95d92/extendeddatasquare_test.go#L11-L28) which continues to pass.

**Comment by rootulp** [comment]
>  to add a comment to the code

I don't think it would hurt. Will add a comment to the code in rsmt2d.
