### ISSUE TITLE
EPIC: share encoding

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1465]
This is a tracking issue for all share encoding issues. Issues that represent breaking share encoding changes need to be completed prior to mainnet.

## Mainnet

- https://github.com/celestiaorg/celestia-app/issues/1110
- https://github.com/celestiaorg/celestia-app/issues/1322
- https://github.com/celestiaorg/celestia-app/issues/1443
- https://github.com/celestiaorg/celestia-app/issues/1434
- https://github.com/celestiaorg/celestia-app/issues/1444
- https://github.com/celestiaorg/celestia-app/issues/1489
- https://github.com/celestiaorg/celestia-app/issues/1490
- https://github.com/celestiaorg/celestia-app/issues/1558

## Post-mainnet

- https://github.com/celestiaorg/celestia-app/issues/802
- https://github.com/celestiaorg/celestia-app/issues/1105
- https://github.com/celestiaorg/celestia-app/issues/1347
- https://github.com/celestiaorg/celestia-app/issues/1522

**Comment by evan-forbes** [comment]
@rootulp are the remaining issues here planned for mainnet?

**Comment by rootulp** [comment]
I just updated the milestone on individual issues to reflect whether I think we should do it before mainnet or after.

**Comment by rootulp** [comment]
FYI the share encoding issues needed for the mainnet milestone are complete. The post-mainnet issues have the "Post-mainnet" milestone so I'm going to close this epic in favor of tracking via the milestone and label "share-encoding"
