### ISSUE TITLE
gobuffalo/packr used in `make build` is not maintained anymore

### ISSUE THREAD

**Issue by smuu** [celestiaorg/celestia-app#1478]
### Summary

The `build` in the `Makefile` installs the go package `packr`, which is no longer maintained.
Additionally, it does not support the used Go version.

References:
- https://github.com/celestiaorg/celestia-app/blob/main/Makefile#L30
- https://github.com/gobuffalo/packr/

### Problem Definition

Using no longer maintained packages creates an attack vector as found security vulnerabilities will not be fixed.

### Proposal

Without knowing what this package does, I suggest you avoid no longer maintained packages.

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
This repo doesn't have any packr [usage](https://github.com/gobuffalo/packr/#usage) and packr isn't present in go.mod so it is safe to remove usage from the Makefile.
