### ISSUE TITLE
Stop pruning high namespace PFBs

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1519]
## Context

https://github.com/celestiaorg/celestia-app/issues/1351#issuecomment-1472762585

## Problem

If a block proposer attempts to construct a max square size data square and can't fit all PFB transactions, the PFB transactions with the highest namespace are pruned first. This issue disincentivizes roll-ups from using high namespace IDs.

## Proposal

Instead of pruning high namespace ID PFBs from the data square, consider pruning the PFB txs with the lowest priority (where priority is based on fees).

**Comment by cmwaters** [comment]
This has been resolved by #1690
