### ISSUE TITLE
Add authz support

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1530]
we should add authz before mainnet now that it has been audited and used meaningfully on other chains. This will allow us basic automation of common tasks such as restaking or wallet management.

**Comment by liamsi** [comment]
There is also the question if we want to integrate authz with the blob module. The only meaningful way I can imagine this to be used is to allow one or several grantee accounts to spend a granter's tokens for PFBs. That kinda overlaps with the feegrant module but might be more flexible.

**Comment by liamsi** [comment]
Let's close this (via #1540) and create a dedicated issue about authz and the blob module.
