### ISSUE TITLE
E2E Fuzzer Tool for celestia-node tests

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1535]
It would be really useful to have a tool to fuzz as many possible scenarios that could happen in celestia-app. This would include things like all possible transactions, validator set changes, block sizes, evidence in the block, and potentially even invalid blocks that are signed over.

We first only target this tool for the non-determinism tests, but in theory (not required to close this issue) could be implemented as a tool that could be applied to any network.

## AC

- [ ] create and submit each tx type that we support
  - [ ] exception for IBC messages due to the infra required, but those would be a huge bonus
  - [ ] ideally this also includes executing the current upgrade, but this is assuming we are using a rolling upgrade. I'm okay with separating this out as well
- [ ] Full blocks

Bonus (not required for merging)
- [ ] IBC messages
- [ ] Rapid changes in the validator set ref https://github.com/celestiaorg/celestia-app/issues/2382

**Comment by evan-forbes** [comment]
ref #1162, as simplifying the programmatic signing of txs could be useful

**Comment by evan-forbes** [comment]
The remaining things for this epic are basically just #2382

**Comment by rootulp** [comment]
Is the tool proposed in this epic: a new stand-alone binary? features added to the existing `txsim` binary? or something else entirely?

**Comment by evan-forbes** [comment]
using txsim, or whatever scripts, in the knuu e2e tests to fuzz the e2e test

it should be similar to if we actually had tests for robusta, so fill the blocks for a while, change the validator set dramatically, perhaps even perform an upgrade or restart nodes. The goal is to provide us with a basic set of behaviors that should all work in an predictable way and cover a wide spectrum of potential states of a chain. This is to give us better confidence that a network consisting of 4 nodes works as intended, along with providing celestia-node with a good foundation for attempting to find edge cases there

**Comment by rootulp** [comment]
> or whatever scripts, in the knuu e2e tests to fuzz the e2e test

Does this modify `make test-e2e` to run an additional test suite that does: " fill the blocks for a while, change the validator set dramatically, perhaps even perform an upgrade or restart nodes..."

Is that reusable by celestia-node?

**Comment by evan-forbes** [comment]
I'm not sure what the exact testing suite infrastructure would look like, it could [fit into the existing tests](https://github.com/celestiaorg/celestia-app/pull/2797#discussion_r1380319085) or be its own test. Therefore, it would also run when we run the e2e tests, and celestia-node could use the same infrastructure we use the run that test (the [e2e](https://github.com/celestiaorg/celestia-app/tree/main/test/e2e) package).

celestia-node doesn't have that infra setup atm afaik, however they should be able to import the same package similar to how they are importing the testnode package

**Comment by evan-forbes** [comment]
moved the AC that this needs to be a tool for celestia-node to use in knuu as a bonus. That might be useful, but doesn't need to be included to close this issue.

**Comment by evan-forbes** [comment]
closing in favor of #3540

if we need a tool for celestia-node to use, then we should create a separate issue for that.
