### ISSUE TITLE
Fully specify `genesis.json`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1536]
If a `genesis.json` doesn't contain a required field then defaults are interpreted. For example `version` isn't specified but blockspace race is producing blocks with `header.version.block: 11` (see [explorer](https://testnet.mintscan.io/celestia-incentivized-testnet/blocks/79491)). It would be nice if the genesis.json fully specified these defaults so that if celestia-app or celestia-core changes these defaults in the future, the `genesis.json` contains all required data to start a node.

**Comment by evan-forbes** [comment]
can we close this as completed?

**Comment by rootulp** [comment]
We can close this as won't do given no one else is asking for it.
