### ISSUE TITLE
Explore enforcing conventional commits

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1539]
In an onsite meeting on "Unification for infra", it was suggested that celestia-app explore ways to enforce [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by liamsi** [comment]
if this is only about the PR title / the commits on main, then this will work: https://github.com/marketplace/actions/conventional-commits-pr
There is probably also one for per commit in a PR.

**Comment by rootulp** [comment]
@MSevey suggested https://github.com/amannn/action-semantic-pull-request
