### ISSUE TITLE
Return a proof that a message has been included in a block

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#154]
The app's client currently returns a timeout error when broadcasting a `WirePayForMessage` in "block" mode, as the app has no way of actually knowing when a `WirePayForMessage` was successfully processed into a block.

This is due to the malleation of `WirePayForMessage`s into `MsgPayForMessages`, which causes us to not properly register or prove that a given message has been included in a block, even though it is.

We need to investigate what needs to be done from an implementation perspective to fix this.

**Comment by liamsi** [comment]
This also impacts users if they submit such a tx on the command line. Users can't query if the tx inclusion was successful or not via `celestia-appd q tx <txhash>`. Another thing I've noticed is that the payformessage txs also do not show up in the block explorer. Which might also be related.
I'll add this to the testnet project and I think we should prioritize fixing this.

**Comment by evan-forbes** [comment]
closed with [#615](https://github.com/celestiaorg/celestia-core/pull/615)
