### ISSUE TITLE
EPIC: Single Binary Syncs

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1568]
We want to be able to sync from genesis using a single binary. This means that all past and present consensus logic needs to be maintained forever. The general thinking is that we will use the app version in the header to determine 

more details in the ADR #1521 

## Tasks
- [x] https://github.com/celestiaorg/celestia-app/issues/3105

**Comment by rootulp** [comment]
@cmwaters is this close-able? I'm not sure which in-flight PRs were alluded to in my previous comment but I don't see any current in-flight PRs related to this.
