### ISSUE TITLE
EPIC: Strict inflation schedule

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1570]
We will be using a simplified inflation schedule that is strict. We start at 8%, decrease 10% each year, and end at 1.5%

**Comment by rootulp** [comment]
- ADR https://github.com/celestiaorg/celestia-app/pull/1584
- Implementation https://github.com/celestiaorg/celestia-app/pull/1578
- Testing https://github.com/celestiaorg/celestia-app/issues/1758

**Comment by rootulp** [comment]
Closing this epic b/c the ADR and implementation merged.
