### ISSUE TITLE
Fix genesis.json stake to celes

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#158]
## Summary of Bug
Now genesis.json contains `stake` instead of `celes` as default.

## Version
1fcccc414127b1dd8399ad35051c8f669a98aa56

## Mitigation
Manually adjust `genesis.json` file in places like
```sh
cat $genesis_path | jq --arg token $token '.app_state.crisis.constant_fee.denom = $token' | sponge $genesis_path
cat $genesis_path | jq --arg token $token '.app_state.mint.params.mint_denom = $token' | sponge $genesis_path
cat $genesis_path | jq --arg token $token '.app_state.staking.params.bond_denom = $token' | sponge $genesis_path
```
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
Note that there is also a bug in the current devnet where uceles are also called celes.

**Comment by marbar3778** [comment]
this is purposefully setup this way in the sdk. There should be a workaround that isn't supported natively but the reason its like this is so the team changing the params needs go through the genesis file manually as its a delicate process.

**Comment by marbar3778** [comment]
I can knock this out quickly.
