### ISSUE TITLE
Set proposer-based rewards to 0%

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#1589]
Param is removed in the latest version of the SDK. In case we launch with 0.46, we should set the param to 0. It over-proportionally rewards proposers and leads to more centralization.

ref: https://github.com/cosmos/cosmos-sdk/pull/12876

**Comment by rootulp** [comment]
Note this issue applies to both: `BaseProposerReward` and `BonusProposerReward` because both are deprecated.

> In case we launch with 0.46

We decided at the most recent on-site that we are launching mainnet with v0.46.x so this issue is needed before Mainnet.
