### ISSUE TITLE
Organize ADR assets

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1602]
Currently all of the [assets for ADRs](https://github.com/celestiaorg/celestia-app/tree/main/docs/architecture/assets) are in one directory, and its getting cumbersome to find specific files. We should organize them better, which could be as simple as giving each ADR with assets a directory of its own for those assets

`./docs/architecture/assets/adr001/image.jpg`

**Comment by Chirag018** [comment]
Hey, @evan-forbes Would like to work on this

**Comment by evan-forbes** [comment]
sounds good @Chirag018 :slightly_smiling_face:
