### ISSUE TITLE
Delete remote branch `master` and protect it if possible

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#1605]
## Issue

This repo contains a branch named `master`. Confirm with

```sh
git branch -r | grep origin/master
```

The issue here is that if someone checks out `master` instead of `main` by accident, depending on their git configuration (e.g. if it's set up to automatically track remote branches), they'll get a successful checkout instead of an error.

## Actions

1. Delete the branch `master` on this repo.
2. If possible, protect `master` so that no one can push to a branch with that name.

**Comment by evan-forbes** [comment]
is this only on people who have downloaded an old copy of the repo? I have this on my local repo, but not if I git clone from scratch

**Comment by adlerjohn** [comment]
Oh damn, you're right. Can't repro on a fresh clone.

**Comment by rootulp** [comment]
Relevant https://github.com/celestiaorg/celestia-app/issues/564
