### ISSUE TITLE
Unable to parse PayForBlobs via CLI

### ISSUE THREAD

**Issue by kinrokinro** [celestiaorg/celestia-app#1620]
### Summary of Bug

I have this output when tryin to parse any `MsgPayForBlobs`
```
celestia-appd q tx 117860E06D33C91DE2B032592631E078DED01A6612E79F1044D0FA8FB3463363
Error: unable to resolve type URL 
 /celestia.blob.v1.MsgPayForBlobsd
/celestia1xh9qhadn3aehnm9h3zmurcf9p4p9uj7w46kgs�Qv|��" �aȼ����
                                                              ��)�4{nJ ��B��B: tx parse error
```
Or
```
celestia-appd q tx 62F28F6042E94684E223EB80013C97F512CFF5B018CB5F11A3F49E23C5E74ED8
Error: unable to resolve type URL 
 /celestia.blob.v1.MsgPayForBlobsd
��s���թ��fzB: tx parse errorzfmnqvmzeqae4zlzpun���Z��pe�" $M�z�BVM$��i��
```

### Version

```commit: 7e1792b3c64f19033b85ccbe78e11a79becf95b3
cosmos_sdk_version: v0.46.7
go: go version go1.19.3 linux/amd64
name: celestia-app
server_name: celestia-appd
version: 0.12.1
```

### Steps to Reproduce

Try to parse any `MsgPayForBlobs` tx, i.e.:
```
celestia-appd q tx 117860E06D33C91DE2B032592631E078DED01A6612E79F1044D0FA8FB3463363
```

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by vanphandinh** [comment]
The same problem in the API server: https://api.celestia.chainno.de/cosmos/tx/v1beta1/txs/2866B2A62C2BD8747C897654465CB9383D85F7EBC9474AA352C33985953BD4F5
I’m looking forward to the next patch to fix it.

**Comment by rootulp** [comment]
Investigation notes
- The error appears to originate from [here](https://github.com/cosmos/cosmos-sdk/blob/866cfa486092653ae45b6021eabfbd1be17e66e3/codec/types/interface_registry.go#L306) which indicates that the `MsgPayForBlobs` wasn't registered correctly
- `MsgPayForBlobs` should be registered [here](https://github.com/celestiaorg/celestia-app/blob/9698a07837c2cc1986f3f59c4cb51459da9c29e5/x/blob/types/codec.go#L19-L21) and [here](https://github.com/celestiaorg/celestia-app/blob/9698a07837c2cc1986f3f59c4cb51459da9c29e5/x/blob/types/codec.go#L15) 
- When I reproduced this error on a local devnet, I encounter:
    ```error
    $ celestia-appd query tx CF5E218E82DA3E4E6B35F383499B8E5FF4B737C90D3E3D4AE7BE682252FA98DE
    Error: unable to resolve type URL
    /celestia.blob.v1.MsgPayForBlobs|
    /celestia1fp2s6cyxp9cay8hrwm757cffg8h543warx8x7n!��[d�pcs�gd" �'$Q��P��s����~Y&�)ۖ��+FB: tx parse error
    ```
    - Note the suffix `|` instead of `d` in the error message in this issue
