### ISSUE TITLE
Consider a global minimum gas price

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1621]
### Summary

Add a new consensus validity rule which sets a lower bound to the gas price of any transaction (that can also be assumed as the fee/gas). 

### Problem Definition

Currently we set an arbitrary 0.002 utia as the default minimum gas price in each nodes `app.toml`. This is a local parameter which prevents a transaction from being accepted in a node's mempool if it has a gas price below that value. Block producers can alter this value. Including setting it to 0. Block rewards for minting a new block + all transaction fees are proportionally distributed to all validators not to the block producer. Therefore there is an incentive for block producers to sell their blockspace through secondary markets. This undercuts the rest of the validators who provide similar compute, bandwidth and storage. Thus each validators strategy would swing to using secondary markets to maximize payoff. Having the transfer of value being conducted in off-chain auctions isn't necessarily that bad, however it likely means an increasingly centralised block production system; the potential exclusion of delegators who might not be privy to the auctions; and less general demand for the TIA token as the auction may be conducted other denominations. 

### Proposal

If we want the blockspace market to remain within Celestia, we should explore economic mechanisms such as setting a global min gas price (possibly controlled through governance) which better distributes value to those that provide it. 

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
noting that this would require the validation of all state transitions during `Prepare/ProcessProposal`, since we cannot have an invalid PFB be included in the block, and this is adding a block validity rule where there can no longer be PFBs with a fee of zero

 ref #49 since that would also require some sort of adjustable enforced min fee

**Comment by liamsi** [comment]
Quoting @musalbas here: 
> Due to deferred execution, making it a consensus rule may not be trivial, and then we might as well implement fee burning.


That is a good point. Gas only gets accounted for in the next block. It is probably sufficient to enforce this on the mempool level only.

**Comment by cmwaters** [comment]
You don't necessarily need to know how much gas a transaction will consume to implement this. In process proposal you simply check that the fee and gas limit equate to a minimum agreed upon gas price. The tx may be invalid and not execute but we allow for that already. This would simply assert: given the tx is valid, the fee payer will pay for at least this price per unit of gas

**Comment by rootulp** [comment]
Cosmos Hub uses the globalfee module which as far as I can tell hasn't been upstreamed to Cosmos SDK. 

Ref:
1. https://github.com/cosmos/gaia/blob/main/docs/modules/globalfee.md
2. https://github.com/cosmos/gaia/tree/main/x/globalfee
