### ISSUE TITLE
add arm64 to the build pipeline of local-celestia-devnet

### ISSUE THREAD

**Issue by pciavald** [celestiaorg/celestia-app#1624]
### Summary

add arm64 to the build pipeline of local-celestia-devnet on this repo: https://github.com/orgs/celestiaorg/packages/container/package/local-celestia-devnet

### Problem Definition

I'm developing on apple silicon so i need to build the image myself, and i'm currently building a [tool that uses the image to facilitate development on Celestia](https://github.com/zkvalidator/ignite-manager), so i'd prefer using an official build. Also interesting for people who would want to experiment on SBCs like raspberry pi.

### Proposal

Build that docker image also for arm64

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Tagging @jrmanes @jcstein for awareness

**Comment by jcstein** [comment]
thank you for flagging @rootulp, here's a related issue in `local-celestia-devnet` https://github.com/rollkit/local-celestia-devnet/issues/11

**Comment by rootulp** [comment]
seems safe to close this issue in favor of tracking https://github.com/rollkit/local-celestia-devnet/issues/11
