### ISSUE TITLE
Functions relying on versioned constants should reject versions > 1

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1626]
There will be various functions that can be imported from the app that rely on versioned constants. These functions need to throw an error on any version greater than 1 so that light clients that don't upgrade will be notified of a version increase.

**Comment by rootulp** [comment]
>  any version greater than 1

Clarifying question: is this specific to `header.version.app`? Because other constants may start at `0` (e.g. `ShareVersion` and `NamespaceVersion`)
