### ISSUE TITLE
Customize and deploy block explorer

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#165]
## Summary

We have a MVP block explorer for devnet running on http://celestia.observer:3080/
It would be neat to a) use a more recent block explorer and b) customize it a tiny bit.

## Problem Definition

https://github.com/forbole/big-dipper is not maintained anymore. 
https://github.com/forbole/big-dipper-2.0-cosmos is its successor that we should be using.

Also, a custom theme, branding, and logos would be neat.

## Proposal

Start experimenting with https://github.com/forbole/big-dipper-2.0-cosmos before launching testnet.

Customize it to our needs (before launching testnet too).

Start here: http://docs.bigdipper.live/cosmos-based/parser/custom-chains
Let's track the changes necessary here: https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues

Example: https://explorer.evmos.org/

Hopefully this can be somewhat re-used for rollups:
ref: https://github.com/celestiaorg/optimint/issues/213
ref: https://github.com/celestiaorg/evmos/issues/3

**Comment by evan-forbes** [comment]
I think we can close this, but pls reopen if this is still needed
