### ISSUE TITLE
Consider removing payforblob.go re-exported constants

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1655]
https://github.com/celestiaorg/celestia-app/blob/a69fe550f8623ba6692e577eb19e8e981b819ec4/x/blob/types/payforblob.go#L23-L24

There are no usages of these constants in this repo and they can be used by downstream consumers from `appconsts`.

**Comment by rootulp** [comment]
The same is true of https://github.com/rootulp/celestia-app/blob/c60fc7416d314d0aec4a0bae0a617ef6c9662ae1/x/blob/types/payforblob.go#L24

**Comment by Chirag018** [comment]
Hey, @rootulp Would like to work on this
