### ISSUE TITLE
Create a function that calculates the max padding for a blob

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1660]
[question][blocking] what is the relationship between subtree width and 

> Blobs start at an index that is equal to a multiple of the blob length divided by MaxSquareSize rounded up.

Source: https://github.com/celestiaorg/celestia-app/blob/main/docs/architecture/adr-013-non-interactive-default-rules-for-zero-padding.md

Related: should we extract a function that calculates the max padding for a blob and unit test it in isolation? Then the unit tests can use the table here to verify max padding matches what we expect: https://github.com/celestiaorg/celestia-app/blob/main/docs/architecture/assets/worst-case-padding-in-blob-size-range.png

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/1659#discussion_r1178027226_

we should create a function that calculates the max padding for a given blob. It should be `shares.SubTreeWidth(numberOfShares)-1`

**Comment by cmwaters** [comment]
Isn't the max padding `shares.SubTreeWidth(shareSize) - 1`. If the subtreewidth is 4, then the amount of padding could be 0, 1, 2, 3. The worst case is 3

**Comment by rootulp** [comment]
This seems no longer relevant b/c we extracted all of the share code to go-square and the rules around padding have changed due to ADR-11.
