### ISSUE TITLE
Blobs should be ordered by namespace

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1673]
https://github.com/celestiaorg/celestia-app/blob/318d7853a3bf5a07bb9530a27bb2e5e314bbde2a/app/write_square.go#L52

This should account for ordering due to the entire namespace (namespace version + namespace ID)

**Comment by Chirag018** [comment]
Hey, @rootulp would like to work on this.

The approach I would be following here is:

<img width="965" alt="Screenshot 2023-05-01 at 11 03 15 AM" src="https://user-images.githubusercontent.com/56735482/235411654-4bf23372-8dc9-465f-9928-2072ab4b9410.png">

**It extracts the byte slices for the namespace IDs of the two blobs being compared,
		removes the last byte (which is the namespace version),
		and then uses `bytes.Compare` to compare the two byte slices.
		If the namespace IDs are equal up to the second-to-last byte,
		 then it compares the last byte to break the tie.**

**Comment by rootulp** [comment]
Thanks for your interest @Chirag018 . I think @cmwaters is already working on this so I just assigned him. The namespace version is the first byte of the namespace. I'll clarify https://celestiaorg.github.io/celestia-app/specs/data_structures.html#namespace
