### ISSUE TITLE
Investigate changing the data commitment window param

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1676]
Currently, we're exposing the data commitment window as a param that can be changed. However, we didn't test extending/shrinking in a hardfork or via a gov proposal to see the consequences of it.

It would be good to have a test that does that and also the implementation might need to be updated not to miss any blocks when shrinking the window or to have overlapping commitments that might break some query that depend on that.

**Comment by SweeXordious** [comment]
Changing the data commitment window manually in the state machine results in the validators getting:
```
11:16PM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 655856A03936DF8A914425FFFE32CDB3FAC493F4BEEBAD7531986AA0491DAB09, got F9F374A6376C2AF6549D28F8381FEF316FE9833088393F02F1700BFAA1597748" module=blockchain
11:16PM ERR Stopping peer for error err="blockchainReactor validation error: wrong Block.Header.AppHash.  Expected 655856A03936DF8A914425FFFE32CDB3FAC493F4BEEBAD7531986AA0491DAB09, got F9F374A6376C2AF6549D28F8381FEF316FE9833088393F02F1700BFAA1597748" module=p2p peer={"Data":{},"Logger":{}}
```

So, if we want to change the window manually, we will either need to do a gov proposal, or we need to have an upgrade logic that specifies when to update the window.

For the former way, via a gov proposal, changing the window will have the following consequences:

- If we shrink the window, we will miss blocks during the transition
- If we expand the window, we will have blocks that are committed to in two different data commitment attestations.

Thus, we will need to update the window logic to support this.

**Comment by cmwaters** [comment]
> For the former way, via a gov proposal, changing the window will have the following consequences:
>
> If we shrink the window, we will miss blocks during the transition
> If we expand the window, we will have blocks that are committed to in two different data commitment attestations.

Can you explain more why that is?

**Comment by SweeXordious** [comment]
This is for the QGB missing blocks and not related to consensus. And, that is because we're creating the data commitments based on the current height.
For example, if the window is 100, and we're at block 200, the commitment will be: `[200-window, 200] = [100, 200]`.
And if we shrink the window at 300 to 50, then, at height 300, the commitment will be `[300-window, 300] = [250, 300]`.

And the same reasoning for expanding. Thus, I will update the mechanism to get the last commitment and add to it the window: `[lastCommitment.EndBlock +1, lastCommitment.EndBlock + window]`.

**Comment by SweeXordious** [comment]
Will be done in https://github.com/celestiaorg/celestia-app/issues/1676
