### ISSUE TITLE
`CreateCommitment` with subtree roots

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1681]
## Context

https://github.com/celestiaorg/celestia-app/blob/a0f1b97ee702d4ee4674572c9b1b9edf4750903a/x/blob/types/payforblob.go#L168-L173

## Problem

Currently celestia-node's BlobModule must download all shares to create the commitment for a blob. They're requesting the ability to `CreateCommitment` just using the leaf hashes of a blob. See https://github.com/celestiaorg/nmt/issues/178

## Proposal

Export a new function that creates a share commitment using a list of leaf hashes. The function may need to perform input validation to ensure that all leaf hashes belong to one namespace.

**Comment by evan-forbes** [comment]
if we're going to use leaf hashes, why not just use subtree roots(which most of the time would be leaf hashes)?

**Comment by rootulp** [comment]
Subtree roots could also work as long as the subtree roots provided are the same subtree roots used by non-interactive default rules. My hesitation around the original proposal in https://github.com/celestiaorg/nmt/issues/178 was that it used subtree roots at a fixed height 1 level above the leaf hashes which doesn't always match the subtree roots used by non-interactive default rules.

@vgonkivs does celestia-node have a preference on using leaf hashes vs. subtree roots? If subtree roots are used, celestia-node may be able to implement optimizations to download less data per inclusion proof.

**Comment by evan-forbes** [comment]
> If subtree roots are used, celestia-node may be able to implement optimizations to download less data per inclusion proof.

which nodes are creating the proofs here? light or full? is there a link to the conversation somewhere?

**Comment by rootulp** [comment]
After a synchronous discussion w/ @evan-forbes @vgonkivs we decided that celestia-node's blob module v2 will use subtree roots for verifying a blob's inclusion in a block. We'll likely need a function in celestia-app to convert from subtree roots to a share commitment but will delay implementing that until we have alignment on the other pieces needed.
