### ISSUE TITLE
Define genesis params

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#169]
## Summary

We currently use the default params of most modules. We should settle on which params we want to launch with. 

## Problem Definition

The defaults might not be the best choices for Celestia. Also, changing a param might cause more friction if they are not modifiable via governance (see: #168).

## Proposal

Decide _on each_ parameter. 

Most important ones include inflation, token name, max validators at launch. An non-exhaustive list can be found here:
https://github.com/gavinly/CosmosParametersWiki/blob/master/param_index.md

Most of the parameters are now also described in the docs of each [module](https://github.com/cosmos/cosmos-sdk/tree/master/x) as well (example: https://github.com/cosmos/cosmos-sdk/blob/master/x/staking/spec/08_params.md). 

While the genesis params could also be defined in the networks repository before launch, I would suggest discussing the parameters in here and maybe have a genesis file (with these decided on parama) we can use as a basis too.

While this could wait until launch, I suggest to prioritize this to have the next testnet with params as close as possible to the launch params.

**Comment by evan-forbes** [comment]
pushing this to the onsite, but we still need to do an initial investigation.

**Comment by evan-forbes** [comment]
We are moving the code to change the defaults the to the application per discussion in https://github.com/celestiaorg/cosmos-sdk/pull/285

**Comment by evan-forbes** [comment]
marking as completed
