### ISSUE TITLE
Bump to go version 1.20

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1691]
I guess even if the repo's go version is 1.19, we're still asking validators for BSR, for example, to run using 1.20. So, bumping this makes sense.

Also, proposing to bump the version in README to 1.20

_Originally posted by @SweeXordious in https://github.com/celestiaorg/celestia-app/pull/1688#pullrequestreview-1410630230_

**Comment by rootulp** [comment]
We're not bound by the Go version celestia-node uses but just noting that they've upgraded to Go 1.20 too: https://github.com/celestiaorg/celestia-node/blob/4d31ad4a537e41b5ac588e14cf807904abbb8d8a/go.mod#L3
