### ISSUE TITLE
Unable to get blob share range when there are multiple blobs in a PFB

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1711]
### Summary

We have hardcoded to only get the range for the first blob listed in the PFB

https://github.com/celestiaorg/celestia-app/blob/c08d1c690945b27c8341d91708419c872f3b69cd/pkg/proof/proof.go#L100-L102

### Problem Definition

Users can't prove blob inclusion when they include multiple blobs in their PFB

### Proposal

Introduce a second argument `blobIndex` that also specifies the index of the blobs in the PFB to get the share range for

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Related https://github.com/celestiaorg/celestia-app/issues/1315
