### ISSUE TITLE
Update the `verify` command to support multiple blobs

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1714]
With these changes, I guess we should see if https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/client/verify.go is still working and we will need to update its implementation to support multiple blobs

_Originally posted by @SweeXordious in https://github.com/celestiaorg/celestia-app/pull/1690#pullrequestreview-1416671349_

**Comment by cmwaters** [comment]
I believe this has been resolved from #1690. Reopen it if I am mistaken

**Comment by SweeXordious** [comment]
Will test it later on real networks and see. We generally need to write tests for that
