### ISSUE TITLE
Consistent usage of ranges for inclusion verification

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1716]
### Summary

When verifying the inclusion of blobs or transactions we first find the shares that these data types range over and then verify that the range of shares were included. The code currently has different interpretations of a range - is it end inclusive or end exclusive. We need to agree on a consistent interpretation so that all shares in the range are verified.

### Problem Definition

We currently denote both the start and end of a ShareRange as being inclusive (see https://github.com/celestiaorg/celestia-app/blob/e223493e3bb53a969b18297150a6de20202feaec/pkg/shares/split_compact_shares.go#L66) i.e. a share range of [3, 5] means the tx takes up shares 3, 4, and 5. But the VerifyProof function here https://github.com/celestiaorg/celestia-core/blob/6e590724cde96109ab4732e0a72a92bb5c2dc912/types/share_proof.go#L114 treats end as being exclusive. In the above example it calculates the sharesUsed as 5-3=2, which is incorrect. 3 shares are actually used. Further down, we use that variable to calculate the shares we want to verify as sp.Data[cursor:sharesUsed+cursor] . go slices are end exclusive so this would only check inclusion of the 3rd and 4th and not the 5th.

### Proposal

As mentioned golang is end exclusive. NMT is also end exclusive. End exclusive is less error prone for length calculations as it's just end - start (whereas inclusive you need +1). However, I feel that people naturally think a range is inclusive.

I would opt for having the range exclusive but don't mind either way so long as it's properly documented.

**Comment by rootulp** [comment]
> I would opt for having the range exclusive

+1. I think we should also consider this for QGB data commitment ranges @SweeXordious

**Comment by SweeXordious** [comment]
Sure, sounds good, I will create an issue to start updating the QGB implementation
