### ISSUE TITLE
ADR11 clarification around component proofs for PFB transaction inclusion proof

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1722]
## Context

https://github.com/celestiaorg/celestia-app/blob/4135eddedaaa2728e96ab134fc8a479a71e487a2/docs/architecture/adr-011-optimistic-blob-size-independent-inclusion-proofs-and-pfb-fraud-proofs.md?plain=1#LL21C146-L21C146

> A PFB transaction inclusion proof contains the shares that have the PFB transaction and the inclusion proof that proves those shares are present in a Merkle tree with root `DataRoot`

## Question

AFAIK there is no Merkle tree that goes directly from shares to the `DataRoot`. I think this should clarified to state something like:

A PFB transaction inclusion proof contains the shares that have the PFB transaction and two distinct inclusion proofs:
1. An NMT proof that proves the shares exist in a Merkle tree with root `RowRoot`
2. A Merkle proof that proves the `RowRoot` exists in a Merkle tree with root `DataRoot`.

Note: the second proof may not be necessary because light clients download the `DataAvailabilityHeader` which contains all `RowRoot`s of the block's EDS.

**Comment by nashqueue** [comment]
Very good clarification, and you understood it correctly.

**Comment by rootulp** [comment]
Thanks, will create a PR shortly.
