### ISSUE TITLE
Consider removing `BlocksPerYear`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1730]
## Context

The inflation module (`x/mint`) proposed in https://github.com/celestiaorg/celestia-app/pull/1578 relies on an estimate for the number of blocks produced in a year. The estimate is currently hard-coded

```
	// BlocksPerYear is an estimate for the number of blocks produced by the
	// Celestia blockchain per year. This number is based on the assumption that
	// the block interval (i.e. TargetHeightDuration) is 15 seconds.
	//
	// 31,536,000 seconds in a year / 15 seconds per block = 2,102,400 blocks per year.
	BlocksPerYear        = 2_102_400
```

The estimate is used to calculate the amount of new tokens that should be minted on a per-block basis. The estimate is needed because the block interval in Tendermint chains isn't guaranteed. We expect the block interval to be 15 seconds but it may diverge.

## Problem

If we keep the estimate hard-coded then it's likely that the actual number of blocks produces diverges slightly from the estimate. When this occurs, the amount of new tokens minted due to inflation will diverge slightly from the intended value.

It is worth noting that the `BlocksPerYear` constant can be updated in future hard-fork upgrades based on the observed network block intervals.

## Proposal

Consider removing the `BlocksPerYear` constant in favor of a dynamic value based on a moving average of the block interval for the last N blocks (e.g. where N is 10,000). Functionally this would behave similarly to https://testnet.mintscan.io/celestia-incentivized-testnet/blocks/909774

<img width="952" alt="Screenshot 2023-05-09 at 11 00 30 PM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/03577d85-c71e-4421-8cf1-882a7db21b5a">

Note this option has the downside that the number of tokens minted for a block is less predictable ahead of time because it will be dependent moving averages of block intervals.

**Comment by evan-forbes** [comment]
not hardcoding blocks per year was my understanding of this [thread](https://github.com/celestiaorg/celestia-app/pull/1584#discussion_r1160877702), and imo we should do this to have stronger guarantees around inflation. Otherwise, if validators change their locally configured values for block times, then they could mint significantly more tokens than otherwise permitted.

**Comment by rootulp** [comment]
> Otherwise, if validators change their locally configured values for block times, then they could mint significantly more tokens than otherwise permitted.

This risk remains if we use a moving average estimate. Validators can configure their local block interval time to be shorter to mint more tokens but I don't think this type of attack is likely considering validators don't earn the inflation rewards on a per block basis. AFAICT block based inflation rewards land in a pool distributed to all delegators. If such an attack were likely, I would expect it to have already occurred on an existing Cosmos chain.

From my perspective, the only difference is that a dynamic moving average estimate would automatically update the `BlocksPerYear` whereas a hard-coded `BlocksPerYear` would require protocol engineers to update the value to reflect the network observed block interval.

I choose to punt this to after mainnet because I think there are risks associated with using a moving average. See
https://github.com/cosmos/cosmos-sdk/issues/5411#issuecomment-597228083 so we should thoroughly explore new attack vectors that may be introduced by a moving average estimate for `BlocksPerYear`.

**Comment by cmwaters** [comment]
I also agree that hardcoding this value is okay for now

**Comment by cmwaters** [comment]
We'd have stronger guarantees around time if proposer based timestamps was implemented. This could also be used to more strongly shape an adequate block production frequency.

**Comment by rootulp** [comment]
Closed via https://github.com/celestiaorg/celestia-app/pull/1578/commits/ebd3775e55b164f828516e42aa828478567a6673
