### ISSUE TITLE
Add more informative events for PayForMessage

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#174]
Currently, we don't have any additional information in the events that we are emitting for `PayForMessage`. We should emit an event that contains attributes that have enough information for external listeners to properly index PayForMessages.

**Comment by toanngosy** [comment]
hey @evan-forbes , could you assign me? Could you explain more on how should we do this?

**Comment by evan-forbes** [comment]
yeah sure! thanks for doing these @toanngosy :purple_heart: 

I would first read up on events here https://docs.cosmos.network/master/core/events.html

Then I would explore a few examples in the sdk (ie [bank module](https://github.com/cosmos/cosmos-sdk/blob/0a7b5232af9556aafbf9f3c1fa7182d26d64fafe/x/bank/keeper/keeper.go#L406-L409))

For now, we only want to emit 
- who is paying for messages of a certain size

Lastly, let's update the docs https://github.com/celestiaorg/celestia-app/blob/master/x/payment/spec/docs.md#events
