### ISSUE TITLE
Fuzz the share commitment correctness

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1744]
Previous to #1690, we were recalculating the share commitment in each PFB using only subtree roots of the data square

https://github.com/celestiaorg/celestia-app/blob/54b65f9c0179359f7af7cdf6b00f8e7a12275783/app/process_proposal.go#L170-L184

given the importance of this property and the complexity of the block construction/share encoding, we should replicate this check using some form of fuzzer.

**Comment by evan-forbes** [comment]
also see #1726 which adds a test for the share commitment

**Comment by cmwaters** [comment]
I can pick this up. I had thought about appending it to the existing fuzzy test I had written

**Comment by evan-forbes** [comment]
> I had thought about appending it to the existing fuzzy test I had written

that would be perfect!
