### ISSUE TITLE
Implement a block height-based inflation mechanism

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1756]
## Context

https://github.com/celestiaorg/celestia-app/pull/1578

## Proposal

A time-based inflation schedule isn't battle tested. In the event that a bug is identified with the time-based inflation mechanism and/or we observe unexpected behavior on mainnet, it may be helpful to have a fallback inflation mechanism already implemented. Such a fallback inflation mechanism can target the same inflation schedule as proposed in https://github.com/celestiaorg/celestia-app/pull/1584 but be based on block-height rather than block-proposal.

Note: a block height based would reintroduce the `BlocksPerYear` constant

**Comment by evan-forbes** [comment]
can we close because of https://github.com/celestiaorg/celestia-app/pull/1584#discussion_r1202453743 ?
