### ISSUE TITLE
Add cli flag to specify specific square sizes

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#180]
We need to add a flag to the `payForMessage` command that allows us to  to pass in specific square sizes via the cli. 

- [ ] Add cli flag to pass square sizes
- [ ] Pass square sizes to `NewWirePayForMessage` 
- [ ] Add an extra test case to the cli integration test to submit a `WirePayForMessage` that includes different square sizes

**Comment by toanngosy** [comment]
Hi @evan-forbes , could you assign me this?

`flags.go` is added to the celestia-app/flags so we can add a new `square-size` flag. Should we do this?
