### ISSUE TITLE
celestia-appd tx has "vesting" option twice

### ISSUE THREAD

**Issue by Agronomistech** [celestiaorg/celestia-app#181]
## Summary of Bug

In help:
```
celestia-appd tx
```

We can see "vesting" option twice:

```
  validate-signatures validate transactions signatures
  vesting             Vesting transaction subcommands
  vesting             Vesting transaction subcommands
```

## Version

commit: ad4650a034e62312e2aa18eb429089fb4d66bdb3

## Steps to Reproduce

```
celestia-appd tx
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
Is the vesting module or at least the sub-command loaded twice? If yes, how did this happen?

**Comment by evan-forbes** [comment]
This is a weird bug! It disappears on the branch that uses an updated version of the sdk #186, but I didn't find any closed issues in the sdk that fixed it.

**Comment by liamsi** [comment]
Maybe it is related to how we wire the app together?

**Comment by liamsi** [comment]
I think this is still an issue on the current master branch 🤔

**Comment by rootulp** [comment]
Doesn't repro on `main` or latest release `v0.6.0`

**Comment by evan-forbes** [comment]
I think we can close then. If someone else finds this bug again, please reopen
