### ISSUE TITLE
State Sync failure

### ISSUE THREAD

**Issue by AlexToTheMoon** [celestiaorg/celestia-app#1814]
### Summary of Bug

I noticed that my snapshot service not producing state synced snapshots anymore (It been working perfectly since testnet launched). I have my state synced machine connection to my RPC/Snapshot node (archive node, no pruning) which making snapshots :
snapshot-interval = 2000
snapshot-keep-recent = 3
And now every time I try state sync I got error :
State sync failed err="snapshot restoration failed: app version mismatch. Expected: 1, got: 0" module=statesync
All what I found regarding versions is that Snapshot node binaries were compiled on :
go version go1.20.3 linux/amd64
On state sync machine celestia-appd binaries were compiled on:
go version go1.19 linux/amd64
But both got : version: 0.13.0, commit: 6ba60e18fec27d3e3a42a71be082e255913cf4cf
  So I have tried to install same go1.20.3 and recompiled binaries at state sync machine, didnt help , the same error.
  
LOGS :

6:40PM INF Applied snapshot chunk to ABCI app chunk=16 format=2 height=549000 module=statesync total=20
6:40PM INF Applied snapshot chunk to ABCI app chunk=17 format=2 height=549000 module=statesync total=20
6:40PM INF Applied snapshot chunk to ABCI app chunk=18 format=2 height=549000 module=statesync total=20
6:40PM INF Applied snapshot chunk to ABCI app chunk=19 format=2 height=549000 module=statesync total=20
6:40PM ERR State sync failed err="snapshot restoration failed: app version mismatch. Expected: 1, got: 0" module=statesync

### Version

 0.13.0, commit: 6ba60e18fec27d3e3a42a71be082e255913cf4cf

### Steps to Reproduce

SNAP_RPC="http://65.108.44.149:36657/";
LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height);
BLOCK_HEIGHT=$(($LATEST_HEIGHT - 4000));
TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash);
echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH

sed -i.bak -E "s|^(enable[[:space:]]+=[[:space:]]+).$|\1true| ;
s|^(rpc_servers[[:space:]]+=[[:space:]]+).$|\1"$SNAP_RPC,$SNAP_RPC"| ;
s|^(trust_height[[:space:]]+=[[:space:]]+).$|\1$BLOCK_HEIGHT| ;
s|^(trust_hash[[:space:]]+=[[:space:]]+).$|\1"$TRUST_HASH"|" $HOME/.celestia-app/config/config.toml

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
while we likely won't have time to debug this for the BSR, we will need to fix this in the future, so posting this note as I believe this is the source of the issue

https://github.com/celestiaorg/celestia-core/blob/34cd5ec4435ae404dd5f576a73c91481883291fd/statesync/syncer.go#L491-L498

**Comment by evan-forbes** [comment]
closing as this is an issue with changing the app version. As stated above, we will have to fix this when we increement the appversion
