### ISSUE TITLE
`share sequence has 1 shares but needed 0 shares`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1816]
## Problem

celestia-node v0.10.0
celestia-app [v0.13.0](https://github.com/celestiaorg/celestia-node/blob/cd8d0b9afd6dd982c43ab306cb9b160e985c6da1/go.mod#L12)

```
op-node_1      | t=2023-05-23T04:32:57+0000 lvl=warn msg="unable to retrieve data from da"        origin=0xcf84a6188
cecba28ad171b215075c2a63820894f5f57b5f9f32cba8f1fe5037d:1289 err="share sequence has 1 shares but needed 0 shares"
op-node_1      | t=2023-05-23T04:37:27+0000 lvl=warn msg="unable to retrieve data from da"        origin=0xf585a7578
b7472f6db418fedf4e7fb460b2c77aa367a33a5c32d48a615fdcd48:1307 err="share sequence has 1 shares but needed 0 shares"
op-node_1      | t=2023-05-23T04:39:27+0000 lvl=warn msg="unable to retrieve data from da"        origin=0xe3c84c695
bcc0403cf07e155a6ec44f3512fa2db9bd2176c6efd07acc8fc7245:1315 err="share sequence has 1 shares but needed 0 shares"
```

Full logs [here](https://media.githubusercontent.com/media/jcstein/logs/main/v0.10.0-logs.log). Originally reported by @jcstein

**Comment by rootulp** [comment]
I suspect that [this line](https://github.com/rootulp/celestia-app/blob/c00e268db4fdd3db99c0236876e3b852e6284f37/pkg/shares/shares.go#L102) is hit but it's difficult to verify without a repro.

**Comment by rootulp** [comment]
Confirmed this error gets hit if a share sequence exists where the first share is not a sequence start so I expect there's an issue with the raw share bytes.

**Comment by jcstein** [comment]
cc @tuxcanfly and linking https://github.com/celestiaorg/optimism/pull/56#issuecomment-1559486512

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/1827

**Comment by jcstein** [comment]
Flagging that I'm still seeing this in https://github.com/celestiaorg/optimism/pull/120#issuecomment-1563251192

**Comment by rootulp** [comment]
Sorry we also need to bump in celestia-node https://github.com/celestiaorg/celestia-node/pull/2257
