### ISSUE TITLE
Unjail command ignore default --keyring-backend option

### ISSUE THREAD

**Issue by Agronomistech** [celestiaorg/celestia-app#182]
## Summary of Bug

Command 
```
celestia-appd tx slashing unjail
```
ignore default value for option --keyring-backend, but in help show this default:

```
--keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "test")
```

## Version

Commit: ad4650a034e62312e2aa18eb429089fb4d66bdb3

## Steps to Reproduce

Run command:
```
celestia-appd tx slashing unjail --from <key>
```

And see error: 
```
Error: <key> info: key not found
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
If the slashing subcommand ignores the defaul keyring that would actually be a cosmos-sdk issue. Here is where the command is put together:
https://github.com/cosmos/cosmos-sdk/blob/56ab4e4c934365662162a91bcf35108a0bd78fef/x/slashing/client/cli/tx.go#L27

**Comment by evan-forbes** [comment]
closing for now, but if this is still an issue, we should open another issue upstream in the cosmos-sdk
