### ISSUE TITLE
Add the `Max` and `MinSquareSize` as a parameter to the payment module

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#183]
Currently, the `MaxSquareSize` constant has to be in celestia-core, but ideally, it should be a parameter in the app. This way, it doesn't require a hardfork to change, we only need 2/3 of the voting power to vote for a proposal using the gov module.

As celestia-core might need that constant and we cannot have import cycles, we can either manually mirror that parameter in celestia-core, or after we begin using ABCI++. It is possible that celestia-core will no longer need to know that constant, because the filling of the data square could happen entirely on the application side.

releated to #168

**Comment by rootulp** [comment]
`MaxSquareSize` was removed from celestia-core in https://github.com/celestiaorg/celestia-core/pull/861 and added to celestia-app in https://github.com/celestiaorg/celestia-app/pull/709 so this issue seems close-able.

**Comment by evan-forbes** [comment]
yeah, we still need to add this as a parameter. At the time of making this, it was unclear if we wanted to leave it as a constant to force a hardfork or if we want a param that can be changed by over two thirds of the voting power via the gov module. Now we want the latter.
