### ISSUE TITLE
Set up a mechanism that automatically comments on a PR that a task was re-run

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1838]
## Problem

Since we have flakey integration tests, PR authors often need to re-run failed CI workflows in order to get them to pass. It's not immediately obvious to a PR reviewer how many times a CI workflow was re-run before it passed.

## Proposal

Set up a mechanism that automatically comments on a PR that a task was re-run.

**Comment by evan-forbes** [comment]
thanks for writing up all these issues @rootulp !!

**Comment by MSevey** [comment]
pruning some old issues of mine. 
is this something at is still of interest @rootulp

**Comment by rootulp** [comment]
This was an action item from a meeting but TBH I didn't agree with the need for this. I'd rather we invest time in fixing the flakes than tooling around how many times a test was re-run.
