### ISSUE TITLE
Bump to the latest stable version of the cosmos-sdk

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#185]
We want to use the latest stable release of the cosmos-sdk, v0.44.5.

**Comment by liamsi** [comment]
Alternative: 
Not sure if it isn’t too early but there is a tagged version of the SDK that uses tendermint 0.35 btw: https://github.com/cosmos/cosmos-sdk/blob/428ae3c15c1729197291e2a3fe77013f255cefb5/go.mod#L50

Might be a good idea to at least explore if using that (or maybe at least the release candidates in between) until 0.46 of the SDK is released.

**Comment by evan-forbes** [comment]
can close since we've upgraded
