### ISSUE TITLE
Square Construction/Deconstruction Fuzzer

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#1859]
To effectively detect potential loopholes and bugs in the square construction, it would be beneficial to create a fuzzer. The primary objective of this fuzzer is to generate fuzz data that covers a range of variables, including transaction types, the number of transactions per type, transaction sizes, and square sizes. For each set of test data generated by the fuzzer, a square will be constructed, and subsequently deconstructed to verify its consistency.

**Comment by cmwaters** [comment]
Note that we do have https://github.com/celestiaorg/celestia-app/blob/main/pkg/square/square_fuzz_test.go
