### ISSUE TITLE
Deduplicate gas and fee estimation

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1868]
## Context

https://github.com/celestiaorg/celestia-app/blob/1ecde6d9e84930a3f091faea15655ed25fd61bf9/test/txsim/blob.go#L110-L124

https://github.com/celestiaorg/celestia-app/blob/1ecde6d9e84930a3f091faea15655ed25fd61bf9/pkg/appconsts/initial_consts.go#L16-L23

## Problem

celestia-node has a duplicate copy of this logic https://github.com/celestiaorg/celestia-node/blob/af8460aaee220162bbd7292a8df04c898fb34618/blob/helper.go#L84-L98

If celestia-node or celestia-app changes a variable in the gas or fee calculation, then the calculation will be inconsistent between the repos and may result in an error. In the most recent case, celestia-node used a `defaultMinGasPrice` of .001 when that value was changed to .1 in celestia-app

## Proposal

Expose an RPC method that estimates the gas and/or fees for a SubmitPayForBlob transaction 

cc: @distractedm1nd @vgonkivs

**Comment by cmwaters** [comment]
Can this be closed @rootulp ?

**Comment by rootulp** [comment]
It looks like the relevant code still exists on main in celestia-node [here](https://github.com/celestiaorg/celestia-node/blob/e354bb5414b5bde5b7b950f6b29a0419ca44214b/blob/helper.go#L84-L98). Do they still need this? Or can they leverage https://github.com/celestiaorg/celestia-app/blob/90f303cc2154adbcfd2e3f1c427baae6c6cc04c1/x/blob/types/payforblob.go#L170-L176

**Comment by rootulp** [comment]
This issue looks done because:
1. https://github.com/celestiaorg/celestia-node/blob/02030bf983ebf2311c54b771233b5c28bc133664/blob/service.go#L102
2. https://github.com/celestiaorg/celestia-node/blob/02030bf983ebf2311c54b771233b5c28bc133664/state/core_access.go#L216
3. https://github.com/celestiaorg/celestia-node/blob/02030bf983ebf2311c54b771233b5c28bc133664/state/core_access_test.go#L75
