### ISSUE TITLE
Expose helper to create a namespace given a < 10 byte namespace ID

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1883]
celestia-app already contains https://github.com/celestiaorg/celestia-app/blob/ddaa261b9b0dec5f5ea10dbfab4c8a03c95d7e72/pkg/namespace/namespace.go#L41-L43 so celestia-node can do:

```diff
		if !sameNID {
+			nid := appns.MustNewV0(tmrand.Bytes(appns.NamespaceVersionZeroIDSize)).Bytes()
-			nid, err := share.NewNamespaceV0(tmrand.Bytes(7))
-			if err != nil {
-				return nil, err
-			}
			appBlob.NamespaceVersion = nid[0]
			appBlob.NamespaceID = nid[1:]
		}
```

however, I see your point that this approach relies on consumers importing a const from celestia-app. I'm open to adding the following function to celestia-app's namespace package given it seems slightly easier to use from DevX perspective:

```go
// NewV0 returns a new namespace with version 0 and id based on subID. subID
// must be <= 10 bytes.
//
// Note: the namespace ID will be right-padded with 0s if subID is < 10 bytes.
func NewV0(subID []byte) (Namespace, error) {
	if lenSubID := len(subID); lenSubID > NamespaceVersionZeroIDSize {
		return Namespace{}, fmt.Errorf("subID must be <= %v, but it was %v bytes", NamespaceVersionZeroIDSize, lenSubID)
	}

	id := make([]byte, NamespaceIDSize)
	copy(id[NamespaceVersionZeroPrefixSize:], subID)

	ns, err := New(NamespaceVersionZero, id)
	if err != nil {
		return Namespace{}, err
	}

	return ns, nil
}
```

Note: it has been slightly modified from the `NewNamespaceV0` in this PR because it returns the `Namespace` type rather than `namespace.ID`. Is that okay for your use case? The motivation for the change is that this function will be defined in the celestia-app `namespace` package which ideally has functions that deal with [Namespace](https://github.com/celestiaorg/celestia-app/blob/ddaa261b9b0dec5f5ea10dbfab4c8a03c95d7e72/pkg/namespace/namespace.go#L8-L11) and not nmt's namespace.ID

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-node/pull/2269#discussion_r1210310411_
           
cc: @distractedm1nd @Wondertan @vgonkivs

**Comment by rootulp** [comment]
Contrary to the issue and discussion above, @jcstein pointed out that it would be more intuitive to **left pad** the namespace ID with leading `0`s.

**Comment by jcstein** [comment]
yep, to provide more context, I'd imagine most folks would prefer that if they are currently using something with nsid `08e5f679bf7116cb`, they would expect it to become `000008e5f679bf7116cb` not `08e5f679bf7116cb0000`

for example, if using function that uses 8 byte, and left padding is what we choose, they’ll have to do less (maybe nothing) to debug integration

if same function and right padding, will most likely need to rework functions in integration
