### ISSUE TITLE
Test for the ability to include transactions in the first block

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1899]
Currently, we have never tested that transactions can actually be included in the first block. We also have issues with accessing the state in PrepareProposal, that's why we have these lines

https://github.com/celestiaorg/celestia-app/blob/9bf0cf1dd9ce31a3fecb51310c3913820b21a8c2/app/square_size.go#L11-L19

If we can't actually process txs in the first block, and there ends up being transactions in the mempool, then we could end up with a "frustrated" start to the chain where we won't be able to create a block until a block producer creates an empty one.

**Comment by cmwaters** [comment]
Have we looked to see how much work it would be to copy over the cosmos-sdk's solution since I don't think they have this problem?

Specifically they have their own `prepareProposalState` and `processProposalState`

**Comment by staheri14** [comment]
> Have we looked to see how much work it would be to copy over the cosmos-sdk's solution since I don't think they have this problem?

> Specifically they have their own prepareProposalState and processProposalState

We haven't identified the underlying cause of the problem yet. Could you please share your perspective on how copying over the prepareProposalState and processProposalState functions will address the issue?

**Comment by staheri14** [comment]
Progress related to this issue is documented on the following Notion page: [Including Transactions in the First Block](https://www.notion.so/celestiaorg/Including-transactions-in-the-first-block-704ea09d81bf4b4f901b232553236889).

**Comment by evan-forbes** [comment]
the linked notion is a great analysis. It appears that it will be very difficult to get a tx included in the first block. So difficult that a validator would have to build a separate binary. 

In an abundance of caution, imo we should still add the hacky yet simple check in `PrepareProposal` that returns zero tx and the empty data root. I doubt we could ever git in a scenario where it could get hit, but it would avoid the worst case scenario described above where proposers would progressively panic

**Comment by staheri14** [comment]
> In an abundance of caution, imo we should still add the hacky yet simple check in PrepareProposal that returns zero tx and the empty data root. I doubt we could ever git in a scenario where it could get hit, but it would avoid the worst case scenario described above where proposers would progressively panic

Sounds good to me too, please see the tracking issue #2221

**Comment by evan-forbes** [comment]
I think we can close with #2233

**Comment by staheri14** [comment]
An update on Evan's last comment: The PR that addressed this issue is https://github.com/celestiaorg/celestia-app/pull/2220 (but not https://github.com/celestiaorg/celestia-app/pull/2233, that one is related to a different issue i.e., https://github.com/celestiaorg/celestia-app/issues/2221).
