### ISSUE TITLE
x/payformessage: Write simulations

### ISSUE THREAD

**Issue by marbar3778** [celestiaorg/celestia-app#190]
Payformessage is missing simulation testing

Usually this is used to find tests and help with overall design. Highly recommend adding them
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
ref #24

**Comment by marbar3778** [comment]
ah okay can close this then.
