### ISSUE TITLE
Handling multiple blobTxs in a block

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1910]
### Summary

It will be typical in most cases that a rollup will be producing blocks faster than Celestia network finalizes them (the network will initially be aiming for 15 second block times). This brings about a set of potential UX problems that we should look to address. Perhaps the most important has to do with nonces.

### Problem Definition

PFB A is submitted before PFB B but B has a higher fee and hence has greater priority. The block producer naively orders them as PFB B and then PFB A. Both get rejected because their nonce numbers are invalid thus both get dropped

### Proposal

There are a few possible solutions:

Group transactions together by signer, using a weighted gas price to indicate the priority of the bundle of txs. The bundle would contains transactions ordered by their nonce. This would have the property that either all transactions would make it or none. We could cap the bundle size before a new bundle was created. It's likely that the gas price will be very similar but if the gas price was different from blobTx to blobTx this could have mixed results.

Taking the list of txs ordered by priority, the proposer would loop through all transaction, popping out any transaction that had an incorrect nonce and tracking the latest nonce of all the signers involved in the proposed block. It would then attempt to push the transaction back into the list after the tx with the correct nonce.

If blobTx order isn't so important to the rollup (it can interpret its own ordering of the transactions) then we could also look to use nonce lanes. If a sequencer submits 10 blobs per 1 Celestia blob, it could use 10 different lanes to divide it's txs across, that way the success of one transaction does not affect the success of others. (See https://github.com/cosmos/cosmos-sdk/issues/13009)

cc @nashqueue 

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nashqueue** [comment]
What are our current options for handling multiple PFBs per Block? What is the Limit for how many blobs fit into a PFB ?

**Comment by cmwaters** [comment]
> What is the Limit for how many blobs fit into a PFB ?

There is no current limit (so long as the blobs can fit in a square)

> What are our current options for handling multiple PFBs per Block?

I think the best solution is a combination of reordering prioritised txs such that the sequencer numbers for each account is ordered and using nonce lanes
