### ISSUE TITLE
Look into more intuitive ways to sign malleated transactions

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#192]
Currently, we use the [`KeyringSigner`](https://github.com/celestiaorg/celestia-app/blob/b4c8ebdf35db200a9b99d295a13de01110802af4/x/payment/types/builder.go#L18-L28) to programmatically sign malleated transactions. This is because the standard cosmos-sdk `tx.Factory` does not support creating multiple malleated transactions and then signing over those as well. We might be able to refactor `KeyringSigner` so that it's more intuitive.

**Comment by marbar3778** [comment]
This is a code smell imo. Duplicating code from the sdk and then seeing comments like 

```
// makeEncodingConfig is copied here so that we don't have to have an
//  import cycle. if possible, use cosmoscmd.MakeEncodingConfig
```

make me a bit worried that the design is incorrect. 


would be nice to remove the testutil/netowrk.go setup as well. Customising the app breaks this because its not automatic in how the app is set up.

**Comment by evan-forbes** [comment]
closing as this is a duplicate of #294, which we will finally be able to handle now that we can simplify the malleation process.
