### ISSUE TITLE
QGB Decide on a `SignificantPowerDifferenceThreshold` upper bound

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/celestia-app#1920]
I guess 5% errs on the side of caution but the upper bound might be something like 33% or 1/3. I haven't spent too much time thinking about the attack vectors here but it might be good to eventually write them up as a form of rationale

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/pull/1911#discussion_r1229267025_

**Comment by evan-forbes** [comment]
fwiw as long as it doesn't change to something higher than it is now, I think we could add this in a non-consensus breaking way

**Comment by SweeXordious** [comment]
I guess it should be higher so the change is not consensus breaking, if i understand right

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
