### ISSUE TITLE
CLI GRPC queries are not working in v1.0.0-rc3

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1925]
When attempting any stateful query, we get 
```
Error: rpc error: code = InvalidArgument desc = failed to load state at height 49788; version does not exist (latest height: 49788): invalid request
```
The same error occurs even if we query old state

**Comment by cmwaters** [comment]
Do we not have any current tests for this?

**Comment by evan-forbes** [comment]
we make frequent use of stateful grpc queries in our tests, which is the weird thing. for example in the square size test we query for params such as GovMaxSquareSize, yet

`celestia-appd q params subspace blob GovMaxSquareSize` from the cli will result in the above error
