### ISSUE TITLE
Non PFB txs need also pass validity checks

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1937]
### Problem

In `PrepareProposal` and `ProcessProposal` we have a two sets of checks using the `sdk.Antehandler`: one for non pfbs and one for pfbs. The non pfb antehandler simply increments the nonce. This is so the second antehandler which checks the signatures and nonce has a correct view of state. However, this falsely makes the assumption that the non pfb transactions prior were all valid and thus would be executed. In a scenario where the non pfb tx is invalid, the nonce is not actually incremented thus what was potentially a valid PFB is now invalid

### Proposal

The solution to this is to have both txs run the full `Antehandler` thus we can ensure that every tx that gets past consensus (i.e. reaches quorum) will be able to be executed in `DeliverTx`. 

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
> In a scenario where the non pfb tx is invalid, the nonce is not actually incremented

mind elaborating on this scenario more? What mechanism is stoping the nonce from being incremented for invalid signatures?

**Comment by cmwaters** [comment]
> mind elaborating on this scenario more? What mechanism is stoping the nonce from being incremented for invalid signatures?

The antehandler fails fast so it returns at the first error. As the nonce incrementing decorator is the last decorator it won't be hit meaning the nonce won't be incremented
