### ISSUE TITLE
More consistent var names in the spec for byte types

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1938]
[Suggestion-optional] All the other size variables are `_BYTES` suffixed, considering this, can we also use the same suffix for the `NAMESPACE_SIZE` i.e., `NAMESPACE_BYTES` (for consistency)?

_Originally posted by @staheri14 in https://github.com/celestiaorg/celestia-app/pull/1880#discussion_r1230255954_

**Comment by rootulp** [comment]
On re-read it looks like all the sizes in https://github.com/celestiaorg/celestia-app/blob/7989d889798bdb063ec152370ba3471f3c765d83/pkg/namespace/consts.go#L11-L32 are suffixed with `*Size`. 

I think it may make more sense to rename the suffix of constants in https://github.com/celestiaorg/celestia-app/blob/7989d889798bdb063ec152370ba3471f3c765d83/pkg/appconsts/global_consts.go#L15-L73 to use `*Size` instead of `*Bytes` where applicable

**Comment by staheri14** [comment]
Based on my understanding, it seems that the names of the constants in  [constants.md](https://github.com/celestiaorg/celestia-app/blob/202852f5b46eec73e116f022c76ae87bc7d3d377/specs/src/specs/consensus.md#constants) may not directly correspond to the names of the constants in the Go code. If this is the case, there is no requirement to modify the constant names in the Go code (hence making API-breaking changes). The changes would only need to be made in the specifications document. WDYT?

**Comment by rootulp** [comment]
Agreed, not all the constants in constants.md match the Go code but IMO they should.

**Comment by staheri14** [comment]
> Agreed, not all the constants in constants.md match the Go code but IMO they should.

Honestly, I don't have a strong opinion on whether the names should be aligned in the go code and the specs. On one hand, consistent names make it easier to link concepts from the specs to the go code. On the other hand, if we integrate proper links from the spec constants to the go constants, that could also work. It's totally up to you to decide what approach works best.
