### ISSUE TITLE
Create IBC connection to another testnet chain

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#195]
As a default, starport chains have the ability to use IBC. We should be able to start a relayer and connect to another chain.

**Comment by evan-forbes** [comment]
currently blocked on mamaki by #412

**Comment by rootulp** [comment]
I'm working on this with notes captured in Notion [here](https://www.notion.so/celestiaorg/Testnet-IBC-0403673617324b3abf58b2c8d2050a88), I'm attempting to test Cosmos Hub testnet <> mocha-4 but I'm currently hitting https://github.com/informalsystems/hermes/issues/3620 . I was able to successfully test Cosmos Hub testnet <> Osmosis testnet.

**Comment by rootulp** [comment]
Made Notion notes public in [this Gist](https://gist.github.com/rootulp/6dd1d298d92f347a349d0e9d92a7519c). 

Example token transfer mocha-4 to Cosmos Hub: https://testnet.mintscan.io/celestia-testnet/txs/C3767DCAA4880DF7CD7A9EAE82CDF02E9A81D516B7548EBF2CDCAC9750C88886?height=78794

Example token transfer Cosmos Hub to mocha-4: https://testnet.mintscan.io/cosmoshub-testnet/txs/B9ACC78B86DDA84B9B3263B9EC1A7311A12F88B44F65B21B5520866C292A43FF?height=17936858

Mintscan doesn't show IBC tokens from mocha-4 on Cosmos Hub testnet but I sent them an email to ask why not. I expect they need to officially recognize the connection.

Created a PR to add the connection to chain-registry: https://github.com/cosmos/chain-registry/pull/2850
