### ISSUE TITLE
Export function to go from block data to EDS

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1952]
there's a [function](https://github.com/celestiaorg/celestia-node/blob/6654cdf4994dbd381efd0d6a29688c731177c855/core/eds.go#L19-L38) in celestia-node that we can move most of to the application

```go
// extendBlock extends the given block data, returning the resulting
// ExtendedDataSquare (EDS). If there are no transactions in the block,
// nil is returned in place of the eds.
func extendBlock(data types.Data) (*rsmt2d.ExtendedDataSquare, error) {
	if len(data.Txs) == 0 && data.SquareSize == uint64(1) {
		return nil, nil
	}

	sqr, err := square.Construct(data.Txs.ToSliceOfBytes(), appconsts.LatestVersion, share.MaxSquareSize)
	if err != nil {
		return nil, err
	}

	shares := make([][]byte, len(sqr))
	for i, s := range sqr {
		shares[i] = s.ToBytes()
	}

	return da.ExtendShares(shares)
}
```

note that I'm unsure if we should move the node specific logic on lines 23-25, as that's node specific logic, which feels like at initial glance that it should stay in node so they can change it if necessary without making changes here

**Comment by evan-forbes** [comment]
@renaynay please feel free to edit the above issue or comment here if there is missing context or we should move other portions here

**Comment by rootulp** [comment]
Note: the `Share` type was previously a byte slice. In https://github.com/celestiaorg/celestia-app/pull/1462 it was switched to a struct to enforce invariants (length of the byte slice).
