### ISSUE TITLE
test: skip data race tests without using `-short` flag

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1964]
## Context

https://github.com/celestiaorg/celestia-app/issues/1369 and https://github.com/celestiaorg/celestia-app/pull/1958#pullrequestreview-1486870364 

## Problem

The `-short` flag is used on this line: https://github.com/rootulp/celestia-app/blob/aa01da8c6d4ab46c5cdafd50ccc95749aa2a01c6/Makefile#L111

## Proposal

1. Remove the `-short` flag from the line above because the `-short` flag mechanism should be used to skip long running tests, not tests that have data races.
2. [short term] use a different mechanism to skip tests that have identified data races
3. [long term] fix https://github.com/celestiaorg/celestia-app/issues/1369 by root causing all data races

**Comment by rootulp** [comment]
We may consider the `-skip` flag from `go help testflag`:

```
	-skip regexp
	    Run only those tests, examples, fuzz tests, and benchmarks that
	    do not match the regular expression. Like for -run and -bench,
	    for tests and benchmarks, the regular expression is split by unbracketed
	    slash (/) characters into a sequence of regular expressions, and each
	    part of a test's identifier must match the corresponding element in
	    the sequence, if any.
```

**Comment by evan-forbes** [comment]
since we don't have direct access to build flags in runtime, in the past we've also considered using build flag switches (add an init to a module that will flip a bool to false that is protected by a build flag)
