### ISSUE TITLE
Add nightly testing workflows

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1968]
### Summary

We have written some good integration and fuzz tests which are significant in duration such that we've chosen not to run them in CI per each PR. It would however be beneficial that we continue to run these batch of tests.

### Proposal

Create a workflow (that can also be manually triggered) that runs every night or couple of nights that runs:

- The larger integration tests that use the `knuu` framework
- Our fuzz tests. Each can run for a set amount of time (perhaps 10minutes)

**Comment by evan-forbes** [comment]
closing as completed
