### ISSUE TITLE
Copy over portions of the gravity module

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#197]
The [QGB](https://github.com/celestiaorg/quantum-gravity-bridge) will necessitate several additions to the app. The largest of which is copying over portions of the gravity module. 

Since the the QGB is only a one way bridge and is not transferring assets, it doesn't require the portions of the gravity module that recreate state from the bridged chain. We only need to keep things relating to signing over the validator set (such as [`MsgSetOrchestratorAddress`](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/7a786d2ba999b45292c976282cf2aa88ba4cbba9/module/proto/gravity/v1/msgs.proto#L56-L73) and [`MsgValsetConfirm`](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/7a786d2ba999b45292c976282cf2aa88ba4cbba9/module/proto/gravity/v1/msgs.proto#L77-L97)) and relayer queries (such as [`ValsetConfirm`](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/7a786d2ba999b45292c976282cf2aa88ba4cbba9/module/proto/gravity/v1/query.proto#L27-L29) and [`GetDelegateKeyByOrchestrator`](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/7a786d2ba999b45292c976282cf2aa88ba4cbba9/module/proto/gravity/v1/query.proto#L81-L83))

tracking issue [#44](https://github.com/celestiaorg/quantum-gravity-bridge/issues/44)

**Comment by SweeXordious** [comment]
@evan-forbes I guess for the QGB, it makes sense to start with this issue and similar ones in `celestia-app` before moving to the rest.
Will start drafting this and see. What do you thin? ?

**Comment by evan-forbes** [comment]
to follow up a sync discussion with @SweeXordious, we decided that this issue is a good starting point, and that the step to completing this issue is to first scaffold out:

- a new `qgb` module, including initializing the app with this module installed
- Copy over the `[ValSetConfirm](https://github.com/Gravity-Bridge/Gravity-Bridge/blob/7a786d2ba999b45292c976282cf2aa88ba4cbba9/module/proto/gravity/v1/query.proto#L27-L29)` proto message
- create the proto message for Confirming `DataCommitments`
- and lastly we should scaffold out the keepers (but not actually introduce any state changes!)

The gravity module currently has confirmation messages change the state by mapping the orchestrater's address to the confirmation, but since we are only a two way bridge, potentially without any slashing, we might not want to change state at all. Instead, we could simply emit an event upon the successful submission.

**Comment by evan-forbes** [comment]
reopening as #208 was only the first half

**Comment by SweeXordious** [comment]
@evan-forbes The https://github.com/celestiaorg/celestia-app/pull/218 and https://github.com/celestiaorg/celestia-app/pull/219 should contain the last changes needed to close this issue.
For the `ValsetConfirm`, it is changing state and also emitting an event. We can keep that logic as it will be handy later on. 
Please take a look when you have time. So that I can start working on: https://github.com/celestiaorg/celestia-app/issues/199

**Comment by SweeXordious** [comment]
@evan-forbes This issue can be closed now. What do you think ?

**Comment by evan-forbes** [comment]
We can close this optimistically, but we might have to reopen if we for some reason don't merge the `qgb-integration` branch to master.

**Comment by SweeXordious** [comment]
Agreed, sounds good. Thank you
