### ISSUE TITLE
MinGasPFBDecorator should also be run in ProcessProposal

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1971]
### Summary

https://github.com/celestiaorg/celestia-app/pull/1936 introduced a new decorator to ensure that PFBs provide a minimum amount of gas to cover for the bytes they are paying for. It would be consensus breaking to include this in `ProcessProposal` so the check initially only covers `CheckTx`. In v2, and once we upgrade SDK (so we can check the state that we call `runtx` in), we should introduce this decorator in `ProcessProposal`.

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
what are the benefits of running this in process proposal?

**Comment by evan-forbes** [comment]
but can they still include zero fee transactions?

**Comment by cmwaters** [comment]
> but can they still include zero fee transactions?

Yes so long as their is no fee mechanism (i.e. they can have a tx with the correct amount of gas but a gas-price of 0). But in the future, I assume we will put in place some fee mechanism that doesn't permit zero-fee transactions

**Comment by cmwaters** [comment]
> I see so we just don't need to worry about this until we have a min fee?

kind of, although there's technically already a min fee. It's just on a per validator basis so I think we should still fix this as soon as possible

**Comment by evan-forbes** [comment]
> It's just on a per validator basis so I think we should still fix this as soon as possible

I'm still unsure of what this adds, since a validator can still include arbitrarily priced txs. This won't contribute to the same issue as #1937 correct?

**Comment by cmwaters** [comment]
Sure but I'm assuming that celestia eventually wants some sustainable economic model and when that happens we need to close off all the ways that users can cut corners. I'd rather adopt this now then have to wait for the next breaking release.
