### ISSUE TITLE
update description of repository

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-app#1998]
### Summary

The description reads "PoS chain powered by celestia-core (fork of tendermint) and the cosmos-sdk", but should read "PoS chain powered by celestia-core (fork of comet-bft) and the cosmos-sdk"

### Problem Definition

The description is just a bit outdated

<img width="590" alt="Screenshot 2023-06-28 at 12 14 46 AM" src="https://github.com/celestiaorg/celestia-app/assets/46639943/2fad2dac-3765-4b85-9582-17afa6b64b59">
<img width="318" alt="Screenshot 2023-06-28 at 12 14 41 AM" src="https://github.com/celestiaorg/celestia-app/assets/46639943/c1286955-2b8c-4bd3-a49d-fa7a45a65d37">

### Proposal

Update it

**Comment by rootulp** [comment]
It looks like only a repo admin can edit the **About** section 😞

**Comment by evan-forbes** [comment]
changed to "PoS application for the consensus portion of the Celestia network. Built using celestia-core (fork of CometBFT) and the cosmos-sdk"

but tbh we can probably do better. before that I don't think it has been updated since Jan 2021 LOL

**Comment by evan-forbes** [comment]
closing for now, but if anyone has suggestions we should discuss somewhere
