### ISSUE TITLE
Create a cli command to fill some portion of the block using `txsim`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2011]
Filling the block for testnets is a frequent enough occurance that we should create a cli command for it. We already have the [`txsim`](https://github.com/celestiaorg/celestia-app/tree/main/test/txsim), which does exactly this. Therefore we should create a cli command that runs a txsim process to fill the block to a given %.

**Comment by starlabman** [comment]
import subprocess
import sys

def fill_block_cli(percentage):
    # Convert percentage to a decimal value
    fill_percentage = float(percentage) / 100

    # Calculate the target block fill limit
    block_limit = int(fill_percentage * 1000000)  # Assuming a block size of 1,000,000 gas limit

    # Run the txsim command to fill the block
    cmd = f"txsim --blocklimit {block_limit}"
    subprocess.call(cmd, shell=True)

if __name__ == "__main__":
    # Check if the percentage is provided as a command line argument
    if len(sys.argv) > 1:
        percentage = sys.argv[1]
        fill_block_cli(percentage)
    else:
        print("Please provide the fill percentage as a command line argument.")
