### ISSUE TITLE
Stop overwriting chain-id in testnode

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2026]
Currently, we're overwriting the configured chain-id in testnode. We should use the configured chain-id and rely on the default to set the initial random value instead.

https://github.com/celestiaorg/celestia-app/blob/965eafb4357376aec31f84f3628f7703c5587f9a/test/util/testnode/full_node.go#L171-L174

**Comment by Frenzoid** [comment]
Fixed on this PR :) 
https://github.com/celestiaorg/celestia-app/pull/2035
