### ISSUE TITLE
All transactions from fuzz_abci_test filtered out

### ISSUE THREAD

**Issue by ivan-gavran** [celestiaorg/celestia-app#2027]
### Summary of Bug

The test `celestia-app/app/test/fuzz_abci_test.go` passes in checking that every proposed block is accepted, but trivially: all the transactions get filtered out. The failure happens on  the antehandler [VerifySignature](https://github.com/ivan-gavran/cosmos-sdk/blob/fae3332d62fc59bea7c97d8105533c83a6c6919a/x/auth/ante/sigverify.go#L293-L293).

### Version

ce0be9516e6e7292cf41f7a073b55fab8346ca3f

### Steps to Reproduce

In the fork of the repo ([here](https://github.com/ivan-gavran/celestia-app/tree/ivan/square_size_test)), I added logs before and after filtering transactions to show how all of them get filtered out.

Run: `go test -v  -run TestPrepareProposalConsistency`

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
great catch, thank @ivan-gavran!
