### ISSUE TITLE
Test that message size is actually the size of the message in integration tests

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#203]
We are checking and testing that the message size matches the size described in the message via the validate basic method of `MsgWirePayForMessage`, but since this is so important, we should also test for this in integration tests.

related to #201

**Comment by Stergios13** [comment]
Hello. Can i work on this? Happy to help!!

**Comment by evan-forbes** [comment]
thanks for interest and quick response @Stergios13 !! 

after thinking about this a bit longer, I remembered that this isn't actually true, as the [validate basic](https://github.com/celestiaorg/celestia-app/blob/5109ffc181a6550b68e271caa65fcd4915934138/x/payment/types/wirepayformessage.go#L88-L95) method covers this. We even have a [test](https://github.com/celestiaorg/celestia-app/blob/5109ffc181a6550b68e271caa65fcd4915934138/x/payment/types/payformessage_test.go#L277-L282) for this. That being said, since this is so important, we could always check this in a more integrative way, for example, we could test [here](https://github.com/celestiaorg/celestia-app/blob/master/app/abci_test.go) and/or [here](https://github.com/celestiaorg/celestia-app/blob/master/x/payment/client/testutil/integration_test.go)

If you are interested in that, definitely let me know and I'll assign you. If you have any questions be sure to reach out in the respective issues or ping me on discord! We also have some other beginner issues that we would be really happy to get contributions for if this doesn't sound interesting

**Comment by quinle** [comment]
@evan-forbes Can I pick up this issue? Thanks

**Comment by YazzyYaz** [comment]
Hi @Stergios13 thanks for reaching out, are you interested in contributing to this ticket or any of our open beginner-friendly tickets?

**Comment by evan-forbes** [comment]
closing as this is already handled
