### ISSUE TITLE
Update the `data_structures.md` portion of the spec

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2037]
Currently, we have duplicate or outdated information in the data structures portion of the spec. We should update it to not have duplicate info and instead point to the relevant portions of the refactored spec. Then we should also remove all things that are not strictly the most up to date data structures (assuming there are any that are not covered elsewhere)

**Comment by rootulp** [comment]
Closing this b/c duplicate of https://github.com/celestiaorg/celestia-app/issues/3113 which has more recent information.
