### ISSUE TITLE
Document need for `GetModuleAccount`

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#2042]
## Context

https://github.com/celestiaorg/celestia-app/blob/65046dd363fd5b50d9cfc8d83290c28de10a22a2/x/mint/keeper/genesis.go#L17

## Problem

This line is not used for anything and can be removed.

## Proposal

Remove the line

**Comment by rootulp** [comment]
+1 appears residual from https://github.com/cosmos/cosmos-sdk/blob/d9800d9c752104a19343fda8837766b7cf3bbfd1/x/mint/keeper/genesis.go#L18

**Comment by rootulp** [comment]
Wow `.GetModuleAccount` is a misleading name. Apparently this function has side-effects that we need to preserve. See https://github.com/cosmos/cosmos-sdk/issues/16863#issuecomment-1625139456

Instead of removing the line, proposal to document why the line is necessary as a code comment
