### ISSUE TITLE
Test continually timing out in CI

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#2050]
### Summary

The following test seems to continually timeout. Locally it only takes 1 and half minutes. See [here](https://github.com/celestiaorg/celestia-app/actions/runs/5487872708/jobs/9999936348?pr=2049) for one of the actions

```
panic: test timed out after 10m0s
running tests:
	TestSquareSizeIntegrationTest (2m16s)
	TestSquareSizeIntegrationTest/TestSquareSizeUpperBound_Flaky (2m10s)
	TestSquareSizeIntegrationTest/TestSquareSizeUpperBound_Flaky/gov_square_size_==_hardcoded_max (39s)
```

### Proposal

Either we need to increase the timeout or modify the tests such that it doesn't take as long.

**Comment by rootulp** [comment]
@cmwaters can this issue be closed? https://github.com/celestiaorg/celestia-app/actions/runs/5532493131/jobs/10094665538?pr=2089 doesn't appear to time out on test.
