### ISSUE TITLE
Document the `mint` module panics

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#2068]
It would be good to document in the `mint` module README all the panics that can occur in the module.

**Comment by rootulp** [comment]
I just started writing this in the README...

```markdown
### `panic`s

This module can panic in the following scenarios:

- When the keeper fails to get the genesis time or minter from the key-value store.
- When the keeper is created prior to a mint module account.
```

but I don't think the maintenance burden of these docs outweighs the benefit. I think the docs are likely to get out of date with respect to the implementation. If a reviewer is interested in learning when the x/mint module panics, they can CTRL + F for occurrences of `panic()` in the codebase. These scenarios are all extremely unlikely b/c they would cause a chain halt.
