### ISSUE TITLE
Remove `fullNamespace`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2071]
## Context

https://github.com/celestiaorg/celestia-app/blob/5bcf4ad51756e5f31dd7d9ea140844063b6ce391/pkg/square/builder.go#L361-L364

## Prerequisites
- [x] Merge https://github.com/celestiaorg/celestia-core/pull/1030 
- [x] Cut a new release of celestia-core: https://github.com/celestiaorg/celestia-core/releases/tag/v1.25.0-tm-v0.34.28

## Proposal
1. Bump to the new release of celestia-core
2. Replace usage of `fullNamespace` in celestia-app with celestia-core's exported `Namespace` method

**Comment by MariusTanase** [comment]
I'm not aware of the codebase but I assume that the feat: add Namespace method to blob will work as intended(in the merge)

As for the Proposal 2, I'm assuming that this function will do the trick

func fullNamespace(blob core.Blob) []byte {
	return blob.Namespace()
}

Let me know if you have any bug.
