### ISSUE TITLE
Export function to determine max blob bytes in a block

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2108]
## Context

celestia-node would like to add a validation step on blobs that checks that the blob size does not exceed the maximum possible bytes that a single blob can occupy in a block.

## Proposal

Export a function from celestia-app that informs celestia-node what is the maximum possible bytes in a block. The amount of data in a block is constrained by two parameters (see [ADR-021](https://github.com/celestiaorg/celestia-app/blob/e06116cb4cd2b3d535fc5de0df9e192bb6902692/docs/architecture/adr-021-restricted-block-size.md#decision)): `MaxBytes` and `GovMaxSquareSize`.

Rough steps:
1. Learn the current value for the params `GovMaxSquareSize` and `MaxBytes`. Note celestia-node has access to the celestia-app version but both these params are governance modifiable so they require a state access
2. Compute the max blob size that can fit into `GovMaxSquareSize` 
3. Compute the max blob size that can fit into `MaxBytes`
4. Take the minimum of steps 2 and 3

cc: @Wondertan @renaynay @musalbas

**Comment by rootulp** [comment]
I think the proposed function will return an upper bound for blob size but it won't be an exact maximum size due to the number of bytes occupied by the PFB tx. In other words, smaller blobs than this upper bound may also be invalid. 

We should consider fuzz testing by attempting to submit blobs of various sizes and confirming that blob sizes > the returned value from the proposed function(s) are never included in a block.

**Comment by Wondertan** [comment]
@rootulp, I am fine with such solution initially. Still, would be nice to think of the long term approach and if not complicated to aim to implement it first.

The stateful approach is annoying, but we can keep it inside stateful blob.Service. It already imports chain state methods and can query any param on start and reuse it throughout its lifespan.

**Comment by rootulp** [comment]
> we can keep it inside stateful blob.Service

Specifically https://github.com/celestiaorg/celestia-node/blob/main/blob/service.go ? 

> can query any param on start

Does it already do this? Can you please link to an example? I'm not sure how celestia-node knows which major version of celestia-app it is connected to?

**Comment by Wondertan** [comment]
My bad, I mean technically/in-theory can. It does not do this right now. The BlobSubmitter api can be extended with MaxBlobSize or something method that it could use.

**Comment by evan-forbes** [comment]
This was discussed with @rootulp synchronously, but I think the best approach here is to validate the size of the blob statelessly using validate basic, and then adding an antehandler that will check the tx size using the stateful parameters upon submission.

This way we get protection locally before we even submit the blob, and then final protection at the mempool level that is stateful

**Comment by Wondertan** [comment]
Agree with the decision. Only wonderting how stateless verification would work then or how what error will it incorporate

**Comment by rootulp** [comment]
> how stateless verification would work

A stateless check on blob size can validate that the blob is < max blob size where max blob size is based on the upper bounds for max square size and max block bytes.
