### ISSUE TITLE
keplr/arabica-9: tx send is failing 

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#2112]
### Summary of Bug

We can't send a simple tx in arabica-9 through keplr. 
What is the base fee? It seems like the keplr's fee is not suited I suppose

### Version

v1.0.0-rc7

### Steps to Reproduce

1. Connect through keplr wallet to arabica-9 chain
2. [Fund account in faucet](https://faucet-arabica-9.celestia-arabica.com/)
3. Send a sample tx from keplr account
4. Select highest fee (4443 utia) 
5. Confirm TX

```json
{
  "account_number": "4033",
  "chain_id": "arabica-9",
  "fee": {
    "gas": "111062",
    "amount": [
      {
        "amount": "4443",
        "denom": "utia"
      }
    ]
  },
  "memo": "",
  "msgs": [
    {
      "type": "cosmos-sdk/MsgSend",
      "value": {
        "amount": [
          {
            "amount": "1000000",
            "denom": "utia"
          }
        ],
        "from_address": "celestia1uglava8p4fxefvtejtnuwvyfvd2plcd8jj2nws",
        "to_address": "celestia145ghvz4hnytqz8utu4jwthsmedhrg42f0hsq0e"
      }
    }
  ],
  "sequence": "0"
}

```

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Bidon15** [comment]
Some screenshot of the fees option in Keplr for arabica-9 chain
![Screenshot 2023-07-17 at 14 47 34](https://github.com/celestiaorg/celestia-app/assets/1822365/3062cd97-8edf-43ce-b797-986815fec362)



Re: https://github.com/celestiaorg/docs/pull/882

**Comment by Bidon15** [comment]
> walkthrough of adding `arabica-9` as experimental from our docs, then bug sending tx
> 
> https://loom.com/share/b0995a40c337499c962b9493fdacf833?sid=4df11b5a-2d9a-4ae9-a55c-cc920a154103

I can't find in keplr api docs how to change fees. @jcstein do you have any ideas how we adapt them to 11k at least which @cmwaters has mentioned above?

**Comment by cmwaters** [comment]
Yes, I would suggest the following:

```
gasPriceStep: {
     low: 0.1,
     average: 0.2,
     high: 0.4,
},
```

It's essentially just one magnitude more than the current gas prices

**Comment by cmwaters** [comment]
Are we able to mark this as resolved now @Bidon15 @jcstein ?

**Comment by jcstein** [comment]
gm @cmwaters - yep. just merged PR to update docs 🫡
