### ISSUE TITLE
docker: Prettify comment sections in Dockerfile and Dockerfile.ephemeral.

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#2117]
It's a copy-cat from Dockerfile and Dockerfile.ephemeral. 
I guess a follow-up PR will fix other Dockerfiles. 

Editing this one, tho

_Originally posted by @Bidon15 in https://github.com/celestiaorg/celestia-app/pull/2052#discussion_r1266621067_

```[tasklist]
### Tasks
- [ ] Edit comments like `# stage 1 .....` and `# stage 2` in DockerFile and DockerFile ephemeral to the style like in tx simulator
```

**Comment by rootulp** [comment]
There is no longer Dockerfile.ephemeral but there are two Dockerfiles that could use improved comments:
1. Dockerfile
2. Dockerfile_txsim

The Dockerfile for testground seem really helpful and could be used for inspiration.

**Comment by rootulp** [comment]
Honestly going to ignore the txsim Dockerfile b/c it's not as important as the other one.
