### ISSUE TITLE
chore: following semantic line breaks in documentations 

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2123]
# Problem
The following issue is more of a suggestion than a problem.
I'd like to recommend incorporating [semantic line breaks](https://sembr.org/) into our documentation. The concept involves strategically placing line breaks at semantic boundaries. In markup languages like Markdown, single line breaks are typically invisible to readers, however, it offers several advantages to the authors and editors, as highlighted in the link provided:

> Why Use Semantic Line Breaks?
For a writer, semantic line breaks allow the physical structure of text to reflect the logical structure of the thoughts that produce them.
> For an editor, semantic line breaks make it easier to identify grammatical mistakes and find opportunities to simplify and clarify without altering original intent.
> For a reader, semantic line breaks are entirely invisible — no changes to the source text appear in the final rendered output.

# Proposal
Once/If the decision to implement semantic line breaks is finalized, we can update the relevant [section](https://github.com/celestiaorg/celestia-app#docs) to reflect this choice and effectively communicate it with the team.

**Comment by staheri14** [comment]
cc: @evan-forbes @MSevey @rootulp @cmwaters @SweeXordious @mojtaba-esk

**Comment by rootulp** [comment]
I'm onboard with adopting semantic line breaks.

**Comment by MSevey** [comment]
Seems good, would need to see an example in our case, I'm not quite sure what this looks like in practice.

**Comment by staheri14** [comment]
> Seems good, would need to see an example in our case, I'm not quite sure what this looks like in practice.

I have applied the semantic break-line rule in this [PR](https://github.com/celestiaorg/celestia-app/pull/2124) for a sample.

**Comment by evan-forbes** [comment]
I'm down

**Comment by mojtaba-esk** [comment]
It seems easier to read, I am in

**Comment by rootulp** [comment]
How do we close this issue? It seems monumental to revisit every document in this repo and apply this rule. Should we only apply it for new docs?

**Comment by staheri14** [comment]
> How do we close this issue? It seems monumental to revisit every document in this repo and apply this rule. Should we only apply it for new docs?

Initially, I think that would be sufficient to ensure that new documents adhere to semantic line breaks. 
Also, the use of semantic line breaks can be added as a recommendation to the contribution section of the repo.

**Comment by staheri14** [comment]
If anyone has different opinions about how to proceed with this issue, feel free to share.

**Comment by rootulp** [comment]
SGTM
