### ISSUE TITLE
namespace (audit): clarifying the implications of namespace overlap

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2125]
# Problem
The following issue aims to capture the potential consequences of two applications choosing the same namespace. It seeks to address the following questions:

1. What can happen if two applications choose the same namespace?
2. Could it cause any security issues, such as spamming each other's data space?
3. Would it make application transaction retrieval less efficient, as the data of one application is mixed with another? (my initial thought is that this mixing of data should not inherently affect efficiency. Each blob transaction typically contains the share indices that allow for the retrieval of application-specific data. However, it is possible that Rollkit may employ a different approach for fetching application data, not solely relying on the share indices of the submitted transaction.)

If any of the above problems are found to be problematic, it would be advisable to suggest that applications choose their namespaces randomly or use any other approach that minimizes the likelihood of collision.

# Acceptance Criteria
Based on the answers to the questions above, it is recommended to update the Consideration and Assumption section of the namespace specification to include any necessary recommendations.

**Comment by staheri14** [comment]
cc: @rootulp @evan-forbes

**Comment by rootulp** [comment]
Related: https://forum.celestia.org/t/woods-attack-on-celestia/59
