### ISSUE TITLE
namespace: implications of using reserved namespaces 

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2127]
# Problem

Celestia reserves certain namespaces, as mentioned in the [Reserved Namespaces](https://github.com/celestiaorg/celestia-app/blob/dec925336384241e55056937633018c64b2c0910/specs/src/specs/namespace.md?plain=1#L43) document. However, it remains unclear whether applications are permitted to utilize these namespaces (specially given that some of them use version `0` which is a valid user-specifiable version number). Furthermore, the consequences of using such namespaces have not been clearly defined.

This issue aims to investigate the implications of utilizing reserved namespaces and propose suitable suggestions to be incorporated into the namespace specification, under [Assumptions and Considerations](https://github.com/celestiaorg/celestia-app/blob/dec925336384241e55056937633018c64b2c0910/specs/src/specs/namespace.md?plain=1#L55) for application developers.

**Comment by rootulp** [comment]
> it remains unclear whether applications are permitted to utilize these namespaces

Applications are not permitted to utilize these namespaces.

**Comment by rootulp** [comment]
Is this closeable? The specs now say:

https://github.com/celestiaorg/celestia-app/blob/b59e876cd15ea9f17608d1c2ca865a86151b7e5f/specs/src/specs/namespace.md?plain=1#L63

and https://github.com/celestiaorg/celestia-app/blob/b59e876cd15ea9f17608d1c2ca865a86151b7e5f/specs/src/specs/namespace.md?plain=1#L86-L88

**Comment by staheri14** [comment]
I think it can be closed. As it stands in the code, validators would not be able to insert(/accept) a blob transaction containing reserved namespaces to the mempool as long as they adhere to the current code. This is because the code filters transactions through the invocation of [CheckTx](https://github.com/celestiaorg/celestia-core/blob/3f3b7cc57f5cfc5e846ce781a9a407920e54fb72/mempool/v1/mempool.go#L177) (which ultimately rejects transactions with reserved namespaces).
