### ISSUE TITLE
Incorporating the protobuf definition of the namespace in the specs 

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2128]
# Proposal

The [current namespace specification](https://github.com/celestiaorg/celestia-app/blob/dec925336384241e55056937633018c64b2c0910/specs/src/specs/namespace.md) does not encompass the protobuf definition of the namespace. However, it could be beneficial to incorporate it into the specifications as a point of reference for other repositories. At the very least, including the data type and encoding details of each field (i.e., version and namespace ID) can serve as a valuable reference.

**Comment by staheri14** [comment]
Found the following protobuf definition for namespace verion and id in the core repo under the `Blob` type def:
```go
type Blob struct {
	NamespaceId      []byte `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Data             []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ShareVersion     uint32 `protobuf:"varint,3,opt,name=share_version,json=shareVersion,proto3" json:"share_version,omitempty"`
	NamespaceVersion uint32 `protobuf:"varint,4,opt,name=namespace_version,json=namespaceVersion,proto3" json:"namespace_version,omitempty"`
}
```

One proposal could be to separate namespace from the blob type
```go
type Namespace struct {
	NamespaceId      []byte `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	NamespaceVersion uint32 `protobuf:"varint,4,opt,name=namespace_version,json=namespaceVersion,proto3" json:"namespace_version,omitempty"`
}
```
and then use it inside the `Blob` type. However, this may require significant refactoring.

**Comment by rootulp** [comment]
I think https://github.com/celestiaorg/celestia-app/pull/3021 can close this b/c there isn't a protobuf definition for the namespace but there is a Go definition that was added to the specs.
