### ISSUE TITLE
Incorporate ParitySharesNamespace and TailPaddingNamespace into IsReserved function

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2138]
# Proposal

The [`IsReserved`](https://github.com/celestiaorg/celestia-app/blob/17c0f583114d13bfddc04b4c6ec6bcbc91c87cd9/pkg/namespace/namespace.go#L124) function currently only checks for namespaces that are less than the maximum reserved namespace. However, according to the [specifications](https://github.com/celestiaorg/celestia-app/blob/main/specs/src/specs/namespace.md#reserved-namespaces), the `ParitySharesNamespace` and `TailPaddingNamespace` are also considered reserved namespaces. Therefore, conceptually, it is expected that the `IsReserved` function should take these two namespaces into account when verifying a namespace. 

Note that the current implementation ensures that `IsParityShares` and `IsTailPadding` are called alongside the `IsReserved` when needed, however, incorporating these two checks inside the `IsReserved` function is a more clear approach.

**Comment by rootulp** [comment]
Agreed, I think it makes sense to have one function (i.e. `IsReserved`) that determines if a namespace is reserved for protocol use. On a related note I think we should consider renaming https://github.com/celestiaorg/celestia-app/blob/1b1078cae1ad94c366adb5912125091b78d6872c/pkg/namespace/consts.go#L54-L56 because after we implement the change to include tail padding and parity as "reserved" namespaces, the MaxReservedNamespace is not the the largest namespace that is reserved for protocol use.

**Comment by staheri14** [comment]
@rootulp Could you please provide some insight into the intended usage of the namespace constants (e.g., `MaxReservedNamespace`, `TailPaddingNamespace`, and `ParitySharesNamespace`) declared in the `celestia-app/pkg/namespace/consts.go` file? Currently, they appear to be utilized exclusively in tests and for verifying whether a namespace is reserved or not. Are there any anticipated external uses for these constants?

**Comment by rootulp** [comment]
They are used outside of tests. I expect they will be use externally by clients but I don't think celestia-app strictly needs to export them as long as they are defined in the specs and external clients can re-define them (if they need them).

`MaxReservedNamespace` is used to determine if a blob namespace is valid (see [here](https://github.com/celestiaorg/celestia-app/blob/78e53270a51961036566f16d6bee546fe1d87895/pkg/namespace/namespace.go#L108), [here](https://github.com/celestiaorg/celestia-app/blob/78e53270a51961036566f16d6bee546fe1d87895/x/blob/types/payforblob.go#L189)). I don't expect other use cases for `MaxReservedNamespace`.
