### ISSUE TITLE
Unintended Side Effects: Namespace Mutability in Repeat Function

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2139]
# Problem
The function [Repeat](https://github.com/celestiaorg/celestia-app/blob/17c0f583114d13bfddc04b4c6ec6bcbc91c87cd9/pkg/namespace/namespace.go#L148) assigns the passed namespace as it is to each element of the generated slice. As a result, any external changes to the namespace fields will be reflected in the returned slice as well.
Below is a test for this issue:
```go
func TestRepeat(t *testing.T) {
	namespace := Namespace{Version: NamespaceVersionMax, ID: []byte{1, 2, 3, 4}}
	repeated := namespace.Repeat(3)
	namespace.ID[0] = 5
	assert.Equal(t, repeated[0], namespace) // other namespaces in the repeated are also changed, which should not
}
```
This function currently is only used in tests, however, it is part of the public API of the namespace package hence it is recommended to solve the issue to avoid unwanted bugs. 
# Solution
To avoid unwanted bugs and ensure the integrity of the returned slice, it is recommended to modify the `Repea`t function to create a deep copy of the namespace before assigning it to each element of the generated slice. This way, any subsequent changes to the original namespace will not affect the elements in the returned slice.

**Comment by rootulp** [comment]
> This function currently is only used in tests

We may also consider making `Repeat` private if it is only needed for tests.

**Comment by cmwaters** [comment]
> In addition to the proposed fix, we may also consider making Repeat private.

Repeat could be useful for users. The case I have in mind is wanting so submit a PFB with multiple blobs belonging to the same namespace
