### ISSUE TITLE
Usage of ShareVersionZero for building padding shares instead blob.sharesversion

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/celestia-app#2142]
Builder for building padding shares is  [created](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/shares/padding.go#L16) using `ShareVersionZero` share version.  This happens within function `NamespacePaddingShare` that is called from Export function when building padding shares ([WriteNamespacePaddingShares](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/square/builder.go#L173)->[NamespacePaddingShares](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/shares/split_sparse_shares.go#L89)->[NamespacePaddingShare](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/shares/padding.go#L42)->[NewBuilder](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/shares/padding.go#L16)). 

It can be seen that the non padding shares within `Export` function are created (([Write](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/square/builder.go#L178)->[NewBuilder(blobNamespace, blob.ShareVersion, true).Init()](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/shares/split_sparse_shares.go#L38))) with shares Builder that takes `blob.ShareVersion`.

At the time being, when there is only `ShareVersionZero` share version, this is not a problem, but when new share versions are introduced it could happen that the padding is created with different share version then the preceding shares which could lead to inconsistency. Passing `blob.ShareVersion` to `NamespacePaddingShare` and using it in the `NewBuilder` constructor should prevent this from happening.

**Comment by rootulp** [comment]
Great catch!
