### ISSUE TITLE
Rename GovSquareSizeUpperBound

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2170]
LGTM.

Do we also want to rename it here https://github.com/celestiaorg/celestia-app/blob/3fc2fed84de759d3b82d80deff5df7f7ad7665b5/app/square_size.go#L10

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/pull/2150#pullrequestreview-1547059659_

**Comment by rootulp** [comment]
We should audit all the variable and function names pertaining to square size and rename them to avoid confusing the two variables.

**Comment by gaurav-11018** [comment]
@rootulp  i am working on this.
small clarification renaming should be done on only in this file :[celestia-app/app/square_size.go](https://github.com/celestiaorg/celestia-app/blob/3fc2fed84de759d3b82d80deff5df7f7ad7665b5/app/square_size.go#L10)

**Comment by gaurav-11018** [comment]
after reading the docs i feel `GetGovernanceMaxSquareSize ` is more descriptive . what say @rootulp ?

**Comment by rootulp** [comment]
IMO we should rename `GovSquareSizeUpperBound` => `GetMaxSquareSize`. It shouldn't use the word "gov" because this function doesn't strictly depend on the governance parameters. It shouldn't use the term `UpperBound` because the upper bound is one constant that influences the max square size.

**Comment by rootulp** [comment]
@gaurav-11018 I'm thinking something like https://github.com/celestiaorg/celestia-app/pull/2173

**Comment by rootulp** [comment]
Closing this as won't do. As confusing as it sounds, there are two parameters:
1. `GovMaxSquareSize`
2. `SquareSizeUpperBound`

And the current function name `GovSquareSizeUpperBound` (even though it is word soup) determines the max of those two parameters and returns it.
