### ISSUE TITLE
Comment above the `SliceStable` is misleading

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/celestia-app#2174]
Ordering of blobs by namespace is done in [SliceStable](https://github.com/celestiaorg/celestia-app/blob/b45d9161991ef6e455fb404352a7687d0d198171/pkg/square/builder.go#L136-L140) 

The comment above the function states “We use slice stable here to respect the order of multiple blobs within a namespace as per the priority of the PFB” which I do not see as a part of this function.

**Comment by rootulp** [comment]
I think the comment is trying to convey that the order of blobs preserves the order of blobs inside each transaction transaction and the order of transactions which is currently based on priority. For example:

- Tx A contains blobs: (namespace: 1, blob: A1), (namespace: 1, blob: A2)
- Tx B contains blobs: (namespace: 1, blob: B1), (namespace: 1, blob: B2)

Assume Tx A has a higher priority than Tx B b/c it paid more fees. The expected sorted order of blobs is: A1, A2, B1, B2. I agree the comment can be rephrased to clarify the point.

**Comment by andrijamitrovic23** [comment]
So that part of the comment is referring to the fact that if the namespaces are the same sorting won't change their places, so they will stay ordered by the priority?

**Comment by rootulp** [comment]
Yep! Put another way, the order of blobs within a namespace is preserved.
