### ISSUE TITLE
Unclear statement that does not follow preceding text in documentation

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/celestia-app#2176]
Statement: “Note that by construction, each share only has a single namespace, and that the list of concatenated shares is lexicographically ordered by namespace ID.” ([here](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/specs/src/specs/data_structures.md?plain=1#L338-L338)), does not follow from the preceding text. 
We suggest modifying the preceding part, e.g. adding to the second point that blobs need be sorted by namespace. (Then the rest follows because reserved namespaces are smaller than any blob namespaces.)

**Comment by rootulp** [comment]
>  adding to the second point that blobs need be sorted by namespace.

Since this statement follows a paragraph on transactions, and PayForBlob transaction shares, I think it states "shares" instead of "blobs" as the unit that gets lexicographically ordered by namespace. I agree it may not follow immediately from the preceding section so can re-arrange or rephrase.

**Comment by rootulp** [comment]
@andrijamitrovic23 how does https://github.com/celestiaorg/celestia-app/pull/2180 look? Open to any other ideas to clarify.

**Comment by andrijamitrovic23** [comment]
This is better.
