### ISSUE TITLE
Rephrase documentation to follow the implementation

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/celestia-app#2178]
This issue is a suggestion about rephrasing the documentation rules to be more clear and be aligned with the code.

[Documentation](https://github.com/celestiaorg/celestia-app/blob/83aff9175f1be0e8bb5fbb2712c143871defcf81/x/blob/README.md?plain=1#L147) about namespace validity rules states: 
"ii. The namespace is not lexicographically less than the [MAX_RESERVED_NAMESPACE](https://github.com/celestiaorg/celestia-app/blob/main/specs/src/specs/consensus.md#constants) range". 

Furthermore, the [following rule (stated below under iii) ](https://github.com/celestiaorg/celestia-app/blob/83aff9175f1be0e8bb5fbb2712c143871defcf81/x/blob/README.md?plain=1#L148) states that namespace should not be reserved padding.

Within the code, both of these are checked using the function [IsReserved](https://github.com/celestiaorg/celestia-app/blob/341006e5a51e6646b2c1eeb91a3ec9781cb6adc7/pkg/namespace/namespace.go#L124) by checking if the namespace falls under reserved if it is less or equal to the MAX_RESERVED_NAMESPACE.

It would be clearer and more aligned with the function if the rule `ii.` is rephrased as "The namespace is lexicographically larger than the [MAX_RESERVED_NAMESPACE](https://github.com/celestiaorg/celestia-app/blob/main/specs/src/specs/consensus.md#constants) range."

**Comment by rootulp** [comment]
Agreed with your proposal to clarify.

Note: there's a bug in these specs. https://github.com/celestiaorg/celestia-app/blob/83aff9175f1be0e8bb5fbb2712c143871defcf81/x/blob/README.md?plain=1#L148-L150 should state `TAIL_PADDING_NAMESPACE` and `PARITY_SHARE_NAMESPACE`.
