### ISSUE TITLE
Enforce that `GovMaxSquareSize` <= `MaxSquareSize`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2185]
## Context

https://github.com/celestiaorg/celestia-app/blob/2de3ed3f1c3bd636e917017c77374036d9c26b97/docs/architecture/adr-021-restricted-block-size.md?plain=1#L83

## Problem

I don't see where this is enforced:

>  Must be smaller than the `MaxSquareSize`.

which means the app needs to determine the limiting max square size via https://github.com/celestiaorg/celestia-app/blob/b3b8611c299a113a7283df2e986b5d7f2498c9e5/app/square_size.go#L8-L28

This means we have a third variable name for max square size which causes confusion (see https://github.com/celestiaorg/celestia-app/pull/2173). Additionally other modules (i.e. `blob`) doesn't have access to app so it can't readily import this function. That means it needs to redefine similar logic to derive the limiting factor for max square size.

## Proposal

Is it possible to enforce that the governance modifiable param is <= the upper bound constant?

1. In [`validateGovMaxSquareSize`](https://github.com/celestiaorg/celestia-app/blob/53e7b57a1a00c952ced0c590a4533b5d116a52f7/x/blob/types/params.go#L76-L77) add a check that ensures the gov max square size is <= the upper bound constant
2. Remove extra logic in [`GovSquareSizeUpperBound`](https://github.com/celestiaorg/celestia-app/blob/53e7b57a1a00c952ced0c590a4533b5d116a52f7/app/square_size.go#L8-L28)

**Comment by rootulp** [comment]
Attempted to do this but it doesn't seem feasible b/c the validate param function needs to conform to a function signature from cosmos-sdk.  See the error [here](https://github.com/rootulp/celestia-app/commit/e375febd3efb881173fb0f1a50cfeabf8126c303#diff-32677395b5a229a23fb69148dd3bbe27316275ecb291928e09f162c38b2e0e67R44).

**Comment by evan-forbes** [comment]
per a sync update, it is worth noting that we likely need to pass the app version to all param changes in the future so that we can determistically change restrictions over parameters.

**Comment by rootulp** [comment]
Closing as won't do b/c we can't easily constraint the bounds of a gov param. That's why we added the kinda confusing logic to determine the `MaxEffectiveSquareSize`
