### ISSUE TITLE
Inconsistent gas usage for PFBs

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#2193]
### Summary

One of the teams reported that the gas used for a PFB isn't consistent in relation to the blob size (some PFBs with the same size of blobs can vary as much as three times in gas price). Gas calculations are expected to be relatively deterministic so that they can be easily predicted. It's also completely unfair if some users have to pay three times as much for the same PFB.

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
to follow up with this, it appears that all gas values in arabica matched the estimated values.

while the current estimation logic isn't perfect, it appears to work for all standard accounts, therefore I'm closing this issue for now.
