### ISSUE TITLE
Remove the unused legacy upgrade proposal handlers

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2195]
We (we as in me :sweat_smile:) left the upgrade [legacy proposal handlers](https://github.com/celestiaorg/celestia-app/blob/6c72c6d97aa24fb8702c4d58d12d08030df789b6/app/default_overrides.go#L126) in the app's gov handler. This isn't a state breaking bug since this part of the code never gets hit since our upgrade module doesn't have any methods that can handle proposals. That's why the celestia-app's [upgrade module tests](https://github.com/celestiaorg/celestia-app/blob/6c72c6d97aa24fb8702c4d58d12d08030df789b6/x/upgrade/test/integration_test.go#L119) that check if the proposals are able to be submitted still pass.

more specifically these lines
https://github.com/celestiaorg/cosmos-sdk/blob/262703adbb31590538bdb4bc6bf8a5135f816537/x/gov/keeper/proposal.go#L43-L47

get hit before 
https://github.com/celestiaorg/cosmos-sdk/blob/262703adbb31590538bdb4bc6bf8a5135f816537/x/gov/keeper/proposal.go#L49-L59C4

so we're ok

We should still remove the mentioned lines to avoid any potential confusion, and double check by attempting to submit a legacy gov proposal contianing a software upgrade on an existing testnet, then syncing using a node that doesn't have the above lines.

**Comment by rootulp** [comment]
Since we're about to create a consensus breaking release candidate (v1.0.0-rc12), proposal to skip manually testing if this is consensus breaking and include a fix for this PR in rc-12.
