### ISSUE TITLE
Loadtest mocha-3 with random blobs

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2197]
We need to monitor mocha-3's performance with handling large amounts of blobs. This means that we should spam the mempool with blobs while monitoring various metrics.

- We should expect to see no to minor increases in block times since it can take multiple seconds to gossip large blocks, but we should not expect to see that it takes multiple rounds to reach consensus. It would be nice if we could know exactly how much longer it is taking to gossip the block.
- We should expect that bandwidth increases significantly, but it would be good to know exactly how much, and the exact distribution between the mempool and proposal gossiping.
- ~~We should expect that node's mempools will begin filtering out transactions with lower fees after hitting their local limit.~~
- ~~We should also look for memory leaks or other critical failures during this time.~~

edit: the two crossed issues will be tracked in a second set of issues dedicated to more formalized performance

it would be nice to combine this with https://github.com/celestiaorg/celestia-core/issues/1054

as a bonus: 
- We should increase the block size to 8MB and perform the same tests
- We should run the same tests with a large portion (if not all) of the validators running CAT

**Comment by staheri14** [comment]
Created a [Notion page](https://www.notion.so/celestiaorg/Effect-of-spamming-on-network-performance-ca7d3100989b483cbdaff16670b2f216) exclusively aimed at compiling insights and discoveries pertaining to the performance evaluation of the network under a spamming attack. This encompasses the testing scenario, essential metrics, and performance indicators.

**Comment by evan-forbes** [comment]
Here is a preliminary analysis

![time between cosecutive blocks and block size](https://github.com/celestiaorg/celestia-app/assets/42654277/23233227-1a4c-4176-8895-846a7b51fd74)

**Comment by staheri14** [comment]
> We should expect that bandwidth increases significantly, but it would be good to know exactly how much, and the exact distribution between the mempool and proposal gossiping.

Link to the notion page where the second item of this issue is covered:

https://www.notion.so/celestiaorg/Analysis-of-Traffic-Distribution

**Comment by evan-forbes** [comment]
I think we can close this as completed @staheri14 wdyt?

**Comment by staheri14** [comment]
> I think we can close this as completed @staheri14 wdyt?

Certainly, we can proceed with closing it, as we have already obtained a variety of insightful test results concerning the network's health and have addressed all the questions in the issue.
