### ISSUE TITLE
Incorrect byte units in comments

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2228]
## Context

https://github.com/celestiaorg/celestia-app/blob/4276080f48dc269c6ec870829801532890191714/app/test/integration_test.go#L95-L115

## Problem

These comments incorrectly use `KiB`. 600 KiB is 614400 bytes. 600 KB is 600000 bytes.

## Proposal

Replace usages of `KiB` with `KB`.

**Comment by lazyfuhrer** [comment]
Assign me @rootulp

**Comment by aliaaquib** [comment]
I want to work on that issue @rootulp

**Comment by lazyfuhrer** [comment]
check #2230 @rootulp
