### ISSUE TITLE
Inaccurate comment about `GovMaxSquareSize` being superseded

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2241]
## Context

https://github.com/celestiaorg/celestia-app/blob/b70048b275a0e16e0509634c2175c99e2aad7bd1/x/blob/README.md?plain=1#L64-L70

## Problem

`GovMaxSquareSize` isn't superseded by `MaxSquareSize`. Maybe this sentence was trying to say that `GovMaxSquareSize` is upper bounded by `MaxSquareSize` but that also isn't the case (see https://github.com/celestiaorg/celestia-app/issues/2185).

## Proposal

Remove this sentence

> This value is superseded by the `MaxSquareSize`, which is hardcoded and cannot change without hardforking the chain.

**Comment by sumanthsumu1418** [comment]
Hii can i work on this ..??

**Comment by aliaaquib** [comment]
@rootulp i want to work on that issue!

**Comment by rootulp** [comment]
Sorry @sumanthsumu1418 already has a PR open https://github.com/celestiaorg/celestia-app/pull/2245
