### ISSUE TITLE
Move the Validator EVM address mapping from the staking module to the qgb module

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2255]
As discussed synchronously with the relevant teams: we are currently defining a mapping between a validator and their evm address in the validator struct of the staking module. This forces us to maintain a large portion of the cosmos-sdk since the staking module is so core to its functionality. Instead, we should move the mapping to the qgb module.

This is already being done in #2169

**Comment by cmwaters** [comment]
Do we want to enforce that validator creation must also be accompanied with declaration of the validators EVM address or do we allow validators to not have to declare it.

**Comment by evan-forbes** [comment]
> Do we want to enforce that validator creation must also be accompanied with declaration of the validators EVM address or do we allow validators to not have to declare it.

to update this from a sync discussion: 

it should be okay for the validators to not declare their evm address. We just have to be sure that the voting power is the same for the qgb's version of the validator set compared to the staking module's representation.

This might involve filling in the evm address with a deterministic value, for example leaving it blank or if they need to be unique, incrementing the zero address.
