### ISSUE TITLE
Decide what to do about including identical messages in the same block

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#226]
Per these initial comments https://github.com/celestiaorg/celestia-app/pull/216#discussion_r809625701 https://github.com/celestiaorg/celestia-app/pull/216#discussion_r815541273

If two identical messages are submitted, then a block producer has the option to 

1. include two copies of the messages in the square, and both PayForMessages
2. include one copy with only one of the PayForMessages
3. include one copy with both of the PayForMessages, each of the PayForMessages pointing to the same data

With the mechansim introduced in #216, we are currently rejecting proposed blocks that include both identical messages, which forces either option 1 or option 3, but we still need to make a formal decision over what we want block producers to do in this scenario.

**Comment by liamsi** [comment]
I think we should not forbid including the same data multiple times. 

Also, on the long run, one PFD should be able to pay for multiple messages anyways. Hence, including the same message multiple times should be valid as long as the PFD pays multiple times (i.e. the paid fee covers all messages).

**Comment by evan-forbes** [comment]
> I think we should not forbid including the same data multiple times.

this is now the case since we implemented the non-interactive defaults and #692
