### ISSUE TITLE
Investigate the `poll.h` warning when building docker image

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#2264]
`sudo make build-docker`
This might give a clue: https://git.musl-libc.org/cgit/musl/tree/include/sys/poll.h

_Originally posted by @mojtaba-esk in https://github.com/celestiaorg/celestia-app/issues/2249#issuecomment-1677432630_

**Comment by mojtaba-esk** [comment]
some build logs if useful:

```
63.61 # github.com/pyroscope-io/godeltaprof/internal/pprof
63.61 /go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.0/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
63.61 /go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.0/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
84.90 # github.com/zondax/hid
84.90 In file included from /go/pkg/mod/github.com/zondax/hid@v0.9.1/hid_enabled.go:22:
84.90 /usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
84.90     1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
84.90       |  ^~~~~~~
101.1 make: *** [Makefile:65: build] Error 1
------
Dockerfile:13
--------------------
  11 |     COPY . /celestia-app
  12 |     WORKDIR /celestia-app
  13 | >>> RUN make build
  14 |     
  15 |     # stage 2
--------------------
ERROR: failed to solve: process "/bin/sh -c make build" did not complete successfully: exit code: 2
make: *** [Makefile:108: build-docker] Error 1
```

**Comment by rootulp** [comment]
Relevant issue https://github.com/Zondax/hid/issues/10 but it doesn't look like there has been a release cut with https://github.com/Zondax/hid/pull/12. I wonder if we should explore replacing our dependency on Zondax/hid with https://github.com/karalabe/hid because Zondax/hid appears unmaintained (see https://github.com/Zondax/hid/issues/13). Are we sure this warning is causing the build error?

**Comment by SweeXordious** [comment]
this is not causing the error, this is just a warning. But we shouldn't  ideally ignore it, that's why I created it as a low priority

**Comment by rootulp** [comment]
This issue will be resolved by bumping to https://github.com/Zondax/hid/releases/tag/v0.9.2

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/2740
