### ISSUE TITLE
Revert First Block Transaction Check

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2271]
# Problem
Following issue #1899, we decided to add some checks to the `prepare_proposal`  process to ensure that the first block does not contain any transactions (#2221).
However, the incorporation of this check is just to avoid unexpected errors, hence after mainnet this check becomes unnecessary and this issue is to remove this check (basically revert changes introduced in #2233) after mainnet.

**Comment by rootulp** [comment]
Mainnet launched so should we revisit reverting https://github.com/celestiaorg/celestia-app/pull/2233? I thought of this because https://github.com/celestiaorg/celestia-app/pull/3122

cc: @cmwaters
