### ISSUE TITLE
Consider refactoring txsim to use latest `user` package

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2287]
Currently, txsim has its own logic for signing and submitting txs. Since this logic already exists in the `user` package, we should consolidate and user our canonical library for doing those things instead

**Comment by mojtaba-esk** [comment]
@evan-forbes it seems like this is implemented: https://github.com/celestiaorg/celestia-app/blob/main/test/txsim/account.go#L42
