### ISSUE TITLE
InitUnlockedBalance will be unlocked from the vesting balance instead of being extra balance

### ISSUE THREAD

**Issue by mojtaba-esk** [celestiaorg/celestia-app#2295]
### Summary

Currently, the behavior of the InitUnlockedBalance feature involves adding an extra unlocked balance to the locked accounts. However, there's a need to reconsider this approach and change it based on the [made decision](https://celestia-team.slack.com/archives/C04KS5R9VQU/p1692262592113819?thread_ts=1692205029.302239&cid=C04KS5R9VQU). 

### Problem Definition

To have a vesting account installed in the genesis file, the total allocation of that account is set to `OriginalVestingBalance` and the same amount is also set in the banking module.
I order to have a `total_allocation` locked and e.g. `1TIA` unlocked, the procedure is as follows:
`account.OriginalVestingBalance = total_allocation`
`account.BalanceInBankModule = total_allocation + 1TIA`
which means that account receives `1TIA` more, now the leadership decided instead of donating `1TIA` to each vesting account, we unlock `1TIA` from their locked allocation. Therefore, we need to subtract it from their total allocation. 
So:
`account.OriginalVestingBalance = total_allocation - 1TIA`
`account.BalanceInBankModule = total_allocation`

Same goal achieved without donating extra balance.

### Proposal

It is simple to do that.
Currently the functions that receive vesting account's details and generate a genesis version with its balances, have the following line of code to add extra unlocked amount:

```golang
balance = banktypes.Balance{
		Address: address,
		Coins:   initUnlockedCoins.Add(vestingBalance...),
	}
```

we need to change that code to the following:
```golang
balance = banktypes.Balance{
		Address: address,
		Coins:   vestingBalance,
	}
vestingBalance = vestingBalance.Sub(initUnlockedCoins...)
```

there are 3 functions that need to be modified:

1. NewGenesisDelayedVestingAccount
2. NewGenesisPeriodicVestingAccount
3. NewGenesisContinuousVestingAccount

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Sorry I don't understand the motivation or context around this issue. Also, the "made decision" link to Slack doesn't work for me. Can you please rephrase the **Summary** or **Problem Definition**?

**Comment by mojtaba-esk** [comment]
Sure I will
