### ISSUE TITLE
Consider enforcing more required CI checks

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2305]
## Context

celestia-app currently has 3 CI checks that are **Required** to pass prior to PR merge.

<img width="849" alt="Screenshot 2023-08-17 at 12 24 55 PM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/0cd2ba53-7397-438e-bccc-d374f36a66d9">

## Proposal

I think we should consider adding the following checks as **Required**:
- docker-build-publish
- lint
- protobuf

This is especially relevant for the v1.x branch but I think we can also add them to main.

**Comment by cmwaters** [comment]
I think in v1.x some of the linting checks are required.

Generally, I'm of the opinion of "why have a check there in the first place if it's not required". I guess in the case of publishing  docker images which may be seen as more optional to development (unless it's for a release tag) and thus may not need to be required.

**Comment by rootulp** [comment]
I don't have permission to view the required CI checks on v1.x but based on https://github.com/celestiaorg/celestia-app/pull/2308 you're right, the lint checks are required on v1.x.

My opinion is: if the check is flakey then we temporarily make it optional. If the check is not flakey, make it required. Separately, prioritize making the flakey checks not flakey 🙂

**Comment by rootulp** [comment]
I have permission to edit branch protection rules so I just enabled the CI workflows I think should be required on **main**. They include 
- test/*
- lint/*
- docker-security-build/*
- proto/*
- markdown-linter/markdown-lint

Note: markdown-linter/markdown-link-check is intentionally not required b/c it can be flakey. If there are no objections, I will re-apply these rules on release branches.

## Screenshot
<img width="735" alt="Screenshot 2023-10-05 at 11 17 01 AM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/f1b017fe-790f-4604-bf74-02eba52dd3f2">
