### ISSUE TITLE
unknown flag: `--evm-address` on v1.0.0-rc12

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2328]
## Problem

```
$ gco v1.0.0-rc12
$ ./scripts/build-run-single-node.sh
...
Error: unknown flag: --evm-address
```

**Comment by rootulp** [comment]
It looks like https://github.com/celestiaorg/celestia-app/commit/8428940f9df4f0411bd5d0385a244f87ec743aa6 doesn't exist on v1.0.0-rc12 or the v1.x branch. 

https://github.com/celestiaorg/celestia-app/blob/e61738f69239f05906cd797f375fd110b527a4c4/scripts/single-node.sh#L20

cc: @SweeXordious

**Comment by SweeXordious** [comment]
This is the commit in main https://github.com/celestiaorg/celestia-app/commit/2ab5aa46096a18fa2155f647ac16ae16fd504a81, that's super weird. Apparently, it wasn't squashed :confused:

We need to port this https://github.com/celestiaorg/celestia-app/commit/2ab5aa46096a18fa2155f647ac16ae16fd504a81 to `v1.x`. I will open a PR shortly.

Good catch :pray:
