### ISSUE TITLE
Remove vesting module tests

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2336]
in #2004 we started to add tests for code that installs a vesting module to the genesis. These tests along with the remaining functionality to add vesting modules to genesis state have been refactored and finished in a different repo, which frees us up to remove them here.

**Comment by rootulp** [comment]
@mojtaba-esk is there anything from https://github.com/celestiaorg/celestia-app/pull/2004 that we need to preserve in celestia-app? If not, we can revert the commit entirely.
