### ISSUE TITLE
e2e tests are currently failing due to the changes in genesis

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#2340]
We need to update our e2e tests so that they continue to pass. We should also look to add incorporate this into a nightly CI

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
I think we've fixed this specific issue, no? please reopen if needed
