### ISSUE TITLE
Unnecessary usage of `-mod=readonly`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2341]
## Context

The Makefile uses `-mod=readonly` 7 times. Ex:

https://github.com/celestiaorg/celestia-app/blob/ee25c955df5150c6788e57738264e2ebda63ab5e/Makefile#L138-L142

## Problem

Based on the docs, `-mod=readonly` is the default if there isn't a vendor directory and we use Go > 1.14. See https://go.dev/ref/mod#build-commands

> By default, if the [go version](https://go.dev/ref/mod#go-mod-file-go) in go.mod is 1.14 or higher and a vendor directory is present, the go command acts as if -mod=vendor were used. Otherwise, the go command acts as if -mod=readonly were used.

## Proposal

Drop the `-mod=readonly` usage from the Makefile

**Comment by Vikramop** [comment]
So I have to just remove -mod=readonly form Makefile right?

**Comment by rootulp** [comment]
Note: to elaborate a bit more on the rationale for this issue, given the `-mod=readonly` doesn't have an effect on any of these commands, I think it should be removed b/c it visually distracts from the parts of each command that actually do impact behavior.
