### ISSUE TITLE
Namespace ID length discrepancy in PayForBlob subcommand

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#2346]
# Issue

There's an inconsistency in the size of the namespace ID mentioned in the `PayForBlob` subcommand of the `blob` module CLI and what's actually needed. It makes the command fail upon receiving seemingly right input. 

The "PayForBlob" part of the blob module suggests that the namespace ID size should be a 28-byte hex encoded string:

```bash
% celestia-appd tx blob PayForBlobs --help 

To pay for publishing a data blob to Celestia blockchain, use [hexNamespaceID] which must be a 28-byte hex encoded namespace ID. You can have hex-encoded data blob [hexBlob] of any length. This command handles only one blob each time.
```
This means the namespace should be a string of 56 characters (28 * 2). However, entering this value gives an error:
```bash
% celestia-appd tx blob PayForBlobs 0000000000000000000000000000000000000000000000000000FFFF abcdef123456 

Error: unsupported namespace id length: id [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255 255] must be 28 bytes but it was 47 bytes
```

## Root cause

After checking, it turns out that when using namespace version 0, the provided namespace ID is actually added with an extra [`NamespaceVersionZeroPrefix`](https://github.com/celestiaorg/celestia-app/blob/cb8247ead807a52bb8915d450982544755efc1e6/pkg/namespace/consts.go#L37) (which has 18 more zero bytes) because of the [`getNamespace`](https://github.com/celestiaorg/celestia-app/blob/e96a050f159267343614209da41d8d826d2e20fa/x/blob/client/cli/payforblob.go#L50C1-L50C1) function. This means, user input can be at most 10 bytes long (20-character hex string), not 28 bytes.

## Why tests did not capture the issue

This wasn't identified during testing due to the way [`TestSubmitPayForBlob()`](https://github.com/celestiaorg/celestia-app/blob/83f91cac8912c10975cff0eceefcee6d8551c9d4/x/blob/client/testutil/integration_test.go#L63) is set up. It uses a utility function [`RandomBlobNamespaceID()`](https://github.com/celestiaorg/celestia-app/blob/83f91cac8912c10975cff0eceefcee6d8551c9d4/x/blob/client/testutil/integration_test.go#L65) that makes a correct 10-byte namespace ID (instead of 28 bytes), so the issue didn't show up in tests.

# Solution Idea

1) Update the CLI description for namespace ID, saying that for version 0, the expected length is 10 bytes.
2) Let users input 28 bytes, but do necessary checks in the background, like the correct format.

Considering that the PayForBlob command already has a "version" flag, it's probably better to go with option 1. The namespace ID can then be extended to 28 bytes automatically behind the scenes.

**Comment by staheri14** [comment]
cc: @evan-forbes @rootulp @cmwaters

**Comment by rootulp** [comment]
Good catch!

> Update the CLI description for namespace ID, saying that for version 0, the expected length is 10 bytes.

Sounds good to me.
