### ISSUE TITLE
Incorrect namespace size in comment

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2348]
## Context

https://github.com/celestiaorg/celestia-app/blob/7f97788a64af7fe0fce00959753d6dd81663e98f/proto/celestia/blob/v1/event.proto#L11-L13

## Problem

After versioned namespaces were implemented, namespaces shrank from 33 bytes to 29 bytes.

## Proposal 

Fix the comment

**Comment by sayeedkhannabil** [comment]
Just to clarify, Is namespaceVersion still 1 byte and namespaceID reduced to 28 bytes?

**Comment by sayeedkhannabil** [comment]
@rootulp

**Comment by rootulp** [comment]
Yep. 

https://github.com/celestiaorg/celestia-app/blob/8eff970a5f9977d5781e4d3921479377b20dba32/pkg/appconsts/global_consts.go#L15-L16

https://github.com/celestiaorg/celestia-app/blob/8eff970a5f9977d5781e4d3921479377b20dba32/pkg/appconsts/global_consts.go#L21-L22
