### ISSUE TITLE
Update EventPayForBlob attribute name

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2349]
## Context

https://github.com/celestiaorg/celestia-app/blob/7f97788a64af7fe0fce00959753d6dd81663e98f/x/blob/README.md?plain=1#L188-L194

## Problem
The docs for EventPayForBlob are slightly out of date. `namespace_ids` was renamed to `namespaces`. See https://github.com/celestiaorg/celestia-app/blob/7f97788a64af7fe0fce00959753d6dd81663e98f/proto/celestia/blob/v1/event.proto#L6-L16

## Proposal

Update the x/blob/README.md to say namespaces

**Comment by evan-forbes** [comment]
since this is consensus breaking, we actually want to do this asap if we can fit it in the next release

also EventPayForBlob -> EventPayForBlob**s**

**Comment by evan-forbes** [comment]
nevermind, I thought we were changing the field name... :man_facepalming: :laughing:
