### ISSUE TITLE
x/blob/README.md contains outdated reserved namespace rules

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2350]
## Context

https://github.com/celestiaorg/celestia-app/blob/7f97788a64af7fe0fce00959753d6dd81663e98f/x/blob/README.md?plain=1#L147-L150

## Problem

After https://github.com/celestiaorg/celestia-app/pull/2257 more namespaces were reserved

## Proposal

Update this section of the README to state that the namespace must be a valid blob namespace (i.e. not reserved for protocol use).

**Comment by Vikramop** [comment]
Can u like explain what to change in ReadMe file.
