### ISSUE TITLE
CI workflow for `make test-short`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2361]
## Problem

We don't have a CI workflow for `make test-short` so we may accidentally introduce a new test that takes 10+ minutes to run and forget to add the skip in short mode.

## Proposal

Add a CI workflow for `make test-short` that times out if `make test-short` takes longer than 60 seconds.

**Comment by sayeedkhannabil** [comment]
Is it possible to give more clarification on this issue?

**Comment by tungbq** [comment]
Hello, I've proposed the new PR #2367 for this task. Could you please review this?
