### ISSUE TITLE
High level fee document

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2373]
tbd

**Comment by adlerjohn** [comment]
We want some additional intuition for developers on Celestia on how to reason about fees and the fee market. [This section](https://github.com/celestiaorg/celestia-app/blob/55f4360666d6ffc8e2a8b8a3a09162371e1eff59/specs/src/specs/resource_pricing.md#fee-market) is a good start but doesn't build intuitions on things like limits and _why_ the fees are the way they are.

**Comment by evan-forbes** [comment]
we still have a follow up in https://github.com/celestiaorg/docs/issues/1003

but this can be closed with https://github.com/celestiaorg/docs/pull/1009
