### ISSUE TITLE
Add a gas price (or fee rate) `TxOption` for the user package

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2377]
Ideally the we would have deeper support for gas price instead of using fee everywhere, but we should add a gas price option for the user package that determines a fee for the user based on a gas price and gas limit.

**Comment by rootulp** [comment]
Is this resolved via https://github.com/celestiaorg/celestia-app/pull/2394/files#diff-d51206df3d744d07f596a93050478fdd0f81917d7a58270468664d8b450acff1R69-R80 ?
