### ISSUE TITLE
Default to signing over all relevant square sizes when creating a `WirePayForMessage`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#239]
Currently we require a user to select which square sizes they want to sign over. This is a hostile UX, as the user must have extraneous knowledge on the data square, malleated transactions, and the non-interactive default rules to know which square sizes to sign over. For most cases, the user will likely want to sign all relevant square sizes.

as pointed out in #236, this does not mean that they have to sign over all square sizes

> if a message can fit on a single row of square size x, then a valid commitment for square size x is valid for all square sizes >= x.

Also, they don't have to sign over square sizes that don't have enough shares to include their message + `MsgPayForMessage` transaction.

**Comment by toanngosy** [comment]
Hi @evan-forbes, can I work on this?

**Comment by evan-forbes** [comment]
certainly!
