### ISSUE TITLE
Consider removing `GetMaccPerms`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2391]
https://github.com/celestiaorg/celestia-app/blob/b73b1817133766ca79a061980042778f9a421f0f/app/app.go#L728-L735 appears unused. If it is no longer needed, consider removing it.

**Comment by vishnujoshi1311** [comment]
So basically I need to remove the GetMaccPerms function. @rootulp

**Comment by rootulp** [comment]
Yes. Before we remove the function, we should try to identify it's original purpose (via git blame or upstream in Cosmos SDK).
