### ISSUE TITLE
Decide on additional indexing keys needed for qgb module's keeper

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#241]
As pointed out by @SweeXordious in #240 and other PRs, we need to index certain data in the qgb module's state to quickly reference it when querying. We should decide on exactly which queries we want, and how to index them.

**Comment by evan-forbes** [comment]
can we close this, or are we still working on indexing?

**Comment by SweeXordious** [comment]
I think we have basic indexing now. We can close until we need better stuff and then think it more
