### ISSUE TITLE
1.0.0-rc13 not working with Ledger on Ubuntu

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#2412]
### Summary of Bug

```console
$ ./build/celestia-appd version
1.0.0-rc13
$ ./build/celestia-appd keys add john-key --ledger
Error: failed to generate ledger key: failed to retrieve device: ledger nano S: support for ledger devices is not available in this executable
```

### Version

`v1.0.0-rc13`

### Steps to Reproduce

`make build` on Ubuntu 20.04, then above.

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
This is really weird as this was fixed here: https://github.com/celestiaorg/celestia-app/pull/2014

**Comment by liamsi** [comment]
Looks like the above made into `main` but never was included in a release candidate.

**Comment by adlerjohn** [comment]
https://github.com/celestiaorg/celestia-app/pull/2014 was merged into main, and not ported to the [v1.x](https://github.com/celestiaorg/celestia-app/tree/v1.x) branch. This is why I was hesitant to have a forward-looking-release branch instead of cutting releases off `main`.

**Comment by adlerjohn** [comment]
We'll need a new rc with #2014 included cc @evan-forbes

**Comment by evan-forbes** [comment]
can close with #2415
