### ISSUE TITLE
Consider adding evidence parameters to the paramfilter

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2418]
We've noticed that there are potentially 3 values that are currently modifiable via token voting that we might not want to be changed. These are the two evidence paramters, `evidence.MaxAgeNumBlocks` and `evidence.MaxAgeDuration`, along with the mint module's `mint.BondDenom` (the denomination sent to the distribution module's account)

**Comment by evan-forbes** [comment]
cc @adlerjohn and @liamsi 

simlar to our latest last minute change, while technically consensus breaking if no one successfully changes these values in governance we should be clear to update by simply upgrading

**Comment by rootulp** [comment]
I'm still investigating if governance can modify any of these 3 params but it doesn't look like it.

- I think`mint.BondDenom` is a genesis config and isn't a governance modifiable param. The x/mint module doesn't appear to use the params module (b/c no param subspace is provided [here](https://github.com/celestiaorg/celestia-app/blob/3f1b99bf940b198e03819b800f8fc7637e1c54cb/app/app.go#L312-L319)).
- For the evidence parameters, [this file](https://github.com/celestiaorg/cosmos-sdk/blob/c525ad72ab1449d31115815f5832a68bc79d4ffd/x/evidence/types/params.go) is mostly empty. Cosmos SDK [docs](https://docs.cosmos.network/v0.46/modules/evidence/05_params.html) claim: "The evidence module does not contain any parameters."

**Comment by rootulp** [comment]
The evidence parameters are a subset of the consensus parameters. https://github.com/cosmos/cosmos-sdk/issues/6197 and https://github.com/cosmos/cosmos-sdk/pull/5952 leads me to think that consensus parameters are modifiable through `abci.EndBlocker` but I don't think they're modifiable through the governance module. The behavior of modifying consensus params isn't documented in the [gov docs](https://docs.cosmos.network/v0.46/modules/gov/) and I couldn't find references to consensus params or evidence params in the x/gov module so they still seem non governance modifiable.

**Comment by rootulp** [comment]
Update: we're not including this in the v1.x release of celestia-app. We do intend on including it in a subsequent breaking change.

**Comment by rootulp** [comment]
I'm not sure why the OP calls out those 3 params. IMO all the params that are currently governance modifiable should be made governance unmodifiable. Instead we should determine the values for those params off-chain via rough consensus and then update them (if necessary) via hard-forks.

**Comment by rootulp** [comment]
Update: moving any param from governance modifiable to unmodifiable requires a CIP. [CIP-16](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-16.md) proposes making the two evidence params gov unmodifiable so I think we can close this issue as won't do until that CIP has reached **Final** status.
