### ISSUE TITLE
QGB data commitment validator address confusion

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#243]
## Summary of Bug
Currently, in the QGB module, we're using the following name to refer to the orchestrator:
https://github.com/celestiaorg/celestia-app/blob/eaed5dbf403395ed58bf74029b1abc650fb44e26/proto/qgb/msgs.proto#L73
This needs to be updated in order to avoid confusion.
The suggested new name is `orchestrator` to stay consistent with the other message types.

**Comment by SweeXordious** [comment]
Will be done after we merge the hanging PRs.

**Comment by evan-forbes** [comment]
can we close this?

**Comment by SweeXordious** [comment]
It is still not done. will do after we merge your branch etc

**Comment by evan-forbes** [comment]
can we close this now?

**Comment by SweeXordious** [comment]
This is still not fixed:
https://github.com/celestiaorg/celestia-app/blob/6b86e91eea1063c27c1ae461eddbe505f778df08/proto/qgb/msgs.proto#L63
Will be a good first issue

**Comment by SweeXordious** [comment]
closing as no longer relevant due to qgb v2
