### ISSUE TITLE
feat(blob): allow for more than one blob to be sumbmitted via the CLI

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2434]
## Context

https://github.com/celestiaorg/celestia-app/pull/2411/files#r1316337240

The blob CLI only allows one blob to be submitted.

## Proposal

Add the ability to submit multiple blobs via the CLI

**Comment by bao1029p** [comment]
hey @rootulp can i work on this

**Comment by rootulp** [comment]
Sure! I think multiple blobs via the CLI may be an interesting UX problem so we may want to design the expected user experience before we start working on code.

**Comment by bao1029p** [comment]
yes absolutely, right now the simplest way i came up with are just allow a bunch of hex blob as arguments but this could be improve by accept file path as input, this file can contain multiple blob data in json format or hex string

**Comment by bao1029p** [comment]
oh sorry for the late reply didn't see your reaction, i will try the file path implementation
