### ISSUE TITLE
Clean up PR/issue templates

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#244]
the current PR and issue templates were originally taken from the cosmos-sdk. While we might need as extensive templates in the future with more engineers working on the project, we are not using them now so we should either agree on consistently using some format, or simplify them.

**Comment by rootulp** [comment]
## Context
- PR and issue templates were added in https://github.com/celestiaorg/celestia-app/commit/c3b312eb68ba8e87f4f26b8c11cfe8ce919ad58b
- Issue templates were last modified in https://github.com/celestiaorg/celestia-app/pull/531

## Investigation
- I sampled the last few approved PRs (see [here](https://github.com/celestiaorg/celestia-app/pulls?q=is%3Apr+is%3Aclosed+review%3Aapproved)) and none included the existing PR template so I propose removing it.
- I also sampled the last few opened issues (see [here](https://github.com/celestiaorg/celestia-app/issues)) and none used them. I think the issue templates are potentially helpful for issues opened by external contributors so I'm indifferent on keeping vs removing.

**Comment by adlerjohn** [comment]
Issue templates can always be bypassed by clicking on the blank issue link.
