### ISSUE TITLE
Backport the QGB docs to v1.x

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/celestia-app#2440]
> Aaaah yes, we could backport. Should I open a PR?

Are there more QGB docs that don't exist on v1.x? If yes, then a PR sounds good.

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/2439#issuecomment-1708575423_

**Comment by rootulp** [comment]
Closing this as something we're not working on. Please reopen if you think it's still necessary @rach-id
