### ISSUE TITLE
Add CI workflow that runs `goreleaser check`

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/celestia-app#2452]
## Context
_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/2437#pullrequestreview-1616607813_
                          
## Proposal
Should we add a CI workflow that runs [`goreleaser check`](https://goreleaser.com/cmd/goreleaser_check/) to make sure that the .goreleaser.yaml is always valid?

**Comment by rootulp** [comment]
We're considering adding more distributions / architectures in https://github.com/celestiaorg/celestia-app/issues/2567 so I think it makes sense to do this now.
