### ISSUE TITLE
Replace start and end block range with nonce in the DataCommitmentConfirms

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#248]
Currently we are using a block range for each data commitment. We should instead replace this with a nonce, as this is more in line with what the contracts expect. This will make relaying and slashing easier.

**Comment by SweeXordious** [comment]
I guess, if we go for a nonce, it is better if we separate:
`MsgDataCommitment` and `MsgDataCommitmentConfirm`, similar to what `ValSet` and `ValSetConfirm` do, with the prior containing a nonce and the latter reference to it.
What do you think ?

**Comment by evan-forbes** [comment]
yeah, that makes sense! Following the pattern is a good idea. We will likely also follow the [ValsetRequest](https://github.com/celestiaorg/celestia-app/blob/df46d122da5f1fab1bd99bfb2bfcf9002f5bc154/x/qgb/keeper/keeper_valset.go#L15-L39) pattern too in order to accomodate https://github.com/celestiaorg/quantum-gravity-bridge/issues/54 and https://github.com/celestiaorg/quantum-gravity-bridge/issues/55

**Comment by evan-forbes** [comment]
can close since we switched to universal nonces
