### ISSUE TITLE
Is `MinCommissionRate` correct?

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2480]
## Context

https://github.com/celestiaorg/celestia-app/blob/41ead770b48d6b86dce3f252e1be844b4978e907/specs/src/specs/params.md?plain=1#L54

On main
 
```shell
$ celestia-appd query  staking params
bond_denom: utia
historical_entries: 10000
max_entries: 7
max_validators: 100
min_commission_rate: "0.000000000000000000"
unbonding_time: 1814400s
```

The default is defined [here](https://github.com/celestiaorg/cosmos-sdk/blob/c525ad72ab1449d31115815f5832a68bc79d4ffd/x/staking/types/params.go#L36-L37).

**Comment by cmwaters** [comment]
I think it should be once https://github.com/celestiaorg/celestia-app/pull/2417/files#diff-008f85e59c1e0f88e9ad4be82fd1a15f29261f9b9d1a71a19488c58b94fef363R98 is merged

**Comment by rootulp** [comment]
Ahh good point. Proposal to update the params.md on main so that it reflects the current value of `0`. I think https://github.com/celestiaorg/celestia-app/pull/2417 should update the param in both places (code and specs) so that the specs always match the observed value.
