### ISSUE TITLE
Add x/mint constants to params.md

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2481]
## Context

https://github.com/celestiaorg/celestia-app/blob/41ead770b48d6b86dce3f252e1be844b4978e907/specs/src/specs/params.md?plain=1#L56-L57

## Problem

We removed these params from the x/mint fork in this repo.

## Proposal

Remove them from params.md

**Comment by evan-forbes** [comment]
I think these should be included in the specs as they are parameter that could be changed, they just require a hardfork. This is same for other hardcoded constants such as max square size

**Comment by rootulp** [comment]
hmm okay since they can be changed with a hardfork, I understand your point. I think this line is slightly misleading 

https://github.com/celestiaorg/celestia-app/blob/0012451c4dc118767dd59bc8d341878b7a7cacdf/x/mint/README.md?plain=1#L81-L83

and we should clarify that although the parameters have been removed, hard-coded constants exist that can change outside token voting governance. Also I think we should use the same names in params.md as the constant names in 
https://github.com/celestiaorg/celestia-app/blob/0012451c4dc118767dd59bc8d341878b7a7cacdf/x/mint/types/constants.go#L17-L22

and we also need to add one more `TargetInflationRate`.
