### ISSUE TITLE
DataCommitmentWindow is not changeable via governance

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2482]
## Context

https://github.com/celestiaorg/celestia-app/blob/41ead770b48d6b86dce3f252e1be844b4978e907/specs/src/specs/params.md?plain=1#L58

## Problem

DataCommitmentWindow is not changeable via governance because it is strictly a genesis param and doesn't exist in the params module. In other words, a governance proposal can't modify it.

## Proposal

Update this entry to describe that DataCommitmentWindow is not changeable via governance.

cc: @SweeXordious

**Comment by SweeXordious** [comment]
was this tested? because the data commitment window is supposed to be changed via governance.

Also, I do change it in orchestrator-relayer:
https://github.com/celestiaorg/orchestrator-relayer/blob/bf6998e3b113a7f808fbee8caba539ad6beb7108/testing/celestia_network.go#L113-L183

**Comment by SweeXordious** [comment]
Also, it is a parameter:
https://github.com/celestiaorg/celestia-app/blob/ee2d952d74db8ae57b3cf95d78fccfe289c08b3f/x/qgb/keeper/keeper.go#L38-L47

**Comment by rootulp** [comment]
> was this tested? 

Nope. I jumped to an incorrect conclusion when I saw that qgb params were not listed in

```shell
$ celestia-appd query params qgb
Error: unknown command "qgb" for "params"
```

I also couldn't find a params.go file in https://github.com/celestiaorg/celestia-app/tree/main/x/qgb/types but I think the relevant file is actually https://github.com/celestiaorg/celestia-app/blob/0629c757ef35a24187a8d7a4c706c7cdc894c8b6/x/qgb/types/genesis.go. Given the test you linked, this should be closed b/c DataCommitmentWindow appears governance modifiable.
