### ISSUE TITLE
audit(tokenfilter): Return error OnRecvPacket

### ISSUE THREAD

**Issue by seantking** [celestiaorg/celestia-app#2488]
### Summary

As part of the TokenFilter module we attempt to unmarshal the incoming `FungibleTokenPacketData` [here](https://github.com/celestiaorg/celestia-app/blob/main/x/tokenfilter/ibc_middleware.go#L44). If we encounter an error we pass the data down the stack (to the transfer module). At present the transfer module only supports this packet type and thus will naturally error as expected but I think a cleaner approach would be to error early and return an error here instead.  

### Problem Definition

This is essentially a nitpick and it's likely the transfer module will not be supporting other packet types (to the best of my knowledge) in the near future but might be good to do to guarantee safety in the future. This is low priority. 

This issue arose as consequence of #1997 

### Proposal

```	
if err := transfertypes.ModuleCdc.UnmarshalJSON(packet.GetData(), &data); err != nil {
        return channeltypes.NewErrorAcknowledgement(Err)
}
```

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Based on https://github.com/celestiaorg/celestia-app/pull/2609#issuecomment-1748935749 I infer that we don't want to do this.
