### ISSUE TITLE
Mint module: Shortening of KeyMinter

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/celestia-app#2497]
## Mint module

| ID         | 001                                                                    |
|------------|------------------------------------------------------------------------|
| Finding    | Shortening of KeyMinter                                                |
| Severity   | 0 - Informational                                                      |
| Description| The bytes key `KeyMinter` is longer than necessary. Shortening it  to something like `[]byte{0x0`, will save minimal storage space and align better with standard module storage practices. Additionally, it paves the way for smoother transitions to collections. |
| Recommendation | Trim the length of KeyMinter.                                       |
| Code References | [keys.go#L4](https://github.com/celestiaorg/celestia-app/blob/main/x/mint/types/keys.go#L4) |

**Comment by rootulp** [comment]
Note this is breaking and if we don't squeeze it into v1.0.0 release, we likely won't ever do it which is a valid option. @evan-forbes @cmwaters

**Comment by rootulp** [comment]
Note: we don't intend on including a fix for this in v1.x

**Comment by rootulp** [comment]
Closing as won't do.
