### ISSUE TITLE
Mint module: Shortening of KeyGenesisTime

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/celestia-app#2498]
## Mint module

| ID         | 002                                                                    |
|------------|------------------------------------------------------------------------|
| Finding    | Shortening of KeyGenesisTime                                           |
| Severity   | 0 - Informational                                                      |
| Description| Similar to `KeyMinter`, the `KeyGenesisTime` can also benefit from a reduction in length. |
| Recommendation | Reduce the length of KeyGenesisTime.                                 |
| Code References | [keys.go#L7](https://github.com/celestiaorg/celestia-app/blob/main/x/mint/types/keys.go#L7) |

**Comment by rootulp** [comment]
Note this is breaking and if we don't squeeze it into v1.0.0 release, we likely won't ever do it which is a valid option. @evan-forbes @cmwaters

**Comment by rootulp** [comment]
Note: we don't intend on including a fix for this in v1.x

**Comment by rootulp** [comment]
Closing as won't do.
