### ISSUE TITLE
Mint module: Streamlined Encoding of GenesisTime

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/celestia-app#2499]
## Mint module

| ID             | 003                                                                                                                   |
|----------------|-----------------------------------------------------------------------------------------------------------------------|
| Finding        | Streamlined Encoding of GenesisTime                                                                                    |
| Severity       | 0 - Informational                                                                                                     |
| Description    | The `GenesisTime` value is currently stored in state via an intermediary protobuf representation. This intermediate step is not essential as there are simpler methods to encode time to bytes, such as `sdk.FormatTimeBytes`. |
| Recommendation | Transition to using direct encoding methods like `sdk.FormatTimeBytes` for a more straightforward and efficient encoding process. |
| Code References| [mint.proto#L37](https://github.com/celestiaorg/celestia-app/blob/main/proto/celestia/mint/v1/mint.proto#L37)           |
|                | [keeper.go#L63](https://github.com/celestiaorg/celestia-app/blob/main/x/mint/keeper/keeper.go#L63)                     |
|                | [keeper.go#L70](https://github.com/celestiaorg/celestia-app/blob/main/x/mint/keeper/keeper.go#L70)                     |

**Comment by rootulp** [comment]
Closing as won't do.
