### ISSUE TITLE
Mint module: Implement gRPC Query Handlers

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/celestia-app#2503]
## Mint module

| ID             | 007                                                                                        |
|----------------|--------------------------------------------------------------------------------------------|
| Finding        | Implement gRPC Query Handlers                                                               |
| Severity       | 0 - Informational                                                                          |
| Description    | Currently, queries are handled via legacy querier methods via a sdk.Querier. Instead, consider implementing a gRPC wrapper around a Keeper which implements the gRPC service and register this in module.go. This also avoids needless JSON marshalling. |
| Recommendation | See description.                                                                           |
| Code References| x/mint/keeper/querier.go                                                                    |

**Comment by rootulp** [comment]
I think this should be resolved by https://github.com/celestiaorg/celestia-app/pull/2258. @onurakpolat can you please confirm?
