### ISSUE TITLE
Mint module: Minter Evaluation

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/celestia-app#2504]
## Mint module

| ID             | 008                                                                                        |
|----------------|--------------------------------------------------------------------------------------------|
| Finding        | Minter Evaluation                                                                          |
| Severity       | 0 - Informational                                                                          |
| Description    | There are a few minor bits in the minter that could minor linting and evaluation. Specifically, There is a needless cast to int64 in yearsSinceGenesis. CalculateBlockProvision should consider ensuring previous is indeed less than current time and perhaps error when that is not the case. Avoid needless int64 casting in CalculateBlockProvision and CalculateInflationRate. |
| Recommendation | See description.                                                                           |
| Code References| x/mint/types/minter.go                                                                      |

**Comment by rootulp** [comment]
> Avoid needless int64 casting in CalculateBlockProvision and CalculateInflationRate.

There is no int64 cast in [CalculateInflationRate](https://github.com/celestiaorg/celestia-app/blob/58c1e4ed41d8bba734f808a3f8dfd3b53cc9a535/x/mint/types/minter.go#L42-L56). There is a uint64 cast that is necessary.

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/issues/2504
