### ISSUE TITLE
Mint module: Reliance on Previous Block Time

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/celestia-app#2505]
## Mint module

| ID             | 009                                                                                        |
|----------------|--------------------------------------------------------------------------------------------|
| Finding        | Reliance on Previous Block Time                                                             |
| Severity       | 3 - Very low                                                                               |
| Description    | CalculateBlockProvision uses the previous block’s time in order to calculate the number of tokens to mint each block. Since in CometBFT, the proposer, or a cabal of validators with sufficient power, of a block could manipulate the block time in order to skew or impact the result of CalculateBlockProvision. In practice, there has been zero evidence of this happening. However, as a defensive measure, until CometBFT implements some notion of PBTS (proposer-based timestamps), ABCI++ should be explored to evaluate timestamps and ensure their integrity. |
| Recommendation | Explore ABCI++ to evaluate timestamps.                                                      |
| Code References| x/mint/abci.go                                                                              |

**Comment by evan-forbes** [comment]
closing as this automatically be fixed with proposer based timestamps, and requires propoper based timestamps
