### ISSUE TITLE
Increase timeouts in cli to match long block times

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#256]
Currently, when using the `--broadcast-mode block` flag, the block times on a live network are too long, resulting the cli almost always timing out. We need to communicate this to the user in some way, along with increasing timeouts to be useful

**Comment by rahulghangas** [comment]
There's this for reference https://github.com/cosmos/cosmos-sdk/issues/3875

**Comment by rahulghangas** [comment]
If my understanding is correct, timeouts aren't configurable through the cli. Now we have two options, either change the default rpc config in `celestia-core` or mutate the imported config in `celestia-app`. Imo any config changes for rpc must be done on the app side

**Comment by evan-forbes** [comment]
> Imo any config changes for rpc must be done on the app side

agree, I've tried in core before and it breaks a bunch of tests
