### ISSUE TITLE
Write a detailed plan for what is needed to be able to unfork from the sdk and have single binary syncs

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2571]
In an ideal world, we’d have the ability to sync from a single binary && be able to reuse a lot of the functionality of the sdk without maintaining a fork or massively vendoring everything. Unfortunately, that’s not the case, and we’re stuck in a trilemma.

The trilemma (pick 2): 
- Single binary syncs (and single binary upgrades)
- Reusing the sdk’s functionality (vs rewriting everything)
- Unforking (this includes not vendoring)

In order to help the sdk team, we should write out our requirements to be able to break the trilemma above.

**Comment by faddat** [comment]
So I had two tendermint issues on this -- there are ways to reproduce this on tendermint itself too:

* https://github.com/tendermint/tendermint/issues/9757

* https://github.com/tendermint/tendermint/issues/9840

**Comment by evan-forbes** [comment]
The current plan is to adopt the cosmos-sdk's yet to be released baseapp that will allow celestia-app to import the old forked cosmos-sdk modules. This means that we don't have to unfork from the current modules
