### ISSUE TITLE
Add ability for the qgb relayer to replay old validator set changes and data commitments

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#260]
Currently, the relayer only listens for changes from celestia, and then posts those on an evm chain when applicable. It will also need the functionality to replay existing validator set  changes and data commitments, effectively catching the qgb contracts up with the current state of celestia.

**Comment by SweeXordious** [comment]
Can we change the title to:
```
Add ability for the qgb relayer to replay old validator set and data commitments changes from celestia to an evm chain
```
?

**Comment by evan-forbes** [comment]
sure, left out the "from celestia to an evm chain" as that is reasonably implicit

**Comment by SweeXordious** [comment]
closing for: https://github.com/celestiaorg/celestia-app/issues/298
