### ISSUE TITLE
Rename the QGB module and docs

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#2613]

**Comment by evan-forbes** [comment]
by rename module, do we mean only go code, and not the actual name of the module in the application? if this is only refering to non-consensus breaking changes, can we clarify that a bit in the description? also, do we plan on doing this separately from the consensus breaking changes, or at the same time?

**Comment by SweeXordious** [comment]
Thanks, the rename will include non-consensus breaking changes and will also include the go code
