### ISSUE TITLE
Create a script that creates an addressbook from a list of peers

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2619]
Validators include node ids in the memo's of gentx, and we could use that help bootstrap peers by parsing it and saving those ids as a initial addressbook.

**Comment by rootulp** [comment]
- A fresh celestia-app address book resides in `config/addrbook.json` and looks like:
  ```json
  {
	  "key": "88cacd28631615b7d3c47b57",
	  "addrs": []
  }
  ```
- An example address book for Cosmos Hub: https://dl2.quicksync.io/json/addrbook.cosmos.json
- Source: https://quicksync.io/networks/cosmos.html
  > You can download an addressbook to get connected to peers faster [here](https://dl2.quicksync.io/json/addrbook.cosmos.json). Place this file in your .gaiad/config folder and restart your node to take effect.
  
  > mv addrbook.cosmos.json addrbook.json

**Comment by evan-forbes** [comment]
> I'm attempting to use mocha-4's genesis.json to explore what a CLI needs to do to build this address_book but it looks like mocha-4 doesn't explicitly set any validators per the empty "validators": [] below. It's valid to have an empty validators (per [docs](https://github.com/cometbft/cometbft/blob/485ef362187a4496aed606b3ee7940e6d9cde5b3/docs/core/using-cometbft.md?plain=1#L69-L77)).

the data is typically stored in the memos of the gentxs, so to find those we'll have to look in the `genutil` module's genesis state

**Comment by evan-forbes** [comment]
if we go down the route of just asking everyone for their peerIDs, then instead of parsing the genesis file, we could just parse a normal text file such as https://github.com/celestiaorg/networks/blob/master/mocha-4/peers.txt

**Comment by rootulp** [comment]
That works and seems a bit more robust than parsing the memo field b/c idk if there is input validation on the memo field and a gentx may not populate a valid peer ID there 🤷
