### ISSUE TITLE
Decrease `SlashFractionDoubleSign` from 5% to 2%

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2628]
## Proposal

Decrease double sign slash should be lowered from 5% to 2%

Originally proposed by Luka from POPs.

**Comment by mindstyle85** [comment]
Was my mistake before as it is 5% now. My suggestion is 2%, reasoning: most historical double slashes were not malicious at all, it was mostly validator state file issue (in case of halts/rewinds etc) or hardware problems

**Comment by cmwaters** [comment]
Ideally, we'd implement something like proportional slashing whereby the percentage slashed is derived from the total percentage that double signed that height. i.e. if 30% in total double signed then the slashing percentage would be 50% else if 1% in total double signed then the slashing percentage would be 1%.

Yes I agree that most historical slashes were not malicious. In fact I'm unaware of any attack on a large production scale Tendermint chain. But the game theory around slashing isn't and really shouldn't be based on historical frequency.
