### ISSUE TITLE
Increase `MinDeposit` from 1K to 10K TIA

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2629]
## Context

https://github.com/celestiaorg/celestia-app/blob/dd4b1c1eb899f83256d9f4818af7d40e51fde494/specs/src/specs/params.md?plain=1#L34

## Proposal

Increase min deposit from 1K to 10K TIA.

Originally proposed by Luka from POPs.

**Comment by mindstyle85** [comment]
this one is purely to have it high enough that we dont get scam proposals, maybe 1k would already do, maybe also 5k would be fine

**Comment by cmwaters** [comment]
I feel like 1K is sufficient as a penalty for a scam proposal. We still want it low enough so members of the community don't feel dissuaded to make proposals.

Just checking now. On Cosmos Hub it is 250 ATOM. On Osmosis it is 1,600 OSMO

**Comment by mindstyle85** [comment]
ok so the consensus on the call today was to set it at 10k tia
