### ISSUE TITLE
Change default denom units from CELES to celes

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#263]
Currently, we are using the `DisplayDenom` (= "CELES") as a default denomination in the genesis file, when we should likely be the equivalent but lower case ("celes").

**Comment by quinle** [comment]
Hi @evan-forbes, can I work on this issue?

**Comment by liamsi** [comment]
Hey @quinle, we will rename the denom to tia, see: https://github.com/celestiaorg/celestia-app/issues/279

@evan-forbes can I close this one and can you help @quinle with #279?

**Comment by YazzyYaz** [comment]
Hi @quinle thank you for supporting Celestia by offering to work on these issues. Would love to connect, feel free to email me: yaz@celestia.org

**Comment by evan-forbes** [comment]
yes, since we closed https://github.com/celestiaorg/celestia-app/pull/267, we should focus on renaming to `tia`
