### ISSUE TITLE
Add E2E tests for upgrades

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#2633]
### Summary

Test out the new upgrade functionality in an e2e test

ref: https://github.com/celestiaorg/celestia-app/pull/2583#discussion_r1348937178

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Is this close-able due to #2797 ?

**Comment by rootulp** [comment]
Assuming this is close-able via #2797. @cmwaters please re-open if that's not the case.
