### ISSUE TITLE
Write an ADR for QGB rename

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/celestia-app#2638]
Now that the decision is finalized of renaming the QGB to BlobStream, we should write an ADR to signal that and the corresponding changes to repos.

**Comment by rootulp** [comment]
Is this still worth doing?

**Comment by rach-id** [comment]
I think yes, we would need an ADR that describes QGB, the rename, then the transition to BlobstreamX so that the community can reference that work if needed

**Comment by rootulp** [comment]
Why does this issue block the v2 release? IMO it can be done before/after because the doc is not a breaking change.

**Comment by rootulp** [comment]
Is this still worth doing now that we're deprecating x/blobstream in v2?

**Comment by rach-id** [comment]
I don't think so, feel free to close :D
