### ISSUE TITLE
Binance Account 

### ISSUE THREAD

**Issue by KJ1403** [celestiaorg/celestia-app#2680]
https://www.binance.info/en/activity/referral-entry/CPA/together?ref=CPA_003UT3YQZ9![share_2023-10-16_00_10_17_186.jpeg_2023-10-16_00_10_17.jpg](https://github.com/celestiaorg/celestia-app/assets/147840786/01872f50-28e9-4bdc-b5fc-a744e4608f85)

**Comment by rootulp** [comment]
I'm confused and don't want to click that sketchy link. Please re-open with more details if this is a real issue.
