### ISSUE TITLE
Key Prefix Type Issue

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2689]
Context: Conformance with cosmos-sdk standards.
Location: [keys.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/keys.go#L27:L42)
Issue: Key prefixes should utilize `bytes` instead of `string`.
Remediation: Convert key prefixes to `bytes` type.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
