### ISSUE TITLE
Slow IsEVMAddress Function

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2690]
Context: Over time, with a bloating state, the function’s performance degrades.
Location: [keeper_valset.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/keeper/keeper_valset.go#L225)
Issue: The function’s iteration over EVMAddresses in the QGB evm addr to val addr prefix results in reduced performance.
Remediation: Integrate a KeySet (refer to [cosmossdk.io/collections.KeySet](http://cosmossdk.io/collections.KeySet)) for faster existence verification.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
