### ISSUE TITLE
Non-Idiomatic Code in genesis.go

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2691]
Context: Improved code readability.
Location: [genesis.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/genesis.go#L61)
Issue: The `else if` structure affects code readability.
Remediation: Replace `else if` with separate `if` conditions.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
