### ISSUE TITLE
Unused Variables in abi_consts.go

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2692]
Locations:
[ExternalQGBABI](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/abi_consts.go#L119)
[BridgeValidatorABI](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/abi_consts.go#L121)
[DcDomainSeparator](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/abi_consts.go#L124)
Issue: Variables present but not used.
Remediation: Delete these variables or provide documentation explaining their presence.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
