### ISSUE TITLE
Non-Idiomatic Bytes-to-String Conversion

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2695]
Context: Code inefficiencies related to unnecessary conversions.
Location: [keys.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/keys.go#L48)
Issue: Non-idiomatic and inefficient string conversion. Resulting string data is converted back to bytes, causing unneeded copying.
Remediation: Return bytes directly.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
