### ISSUE TITLE
Sorting Inefficiency in validator.go

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2696]
Context: Proper implementation of sorting for improved efficiency.
Location: [validator.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/validator.go#L83)
Issue: The `sort.Interface` is not optimally implemented.
Remediation: Use the sort.Interface correctly or utilize the `slices.Sort` package (if permitted by the Go version).

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
