### ISSUE TITLE
Test Method in Production Code

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2698]
Context: Proper separation of test and production code.
Location: [validator.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/validator.go#L161)
Issue: `GetPowers` method is used only in tests but exists in production code.
Remediation: Move the method to test files.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
