### ISSUE TITLE
Silent Overflow in PowerDiff

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2701]
Context: Potential for incorrect results due to unnoticed overflows.
Location: [validator.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/validator.go#L119)
Issue: The function allows silent overflow.
Remediation: Trigger a panic for overflows or use a type that supports conversion to int64 without overflow.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
