### ISSUE TITLE
Excessive Computation in PowerDiff

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2702]
Context: Optimizing performance by reducing unnecessary calculations.
Location: [validator.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/validator.go#L124:L136)
Issue: The delta can be computed more efficiently during single validator power changes.
Remediation: Optimize delta calculations.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
