### ISSUE TITLE
TwoThirdThreshold Precision

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2703]
Context: Improving precision in ratio calculations.
Location: [valset.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/types/valset.go#L78)
Issue: The returned ratio could be made more precise.
Remediation: Enhance the precision of `TwoThirdThreshold` by applying a suitable multiplication factor.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
