### ISSUE TITLE
Redundant Calculations in handleValSetRequest

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2704]
Context: Optimizing computation by eliminating redundancy.
Location: [abci.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/abci.go#L84)
Issue: The function checks three conditions before the `SetAttestationRequest` branch, each with its computational overhead.
Remediation: Sequentially check each condition and execute the branch once a condition evaluates to true.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
