### ISSUE TITLE
Unoptimized Data Retrieval

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2705]
Context: Performance optimization for data fetches.
Location: [keeper_data_commitment.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/keeper/keeper_data_commitment.go#L44)
Issue: The `GetDataCommitmentWindow` method unnecessarily goes through the gRPC server.
Remediation: Use `keeper.GetParams`.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
