### ISSUE TITLE
Incomplete Genesis Export/Import

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2706]
Context: Chain upgrades and state migrations.
Location: [genesis.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/genesis.go#L31)
Issue: Only Parameters are exported, not attestations.
Remediation: Enable attestation export or provide documentation justifying its omission.

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
