### ISSUE TITLE
Unexplained Module Consensus Version

### ISSUE THREAD

**Issue by newTendermint** [celestiaorg/celestia-app#2707]
Context: Chain upgrades and state migrations.
Location: [module.go](https://github.com/celestiaorg/celestia-app/blob/main/x/qgb/module.go#L16)
Issue: The consensus version of 2 is not documented, and no migration is registered.
Remediation: Provide documentation or comments explaining this choice.

**Comment by rootulp** [comment]
I think this issue meant to link to: https://github.com/celestiaorg/celestia-app/blob/2bf99995ea42c27a5aec22587b1a08247317f12c/x/qgb/module.go#L156-L157

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX

**Comment by rootulp** [comment]
I think we have to maintain the x/blobstream module indefinitely so IMO this still seems worth doing

**Comment by rach-id** [comment]
The way I see it is that once we have the versioning handler merged, we will have a PR to move the blobstream module from an active state to only being touched by v1 syncs and that would involve fixing the versioning etc. that's why I closed this issue

**Comment by rootulp** [comment]
what do you mean by "fixing the versioning"?

**Comment by rach-id** [comment]
Setting the correct consensus version and documenting that

**Comment by rootulp** [comment]
What is the correct consensus version? I would've expected it to be `1` initially but I don't think we can decrement from `2` to `1` based on 

> Consensus versions serve as state-breaking versions of app modules and must be incremented when the module introduces breaking changes.

So are you proposing incrementing it to `3`?

Ref: https://docs.cosmos.network/main/build/building-modules/upgrade#consensus-version
