### ISSUE TITLE
CosmJS Transaction Decoding Incompatibility

### ISSUE THREAD

**Issue by blorgon1** [celestiaorg/celestia-app#2715]
### Summary of Bug

[CosmJS](https://github.com/cosmos/cosmjs) fails to decode blocks which contain "Pay For Blobs" type transactions, due to those transactions having a [non-standard protobuf format](https://github.com/celestiaorg/celestia-core/blob/main/proto/tendermint/types/types.proto#L203).

```
Error: invalid wire type 6 at offset 38
    at Reader.skipType (node_modules/protobufjs/src/reader.js:377:19)
    at Object.decode (node_modules/cosmjs-types/cosmos/tx/v1beta1/tx.js:703:28)
    at Object.decode (node_modules/cosmjs-types/cosmos/tx/v1beta1/tx.js:382:47)
    at decodeTxRaw (node_modules/@cosmjs/proto-signing/build/decode.js:11:33)
```

This will likely hinder adoption as CosmJS is widely used to interact with Cosmos SDK-based chains.

### Version

v1.0.0-rc17

### Steps to Reproduce

Using this transaction from the `mocha-4` testnet: https://celestia.explorers.guru/transaction/E369E8DCDC66E33DEC748B18B5E7203092F4D47D0E28B24F34DED3B296599CA8

```typescript
import { decodeTxRaw } from '@cosmjs/proto-signing';
decodeTxRaw(Buffer.from('Cs0CCp8BCpwBCiAvY2VsZXN0aWEuYmxvYi52MS5Nc2dQYXlGb3JCbG9icxJ4Ci9jZWxlc3RpYTE3OHlmeHNuZ2cwcHBhdjMwcTd1anZrMms5MGo2MHoyajV6a3hqNhIdAAAAAAAAAAAAAAAAAAAAAAAAACVRklUZJVGSVRkaAXkiIDlyQrVAlX3r4kfLJGD4HTnmrZwZObqPets9NSjjg93MQgEAEmcKUQpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQPKJy7Vb2UGw7or1J8cr4oOzm9KBTMNwe4Le0rIZSHy6RIECgIIARiUARISCgwKBHV0aWESBDc5ODAQtO8EGkBbXgq3TpZoDBM5yt5ycdfe1zPjnb3Y1w7vlL76nPejnSMqw2rS+RRc5YamiiIHhJLVJTA7fp0oBQjM2rq5JfxiEpkBChwAAAAAAAAAAAAAAAAAAAAAAAAlUZJVGSVRklUZEnkA8faHWX5A+pbDpfDV2gXSYAAAAAAAYXjaAFEArv+4TwD4TKD8Tf3eKe8QIDQw0CsZKVv4LyzGYKfQaTBK5ZBgdkSJ54P02eKgRxwQcHL6xCaJqS/B3LOT5J53GRWzuzLfpeVBroaHyfOEZS4eKMABAAD//4AsKXoBGgRCTE9C','base64'));
```

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
> Alternatively, the Tendermint block endpoint could be modified to unwrap the BlobTx into Tx before returning it.

this is an idea we can explore! thanks for the good rec @blorgon1 . We'd have to implement the "blobless" block in a separate endpoint to not also break some important downstream things ofc, but this seems like the simplest change.

**Comment by evan-forbes** [comment]
closing this in favor of https://github.com/celestiaorg/celestia-core/issues/1136
