### ISSUE TITLE
Missing transaction in tx_search

### ISSUE THREAD

**Issue by lzrscg** [celestiaorg/celestia-app#2726]
### Summary of Bug

Block 279207 on Mocha 4 has a transaction:
[Click here because the response is long](http://consensus-full-mocha-4.celestia-mocha.com:26657/block?height=279207)

But when using `tx_search` (http://consensus-full-mocha-4.celestia-mocha.com:26657/tx_search?query=%22tx.height=279207%22) the result is empty:
```json
{
    "jsonrpc": "2.0",
    "id": -1,
    "result": {
        "txs": [],
        "total_count": "0"
    }
}
```

# Expected behavior
[Subsequent block 279208 has a transaction.](http://consensus-full-mocha-4.celestia-mocha.com:26657/block?height=279208)

And [so does the `tx_search` result for 279208](http://consensus-full-mocha-4.celestia-mocha.com:26657/tx_search?query=%22tx.height=279208%22).

### Version

Presumably [v1.1.0](https://github.com/celestiaorg/celestia-app/releases/tag/v1.1.0), which should be running on http://consensus-full-mocha-4.celestia-mocha.com:26657

We have not replicated this on a local node, but are happy to do so if helpful.

### Steps to Reproduce

1. Use a Mocha 4 node
2. Make an RPC call using `tx_search` ([docs](https://docs.tendermint.com/v0.34/rpc/#/Info/tx_search)) for transactions in block 279207. i.e. http://consensus-full-mocha-4.celestia-mocha.com:26657/tx_search?query=%22tx.height=279207%22
3. Use RPC to independently check block 279207 and see how many transactions are inside `result.block.data.txs` i.e. http://consensus-full-mocha-4.celestia-mocha.com:26657/block?height=27920
4. Notice the discrepancy between the number of transactions in the block and the number of results from `tx_search`

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
I think this is the same issue as https://github.com/celestiaorg/celestia-app/issues/2806#issuecomment-1798776619

does that make sense @lzrscg ? also apologies that this issue slipped through the cracks

**Comment by mhstom** [comment]
thanks for the reply @evan-forbes!

based on what we have seen, I don't think it's the same issue. For reasons:

1. We are using the `/tx_search` endpoint. Based on our experience, it returns tx regardless of normal tx or payForBlob tx. We are able to get the result for other blocks that have payForBlob transactions
2. The rpc provided by pops one **does** return transactions for the same block 279207 http://rpc-mocha.pops.one:26657/tx_search?query=%22tx.height=279207%22 while this http://consensus-full-mocha-4.celestia-mocha.com:26657/tx_search?query=%22tx.height=279207%22 doesn't.

my two cents is that there might be a glitch somewhere in the system.

**Comment by evan-forbes** [comment]
I believe we can close this with https://github.com/celestiaorg/celestia-core/pull/1533

apologies for taking so long to get to @lzrscg this was a non-trivial bug in comet that has been there for years

s/o @ninabarbakadze for finding
