### ISSUE TITLE
Consider supporting older and other versions of linux/macos

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2738]
We're already building the prebuilt binary for ubuntu-20.04, so might as well have full support for that version of linux and what we're testing against (latest). We could also consider running the entire set of unit/integration tests using macos is we really wanted to be comprehensive.

**Comment by rootulp** [comment]
Closing this in favor of the prerequisite https://github.com/celestiaorg/celestia-app/issues/2742
