### ISSUE TITLE
disable api, grpc and grpc-web by default in app.toml

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-app#2758]
### Summary

disable api, grpc and grpc-web by default in app.toml

### Problem Definition

n/a

### Proposal

disable api, grpc and grpc-web by default in app.toml

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
@mindstyle85 can you provide more details for why they should be disabled by default?
