### ISSUE TITLE
Add new key in store for latest valset

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/celestia-app#2759]
The definitive fix for https://github.com/celestiaorg/orchestrator-relayer/issues/556 would be to store the latest valset in store. Should be included in the next upgrade.

**Comment by evan-forbes** [comment]
can we add proposal tag to this and discuss it further?

**Comment by SweeXordious** [comment]
sure, added

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
