### ISSUE TITLE
Unnecessary code

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/celestia-app#2765]
**Involved artifacts**
* [/x/qgb/abci.go](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/x/qgb/abci.go)

**Description**
In `pruneAttestations` function  the whole earliest attestation is taken out of the store [here](https://github.com/celestiaorg/celestia-app/blob/d8d91e51791e80db92b89f0b54e5d84b0bd1c20a/x/qgb/abci.go#L145-L157) using `GetEarliestAvailableAttestationNonce`. This is done just to get the earliest nonce to use for [newEarliestAvailableNonce](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/x/qgb/abci.go#L161) in the for loop and for updating state and logging [here](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/x/qgb/abci.go#L183) and [here](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/x/qgb/abci.go#L189). It would be sufficient to get the earliest nonce directly by using `GetEarliestAvailableAttestationNonce`.

**Problem Scenarios**
Unnecessary access to the storage.

**Recommendation**
Just use the functions `CheckEarliestAvailableAttestationNonce` and  `GetEarliestAvailableAttestationNonce` for getting earliest nonce.

**Comment by bao1029p** [comment]
Hi guys, is this issue open for work ?
