### ISSUE TITLE
Move the merkle package to a go.mod that doesn't import tendermint/core

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2769]
We don't plan on modifying the crypto/merkle package, however that package needs to have its own go module so that users can import it without needing the rest of tendermint.

That could involve moving that package into the `pkg` here, or just adding a go module to that package in core. The issue with adding a go module in core is that the module's path would have to be celestiaorg/celestia-core unless we wait for upstream to do this. If we wanted to get the benefits of not copying code, we'd have also change all of the references to that code to also point to the new module.

for now, I'm planning on just moving the package here in our `pkg` directory, but this will likely change in an upcoming refactor to the module in `pkg` #2570

**Comment by rootulp** [comment]
I think this was completed when go-square was extracted. See https://github.com/celestiaorg/go-square/tree/main/merkle
@cmwaters please re-open if that's not the case.
