### ISSUE TITLE
Have a default way to download genesis files

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2777]
It would be nice if users have to spend less time thinking about which genesis they download and install.

As pointed out in a sync discussion, osmosis acheives this by including the genesis in the binary. This is a good simple option, as users likely have to download the mainnet genesis anyway.

Another option would be to hardcode the hashes of the genesis for each live network in the binary, and add a subcommand that would download, verify the hash of, and then install the genesis of a specific network.

**Comment by cmwaters** [comment]
I agree with just adding support to download the genesis when `init` is run

**Comment by rootulp** [comment]
I briefly explored adding this to the `celestia-appd init` command but `init` is defined in Cosmos SDK which makes it (a) more difficult to modify and (b) more likely to break when we pull upstream changes. Given our motivation to minimize the diff with upstream, I think another option worth exploring is adding a unique command to celestia-app (e.g. `celestia-appd download-genesis <chain-id>`).
