### ISSUE TITLE
Address serialization in PayForBlobs event

### ISSUE THREAD

**Issue by lzrscg** [celestiaorg/celestia-app#2781]
### Summary of Bug

In `celestia.blob.v1.EventPayForBlobs`, the signer address is represented incorrectly:
1. It does not match the signer address in the corresponding PayForBlobs message
2. It is a string containing quotes, which is not how addresses are usually represented in messages
3. It is an invalid address format

For example take [this transaction](https://celestiascan.com/mocha/transaction/e38d16712833ba89de7b37d269a92215528e62b6ceabd31c55090821e949f491). In the event, the signer is: `"celestia1vdjkcetnw35kzvtpwye8gdtvxfu8jcmh8y685emcvuenydekxp5rj6mxx36ksctn0y6rywfswahq0lqt35"`. This is has quotes and too long to be a valid address. By contrast, in the message, the address is represented as `celestia1aq2t5l2xycw94zgxg32760h9kf4uhasy4290wn`.

### Version

v1.1.0

### Steps to Reproduce

1. Visit https://celestiascan.com/mocha/transaction/e38d16712833ba89de7b37d269a92215528e62b6ceabd31c55090821e949f491 and click the source data icon in the top right (or just use this link: http://consensus-full-mocha-4.celestia-mocha.com:26657/tx?hash=0xe38d16712833ba89de7b37d269a92215528e62b6ceabd31c55090821e949f491)
2. Find the EventPayForBlobs in the events
```json
{
                    "type": "celestia.blob.v1.EventPayForBlobs",
                    "attributes": [
                        {
                            "key": "YmxvYl9zaXplcw==",
                            "value": "WzEyMzI5Ml0=",
                            "index": true
                        },
                        {
                            "key": "bmFtZXNwYWNlcw==",
                            "value": "WyJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQWVOSTllb2gvN3dWSHM9Il0=",
                            "index": true
                        },
                        {
                            "key": "c2lnbmVy",
                            "value": "ImNlbGVzdGlhMXZkamtjZXRudzM1a3p2dHB3eWU4Z2R0dnhmdThqY21oOHk2ODVlbWN2dWVueWRla3hwNXJqNm14eDM2a3NjdG4weTZyeXdmc3dhaHEwbHF0MzUi",
                            "index": true
                        }
                    ]
                }
```
3. [Decode](https://www.base64decode.org) the last entry from base64
**Key:** `signer`
**Value:** `"celestia1vdjkcetnw35kzvtpwye8gdtvxfu8jcmh8y685emcvuenydekxp5rj6mxx36ksctn0y6rywfswahq0lqt35"`
4. Find the correct signer address in the message:https://celestiascan.com/mocha/transaction/e38d16712833ba89de7b37d269a92215528e62b6ceabd31c55090821e949f491/messages (`celestia1aq2t5l2xycw94zgxg32760h9kf4uhasy4290wn`)

### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Thanks for identifying and providing clear repro steps! This does look like a bug. I added these lines prior to [here](https://github.com/celestiaorg/celestia-app/blob/a856af5c0c7ccd4129a9a27fe6686905485324ed/x/blob/keeper/keeper.go#L56)

```go
	signer := msg.Signer
	eventSigner := sdk.AccAddress(signer).String()

	ctx.Logger().Info(fmt.Sprintf("[debug] signer %v\n", signer))
	ctx.Logger().Info(fmt.Sprintf("[debug] eventSigner %v\n", eventSigner))
```

and it results in

```
1:53PM INF [debug] signer celestia15drmhzw5kwgenvemy30rqqqgq52axf5wwrruf7
1:53PM INF [debug] eventSigner celestia1vdjkcetnw35kzvf4v3ex66r6wu6kkam8v4h8vetd0yenqun3w9ckwuf4xfshse34wamhyun4vcmsgysde8
```

**Comment by rootulp** [comment]
This bug has existed since the event was first introduced [here](https://github.com/celestiaorg/celestia-app/pull/213/files#diff-393b3dbd7c98e0ae217ad0e422e344116cc55b64c3e385789df7d7244eec95e9R39).
