### ISSUE TITLE
feature: add real vesting module 

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#280]
## Summary

We also want this: https://github.com/agoric-labs/cosmos-sdk/pull/155
We don't want to wait on the SDK to upstream this though.

**Comment by rootulp** [comment]
Notes from @musalbas
- We may want to add the ability to have custom vesting schedules (e.g. 6 month lock up and then unlock daily after. This scenario requires two separate accounts currently).

**Comment by evan-forbes** [comment]
during the onsite, we decided to use the standard vesting (lockup) module

**Comment by rootulp** [comment]
[no change needed] the Cosmos SDK vesting module appears already enabled: https://github.com/celestiaorg/celestia-app/blob/58352d17a16910ca7de94279b7a25c1ac5b0d791/app/app.go#L146 but we may want an additional issue to verify it can be used as expected.
