### ISSUE TITLE
Investigate why IBC relaying is so expensive

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2807]
## Context

We received a report that states running an IBC relayer for Celestia mainnet costs > 100 TIA per day.

## Proposal

Investigate why IBC relaying is particularly expensive on Celestia. 

## Questions

1. Which parameters impact the cost imposed on IBC relayers?
1. Have any of those parameters been modified from defaults?
1. Is running an IBC relayer for Celestia particularly more expensive than other Cosmos chains?

**Comment by rootulp** [comment]
## Notes

1. Which parameters impact the cost imposed on IBC relayers?
https://github.com/celestiaorg/celestia-app/blob/c34a93d79419a75e077103c3f1785c64f854641c/specs/src/specs/params.md?plain=1#L14

and the default also seems to be [10](https://github.com/celestiaorg/cosmos-sdk/blob/4c897c6e15c7c0b956ca9fa25d0625ff7a39553a/x/auth/spec/06_params.md?plain=1#L13).

// TODO any others?

**Comment by rootulp** [comment]
Closing this as resolved. Please re-open if any questions @Qubelabsio

**Comment by qubelabsio** [comment]
Thanks for investigating, @rootulp. Indeed, the higher costs for IBC relaying as well as other types of transactions come from the `minimum-gas-price` set initially.
