### ISSUE TITLE
Add CLI support for initializing application stores from an existing snapshot

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#2824]
### Summary

In SDK v0.47, a cli feature was introduced that allowed for node operators to initialise their `application.db` based off a trusted snapshot. This provides an alternative way (other than statesync) to bootstrap a node to a certain height. This can be super useful for starting up one node from another trusted node and is important in the case of wanting to debug the state transitions that happen at a certain height

### Proposal

Port over the features https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/client/snapshot/cmd.go

### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
It looks like the snapshots command was originally introduced in https://github.com/cosmos/cosmos-sdk/pull/16067. Our fork already includes https://github.com/celestiaorg/cosmos-sdk/tree/release/v0.46.x-celestia/client/snapshot so I think we just need to add the command to the root celestia-app command.
