### ISSUE TITLE
Adopt the packet forward middleware

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2831]
A common feature request for teams building on IBC is for the PFM to be added to the middleware of celestia-app

**Comment by rootulp** [comment]
Ref: https://github.com/cosmos/ibc-apps/tree/main/middleware/packet-forward-middleware

**Comment by rootulp** [comment]
Based on a synchronous discussion I think we want to hold off on tackling this until a CIP is written.

**Comment by rootulp** [comment]
https://github.com/celestiaorg/CIPs/blob/main/cips/cip-9.md exists and it is in **Review** status.

**Comment by danburck** [comment]
Looking forward to this

**Comment by ninabarbakadze** [comment]
pfm has not been audited, pausing work on this for now.

**Comment by ninabarbakadze** [comment]
decided to resume work on pfm, since it's been integrated and tested by multiple other major projects.
