### ISSUE TITLE
Creating a Celestia  pair account A address  programmatically and transfer

### ISSUE THREAD

**Issue by loveyandex** [celestiaorg/celestia-app#2839]
### Summary

  how to create A account like `celestia1r6extvk2.....` (public and private key) and transfering TIA from A to B Account by coding or rest api

### Problem Definition

same

### Proposal

same

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
I think the docs here https://docs.cosmos.network/v0.46/basics/accounts.html would be helpful.

I'm going to close this issue for now as it seems like a question. Please reopen the issue if this is actually a bug or proposal. If this is a proposal or `enhancement` as tagged, please provide more details as to what is being proposed. Thanks!

**Comment by loveyandex** [comment]
thanks 
What does Cosmoshave to do with Celestia?

**Comment by loveyandex** [comment]
we want straight answer like a code `pair = X.createAccount()` to create new account and also able to transfer TIA from A account to B account (by a code like `X.transferTIA(A, B,1000) `)like cryptocurrency exchange .

please dont DM to other links just give me code in any programing lang

**Comment by evan-forbes** [comment]
> What does Cosmos have to do with Celestia?

this implementation of celestia is built using the cosmos-sdk, so those are docs are critical in understanding how to create an account or create a transaction that moves funds from one account to another.

if you are just interested in digging into code that creates arbitrary transactions, then asking others in the discord is likely the best bet to get started or digging into the user package https://github.com/celestiaorg/celestia-app/blob/main/pkg/user/signer.go

**Comment by evan-forbes** [comment]
Our specification for all of the state machine modules can be found [here](https://github.com/celestiaorg/celestia-app/tree/main/specs/src), and specifically the [x/bank](https://github.com/celestiaorg/cosmos-sdk/blob/v1.14.0-sdk-v0.46.11/x/bank/spec/README.md) can be found here. The bank module contains the logic and sdk.Msg type to transfer funds.

**Comment by loveyandex** [comment]
> Our specification for all of the state machine modules can be found [here](https://github.com/celestiaorg/celestia-app/tree/main/specs/src), and specifically the [x/bank](https://github.com/celestiaorg/cosmos-sdk/blob/v1.14.0-sdk-v0.46.11/x/bank/spec/README.md) can be found here. The bank module contains the logic and sdk.Msg type to transfer funds.

thanks but think simple... i want create account and transer funds(TIA not cosmos) in Celestia . give it that code

**Comment by loveyandex** [comment]
@evan-forbes

**Comment by mindstyle85** [comment]
@loveyandex he gave you all the info you need to work on what you want, stop the spam and tagging please.

**Comment by loveyandex** [comment]
> thanks but think simple... i want create account and transer funds(TIA not cosmos) in Celestia . give it that code

thanks but think simple... i want create account and transer funds(TIA not cosmos) in Celestia . give it that code please

**Comment by loveyandex** [comment]
> @loveyandex he gave you all the info you need to work on what you want, stop the spam and tagging please.

you dont give answer any judger give me right

**Comment by loveyandex** [comment]
Mr @evan-forbes @mindstyle85

**Comment by loveyandex** [comment]
mf @evan-forbes

**Comment by evan-forbes** [comment]
@loveyandex all resources have been provided, and the examples you are looking for are there.

You can ask chatgpt if you want something to write code for you.

**Comment by loveyandex** [comment]
`import (
	"fmt"

	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/tendermint/tendermint/crypto/secp256k1"
)

func main() {
	privKey := secp256k1.GenPrivKey()
	pubKey := privKey.PubKey()
	address := sdk.AccAddress(pubKey.Address())

	fmt.Println("Cosmos SDK account address:", address.String())
}`

this address is cosmos15s7grpjeyepv65k8267ldu07xfusmukekwj7rf

it is not valid in celestia
