### ISSUE TITLE
Add CI test for compiling proto files

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#284]
We currently do not have a test for compiling the proto files in the CI. We should add one.

**Comment by adlerjohn** [comment]
@rootulp @evan-forbes while #555 added a CI workflow to build proto files, it doesn't check that the generated files match the committed files. Should that check also be added to CI?

**Comment by rootulp** [comment]
thanks for flagging @adlerjohn I created https://github.com/celestiaorg/celestia-app/issues/560 and will investigate today
