### ISSUE TITLE
misspelled words

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2848]
## Context

https://goreportcard.com/report/github.com/celestiaorg/celestia-app

## Problem

<img width="747" alt="Screenshot 2023-11-16 at 10 18 01 AM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/c90f3262-6373-4f5c-9923-94b794c5e123">

## Proposal

1. Fix the misspelled words
2. Ensure that CI will fail if new misspelled words are added. We already have this enabled so it may require investigation https://github.com/celestiaorg/celestia-app/blob/fc03393dce943532c618da53069f9331fc575b1d/.golangci.yml#L9

**Comment by Caerlower** [comment]
> ## Context
> https://goreportcard.com/report/github.com/celestiaorg/celestia-app
> 
> ## Problem
> <img alt="Screenshot 2023-11-16 at 10 18 01 AM" width="747" src="https://user-images.githubusercontent.com/3699047/283501596-c90f3262-6373-4f5c-9923-94b794c5e123.png">
> ## Proposal
> 1. Fix the misspelled words
> 2. Ensure that CI will fail if new misspelled words are added. We already have this enabled so it may require investigation https://github.com/celestiaorg/celestia-app/blob/fc03393dce943532c618da53069f9331fc575b1d/.golangci.yml#L9

I would like to do this issue can you assign this issue to me.

**Comment by rootulp** [comment]
Nvm it looks like the previous report was based on a view of the codebase that was a year old. I refreshed the report via **Refresh now** and now there are no more reported spelling mistakes 

<img width="750" alt="Screenshot 2023-11-17 at 10 03 57 AM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/1fd8f726-9e40-44ad-ba8e-afb85045d687">

**Comment by Caerlower** [comment]
> Nvm it looks like the previous report was based on a view of the codebase that was a year old. I refreshed the report via **Refresh now** and now there are no more reported spelling mistakes
> 
> <img alt="Screenshot 2023-11-17 at 10 03 57 AM" width="750" src="https://user-images.githubusercontent.com/3699047/283842060-1fd8f726-9e40-44ad-ba8e-afb85045d687.png">

okay, thanks for assigning me the request.
