### ISSUE TITLE
Panic when send tx and set fees without typing unit.

### ISSUE THREAD

**Issue by HoytRen** [celestiaorg/celestia-app#2857]
### Summary of Bug

```
celestia-appd tx distribution withdraw-rewards celestiavaloper1zdrz4w2pwwffdvmpum0626vycel9caay9n3pll --from W3 --commission --fees 21500
```

It's panic because '21500' but not '21500utia'.

### Version

1.3.0 on mainnet.

**Comment by evan-forbes** [comment]
Hey again @HoytRen, I believe this is intented behavior from the cosmos-sdk. If you think this should be changed, then I would reccomend moving this upstream. There might be a way to pick a default denomination for fees, but I'm not sure we would adopt such a feature without it also being adopted upstream.

If this is a bug or something else, please elaborate further and reopen this issue, :slightly_smiling_face: thanks!

**Comment by HoytRen** [comment]
Hi, @evan-forbes don't see you for a while. I believe it just need to be wrapped with a error prompt. I may have time to look into the code on thursday or friday.

**Comment by HoytRen** [comment]
I checked the code and need more time to work out a solution because the sdk doesn't throw out errors by design. Hardcoding the error prompt could be a solution, but can not be pushed back to upstream, then I need to think about a better solution so that we don't need to maintain the modification over and over again.

**Comment by HoytRen** [comment]
Maybe, I should close this issue, and try a PR to Cosmos SDK, and wait until Celestia imports the new version of SDK?

**Comment by HoytRen** [comment]
I checked the latest version of Cosmos SDK, this problem is fixed already, then, let me close this issue and simply wait for bump up of the sdk.

**Comment by rootulp** [comment]
Thanks for investigating this! Out of curiosity which Cosmos SDK version fixes this? celestia-app currently uses a fork of cosmos-sdk that we regularly pull upstream changes from.

Ref: https://github.com/celestiaorg/cosmos-sdk/releases/tag/v1.20.0-sdk-v0.46.16 which is based on Cosmos SDK v0.46.16
