### ISSUE TITLE
Auto retry CI for specific errors

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2858]
There are two common errors that are simply due to the CI setup that we can auto retry for for all integration tests.

- If the IP is already in use
- If no directory exists

We should be able to do this in testnode. We should also be careful to only retry on errors that are unavoidable and only due to github's CI setup, and never for errors that could be otherwise fixed by us writing more robust or bugfree tests.

**Comment by rootulp** [comment]
> If no directory exists

A clean up function may be failing a test because it fails to delete a directory. If the directory was already deleted, it may be safe to ignore that error and continue running the test.

**Comment by rootulp** [comment]
I found one instance of the IP already in use issue:
1. https://github.com/celestiaorg/celestia-app/actions/runs/6324469397/job/17174044490#step:4:63

**Comment by rootulp** [comment]
Closing as won't do for now. Trying to fix flakes via other means.
