### ISSUE TITLE
'incorrect account sequence' when calling celestia-appd tx bank send many times in single block

### ISSUE THREAD

**Issue by zvolin** [celestiaorg/celestia-app#2869]
### Summary of Bug

I have a celestia network docker compose setup which starts a validator node and a few bridge nodes. The validator node should transfer some of it's coins to the bridges to let them operate. Unfortunately it only works if I wait for the next block after each coins transfer.

### Version

v1.0.0-rc17, v1.0.0, v1.3.0

### Steps to Reproduce

Assuming you have validator node with keys name 'validator-0'
```sh
fd236fbdb8d0:/$ for addr in celestia1kkaeqfx4qhdv7g9y9s4m30utwp328ezh5xzkt9 celestia1qtl602v5jqcen9yam052fywr6te7ulfqu4x7qt; do                                                                
    celestia-appd tx bank send validator-0 "$addr" 100000utia --fees 21000utia
done
```

outputs
```
auth_info:
  fee:
    amount:
    - amount: "21000"
      denom: utia
    gas_limit: "210000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /cosmos.bank.v1beta1.MsgSend
    amount:
    - amount: "100000"
      denom: utia
    from_address: celestia1zy95eqlpfr2afytefsknuvgp9uussk5hhmj2h5
    to_address: celestia1kkaeqfx4qhdv7g9y9s4m30utwp328ezh5xzkt9
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: 97E6F63C32C6FCF827805CC321DAAC26D887A929ADF74A39545569669F900589
auth_info:
  fee:
    amount:
    - amount: "21000"
      denom: utia
    gas_limit: "210000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /cosmos.bank.v1beta1.MsgSend
    amount:
    - amount: "100000"
      denom: utia
    from_address: celestia1zy95eqlpfr2afytefsknuvgp9uussk5hhmj2h5
    to_address: celestia1qtl602v5jqcen9yam052fywr6te7ulfqu4x7qt
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 32
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'account sequence mismatch, expected 4, got 3: incorrect account sequence'
timestamp: ""
tx: null
txhash: 98CCF59092C200163118C969B1335A589D30C735A622A0ACE64599AD50B46E4C
```

Notice the result of second transfer:
```
'account sequence mismatch, expected 4, got 3: incorrect account sequence
```

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
> Unfortunately it only works if I wait for the next block after each coins transfer.

This is an astute observation! It is because all CometBFT/cosmos-sdk based chain currently use "deferred execution", so the txs don't actually get executed until after consensus has been reached, and therefore the state doesn't get updated until the next block. 

If this makes sense and you agree that this isn't a bug, do you mind closing this issue? Thanks for opening it though, someone else in the future might find it helpful.

**Comment by zvolin** [comment]
Hey
> celestia-appd tx bank multi-send

this one works for my use case so I'm fine with it.

> you agree that this isn't a bug, do you mind closing this issue?

I'm not sure if it is a bug or not, so I'll leave it up to you. I don't mind closing this tho, thanks

**Comment by evan-forbes** [comment]
@zvolin you might also be interested in the `celestia-appd tx feegrant` module, it enables the user to keep funds in a single account, and then that account can pay for gas fees of an arbitrary number of other accounts
