### ISSUE TITLE
Update spec with signalling upgrades

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2874]
With the addition of signalling upgrades in #2832, we should also update the spec to match the new implementation. This could go hand in hand with writing the spec.

**Comment by rootulp** [comment]
https://github.com/celestiaorg/celestia-app/pull/3224 updates the `x/upgrade` README which we use as specs for modules. Does this issue entail adding a dedicated page to the [specs](https://celestiaorg.github.io/celestia-app/)? If not, we can close it after #3224 merges.
