### ISSUE TITLE
Consider removing "version_bump"

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2884]
## Context

We have a `version_bump` workflow in ci-release that is responsible for pushing a new tag if a Release is created via

<img width="350" alt="Screenshot 2023-11-30 at 3 08 38 PM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/89f7f7c8-d197-4744-8a21-90e6d891093d">

https://github.com/celestiaorg/celestia-app/blob/35b76bf55faa96d869bccb64cd7fe29ebfd8728a/.github/workflows/ci-release.yml#L50-L82

## Proposal

If we decide that this feature isn't necessary and we're okay with creating releases via https://github.com/celestiaorg/celestia-app/releases/new then we can remove the `version_bump` and `branch_name` workflows. This would simplify the ci-release file.

**Comment by anhductn2001** [comment]
Can I take this issue ?

**Comment by rootulp** [comment]
Let's hold off for now because we need alignment that it's safe to remove this feature.

cc: @evan-forbes

**Comment by anhductn2001** [comment]
Make sense!!
