### ISSUE TITLE
Write an initial draft implementation of the Tx and Account Type

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2905]
In order to better understand, design, and specify SNARK accounts, we should have an initial implementation that focuses purely on the new tx and account type.

Criteria:
- the new SNARKTx type
- module to accomodate the new SNARKAccount type
- tooling to create the new tx type in the user package
- groth16 verifier 
- unit and integration tests that use super simple predicates

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/celestia-app/issues/2923
```

**Comment by staheri14** [comment]
Not sure if we are going to need this issue @evan-forbes, shall we close it?

**Comment by evan-forbes** [comment]
Yeah we can close it.
