### ISSUE TITLE
Mock Implementation of a SNARK Account Rollup

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2906]
In order to better understand, specify, and design SNARK accounts, we should implement a mock SNARK Account rollup. While not required to close this issue, if this is implemented in go code, it could be used to help test the implementation for SNARK Accounts.

**Comment by cmwaters** [comment]
Closing this in favour of https://github.com/celestiaorg/celestia-app/issues/4001 and https://github.com/celestiaorg/celestia-app/issues/4000 which are the two success criteria for the ZK IBC Client
