### ISSUE TITLE
Design a SNARK Account Gas Payment Mechanism

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2907]
SNARK Accounts are supposed to be able to do everything that a normal account could. This includes paying for gas. However, there are usecases where the users of the SNARK account don't want thier funds to be usable by a prover to pay for gas. To better accomodate these scenarios, we need the ability to restrict a SNARK Account so that it must rely on another account to pay for gas. We could
- Use a new transaction that works in a similar way to authz, where we are essentrially wrapping a SNARK tx with a normal tx signed by a different user
- Use something similar to or just use feegranter

**Comment by cmwaters** [comment]
This no longer seems relevant for the current ZK accounts work. If so, can we close this?

**Comment by evan-forbes** [comment]
agree, closing
