### ISSUE TITLE
Adopt Tx prioritization  

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#291]
## Summary

With upgrading the SDK to 0.46.x ([beta is tagged](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.0-beta2)) and tendermint 0.35.x, we get Tx prioritization. But we should make sure that this also properly applies to messages/data in the same namespace. Or as @musalbas put it:
> for validators I think we should introduce a tx prioritisation mechanism where if there are multiple transactions in the same namespace, the one that pays the highest fees gets included first
> When ordering messages in the block
> This is so that sovereign zk rollups can impose block size limits... Because generating proofs is expensive (edited) 
> So DoS resistance is needed

This is somewhat critical for launch and hence for incentivized testnet too. Let's add a test-case that asserts the above behaviour.

**Comment by evan-forbes** [comment]
closing as we updated to v0.46 of the sdk, but also created #513
