### ISSUE TITLE
Increase test coverage for governance modifiable and governance unmodifiable params

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2916]
## Context

Our specs have [params.md](https://github.com/celestiaorg/celestia-app/blob/main/specs/src/specs/params.md) which has a column for whether a parameter is governance modifiable. 

## Problem

AFAICT there aren't tests that verify whether the parameters in the table are governance modifiable. https://github.com/celestiaorg/celestia-app/blob/ce1c6cd93278031bb56ed9910e5c706aa2c3c6cc/x/paramfilter/test/param_filter_test.go#L17 exists but it only verifies the 4 blocked params aren't modifiable: https://github.com/celestiaorg/celestia-app/blob/ce1c6cd93278031bb56ed9910e5c706aa2c3c6cc/app/app.go#L733-L746

## Proposal

Increase the test coverage of the blocked / unblocked params. Ideally each param in the table is covered by a test.

**Comment by fahimahmedx** [comment]
Taking this on!
