### ISSUE TITLE
`TempDir RemoveAll cleanup: unlinkat ... application.db: directory not empty`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2918]
## Context

We're trying to eliminate test flakes in this repo. A flake just occurred

```
--- FAIL: TestSquareSizeIntegrationTest (107.50s)
    square_size_test.go:47: setting up square size integration test
    network.go:48: tearing down testnode
    rpc_client.go:39: stopping tmNode
    rpc_client.go:45: tmNode has stopped
    rpc_client.go:99: removing addrbook.json
    rpc_client.go:99: removing genesis.json
    rpc_client.go:99: removing node_key.json
    rpc_client.go:99: removing priv_validator_key.json
    rpc_client.go:105: removing /tmp/TestSquareSizeIntegrationTest3506[33](https://github.com/celestiaorg/celestia-app/actions/runs/7143755872/job/19455934846#step:4:34)4195/001/.celestia-app/config
    testing.go:1225: TempDir RemoveAll cleanup: unlinkat /tmp/TestSquareSizeIntegrationTest35063[34](https://github.com/celestiaorg/celestia-app/actions/runs/7143755872/job/19455934846#step:4:35)195/001/.celestia-app/data/application.db: directory not empty
```

## Occurrences

- https://github.com/celestiaorg/celestia-app/actions/runs/7143755872/job/19455934846#step:4:27
- https://github.com/celestiaorg/celestia-app/actions/runs/7189162265/job/19580189334#step:4:30
- https://github.com/celestiaorg/celestia-app/actions/runs/7253416073/job/19759958051?pr=2940#step:4:30

**Comment by cmwaters** [comment]
I would assume the other directories are also not empty, right?

Perhaps we need to apply:
https://github.com/celestiaorg/celestia-app/blob/e0edb4cf0d89a08c46c5634d653e44a77d1d517c/test/util/testnode/rpc_client.go#L39
to the `data` directory as well

**Comment by rootulp** [comment]
Hmm can try that. So far the flakes are only for `.celestia-app/data` so I think your suggestion could resolve
