### ISSUE TITLE
Investigate simplifying `KeyringSigner` api 

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#294]
per dicsussion in https://github.com/celestiaorg/celestia-app/pull/293#discussion_r848826246 we should be able to simplify the API for the `KeyringSigner` by unexporting `QueryAccount`

**Comment by evan-forbes** [comment]
after thinking about this more, I'm not sure that we should do this exact change, as we need to sign the share commitments after we query for the account number. We should still take another look at simplifying the API though

cc: @renaynay

**Comment by renaynay** [comment]
It would make my life a lot easier if the canonical implementation of constructing + signing a PFD existed in celestia-app @evan-forbes

**Comment by renaynay** [comment]
I have the initial implementation here: 

https://github.com/celestiaorg/celestia-node/pull/619

**Comment by evan-forbes** [comment]
We should be able to not use the keyring signer after implementing #951

**Comment by evan-forbes** [comment]
can close with addition of the canonical mechanism for submitting a PFB and the user package
