### ISSUE TITLE
Fix the proto-gen script 

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#295]
## Problem statement
Currently, the `protogen.sh` script is not up-to-date with the `tendermintdev/sdk-proto-gen` docker image changes.
And that is  because, [`buf`](https://github.com/bufbuild/buf/releases) dropped support for:
```ssh
$ buf protoc ...
```
after version `1.0.0`. 
Thus, the current scripts need to be updated to follow this change and be able to run:
```ssh
$ make proto-gen
```
Correctly. 

## Expected behavior
```ssh
$ make proto-gen
```
Executes without errors.

##  Actual behavior
```ssh
$ make proto-gen
```
Returns errors.

### More context
Check the following:
- Updated cosmos-sdk `protocgen` script: https://github.com/cosmos/cosmos-sdk/blob/master/scripts/protocgen.sh
- `Buf` releases: https://github.com/bufbuild/buf/releases

**Comment by evan-forbes** [comment]
closing for now with #340
