### ISSUE TITLE
Add a column for which params are governance modifiable

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2966]
## Context

https://github.com/celestiaorg/celestia-app/blob/4a3500d3e14fab6b788984d4344279a79443bed9/specs/src/specs/resource_pricing.md?plain=1#L142-L152

## Problem

The statement before the table claims 3 params are governance modifiable but it's not immediately clear which 3 out of the 4 in the table are governance modifiable.

## Proposal

Add a column to the table that states if a param is governance modifiable

**Comment by SanjayNithin2002** [comment]
Can you tell which parameter is not governance modifiable?

**Comment by rootulp** [comment]
I can't. We do have https://celestiaorg.github.io/celestia-app/specs/params.html but it may not be 100% correct because  https://github.com/celestiaorg/celestia-app/issues/2916

**Comment by fahimahmedx** [comment]
Made a PR for this: #2974

**Comment by fahimahmedx** [comment]
PR is merged, this can be closed now! :)

**Comment by rootulp** [comment]
Thanks @fahimahmedx !
