### ISSUE TITLE
[bug]: Nondescript error code returned when trying to submit tx using reserved `namespaceID`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-app#297]
Attempted to submit a tx with `nID = []byte{0,0,0,0,0,0,0,0}`

Got: 
```
        Response:
          TxHash: BD4DDDEF78464185F1FB96F7904EDA568435E83DDC9CFA4EBDECAAE35751E83D
          Code: 1
          Raw Log: internal
          GasUsed: 6474
          Codespace: undefined
```

Instead of returning `internal`, it should return a `reserved namespace` error or something like that.

cc @liamsi 

Btw, when submitting a PFM with `nID = []byte{0, 0, 1, 0, 0, 0, 0, 0}`, I get success: 

```
        Response:
          Height: 8164
          TxHash: 8D7FBF77ACBAE66875438BBDD33C3DCB94C33882A3E396C52C52A87D4FAB456C
          Data: 0A1B0A192F7061796D656E742E4D7367506179466F724D657373616765
          Raw Log: [{"events":[{"type":"message","attributes":[{"key":"action","value":"/payment.MsgPayForMessage"}]},{"type":"payformessage","attributes":[{"key":"signer","value":"celes1vdjkcetnx9khvun3d4kx2emvx36hxertw3skwamp0furvvrnvaerqut5d4nns6nc8pmrvvcxu6e2w"},{"key":"size","value":"256"}]}]}]
          Logs: [{"events":[{"type":"message","attributes":[{"key":"action","value":"/payment.MsgPayForMessage"}]},{"type":"payformessage","attributes":[{"key":"signer","value":"celes1vdjkcetnx9khvun3d4kx2emvx36hxertw3skwamp0furvvrnvaerqut5d4nns6nc8pmrvvcxu6e2w"},{"key":"size","value":"256"}]}]}]
          GasWanted: 200000
          GasUsed: 38486
```

**Comment by evan-forbes** [comment]
> Btw, when submitting a PFM with nID = []byte{0, 0, 1, 0, 0, 0, 0, 0}, I get success:

wait, should this fail or is this related to something else?

**Comment by liamsi** [comment]
No, I think Rene is just confirming that this works with a proper non-reserved namespace.

**Comment by renaynay** [comment]
No I'm just saying the happy case works fine @evan-forbes

**Comment by liamsi** [comment]
We are trying to say the same thing Rene :D 

This should help resolve this:
https://github.com/celestiaorg/cosmos-sdk/blob/68dd969b4d3ae42728b63753f2bd28b273e6eb21/types/errors/doc.go#L9-L12

**Comment by renaynay** [comment]
race condition comments @liamsi  😂
