### ISSUE TITLE
Parameters that are stated as not governance modifiable, are actually governance modifiable.

### ISSUE THREAD

**Issue by fahimahmedx** [celestiaorg/celestia-app#2972]
### Problem

Two governance params are actually modifiable when the specs claim they aren't governance modifiable:

- `consensus.Version.AppVersion`
- `staking.MaxValidators`

## Proposal

Update the specs

**Comment by rootulp** [comment]
IMO we should update the specs to state these params are governance modifiable. We'll also need to update https://github.com/celestiaorg/CIPs/blob/main/cips/cip-13.md

We can only make them non governance modifiable via a hard-fork which requires a CIP.

**Comment by rootulp** [comment]
The original issue isn't accurate because these aren't governance modifiable:
- bank.SendEnabled
- staking.BondDenom
- staking.UnbondingTime
- conensus.validator.PubKeyTypes

Modification is prevented via the paramfilter.

**Comment by rootulp** [comment]
Since only two params are modifiable
- consensus.Version.AppVersion
- staking.MaxValidators

Let's repurpose this issue to fix the specs for those two.
