### ISSUE TITLE
Add support for arabica-11 in download-genesis command

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2976]
## Context

A new testnet is being deployed: https://github.com/celestiaorg/devops/issues/692

## Problem

The `download-genesis` command only supports hard-coded chain-ids. See https://github.com/celestiaorg/celestia-app/blob/95496d90c79ad841c728998f6b51ecf9277adb5c/cmd/celestia-appd/cmd/download_genesis.go#L15-L22

## Proposal

After `arabica-11` is deployed, add it to the list of supported chain-ids.

**Comment by subhajit20** [comment]
Hey I want to work on this.
Can you assign this issue to me?

**Comment by subhajit20** [comment]
hey @rootulp , made a pr as of now and after adding the arabic-11 I will add the hash right there.
