### ISSUE TITLE
mdbook serve creates a `specs/src/https:/` directory

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2995]
### Summary of Bug

When I run `mdbook serve` for the specs, a new directory gets created with README.md pages for all the Celestia-specific modules

```
$ tree specs/src/https:/github.com/celestiaorg/celestia-app/blob/main/x
.
├── blob
│   └── README.md
├── blobstream
│   └── README.md
├── mint
│   └── README.md
├── paramfilter
│   └── README.md
├── tokenfilter
│   └── README.md
└── upgrade
    └── README.md
```

All the READMEs just contain a header. I don't think these are necessary so ideally mdbook serve doesn't create them.

### Version

main

### Steps to Reproduce

```bash
cd specs
mdbook serve
```

Observe that a new directory was created

**Comment by subhajit20** [comment]
@rootulp hey can you help me to solve this issue.

**Comment by rootulp** [comment]
Sure! To repro the issue, 
1. Navigate to the specs directory in this repo 
2. Run `mdbook serve`
3. Confirm that some new directories were created via `git status`

To resolve the issue, I think we want to investigate why mdbook creates blank READMEs for the Celestia-specific modules. Does that make sense?

**Comment by subhajit20** [comment]
> Sure! To repro the issue,
> 
> 1. Navigate to the specs directory in this repo
> 2. Run `mdbook serve`
> 3. Confirm that some new directories were created via `git status`
> 
> To resolve the issue, I think we want to investigate why mdbook creates blank READMEs for the Celestia-specific modules. Does that make sense?

Okay will do that

**Comment by subhajit20** [comment]
hey @rootulp I can't find mdbook command how to install that?

**Comment by rootulp** [comment]
Turns out we don't need these in the summary page. https://github.com/celestiaorg/celestia-app/blob/e05d105e537f1c34bf5a48586f0d0ac32b51df1b/specs/src/SUMMARY.md?plain=1#L21-L26

mdbook is trying to create pages for them.
