### ISSUE TITLE
Use nodes local min gas price for prepare proposal

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#3016]
### Summary

The global min gas price is used as the minimum price for a transaction to enter a nodes mempool. The node still has a locally configured min price. This should be used when preparing the proposal such that all transaction included must be greater than that price

### Proposal

In `PrepareProposal`, while looping through all transactions, if one has a gas price lower than the nodes own threshold skip over it and do not include it in the list of transactions to be proposed

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
> The global min gas price is used as the minimum price for a transaction to enter a nodes mempool. The node still has a locally configured min price. This should be used when preparing the proposal such that all transaction included must be greater than that price

do transactions make it in the mempool that are less than the locally configured min fee? if not, then would the filter in prepare proposal every filter anything out?

**Comment by cmwaters** [comment]
> do transactions make it in the mempool that are less than the locally configured min fee?

Yes so long as they are greater than the global min gas price. 

The locally configured min fee just means that this proposer won't include them but they may be included by another proposer. If the transaction has too low of a fee, it will eventually be kicked.

**Comment by rootulp** [comment]
Sorry for the silly question but why do we want to support this?

**Comment by ninabarbakadze** [comment]
update: we stopped working on this until we figure out next steps including whether or not we even want this feature.

**Comment by rootulp** [comment]
I think we can close this as won't do b/c we decided to not modify the local min gas price. Copying from Slack:

> Decision to not modify the purpose of the local config. It can still be used to increase the min fee to be accepted in the mempool.

Please re-open if I misinterpreted @ninabarbakadze @cmwaters
