### ISSUE TITLE
Be consistent in the naming for QGB

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#303]
Currently, in the QGB branch, we are confusing the names of the following:
- `evmAddress` and `ethereumAddress`
- `valset` and `valSet`
- `validatorAddress` should be changed to `orchestratorAddr` in the `MsgDataCommitment` struct: https://github.com/celestiaorg/celestia-app/issues/243
This should be fixed to have a cleaner codebase.

**Comment by SweeXordious** [comment]
Also, on the cosmos-sdk side, the following issue discusses it: https://github.com/celestiaorg/cosmos-sdk/issues/136

**Comment by evan-forbes** [comment]
per sync discussion, this issue can be closed due to moving to v2
