### ISSUE TITLE
Consider moving BlockedParams to paramfilter

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3038]
nice, if we're going to add the tests here, then we might want to move the actually params to block here as well. super duper optional tho

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/3007#pullrequestreview-1839913987_

**Comment by rootulp** [comment]
@evan-forbes is the proposal to move https://github.com/celestiaorg/celestia-app/blob/cd0a1cdbb2b06c9e3e89bbdaa54cfbfbb23a5c6d/app/app.go#L733-L746 from the app package to the paramfilter package? I think that's API breaking but do-able.

**Comment by evan-forbes** [comment]
yeah, I think that would close this issue. I'm still of the opinion that its super optional. I don't see that much benefit either way.

we could explore other refactors as well. in the context of versioning and migrations, there might be a small benefit to moving the module. It could also make it worse if we have to import a bunch of modules with their own go mods there just to name them

**Comment by rootulp** [comment]
kk if super optional, let's close as won't do for now. Please reopen if there's a compelling reason to do this
