### ISSUE TITLE
Separate the proto-gen from the proto-breakage CI

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3049]
this is a kinda unrelated, but I think we should separate the proto-gen vs proto-break-check. 

it might be okay if the proto has changed, like in this PR. However we are bundling that check with the one that compiles the protos and checks for a difference in generated code, which should always block merging. (tbc, the second check doesn't appear to be hit here)

https://github.com/celestiaorg/celestia-app/blob/5476636002d4c4be029718230d5f8f6d321e3b6f/.github/workflows/protobuf.yml#L12-L34

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/issues/3026#issuecomment-1912256791_

**Comment by rootulp** [comment]
Sorry I don't quite follow. All three jobs are running. See https://github.com/celestiaorg/celestia-app/actions/runs/7660757233?pr=3026

**Comment by evan-forbes** [comment]
just so that its easier to see which is failing

**Comment by evan-forbes** [comment]
lol sorry yeah I get that, but I guess I'm just complaining that I have to click :shrug: 

![Screenshot from 2024-02-06 09-51-48](https://github.com/celestiaorg/celestia-app/assets/42654277/d508a277-638b-4bc3-8e8c-f540851ce76e)

**Comment by evan-forbes** [comment]
also, can we make one blocking and another not without splitting?

**Comment by rootulp** [comment]
> also, can we make one blocking and another not without splitting?

Yes. In the screenshot proto-gen is **Required** to pass before we merge a PR. proto-check-breaking is not required to pass before we merge.

> lol sorry yeah I get that, but I guess I'm just complaining that I have to click 🤷

What do you mean you have to click? The 3 jobs have 3 separate Details links.

**Comment by evan-forbes** [comment]
okay I think I'm just blind then and complaining about nothing, apologies for the confusion

will close

**Comment by rootulp** [comment]
no worries, thanks for closing! Since there are so many CI tasks, I think it's easy to miss the one you were looking for on the original PR.
