### ISSUE TITLE
Go over the small TODOs left in the QGB

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#305]
The minor TODOs we have in the QGB that are not tracked by any issue (won't be useful to have separate issues for them) need to be fixed before merging the QGB branch to master.

**Comment by SweeXordious** [comment]
Also, go over the `nolint` flags we're adding to the codebase for the linter to pass and see if there is a better way to handle them

**Comment by evan-forbes** [comment]
per sync discussion, this issue can be closed due to moving to v2
