### ISSUE TITLE
Local test environment for IBC features

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3050]
## Context 

There are 3 active CIPs related to IBC:
1. [CIP-9](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-9.md): Packet Forward Middleware 
2. [CIP-12](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-12.md): Relayer Incentivisation Middleware
3. [CIP-14](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-14.md): Interchain Accounts

## Problem

While we can develop these and test them on Mocha, that would involve cutting RCs and coordinating with external parties to upgrade Mocha.

## Proposal

Ideally we would have a faster iteration cycle while implementing these CIPs. It would be nice to test these features in a local environment prior to deploying to a testnet. Proposal to write some script that allows a contributor to spin up a test environment with at least:
1. Celestia devnet
2. Cosmos Hub devnet (or any another IBC chain)
3. IBC relayer

and then spins up the necessary IBC channels and connections. This script could use [docker-compose](https://docs.docker.com/compose/), [kurtosis](https://www.kurtosis.com/), or any other tool.

**Comment by rootulp** [comment]
Tip from @evan-forbes  is to check out:
- https://github.com/cosmos/ibc-go/tree/v6.0.0/testing
- https://github.com/celestiaorg/celestia-app/blob/30aa1b0dddf5871f51b99e60b925dca6caeacc95/test/tokenfilter/tokenfilter_test.go#L1

**Comment by evan-forbes** [comment]
does this still need to be open?

**Comment by rootulp** [comment]
We can close. We'll need to test all three of these features before we release them so we include tests (and the necessary testing tools) in the PRs that implement the features.

**Comment by rootulp** [comment]
Circling back on this [interchaintest](https://github.com/strangelove-ventures/interchaintest) seems to be the most adopted tool for this but I'm curious if there are others b/c it wasn't easy to set up.
