### ISSUE TITLE
`GlobalMinGasPrice` doesn't support versions outside of v2

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3067]
`GlobalMinGasPrice` currently throws an error if if the version is not v2.

https://github.com/celestiaorg/celestia-app/blob/ef3c0d574973fb8aabedb1c1d9626f6a24ccdb31/pkg/appconsts/versioned_consts.go#L27-L36

When running on a chain that is currently on v1, this will cause non-determinism since this value is called in the antehandlers in process and prepare proposal. It will also stop all txs from being able to be created or pass CheckTx.

**Comment by ninabarbakadze** [comment]
I was just in the process of fixing it when I realised that the only place this function is getting called is in `CheckTxFeeWithGlobalMinGasPrices` inside the if clause where the `appVersion` has to be greater than 1. https://github.com/celestiaorg/celestia-app/blob/ef3c0d574973fb8aabedb1c1d9626f6a24ccdb31/app/ante/fee_checker.go#L32

I could be missing something but I don't understand how this would be causing issues on v1

**Comment by evan-forbes** [comment]
yeah good point, it shouldn't cause issues on v1, however it will cause issues on versions greater than v2, such as in the testground tests
