### ISSUE TITLE
Discrepancy in Public Address for Genesis $TIA Airdrop on Mainnet

### ISSUE THREAD

**Issue by rajeshb62** [celestiaorg/celestia-app#3073]
### **Summary**

There appears to be a discrepancy between the public address used for the Genesis $TIA airdrop on the Mamaki testnet (it was so long ago, I know!!) and the address generated on the Mainnet using the same mnemonic.

### **Details**

In 2022, I set up a node on the Mamaki testnet and received a public address and corresponding seed phrase/mnemonic. This address (**celestia1ksk5qncg4xyl4mknswygvx66yecha2q63c0ymt**) was used for the Genesis $TIA airdrop. I have confirmed that the airdrop did occur at this address.

However, upon transitioning to the Mainnet, using the same mnemonic/seed phrase now points to a different public address (**celestia176vjgncu9k0zy3gyu8h7dq2y53r35ngm4gk6af**). As a result, I am unable to access the airdropped $TIA tokens, as they were delivered to the initial address on the Mamaki testnet.

### Expected Behavior

The mnemonic used on the Mamaki testnet should point to the same public address on the Mainnet, allowing access to the airdropped $TIA tokens.
Steps to Reproduce

    Set up a node on the Mamaki testnet in 2022.
    Receive a public address and mnemonic.
    Use the same mnemonic on the Mainnet.
    Observe that the Mainnet generates a different public address.

### Additional Information

    Mamaki Testnet Address: celestia1ksk5qncg4xyl4mknswygvx66yecha2q63c0ymt
    Mainnet Address (using the same mnemonic): celestia176vjgncu9k0zy3gyu8h7dq2y53r35ngm4gk6af

I kindly request guidance or a resolution on how to access the airdropped tokens, or an explanation if this behavior is expected due to differences between the testnet and Mainnet.

**Comment by rajeshb62** [comment]
Hey @evan-forbes , need your help with resolving this issue!

**Comment by rootulp** [comment]
Caveat before anything else: please don't share your mnemonic or private key with anyone.

1. Can you describe which tool you used to create the Celestia address? For example: 
    1. `celestia-appd keys add foo`
    2. Keplr
1. If you used `celestia-appd keys add`, did you supply the `--interactive` flag? If yes, please review https://github.com/celestiaorg/celestia-app/issues/2674
1. Are you using the same tool for testnet and mainnet? Or did you create an address with one and you're trying to import it into a different tool?

**Comment by evan-forbes** [comment]
was a password used? that adds to the mnemonic

is the same keypath being used?

**Comment by rajeshb62** [comment]
answers to rootulp:
1. I used commandline. I need to dig up and then revert on the commands used
2. Dont remember. Will revert
3. I used different tools! For Mamaki testnet i used command line. For mainnet, I used keplr & leap wallet plugins

Answers to Evan:
1. No password was used
2. I dont know what a keypath is :(. Fwiw here is the details I had copied from commandline
2022-10-19T16:28:30.438+0530 INFO state-access-constructor state/keyring.go:69 constructed keyring signer {"backend": "test", "path": "/home/ubuntu/.celestia-light/keys", "key name": "my_celes_key", "chain-id": "mamaki"}

The questions have been informative. I will try using command line to access the wallet, and revert only if it still does not solve the problem!!!

Thank you for your patience.

**Comment by rootulp** [comment]
Based on that log, it seems like you used https://github.com/celestiaorg/celestia-node to generate the key. I have a rough idea of steps you could use to export your key and import it in Keplr (if that's what you want to do). I just did this for a Celestia light node key that was funded on the mocha-4 testnet.

1. `git clone https://github.com/celestiaorg/celestia-node`
2. `make cel-key`
3. `./cel-key export my_celes_key --p2p.network mamaki --node.type light --unarmored-hex --unsafe`
4. In Keplr: Add wallet -> Import an existing wallet -> Use recovery phrase or private key -> Private key -> Paste value from step 3

**Comment by rootulp** [comment]
@rajeshb62 any updates?

**Comment by rajeshb62** [comment]
Thank you for the follow up!

make cel-key
does not work on my mac. I get error  'make: *** No rule to make target `cel-key'.  Stop.' when i run command outside celestia-node. I get error, '-bash: ./cel-key: No such file or directory' when i run in celestia-node directory

I removed a lot of the libraries and files on my mac, deleted some old system data and reinstalled docker a few months ago to reduce space used on disc. I wonder if the data on 'my-celes-key' including private key got deleted it too.

I wish that was not the case! I would be accessing my wallet on mainnet right now.

So as of now status is still the same. I am unable to access the funds on celestia1ksk5qncg4xyl4mknswygvx66yecha2q63c0ymt

**Comment by rootulp** [comment]
>  I get error 'make: *** No rule to make target `cel-key'.

Try checking out v0.12.4 and then running make cel-key. If you cloned the repo:

```
cd celestia-node
git checkout v0.12.4
make cel-key
```

> I wonder if the data on 'my-celes-key' including private key got deleted it too.

You can look for directories prefixed with `~/.celestia-*`. For example I have a directory called: `~/.celestia-light-mocha-4/keys`

**Comment by rajeshb62** [comment]
I checked out v0.12.4 and ran make cel-key, reproducing commands above. I get the following error:

$ make cel-key
--> Building cel-key
bash: line 1: go: command not found
make: *** [cel-key] Error 127

search for file with private key came to a dead end. there is no such file or directory on my mac.

**Comment by rootulp** [comment]
- That error indicates that Go isn't installed so you would need to install Go. See https://go.dev/doc/install
- Hmm if there are no directories in `~/.celestia-*` then I'm not sure where else to look. Do you have backups of your machine before you deleted directories. For example do you use Time Machine? If not, then we don't need to pursue this path.
- Given you still have the seed phrase, you should be able to recover the public/private key for this address on mainnet. One option is to use the [celestia-app](https://docs.celestia.org/nodes/celestia-app#install-celestia-app) binary

```
$ celestia-appd keys add --recover foo
> Enter your bip39 mnemonic
```

**Comment by rajeshb62** [comment]
I could not find my_celes_key by the make cel-key option. I got the following error:

 git checkout v0.12.4
HEAD is now at 8e5a7174 ci: add continue-on-error temporarily (#3100)
apples-MacBook-Air:celestia-node appleapple$ make cel-key
--> Building cel-key
apples-MacBook-Air:celestia-node appleapple$ ./cel-key export my_celes_key --p2p.network mamaki --node.type light --unarmored-hex --unsafe
WARNING: unknown network specified:  mamaki
using directory:  /Users/appleapple/.celestia-light-mamaki/keys
WARNING: The private key will be exported as an unarmored hexadecimal string. USE AT YOUR OWN RISK. Continue? [y/N]: y
Error: my_celes_key.info: key not found

**More importantly**, I tried to get hold of public/ private key using mnemonic, using celestia-app binary as shown by you. The mnemonic points to the wrong public address (celestia176vjgncu9k0zy3gyu8h7dq2y53r35ngm4gk6af), the one different from the mamaki public address. Output below (ive replaced some alphabets by *)

- address: celestia176vjgncu9k0zy3gyu8h7dq2y53r35ngm4gk6af
  name: foo
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A/Ve2miJfl24cWu8irf**********vj03q9izBqFgMbD"}'
  type: local

Thus, the address recovered from command line using the mnemonic is the same as the address when mnemonic is entered in keplr wallet (and different from mamaki public address for the mnemonic)

**Comment by rootulp** [comment]
I tried to repro the behavior you observed by creating a new light node and then importing the mnemonic via celestia-appd but I'm observing that the addresses match. So I'm not sure how to proceed here.

Created mnemonic via light node. Note: I replaced most of the mnemonic with "..." in the output below:
```shell
root@rootulp-mocha:~/celestia-node# celestia light init
2024-02-07T17:49:16.240Z	INFO	node	nodebuilder/init.go:31	Initializing Light Node Store over '/root/.celestia-light'
2024-02-07T17:49:16.241Z	INFO	node	nodebuilder/init.go:63	Saved config	{"path": "/root/.celestia-light/config.toml"}
2024-02-07T17:49:16.241Z	INFO	node	nodebuilder/init.go:65	Accessing keyring...
2024-02-07T17:49:16.248Z	WARN	node	nodebuilder/init.go:194	Detected plaintext keyring backend. For elevated security properties, consider using the `file` keyring backend.
2024-02-07T17:49:16.249Z	INFO	node	nodebuilder/init.go:209	NO KEY FOUND IN STORE, GENERATING NEW KEY...	{"path": "/root/.celestia-light/keys"}
2024-02-07T17:49:16.266Z	INFO	node	nodebuilder/init.go:214	NEW KEY GENERATED...

NAME: my_celes_key
ADDRESS: celestia1rv9380daavjp28cu3c34ltwlkkakq9wm0tws2p
MNEMONIC (save this somewhere safe!!!):
fitness snow ...

2024-02-07T17:49:16.266Z	INFO	node	nodebuilder/init.go:72	Node Store initialized
```

Then imported via celestia-appd:

```shell
root@rootulp-mocha:~/celestia-node# celestia-appd keys add import --recover
> Enter your bip39 mnemonic
fitness snow ...

- address: celestia1rv9380daavjp28cu3c34ltwlkkakq9wm0tws2p
  name: import
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AwQJYU3FCjRGInA9QtaT22s7df4w1BasFRtbjtw1Qg0b"}'
  type: local
```

**Comment by rajeshb62** [comment]
i will try to reproduce at my end with an new address and revert with results

**Comment by rajeshb62** [comment]
**update**: I found the linus vm i had created to run mamaki nodes. Within that I found the .celestia-light/keys folder.

all the node folders and files seem to be intact in the vm.

what should I do next? how do I retrieve the private key?

**Comment by dzhelezov** [comment]
Hey possibly not a related issue -- but is there a tool to convert an EVM public address to the Celestia address the same way it was done for the genesis airdrop? How exactly did that work?

**Comment by rootulp** [comment]
@dzhelezov mind creating a new GH issue for your question or asking in Discord? It doesn't seem related to this issue.

> how do I retrieve the private key?

@rajeshb62 there are a few options depending on which binary and version you're using. You could use `celestia-appd` (celestia-app binary), `celestia` (celestia-node binary), or `cel-key` (celestia-node key binary). Given you ran a light node, I'm assuming you already have `celestia` or `cel-key` installed. If not refer to the [docs](https://docs.celestia.org/nodes/light-node#install-celestia-node) to install the binary. Then try the commands in https://github.com/celestiaorg/celestia-app/issues/3073#issuecomment-1924722450

**Comment by dzhelezov** [comment]
Thanks, opened -- https://github.com/celestiaorg/celestia-app/issues/3103

**Comment by rajeshb62** [comment]
> @dzhelezov mind creating a new GH issue for your question or asking in Discord? It doesn't seem related to this issue.
> 
> > how do I retrieve the private key?
> 
> @rajeshb62 there are a few options depending on which binary and version you're using. You could use `celestia-appd` (celestia-app binary), `celestia` (celestia-node binary), or `cel-key` (celestia-node key binary). Given you ran a light node, I'm assuming you already have `celestia` or `cel-key` installed. If not refer to the [docs](https://docs.celestia.org/nodes/light-node#install-celestia-node) to install the binary. Then try the commands in [#3073 (comment)](https://github.com/celestiaorg/celestia-app/issues/3073#issuecomment-1924722450)

I was able to find the private key and retrieve my funds. I really appreciate the help and follow up (I had to play around with the ./cel-key command using --help and then succeeded- using the advice in this thread). 

Thank you

**Comment by rootulp** [comment]
Glad you were able to retrieve your funds!
