### ISSUE TITLE
Make GlobalMinGasPrice constant gov modifiable

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3092]
**Description**

Currently GlobalMinGasPrice is a hard-coded constant but should be gov modifiable.

**Comment by rootulp** [comment]
Note, if we make it gov modifiable we should also add it to the specs page: [Mainnet Parameters](https://celestiaorg.github.io/celestia-app/specs/params.html) and [cip-13](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-13.md)
