### ISSUE TITLE
A tool to canonically generate a celestia address from an EVM one

### ISSUE THREAD

**Issue by dzhelezov** [celestiaorg/celestia-app#3103]
### Summary

The genesis airdrop used existing EVM addresses to derive a celestia address for an airdrop. However, there's no tool or documentation for the canonical derivation 

### Problem Definition

There is no documentation on how a celestia address can be derived from an EVM one. Such a tool would be useful for better Celestia <-> EVM interop and facilitate the account for the genesis allocation.

### Proposal

A CLI tool would take an EVM address and spit out the corresponding celestia address the same way it was done for the genesis airdrop event

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Users needed to generate a Celestia address for the Celestia airdrop (usually via Keplr or Leap).
