### ISSUE TITLE
Version compatibility testing

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#313]
When we begin to ship different versions of the app, each version not only has to be completely compatable with all mainnet blocks up to that point, but it also has to be able to coexist with the latest release for an indefinite amount of time. This means that we have to run more than one binary on the same network while we "fuzz" that network. 

very related to #1535 and #2061 
adjacent to #2414

**Comment by adlerjohn** [comment]
And patch, ofc

**Comment by liamsi** [comment]
It is a bit unclear to me how this would look like. I think ideally simulate a network with the versions we expect to be compatible (one half runs the old, and another half the new but expected to be compatible version).
