### ISSUE TITLE
Make the encoding require the app version

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3134]
The encoding could differ between app versions. This could result in non-determinism. The safest thing to do imo would be to require the app version when creating an encoding config, and we create a new encoding config each height. This way we ensure that there encoding is done deterministically across heights and nodes. There might be other mechanisms for forcing this.

**Comment by cmwaters** [comment]
Another option is to have the encoding config simply support all versions

**Comment by evan-forbes** [comment]
> Another option is to have the encoding config simply support all versions

does the user need to specify which version of the encoding is needed at a given point?

**Comment by cmwaters** [comment]
I guess what we are trying to prevent is someone submitting a transaction that is not yet or no longer supported right?

Or is there any other use cases you had in mind?

**Comment by evan-forbes** [comment]
the main thing is trying to avoid non-determinism when upgrading since being able to decode or not decode a tx could result in that if we didn't get everything perfect. I was worried about differences in the antehandlers during process and even finalize block. Like, if someone submits a new tx type, will that get passed to ante handlers on nodes that have been upgraded where nodes that have not it would not get passed since it couldn't be decoded.

by requiring the app version, we ensure that this doesn't occur. We could also ensure that all old tx types are treated as unsupported, instead of quasi-supported

**Comment by cmwaters** [comment]
For the antehandler, I was planning on trying to decode it and if it was successful then checking that the msg type was supported by the current version

**Comment by evan-forbes** [comment]
I could see that working as well, can we document that somewhere if its not already? this is marked as `needs-discussion` with the intention to disucss this during the next v2 sync so we can discuss further there. 

while requiring the app version is annoying, imo I think its annoying in a good way similar to a strict type system. Especially if it avoids a bug that requires manually digging through protobuf bytes

**Comment by evan-forbes** [comment]
we don't need this because of #3162
