### ISSUE TITLE
ibctesting framework does not support multiple versions

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#3137]
### Summary

Discovered in https://github.com/celestiaorg/celestia-app/pull/3112, `github.com/cosmos/ibc-go/v6/testing` doesn't support versions as it does not pass the version field to `BeginBlock`. The `0` app version causes the application to panic.

### Proposal

Amend "github.com/cosmos/ibc-go/v6/testing" to pass the app version initiated in the `InitialHeader` through to the `CurrentHeader`

**Comment by rootulp** [comment]
Pretty sure this is closed by https://github.com/cosmos/ibc-go/pull/6179 which was included in https://github.com/cosmos/ibc-go/releases/tag/v6.3.1 which we upgraded to in https://github.com/celestiaorg/celestia-app/pull/3379
