### ISSUE TITLE
Handle the case where a module is no longer supported

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3139]
> // TODO: handle the case where a module is no longer supported (i.e. removed from the state machine)

Moving this todo to an issue

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/3112#discussion_r1507652084_

**Comment by ninabarbakadze** [comment]
added back need-discussion so we can align on whether we're disabling any state machine modules in v2

**Comment by rootulp** [comment]
There has been discussion on disabling `x/blobstream` in v2 but we haven't reached social consensus on it. I wonder if @rach-id has any feedback on whether it's needed in v2 or can be disabled.

**Comment by rootulp** [comment]
We may need a migration script for this that deletes the `x/blobstream` state. We also need a modification to app/module/module.go to run the migration scrip in `RunMigrations` when a module is deleted.

**Comment by cmwaters** [comment]
I think this can be closed now. Or at least can be tied with https://github.com/celestiaorg/celestia-app/issues/3305
