### ISSUE TITLE
The QGB orchestrator should be able to query the genesis params

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#318]
Currently, the QGB is unable to query for the genesis params to get the data commitment window. This is necessary to know when to sign the data commitments and for which interval. This is needed to have a working QGB MVP.

**Comment by evan-forbes** [comment]
is this still an issue? is there a general way to query for params using the paramstore w/ the cosmos-sdk https://github.com/celestiaorg/cosmos-sdk/blob/release/v0.46.x-celestia/proto/cosmos/params/v1beta1/query.proto ?

**Comment by SweeXordious** [comment]
This is already implemented here: 
https://github.com/celestiaorg/celestia-app/blob/6b86e91eea1063c27c1ae461eddbe505f778df08/x/qgb/keeper/keeper_valset.go#L56-L64
via linking this to a query:
https://github.com/celestiaorg/celestia-app/blob/6b86e91eea1063c27c1ae461eddbe505f778df08/x/qgb/keeper/query_general.go#L11-L18
So,  this can be closed
