### ISSUE TITLE
Update specs to include new modules 

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3192]
## Description

Update `state_machine_modules.md` to include new modules.

**Comment by rootulp** [comment]
Which modules? minfee and upgrade are already listed:

https://github.com/celestiaorg/celestia-app/blob/f23cf46d976e59e4728da1575dc2f5c194ace254/specs/src/specs/state_machine_modules.md?plain=1#L9

https://github.com/celestiaorg/celestia-app/blob/f23cf46d976e59e4728da1575dc2f5c194ace254/specs/src/specs/state_machine_modules.md?plain=1#L12

**Comment by rootulp** [comment]
bump @ninabarbakadze

**Comment by ninabarbakadze** [comment]
I forgot to reference this issue in my follow-up pr! thanks for pointing it out @rootulp
