### ISSUE TITLE
add more linter checks

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#323]
while skimming through the code, I've noticed quite a few typos. We should add a spell-checker to the linter in CI so these get automatically detected (and fix those).

While at it, we should probably re-evaluate which other linters we want enabled in this repository.

**Comment by evan-forbes** [comment]
as stated by @adlerjohn and @SweeXordious, we should see if we can add a linter to check for bugs like that found in #486

**Comment by SweeXordious** [comment]
For some reason, GoLand is no longer pointing the loop variable dereferencing. However,  I found the following:
- https://github.com/kyoh86/exportloopref
- https://github.com/kyoh86/looppointer
And, static check will also include this check in upcoming months: https://github.com/dominikh/go-tools/milestone/13

**Comment by rootulp** [comment]
> We should add a spell-checker to the linter in CI so these get automatically detected (and fix those)

For typos in Go files, we can use https://golangci-lint.run/usage/linters/#misspell

**Comment by rootulp** [comment]
https://github.com/kyoh86/looppointer doesn't appear on https://golangci-lint.run/usage/linters/ but the docs say
> If you want to ignore false-positives (with some lints ignored), you should use [exportloopref](https://github.com/kyoh86/exportloopref).

So will opt to enable exportloopref instead
