### ISSUE TITLE
testground's app version is not supported by the versioned module manager

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3242]
## Problem
To facilitate unbounded block size experiments in e2e tests using knuu, we require to use the testground app version that extends the permissible square size to `512`, thereby accommodating block sizes of up to ~126MB. However, the current module manager fails to properly render this app version, resulting in a validator panic when such a version is provided. Specifically, when running `SimpleE2ETest` with the testground's app version, the validator panics at the outset with the following message (thrown at this [line](https://github.com/celestiaorg/celestia-app/blob/91603c49c4fc823a1b83d5ea3d6d6abf0d2e115c/app/module/module.go#L159)):
```
panic: version 420420420 not supported
```
Where `420420420` is the[ testground app version](https://github.com/celestiaorg/celestia-app/blob/ce1c6cd93278031bb56ed9910e5c706aa2c3c6cc/pkg/appconsts/testground/app_consts.go#L7)

## More context
The maximum block size is limited by the following factors:
- The versioned constant `SquareSizeUpperBound`
- The parameter `GovMaxSquareSize` in the blob's module
- The `max_bytes` setting in the consensus block parameters

Although the last two parameters can be modified at the time of genesis creation, the first is dependent on the application version. Currently, versions v1 and v2 support a maximum square size of 128, which limits the block size to 8 MB. However, our goal is to increase the block size to 100 MB.

We have previously introduced a testground application version that raises the `SquareSizeUpperBound` to 512, allowing for block sizes greater than 100 MB. Nonetheless, with the implementation of the versioned module manager, it is now necessary to ensure that the testground application version is also relevant to this module manager. Specifically, there should be a mechanism in versioned module manager to use the latest app version available in the code when the testground app version is seen (that is a potential solution). This capability is currently lacking.

**Comment by cmwaters** [comment]
In the constructor of the application, each module states the versions it supports and thus the application determines all the versions that it can run over. Given that v2 is just v1 and v2, v420420420 is not supported and thus it panics when genesis provides it an app version that it does not support

**Comment by cmwaters** [comment]
If we want to have an unbounded test, we could use a different docker image that we build specifically for our tests. This would allow us to make other alterations that aren't available in our official docker image. I believe this was the approach that testground used to take

**Comment by staheri14** [comment]
>If we want to have an unbounded test, we could use a different docker image that we build specifically for our tests. This would allow us to make other alterations that aren't available in our official docker image. I believe this was the approach that testground used to take

So, this means we need to maintain a separate long-lived branch mirroring the main branch with additional modifications for testing purposes only? At this point, I cannot see a lot of such test-related modifications that would motivate having a separate branch except for amending the square size limit. Nevertheless, I am not opposing it, just brain storming.

**Comment by cmwaters** [comment]
It's a bit difficult to inject code for test purposes in the production binary yet prevent it from users from using it. If we want greater flexibility (for testing sake), perhaps some of these variables shouldn't be hardcoded

**Comment by staheri14** [comment]
To outline the next steps required to implement this change, following actions seem necessary for a long-term sustainable solution (please let me know your thoughts):
- Create a separate branch dedicated to testing.
- Setting up a bot for backporting changes from the main branch to this testing branch.
- Ensure that an image is generated for every commit in this testing branch and is pushed to  https://github.com/celestiaorg/celestia-app/pkgs/container/celestia-app.

As for my current effort to test unbounded block size, I can push an image manually (which I will do), but it is better to aim for a more sustainable long-term solution.

**Comment by evan-forbes** [comment]
> I believe this was the approach that testground used to take

yeah, correct unfortunatley

we had to have this hack

https://github.com/celestiaorg/celestia-app/blob/bce5d07d4c71731be3f6a45cce54762c9a28f0db/app/module/module.go#L144-L145

other than that tho, testground is just using the testground specific app version in the genesis 

https://github.com/celestiaorg/celestia-app/blob/90a5d2d8281cd3c9727a9d17e6c8ebe1de3b9002/test/testground/network/consensus_node.go#L198-L204

https://github.com/celestiaorg/celestia-app/blob/90a5d2d8281cd3c9727a9d17e6c8ebe1de3b9002/test/testground/network/leader.go#L211-L218

https://github.com/celestiaorg/celestia-app/blob/90a5d2d8281cd3c9727a9d17e6c8ebe1de3b9002/test/testground/network/params.go#L184-L189

I can see why that's hacky, but imo its also not the _worst_ idea in the world since the we're using the app version for consensus critical params

**Comment by cmwaters** [comment]
> Create a separate branch dedicated to testing.

We don't necessarily have to have a separate branch. It could be possible to have two binaries within the same codebase (and two docker images for each binary)

**Comment by staheri14** [comment]
The resolution for the current issue is captured in https://github.com/celestiaorg/celestia-app/issues/3370. Therefore, we can close this one.
