### ISSUE TITLE
Tx consumes more gas in case of set GranterFee

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-app#3258]
I'm currently working on enabling GrantFee functionality in celestia-node for SubmitPFB transactions and I'm observing that the [gas estimation](https://github.com/celestiaorg/celestia-app/blob/ac9428872d803264f9c6ea595cbb2d6cc2d8c519/x/blob/types/payforblob.go#L171) is not working as I'm getting "out of gas" each time I set a tx granter.

**Comment by cmwaters** [comment]
Yeah, the model for estimating works on the assumption that there are no added options to the transaction i.e. it's just a vanialla PFB

**Comment by Bidon15** [comment]
> Yeah, the model for estimating works on the assumption that there are no added options to the transaction i.e. it's just a vanilla PFB

So does it mean this is node issue or app?

**Comment by cmwaters** [comment]
Its an app issue. The best short term solution is to use the `EstimateGas` on signer or `SimulateTx` via grpc which should provide an accurate gas estimate

**Comment by cmwaters** [comment]
Ref: https://github.com/celestiaorg/celestia-app/issues/3342
