### ISSUE TITLE
send raw transaction error

### ISSUE THREAD

**Issue by zhp1254** [celestiaorg/celestia-app#3296]
api ： https://api.lunaroasis.net/
url: /cosmos/tx/v1beta1/txs
method: POST

http body :{"tx_bytes":"CpoBCo8BChwvY29zbW9zLmJhbmsudjFiZXRhMS5Nc2dTZW5kEm8KLWNvc21vczFkcjk3NXR3M3d1N2xsdHltaGNrNG1odmY3dDM5cWp1ZDd4MG1kZxItY29zbW9zMXJkbTUzNW4yYXBycTA3NWF3aDR2a2Q2eGswenRkbW5hOGp3YXVzGg8KBXVhdG9tEgYxMDAwMDASBjEyMzQ1NhJmClAKRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiEDG7aJ3yCyCam9C8pknlWIHX4zqfLoV3rbF4SWknzd8O0SBAoCCAEYaRISCgwKBXVhdG9tEgM0MDAQgPEEGkBF8knmROE6Hu055jSa3pH4RG+UxhxQYF72xVdll2kPwnmp0S+pjNcBpVWYPyYQFD0mOnx9Em0n49eTSMkNRU8m","mode":"2"}

http response:
{
  "code": 3,
  "message": "must declare at least one event to search",
  "details": [
  ]
}

**Comment by cmwaters** [comment]
I get:

```{
    "code": 3,
    "message": "unknown value \"2\" for enum cosmos.tx.v1beta1.BroadcastMode",
    "details": []
}
```
when trying this request. I've never seen: "must declare at least one event to search" before. Do you get the same error on a different endpoint

**Comment by rootulp** [comment]
Closing due to lack of response. Please re-open if this is still an issue.
