### ISSUE TITLE
docs: adopt spec structure in x/payment and x/qgb

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#330]
## Summary

The readme in https://github.com/celestiaorg/celestia-app/blob/91e35a90c00d49b7fc302f356220d8d830b8fa3b/x/payment/spec/docs.md is a great start. IMO, we should structure this the same way as all sdk modules. This will help auditors and SDK devs understand the modules we are writing.

Also, we must ensure that these docs are and stay up to date (especially as we might add some params like max ODS size etc).

Example: https://github.com/cosmos/cosmos-sdk/tree/e7066c4271ff3d33dc426dc6313c82a1201ae3c6/x/distribution/spec#contents

**Comment by rootulp** [comment]
It looks like Cosmos SDK modules have migrated away from this `spec/*` directory structure in favor of a `README.md` at the root of the module directory (e.g. [distribution/README.md](https://github.com/cosmos/cosmos-sdk/blob/5a94358a8e5fc6bfe09fbca7bdbfee0e7395175f/x/distribution/README.md)). Related https://github.com/cosmos/cosmos-sdk/issues/13758 . To conform with the new style:

`x/payment`
 - [ ] move https://github.com/celestiaorg/celestia-app/blob/6f3b3ae437b2a70d72ff6be2741abb8b5378caa0/x/payment/spec/docs.md to `x/payment/README.md`
 - [ ] update docs (started in https://github.com/celestiaorg/celestia-app/pull/948)

`x/qgb`
- [ ] write new docs in `x/qgb/README.md`

**Comment by rootulp** [comment]
See https://github.com/cosmos/cosmos-sdk/blob/main/docs/spec/SPEC-SPEC.md#common-layout for an updated guide
