### ISSUE TITLE
restructure modules to be canononical and for readability

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#331]
Currently, we use the file and folder structure from startport. What we should be doing is rather using the recommended folder structure here: https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md#recommended-folder-structure

Where it helps readability we should deviate from that. I think Osmosis did a great job structuring their modules: https://github.com/osmosis-labs/osmosis/tree/main/x

A good opportunity to tackle this, would be when we upgrade to tendermint 0.35 and 0.46 of the SDK (related to https://github.com/celestiaorg/celestia-core/issues/630#issuecomment-1090035895).

**Comment by evan-forbes** [comment]
leaving a comment to remind us to also fix https://github.com/celestiaorg/celestia-app/pull/472#discussion_r938398480 when we address this issue

**Comment by rootulp** [comment]
Closing this because we have stand-alone modules in the `x/` directory
