### ISSUE TITLE
Integrating data tracing in e2e tests 

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3318]
## Problem

The inclusion of tracing data is essential for the testground sanity test, primarily for precise bandwidth utilization comparisons. Currently, our e2e tests do not incorporate this feature.

## Acceptance Criteria
This issue aims to implement the required modifications to the e2e tests, enabling them to trace and either download data from the Knuu instances or upload it to an external server.

**Comment by evan-forbes** [comment]
to update this, we are just waiting to merge some existing work that integrates the tracing data. PR incoming
