### ISSUE TITLE
Consensus failure on reboot on `main`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3336]
using current `main`, if we reboot, we currently panic

perhaps we're not peristing some state or value for the context? In theory, I don't think the recent change to `MaxEffectiveSquareSize` should have changed anything, but perhaps we missed something? This doesn't occur on 97f09de75098e4bb5176b845b97628f73058745d , the commit directly before that change.

To recreate, we can run the single node script, shut down after producing a block or two, then reboot.

> 5:59PM ERR CONSENSUS FAILURE!!! err="runtime error: invalid memory address or nil pointer dereference" module=consensus stack="goroutine 152 [running]:\nruntime/debug.Stack()\n\t/home/evan/.go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:746 +0x46\npanic({0x223d680?, 0x4592610?})\n\t/home/evan/.go/src/runtime/panic.go:770 +0x132\ngithub.com/celestiaorg/celestia-app/v2/app/squaresize.MaxEffective({{0x322b7e8, 0x4705560}, {0x323fc60, 0xc000b94fc0}, {{0x0, 0x0}, {0xc001742eb0, 0x7}, 0x3, {0x12deb704, ...}, ...}, ...}, ...)\n\t/home/evan/go/src/github.com/celestiaorg/celestia-app/app/squaresize/max_effective.go:21 +0x177\ngithub.com/celestiaorg/celestia-app/v2/app.(*App).PrepareProposal(0xc000579508, {0xc000b94a00, 0x1e1cb6, {0xc001742eb0, 0x7}, 0x3, {0x12deb704, 0xeddb0f9b5, 0x0}})\n\t/home/evan/go/src/github.com/celestiaorg/celestia-app/app/prepare_proposal.go:52 +0x4ac\ngithub.com/tendermint/tendermint/abci/client.(*localClient).PrepareProposalSync(0xc000183740, {0xc000b94a00, 0x1e1cb6, {0xc001742eb0, 0x7}, 0x3, {0x12deb704, 0xeddb0f9b5, 0x0}})\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/abci/client/local_client.go:359 +0x158\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).PrepareProposalSync(0xc000a6f980?, {0xc000b94a00, 0x1e1cb6, {0xc001742eb0, 0x7}, 0x3, {0x12deb704, 0xeddb0f9b5, 0x0}})\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/proxy/app_conn.go:102 +0x66\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).CreateProposalBlock(_, _, {{{0xb, 0x2}, {0xc001742e89, 0x7}}, {0xc001742eb0, 0x7}, 0x1, 0x2, ...}, ...)\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/state/execution.go:125 +0x2f3\ngithub.com/tendermint/tendermint/consensus.(*State).createProposalBlock(0xc000005888)\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:1246 +0x27b\ngithub.com/tendermint/tendermint/consensus.(*State).defaultDecideProposal(0xc000005888, 0x3, 0x0)\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:1161 +0x53\ngithub.com/tendermint/tendermint/consensus.(*State).enterPropose(0xc000005888, 0x3, 0x0)\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:1141 +0x83e\ngithub.com/tendermint/tendermint/consensus.(*State).enterNewRound(0xc000005888, 0x3, 0x0)\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:1060 +0xb58\ngithub.com/tendermint/tendermint/consensus.(*State).handleTimeout(0xc000005888, {0x6139646230303063?, 0x6722202c7d293034?, 0x2d637072?, 0x6f?}, {0x3, 0x0, 0x1, {0x3bea2d6, 0xeddb0f9cc, ...}, ...})\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:929 +0x8c7\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000005888, 0x0)\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:811 +0x6a5\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart in goroutine 68\n\t/home/evan/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:391 +0x13b\n"

**Comment by rootulp** [comment]
Thanks for the issue and all the info. I just repro'ed so will revert my refactor.

**Comment by evan-forbes** [comment]
I think the refactor is good, so ideally we'd be able to have both

**Comment by MSevey** [comment]
Running a node, stopping, and restarting sounds like a very simple test that should be in the test suite. 
Should definitely add that if it doesn't exists, and if it does, we should figure out why it didn't fail.

**Comment by rootulp** [comment]
See https://github.com/celestiaorg/celestia-app/issues/3337
