### ISSUE TITLE
Add a test to restart the app

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3337]
## Description 

In the past, we've ran into at least two bugs that resulted in a panic after restarting (one being #3336).

## Acceptance criteria

- [ ] Unit test that starts stops and restarts a node. If a unit test format is not possible e2e test will also do

**Comment by cmwaters** [comment]
Good shout. it's hard to do a full reboot as a unit test. I think this would be better suited as a knuu test.

In cometbft's test they include perturbations which involve killing and restarting the docker instance

**Comment by evan-forbes** [comment]
we might be able to with testnode if we manually call these and shutdown, then restart https://github.com/celestiaorg/celestia-app/blob/9db2f8b8bffe3dd1dd4eaf7d9b1d38afb71a193a/test/util/testnode/network.go#L36-L43

that might not work tho, in which case I agree, knuu is the way to go

**Comment by cmwaters** [comment]
FYI, I think the upgrade tests already kill the node and restart it
