### ISSUE TITLE
Make the e2e tests runnable on minikube

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3340]
For external contributor, and for debugging (especially on planes), it would be great to integrate and document how to run the e2e tests using minikube.

**Comment by rootulp** [comment]
How does this relate to https://github.com/celestiaorg/celestia-app/issues/3255 ? It look like the e2e test binary still uses knuu so maybe this issue can be a follow-up after that issue is addressed?

**Comment by cmwaters** [comment]
Yeah it's still the same. I think you'd have to create a `~/.kube/config` that created local pods (forgive me if I am using the wrong terminology here)

**Comment by evan-forbes** [comment]
nice! I didn't see that. Just wrote this quickly this morning for @rach-id 

we can close in favor of that one.

**Comment by rootulp** [comment]
This issue is still open because https://github.com/celestiaorg/celestia-app/issues/3255 doesn't actually close this. I was trying to say that this issue should be tackled _after_ https://github.com/celestiaorg/celestia-app/issues/3255 is addressed.

**Comment by rach-id** [comment]
I guess this PR https://github.com/celestiaorg/celestia-app/pull/3350 adds instructions for that. But for the monitoring, it's gonna require more time since a lot of values are hardcoded. This means that we will need to update knuu to expose more parameters, and only then be able to get have local monitoring

**Comment by rach-id** [comment]
That depends, if we want to have e2e tests that only spin up < 10 validators (I assume anyone's computer can run 10 validators without issues if there isn't a big volume of transactions), then we can have those locally as it would make dev easier and also would open the gate for exterior contributors to just run them locally. I would personally just run a 10 validators test locally.
If we want to the tests to be only +20 validators. Then, not worth it.
