### ISSUE TITLE
pkg/user: Signer automatically estimates gas

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-app#3342]
https://github.com/celestiaorg/celestia-node/pull/3298#discussion_r1568997897

**Comment by cmwaters** [comment]
For simple PFBs we should use the modelled formula for estimating gas. For any other transaction we should use the `EstimateGas` function.

We should have a gas multiplier field which we multiply by when using `EstimateGas` (as it occasionally underestimates). This should be adjustable with a default of 1.1
