### ISSUE TITLE
Bump Knuu version to v0.13.2

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/celestia-app#3349]
### Summary

hello team!

we have released the knuu version [v0.13.2](https://github.com/celestiaorg/knuu/releases/tag/v0.13.2), feel free to bump it to this one, it should speed up the process + add the `scope` labels to simplify the way to find the metrics in Grafana, instead of using the namespace, we switch to `scope`.

one recommendation, if you are using the `AddFile` or `AddFolder` to mount files to the instances, I would recommend you to do it *after* the *Commit*, this will reuse previous images (using cached ones).

you can check the examples: [AddFile](https://github.com/celestiaorg/knuu-example/blob/main/basic/file_test_image_cached_test.go#L56-L59) or this one [AddFolder](https://github.com/celestiaorg/knuu-example/blob/main/basic/folder_test_image_cached_test.go#L57-L60), you'll find the [Commit](https://github.com/celestiaorg/knuu-example/blob/main/basic/folder_test_image_cached_test.go#L42-L45) before.

any feedback or reported issue is welcome!

Best! 🚀 

cc: @staheri14 @cmwaters @evan-forbes 

### Problem Definition

bump versions

### Proposal

bump version to: [v0.13.2](https://github.com/celestiaorg/knuu/releases/tag/v0.13.2)

**Comment by rootulp** [comment]
No instances of `AddFile`. Two instances of `AddFolder` which I'll rearrange to execute _after_ `Commit`. I'll do that in a separate PR.
