### ISSUE TITLE
Implementing chainID dependency for versioned constants 

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3370]
As part of the knuu e2etests, we need to conduct tests under different values of the current versioned constant, specifically larger square sizes. Currently, the retrieval of these values depends on the app version. We previously attempted to introduce a new app version, namely the "testground" version. However, this required changes to the versioned module manager as well, to accommodate this new custom version and ensure correct behavior. This would result in introducing custom behaviors into the production code, which could increase the risk of errors for regular users.

To avoid such confusion and inadvertent mistakes, it has been decided to make versioned constants dependent on an additional parameter, i.e., chainID. Thus, while the app version remains unchanged, we can assign various values to the same constant based on the chainID.

**Comment by evan-forbes** [comment]
since this is consensus breaking, we don't want to stick this in v2 or even v3 until we have fully considered everything that is needed to safely add this

**Comment by evan-forbes** [comment]
this is blocking the merging of the network tests in knuu

**Comment by evan-forbes** [comment]
this is technically consensus breaking, so we're blocking until we cut the v2 branch.

**Comment by evan-forbes** [comment]
we're using build tags in favor of this
