### ISSUE TITLE
Dedicated feature branch for e2e benchmark tests with main branch sync

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3371]
In the Knuu e2e benchmark tests, we sometimes encounter the need to use versions of celestia-core that include unreleased breaking changes or features not fully integrated into celestia-app. This situation becomes a barrier to developing and merging benchmark tests into the celestia-app main branch. To address this issue, a decision has been made to establish a feature branch specifically for benchmark tests. Future PRs will be directed to this branch, facilitating seamless integrations without affecting the main branch of celestia-app.

Additionally, it would be useful to have an automated way to backport features from the main branch to this new feature branch, ensuring it remains up-to-date with the latest developments in the main.

**Comment by evan-forbes** [comment]
the goal is to merge this feature branch after v2

**Comment by evan-forbes** [comment]
we can unblock with https://github.com/celestiaorg/celestia-app/issues/3370

**Comment by staheri14** [comment]
> we can unblock with #3370

And https://github.com/celestiaorg/celestia-core/issues/1363
