### ISSUE TITLE
`ERROR E2ESimple: expected at least 10 transactions, got 1`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3383]
## Context

I'm trying to run the end-to-end tests

## Problem

```
make test-e2e

test-e2e2024/04/24 15:42:27 Starting testnets
test-e2e2024/04/24 15:45:31 Running txsim
test-e2e2024/04/24 15:46:01 Reading blockchain
test-e2e2024/04/24 15:46:51 --- ERROR E2ESimple: expected at least 10 transactions, got 1
exit status 1
make: *** [test-e2e] Error 1
```

**Comment by ninabarbakadze** [comment]
I've never gotten this flake. I think for some reason (probably network issues) you were getting these flakes that should not happen. It's also very difficult to test that the fix worked because these flake is not frequent.

**Comment by rootulp** [comment]
Let's close for now. Will re-open if it repros.
