### ISSUE TITLE
Version gas schedule variables

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#3404]
All on-chain governance modifiable parameters associated with the gas scheduler (i.e. GasCostPayForBlobs) should become versioned parameters i.e. they can only change with a hard fork upgrade.

The reason is to help clients who are submitting transactions make it easier to estimate the gas (as it won't fluctuate from block to block and you won't need additional queries for these values - they can be hardcoded into your estimator)

Context: https://github.com/celestiaorg/celestia-app/issues/3011#issuecomment-2071835562_
            
Acceptance Criteria

- [x] Write a CIP 
- [ ] Implement the change

**Comment by rootulp** [comment]
> All on-chain governance modifiable parameters should become versioned parameters

Clarifying question: do you mean all params or just the params related to the gas scheduler?

I'm a fan of moving governance modifiable params to versioned constants. IMO this likely warrants a CIP b/c it's moving scope for modifying these params from token governance to the CIP process. I think this will be a relatively small code change but it will take time to get through the CIP process so I think it's unlikely to get finalized prior to our scheduled feature freeze on May 15th for v2.

**Comment by cmwaters** [comment]
Just related to the gas scheduler. I thought I had specified it but I must have missed it. Thanks for catching it.

**Comment by rootulp** [comment]
The two params that are being considered:
- auth.TxSizeCostPerByte
- blob.GasPerBlobByte

**Comment by cmwaters** [comment]
Can we have this planned for v3? @evan-forbes

**Comment by cmwaters** [comment]
We would first need to write a CIP on this

**Comment by rootulp** [comment]
For posterity:
- CIP: https://github.com/celestiaorg/CIPs/blob/main/cips/cip-24.md
- Implementation: https://github.com/celestiaorg/celestia-app/pull/3735
