### ISSUE TITLE
Debugging ResourceExhausted Error in big block sanity test while submitting txs from txsim to celestia validator Instances in knuu

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3437]
We are running an e2e test using knuu that involves two validators and one txsim instance for each ([Link](https://github.com/celestiaorg/celestia-app/blob/c64897b42d0ebf87b0666d511356bd1d555d8723/test/e2e/benchmark/throughput.go#L206) to the test; [link](https://github.com/celestiaorg/celestia-app/pull/3415) to the PR). One txsim runs without issues, but the other consistently produces the following error:

```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (20016481 vs. 4194304) 

2024-05-03 17:42:20.161	
{"level":"info","height":5,"address":"celestia1phk8jqaylvy7znp2n8444jxxph3eaf4hpa42yy","msgs":"/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend,/cosmos.bank.v1beta1.MsgSend","time":"2024-05-04T00:42:20Z","message":"tx committed"}
2024-05-03 17:42:16.972	
{"level":"info","address":"celestia1phk8jqaylvy7znp2n8444jxxph3eaf4hpa42yy","balance":10000000000000000,"time":"2024-05-04T00:42:16Z","message":"set master account"}
```

Each txsim generates PFBs each with the total blob size of 1MB (1,000,000) (which are less than the indicated max 4194304 in the error messages).

**Comment by staheri14** [comment]
Multiple theories are being considered:

- There may be a need for configuration adjustments to the validators (identifying the specific configurations required).
- This issue could stem from limitations on the knuu side, such as resource sharing across instances (from DevOps response it looks like this is not the case and each instance runs in its own pod, hence no resource sharing happens) or the handling of network communication (this still needs to be verified as whether the resources may get shared during network communication between pods).

I'll conduct tests and share further results here to determine the minimal settings in which this error occurs:

1. Does it occur with any PFB size?
2. Does the number of sequences impact the error?
3. Can we direct two txsim instances to the same validator?

**Comment by staheri14** [comment]
I conducted the same tests under various txsim configurations, and the results are detailed below. My goal was to identify the point at which errors begin to manifest. For each configuration, two txsim knuu instances were created. Tests using the configs marked with a two green checkmark concluded without errors, while others experienced failures in the second txsim, as indicated by the provided error messages. 

- BlobsPerSeq = 1, BlobSequences = 1, BlobSizes = 100,000 ✅ ✅
- BlobsPerSeq = 1, BlobSequences = 1, BlobSizes = 200,000 ✅ ✅ 
- BlobsPerSeq = 6, BlobSequences = 1, BlobSizes = 200,000 ✅ ✅ 
- BlobsPerSeq = 6, BlobSequences = 5, BlobSizes = 200,000 ✅  🛑 
- BlobsPerSeq = 1, BlobSequences = 5, BlobSizes = 200,000 ✅ ✅ 
- BlobsPerSeq = 1, BlobSequences = 30, BlobSizes = 200,000 ✅ 🛑 
- BlobsPerSeq = 1, BlobSequences = 15, BlobSizes = 200,000 ✅ 🛑 
```bash
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (6013070 vs. 4194304)
```
- **BlobsPerSeq = 1, BlobSequences = 10, BlobSizes = 200,000**  ✅ ✅ 
- **BlobsPerSeq = 1, BlobSequences = 12, BlobSizes = 200,000**  ✅ 🛑 
```bash
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4809096 vs. 4194304)
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4809096 vs. 4194304)
```
- BlobsPerSeq = 1, BlobSequences = 12, BlobSizes = 100,000  ✅ ✅
- BlobsPerSeq = 1, BlobSequences = 30, BlobSizes = 100,000  ✅ 🛑 
 ```
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (6024558 vs. 4194304)
```
- BlobsPerSeq = 1, BlobSequences = 48, BlobSizes = 100,000 ✅  🛑 
```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9631632 vs. 4194304)
```
- BlobsPerSeq = 1, BlobSequences = 48, BlobSizes = 200,000 ✅  🛑 
```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (19231637 vs. 4194304)
```

No conclusive findings yet; I'm continuing to debug and checking the details of txsim internals. The only notable insight so far is that the initial txsim consistently succeeds. Furthermore, a comparison of the highlighted configurations reveals that merely increasing the sequence count by two causes the second txsim to begin failing.
> - **BlobsPerSeq = 1, BlobSequences = 10, BlobSizes = 200,000**  ✅ ✅ 
> - **BlobsPerSeq = 1, BlobSequences = 12, BlobSizes = 200,000**  ✅ 🛑

**Comment by staheri14** [comment]
Theory: Could the error be misleading, with the txsim failing due to resource limitations either on the validator side or the txsim side?

Test: Increasing resources on both the validator side and the txsim side does not resolve the issue. Here are the resources used:
```Go
	ValidatorResource: testnet.Resources{
		MemoryRequest: "12Gi",
		MemoryLimit:   "20Gi",
		CPU:           "10",
		Volume:        "20Gi",
	},
	TxClientsResource: testnet.Resources{
		MemoryRequest: "1Gi",
		MemoryLimit:   "4Gi",
		CPU:           "4",
		Volume:        "1Gi",
	}
```

**Comment by staheri14** [comment]
Theory: The second validator might be problematic. Therefore, directing both  txsims to the first validator could potentially resolve the issue.

Test and Results: However, pointing both txsims to the same validator did not eliminate the failure.

**Comment by staheri14** [comment]
Adding more context as I further my debugging: The line from which the error is emitted is [this line from the parser's recvMsg method](https://github.com/grpc/grpc-go/blob/5cce560107722844c00e1d3a0b23d4cc18087a75/rpc_util.go#L627) from grpc library.

**Comment by staheri14** [comment]
Theory: Are the messages/txs being batched on the txsim side?

It does not seem so, each sequence of txsim uses the [`BroadcastTx` rpc API](https://github.com/celestiaorg/celestia-app/blob/32e7015aba1fd808ae8b782f4e49c3dfb7e1702b/pkg/user/signer.go#L308), which is a unary API, and encapsulates encoded version of one single tx, hence no batching is expected.

**Comment by rach-id** [comment]
I did a few tests and was able to reproduce the issue locally:

1. Run `single-node.sh` script
2. Run `txsim --blob-sizes 20016469 --key-mnemonic "arch extra share tag great resource family owner shrug nominee crunch bulk cart twenty ripple bunker sugar carbon unable visual fold leave lyrics soda"  --grpc-endpoint localhost:9090  --blob 1`

This returns:
```
{"level":"info","address":"celestia1kkthrhfut4s7weqkzd0g3667r53nrjkc77lxk6","balance":899984999534100,"time":"2024-05-13T01:23:56+04:00","message":"set master account"}
{"level":"info","height":148,"address":"celestia1kkthrhfut4s7weqkzd0g3667r53nrjkc77lxk6","msgs":"/cosmos.bank.v1beta1.MsgSend","time":"2024-05-13T01:23:59+04:00","message":"tx committed"}
{"level":"info","address":"celestia1nuxenvm599vezdsrtxufmrr032xrcrrcyefgp3","balance":1000000000,"account number":10,"time":"2024-05-13T01:23:59+04:00","message":"initialized account"}
{"level":"error","error":"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (20016861 vs. 10485760)","address":"celestia1nuxenvm599vezdsrtxufmrr032xrcrrcyefgp3","blobs":"1","total size of blobs":20016469,"time":"2024-05-13T01:24:00+04:00","message":"tx failed"}
{"level":"error","error":"sequence 0: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (20016861 vs. 10485760)","time":"2024-05-13T01:24:00+04:00","message":"sequence failed"}
Error: sequence 0: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (20016861 vs. 10485760)
Usage:
  txsim [flags]

Examples:
txsim --key-path /path/to/keyring --grpc-endpoint localhost:9090 --seed 1234 --poll-time 1s --blob 5

Flags:
      --blob int               number of blob sequences to run
      --blob-amounts string    range of blobs per PFB specified as a single value or a min-max range (e.g., 10 or 5-10). A single value indicates the exact number of blobs to be created. (default "1")
      --blob-sizes string      range of blob sizes to send (default "100-1000")
      --feegrant               use the feegrant module to pay for fees
      --grpc-endpoint string   grpc endpoint to a running node
  -h, --help                   help for txsim
      --key-mnemonic string    space separated mnemonic for the keyring. The hdpath used is an empty string
      --key-path string        path to the keyring
      --master string          the account name of the master account. Leaving empty will result in using the account with the most funds.
      --poll-time duration     poll time for the transaction client (default 3s)
      --seed int               seed for the random number generator
      --send int               number of send sequences to run
      --send-amount int        amount to send from one account to another (default 1000)
      --send-iterations int    number of send iterations to run per sequence (default 1000)
      --stake int              number of stake sequences to run
      --stake-value int        amount of initial stake per sequence (default 1000)
      --suppressLogs           disable logging

sequence 0: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (20016861 vs. 10485760)%   
```

Then, I change the `max-recv-msg-size` in `app.toml` to `1048576000000`, restart the node (in your branch this doesn't work, so I just add this to the `single-node.sh`: `sed -i'.bak' 's#"10485760"#"1048576000000"#g' "${CELESTIA_APP_HOME}"/config/app.toml`,

Then I run again the `txsim` command, and it returns:

```
{"level":"info","address":"celestia1kkthrhfut4s7weqkzd0g3667r53nrjkc77lxk6","balance":899984999936500,"time":"2024-05-13T01:24:59+04:00","message":"set master account"}
{"level":"error","error":"tx was included but failed with code 11: out of gas in location: WritePerByte; gasWanted: 100000, gasUsed: 100375: out of gas","address":"celestia1kkthrhfut4s7weqkzd0g3667r53nrjkc77lxk6","msgs":"/cosmos.bank.v1beta1.MsgSend","time":"2024-05-13T01:25:02+04:00","message":"tx failed"}
Error: error funding accounts: tx was included but failed with code 11: out of gas in location: WritePerByte; gasWanted: 100000, gasUsed: 100375: out of gas
Usage:
  txsim [flags]

Examples:
txsim --key-path /path/to/keyring --grpc-endpoint localhost:9090 --seed 1234 --poll-time 1s --blob 5

Flags:
      --blob int               number of blob sequences to run
      --blob-amounts string    range of blobs per PFB specified as a single value or a min-max range (e.g., 10 or 5-10). A single value indicates the exact number of blobs to be created. (default "1")
      --blob-sizes string      range of blob sizes to send (default "100-1000")
      --feegrant               use the feegrant module to pay for fees
      --grpc-endpoint string   grpc endpoint to a running node
  -h, --help                   help for txsim
      --key-mnemonic string    space separated mnemonic for the keyring. The hdpath used is an empty string
      --key-path string        path to the keyring
      --master string          the account name of the master account. Leaving empty will result in using the account with the most funds.
      --poll-time duration     poll time for the transaction client (default 3s)
      --seed int               seed for the random number generator
      --send int               number of send sequences to run
      --send-amount int        amount to send from one account to another (default 1000)
      --send-iterations int    number of send iterations to run per sequence (default 1000)
      --stake int              number of stake sequences to run
      --stake-value int        amount of initial stake per sequence (default 1000)
      --suppressLogs           disable logging

error funding accounts: tx was included but failed with code 11: out of gas in location: WritePerByte; gasWanted: 100000, gasUsed: 100375: out of gas%  
```

Which is a gas issue, meaning that the transaction passed in the gRPC channel.

Given the original message in the first message in the issue: 
```
grpc: received message larger than max (20016481 vs. 4194304) 
```

It shows that the gRPC channel received 20mb of data vs 4mb that it's the default (not sure where this value is coming from, maybe some config in the test? I didn't dig into this one as I guess you have more info on this). The 20mb doesn't necessarily mean you sent a PFB of 20mb, but maybe it received 20 PFBs at the same time, each with 1mb.

I wanted to make the changes and test it on knuu, but it's too cumbersome and CI is taking too much time. Also, wanted to discuss this with you in case you already went this path so I don't waste time with CI.

Let me know what you think.

Note: I guess the process of waiting for the CI to build the image is unpractical and slow, we should improve on there.

**Comment by evan-forbes** [comment]
to update, we can close this issue when we merge https://github.com/celestiaorg/celestia-app/tree/experimentation
