### ISSUE TITLE
e2e tests are currently not working

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3453]
## Context

```
--> Running end to end tests
go run ./test/e2e 
test-e2e2024/0[5](https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567#step:5:6)/08 06:01:04 No particular test specified. Running all tests.
test-e2e2024/05/08 0[6](https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567#step:5:7):01:04 go run ./test/e2e <test_name> to run a specific test
test-e2e2024/05/08 06:01:04 Valid tests are: MinorVersionCompatibility, MajorUpgradeToV2, E2ESimple

test-e2e2024/05/0[8](https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567#step:5:9) 06:01:04 === RUN MinorVersionCompatibility
test-e2e2024/05/08 06:01:04 no versions to test
exit status 1
make: *** [Makefile:140: test-e2e] Error 1
```

https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567

```
test-e2e2024/05/15 16:35:44 Starting testnet
2024/05/15 16:37:50 Failed to start testnet: node val0 failed to start: forwarding port 26657: error forwarding port after 5 retries: timed out waiting for port forwarding to be ready
exit status 1
```
https://github.com/celestiaorg/celestia-app/actions/runs/9099118540/job/25011842760?pr=3487

```
2024/05/17 10:38:49 Failed to start testnet: node val0 failed to start: error waiting for instance 'val0-ee2a49ab' to be running: timeout while waiting for instance 'val0-ee2a49ab' to be running
exit status 1
```

https://github.com/celestiaorg/celestia-app/actions/runs/9126237806/job/25095937942?pr=3487

## Problem

e2e tests are failing locally and also in the nightly workflow. 

## Proposal

Fix it so it passes

[Optional follow-up] Instead of running it nightly, run it on every PR and make it an optional check. Currently, no one notices when the nightly fails because we have no hooks set up to alert us of failures.

**Comment by ninabarbakadze** [comment]
Fixed the issue where it wasn't able to fetch tags but now i get a [port forwarding error in MinorVersionCompatibilitiy](https://github.com/celestiaorg/celestia-app/actions/runs/9099118540/job/25011842760?pr=3487). 

The test is working locally but the error in ci could be happening because the gh pipeline workers are very limited. looking into this with devops @smuu

**Comment by evan-forbes** [comment]
> Instead of running it nightly, run it on every PR and make it an optional check. Currently, no one notices when the nightly fails because we have no hooks set up to alert us of failures.

imo, this does not have to be tied to fixing this test, and instead could be a separate issue. That separate could optionally be tied to enabling alerts in slack after something fails the tests when merging to main.

**Comment by ninabarbakadze** [comment]
not being able to fetch tags was the least of our worries. we're not able to start testnet at first because of port forwarding now different knuu issues are coming up. you can view the runs in ci on my pr. working on resolving this with @smuu
