### ISSUE TITLE
Update workflow for e2e tests to run after merge to main

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3489]
## Description

Currently our e2e tests are running nightly and it's not easy to identify the pr that breaks them. We want to change them to run after PRs are merged to main and set up slack notifications [in a follow-up issue](https://github.com/celestiaorg/celestia-app/issues/3506).

## Acceptance Criteria

- [ ] E2E tests are run after every merge to main.

**Comment by evan-forbes** [comment]
If its possible to run after each merge, then we should do that. If it's not, then we should run it nightly. We also need to ping folks on slack when the merge fails (todo @evan-forbes link the new issue here).
