### ISSUE TITLE
New issues should automatically go into No Status

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3508]
## Description

Currently GitHub automation adds all new issues directly to Todo. This gets in the way of us efficiently managing our board since new issues require grooming and triaging where issues in Todo should be ready to be picked up and worked on.

This can be achieved by just simply removing the status assignment.

## Acceptance Criteria

- [ ] Update the workflow to move new issues to No Status rather than Todo

**Comment by evan-forbes** [comment]
@MSevey when digging into this, it looks like we're only adding the `needs: triage` label, but the issue's `Status` is being marked as `Todo`. 

do you happen to know, if this behavior is a default to gitub status'? It's unclear to me how we can change the `Status` and not just add a label.

**Comment by MSevey** [comment]
@evan-forbes @ninabarbakadze you can adjust the default behavior of adding items to the project board with the project board workflows https://github.com/orgs/celestiaorg/projects/24/workflows

You and set whatever default value you want there. 

So then the flow is that the github action in this repo triggers to add things to the project board, and the project board workflow sets the default initial status. 
<img width="1357" alt="Screenshot 2024-06-13 at 11 29 43 AM" src="https://github.com/celestiaorg/celestia-app/assets/15232757/a7a7491f-037e-4c73-bdc0-84a61579c569">

**Comment by MSevey** [comment]
this thread has some more background on some custom actions if you want more control, but I think the above is what you were looking for. 

https://github.com/actions/add-to-project/issues/71

**Comment by evan-forbes** [comment]
closing as completed, thanks a ton @MSevey !!
