### ISSUE TITLE
Add exception to get go-vuln passing 

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3516]
## Description

There is rightfully a vuln in ibc v6.2, so the ci will fail. This vuln doesn't affect celestia-app since cosmwasm is not installed, therefore we can add an exception to avoid the red x in CI

## Acceptance Criteria
- [ ] go-vuln CI to passes after adding an exception to ibc v6.2.2

**Comment by rootulp** [comment]
Doesn't seem possible to ignore a particular vulerability per 
- https://github.com/golang/go/issues/59507
- https://github.com/golang/go/issues/61211
