### ISSUE TITLE
Draft a release guide

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3521]
## Context

Spun out from https://github.com/celestiaorg/celestia-app/issues/2810

## Problem

Currently there are manual tests that we want to perform before cutting future v1.x releases. These release blocking steps aren't documented or common understanding amongst the team.

## Proposal

Draft a release guide that includes a checklist for steps that must be performed before cutting future v1.x releases. Example:

```markdown
Before cutting a v1.x.x release, please perform the following:
- [ ] Create a release candidate
- [ ] Start a testnet with via auto-devops that uses the release candidate. Confirm it works.
- [ ] [Optional] Use the release candidate to sync from genesis
- [ ] Cut an official release and include in the release notes and "Upgrade Notice" section
```

**Comment by ninabarbakadze** [comment]
moving this to no status since the team has not prioritized it for the upcoming sprint. currently, the automation adds everything to todo but before we change it let's try and keep new issues in no status 🙏🏻
