### ISSUE TITLE
Print a version of the app with the `version` sub command

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#357]
We are not properly registering a version for the version subcommand, so the command simply prints an empty line. We should change this to print the actual version, and ideally have some sort of CI test that ensures that we are actually using the correct version.

**Comment by liamsi** [comment]
Weird, we even use a version variable without ever defining it: https://github.com/celestiaorg/celestia-app/blob/56c82ec19c74a9a1e59dc4628124ef48f59ff3d1/Makefile#L63

**Comment by mindstyle85** [comment]
if i remember correctly, in v0.2.0 you guys had that working already, just as fyi if it helps

**Comment by liamsi** [comment]
This is really weird. I'll create a quickfix shortly.

**Comment by liamsi** [comment]
https://github.com/celestiaorg/celestia-app/pull/360
