### ISSUE TITLE
Unit test prepare proposal

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3573]
## Context

Informal Systems audit v2 informational finding 5: Proposed block could exceed size limit

## Problem

https://github.com/celestiaorg/celestia-app/blob/main/app/prepare_proposal.go

## Proposal

Add a unit test to ensure that prepare proposal never returns a `ResponsePrepareProposal.BlockData.Txs` where the total size of Txs exceeds the value of `RequestPrepareProposal.BlockDataSize` because if it does then celestia-core will panic [here](https://github.com/rootulp/celestia-core/blob/7e97bb0f2b8747e4ad144589295c078268ce1a89/state/execution.go#L146-L153)

**Comment by cmwaters** [comment]
> Informal Systems audit v2 informational finding 5: Proposed block could exceed size limit

Can you explain how this could happen. I don't believe we ever add data only remove transactions

**Comment by rootulp** [comment]
Correct, the application only ever filters transactions out.

**Comment by rootulp** [comment]
Discussed with @cmwaters offline and we decided this informational audit finding should just be acknowledged and the unit test doesn't add much value.
