### ISSUE TITLE
Comprehensive Bandwidth Utilization Analysis Across Network Experiments (Knuu and Testground)

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3576]
# Problem

Previously, when aiming to debug network behavior w.r.t. bandwidth utilization in Testground, our focus was often narrowed to a single height of the experiment or even to a specific node or pair of nodes. However, for comparing the performance of two experiments (i.e., sanity check of testground using knuu), a broader view is essential. We need statistics that provide insights into the state of bandwidth utilization across the entire experiment, including all heights and nodes, rather than focusing on a single height or node.

# Proposed Solution

Recall that we aim to answer the question, "Is Testground the reason why Comet can’t utilize its bandwidth effectively?" One way to assess this, which is the approach pursued in this proposal, is by examining the best performance of P2P connections to determine if Testground performs as well as Knuu.

I have developed a method to summarize the bandwidth utilization of the entire network when nodes are at their highest performance. This method is focused on providing a comprehensive overview of the bandwidth utilization across the network by utilizing the data traced in [received bytes table](https://github.com/celestiaorg/celestia-core/blob/800924f1db5256e0d2905ae1001384ca76de9e15/pkg/trace/schema/p2p.go#L66-L82)[for additional context: received bytes capture the size of messages received by a node from all of its connections across all channel IDs]. The process involves:

1. **Identifying the Best Connection**: For each node in the experiment, I identify the best connection, which is defined as the peer whose top 10% traffic rate outperforms all other connections of that node.
   - Alternatively, we could focus on the block propagation time periods. Specifically, for each height, we would identify when a node starts receiving block parts from its connections and capture the received rate for that period only. This approach targets the busiest period of the consensus state machine. While feasible, it requires cross-referencing multiple traced tables, which could increase the likelihood of errors. Analyzing the top 10% (or another percentage) of received rates is likely just as effective for gaining insights into the maximum performance of P2P connections.

3. **Calculating Statistics**: For the identified best connection of each node, the following statistics are calculated for the top 10% of the times:
   - Average
   - Standard Deviation
   - Minimum
   - Maximum
   - Total number of samples in the determination of the top 10% traffic. Each sample represents 1 second.
4. **Summarizing for All Nodes**: The above calculations are performed for all nodes in the experiment.
5. **Extracting and Comparing Data**: A table is extracted to summarize and compare data from Knuu and Testground, considering the nodes' degree (number of connections). The statistics of nodes with similar degrees are compared between the two platforms. We expect to see similar performance, i.e., received traffic rate, across nodes with similar degrees in both backends.

# Action Items
- [ ] Discuss the effectiveness of this method in capturing the bandwidth utilization of the experiments from various aspects.
- [x] Implement the proposed method for summarizing bandwidth utilization.
- [x] Extract and format the summarized data into a table.  
- [ ] **(In Progress)** Compiling a doc comparing Knuu and Testground using this method.

**Comment by staheri14** [comment]
cc: @evan-forbes

**Comment by evan-forbes** [comment]
marking as completed due to us having enough comparisons along with having enough congest data to prove that tc is not suitable for introducing network latency and packet loss in a realistic way for network tests
