### ISSUE TITLE
Documenting best practices of knuu for test development 

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3601]
what's the best way to keep track of important details such as this @smuu? we could add a code comment above, but I imagine this would also be important to know when creating tests for node as well

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/3515#discussion_r1646241039_

**Comment by evan-forbes** [comment]
I think in this particular case, we should just require that we add appropriate documentation either before merging or write an issue that describes which documentation needs to be written.

so imo we can close this issue

**Comment by staheri14** [comment]
Closing this in favour of a new issue created in the knuu repository. https://github.com/celestiaorg/knuu/issues/474
