### ISSUE TITLE
Extend the wait time for genesis nodes to produce the first block in e2e tests

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-app#3610]
## Problem

In the e2e tests, we wait for a total of 1 second for the genesis nodes to progress to height 1, however, this amount is insufficient, given that block times are typically around 10 seconds and more. This causes the e2e benchmark tests fail to be initialized nondeterministically, specially for the big block tests, requiring to rerun the test multiple times. 

## Proposal
Proposal to change this wait time to 10 seconds.

**Comment by rootulp** [comment]
If this test is to mimic network conditions, why 10 seconds instead of ~12 seconds? Celestia block times are usually like ~11.8 seconds per https://www.mintscan.io/celestia/block/
