### ISSUE TITLE
AppHash mismatch test between main and v2 

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3624]
## Description

Currently we have an AppHash mismatch test on main and v1.x executing state machine messages on v1. We should have the same test for v2.

## Acceptance Criteria

- [ ] We have a consistent apphash test between v2 and main executing v2 state machine messages
- [ ] Refactor the existing test to table driven test

**Comment by rootulp** [comment]
For clarification: the [consistent app hash test](https://github.com/celestiaorg/celestia-app/blob/9475c4bcb9f9cb3f27c9be054201303526c11f2f/app/test/consistent_apphash_test.go#L38-L42) on `main` executes v1 state machine messages and compares against an app hash generated from executing the same messages on the `v1.x` branch.

Which git branch do you propose adding the test in this issue to (presumably `main`)? If `main` where you plan to source the app hash used to compare against (presumably `v2.0.0-rc2`)?

**Comment by rootulp** [comment]
@ninabarbakadze does this issue include a new app hash test for v3? If not, do we need a separate issue for that?
AFAIK v3 doesn't introduce any new message types so IMO it doesn't need one but if that's the case, idk why this issue blocks v3.

**Comment by rootulp** [comment]
Answering my own questions from above:

> Which git branch do you propose adding the test in this issue to (presumably main)? 

main

> If main where you plan to source the app hash used to compare against (presumably v2.0.0-rc2)?

Looks like v2.x based on [this line](https://github.com/celestiaorg/celestia-app/pull/3879/files#diff-de1da0384e69ff8f40e98d1cd0fa0520d40b0ef1afff1b74e2be009820ce30d7R91) but unclear if it was v2.1.2 or an earlier release.
