### ISSUE TITLE
Optimize QGB Queries

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#369]
We've been iterating quickly in the `qgb-integration` feature branch, we should keep track of all the instances where we think there is room to optimize in the future, so that we can do so before merging.

**Comment by SweeXordious** [comment]
## Proposal
One possible way for optimizing the queries is setting multiple keys for the same instance.
For example, in the cosmos-sdk, under the staking module validator:

```golang
// set the main record holding validator details
func (k Keeper) SetValidator(ctx sdk.Context, validator types.Validator) {
	store := ctx.KVStore(k.storeKey)
	bz := types.MustMarshalValidator(k.cdc, &validator)
	store.Set(types.GetValidatorKey(validator.GetOperator()), bz)
}

// validator index
func (k Keeper) SetValidatorByConsAddr(ctx sdk.Context, validator types.Validator) error {
	consPk, err := validator.GetConsAddr()
	if err != nil {
		return err
	}
	store := ctx.KVStore(k.storeKey)
	store.Set(types.GetValidatorByConsAddrKey(consPk), validator.GetOperator())
	return nil
}

// validator index
func (k Keeper) SetValidatorByPowerIndex(ctx sdk.Context, validator types.Validator) {
	// jailed validators are not kept in the power index
	if validator.Jailed {
		return
	}

	store := ctx.KVStore(k.storeKey)
	store.Set(types.GetValidatorsByPowerIndexKey(validator, k.PowerReduction(ctx)), validator.GetOperator())
}
```

Thus, when we're trying to query for a validator, we use an easy:

```golang
        value := store.Get(types.GetValidatorKeyBy<type>(addr))
```

Where <type> is the key used to persist the validator. In this case, it can be: `PowerIndex` or `ConsAddr`.

## Downsides
This optimization results in fast requests on the cost of storage. 
In the case of validators, the network is not expected to have tons of validators, thus, it can be used.
Also, when a validator is stopping, it is deleted. 
So, the impact wouldn't be that big.
For valsets/data commitments, that might be different. Needs to be discussed.

### Additional information
This approach can be implemented once we analyze which requests are used the most, so the storage cost is justified.
Also, https://github.com/celestiaorg/celestia-app/issues/309 should be taken in consideration.

**Comment by SweeXordious** [comment]
@evan-forbes I guess this is no longer relevant, what do you think

**Comment by evan-forbes** [comment]
:axe:
