### ISSUE TITLE
Enforce consistent linting rules

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3723]
@ninabarbakadze 
```
~/Celestia/celestia-core on main *2 > make lint                                                                                                                                                     took 19s
--> Running linter
~/Celestia/celestia-core on main *2 >     
```

It's not showing anything locally. I guess that I have a different version. 

Generally, if we want to enforce specific linting rule, we should add a workflow that runs the linter and complains if there are any changes to the repo. Otherwise, we will need to make this change manually every time, and not expect contributors to do it themselves.

Not blocking on this tho, thanks for handling it :pray:

_Originally posted by @rach-id in https://github.com/celestiaorg/celestia-app/pull/3720#pullrequestreview-2193629605_

**Comment by rootulp** [comment]
@ninabarbakadze what golangci-lint version do you have installed locally? For me:

```
$ golangci-lint version
golangci-lint has version 1.59.0 built with go1.22.3 from 2059b18a on 2024-05-26T18:13:27Z
```

I think this issue may be resolvable by bumping golangci-lint in this repo / CI to use the latest version and then to recommend contributors to also use the latest version. 

Latest seems to be https://github.com/golangci/golangci-lint/releases/tag/v1.59.1
