### ISSUE TITLE
By default, stop the node unless using bbr

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3745]
Since using bbr as a congestion control algo increases throughput significantly, by default the node should not start without it. Node operators still need the ability to bypass this default.

## AC

- [ ] Add a mechanism that will not start the node unless using bbr as a congestion control algo in any environment (docker, vm, hardware etc)
- [ ] Add a flag that bypasses the above mechanism

**Comment by rootulp** [comment]
Updating this from an in-person sync. We want to:
1. encourage users to run BBR in v2.
1. enforce that users are running BBR in v3.

Concretely that means adding a warning to v2 if the node starts up and BBR isn't enabled. Ideally the warning also includes instructions on how to enable BBR.
