### ISSUE TITLE
Come back to versioned gas scheduler variables 

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3748]
## Description

Come back to #3404 https://github.com/celestiaorg/celestia-app/pull/3735 after versioned app module upgrades and see if we want to keep the current design. 

## Acceptance Criteria

- [ ] reevaluate the current status of refactor
- [ ] write docs for the final version

**Comment by evan-forbes** [comment]
to clarify from a sync, this is also dependent upon the app multiplexer

**Comment by rootulp** [comment]
> Come back to https://github.com/celestiaorg/celestia-app/issues/3404 https://github.com/celestiaorg/celestia-app/pull/3735 after versioned app module upgrades

Clarification: multi-app doesn't change the upgrade mechanism. It refactors how the binary supports multiple state machines.
