### ISSUE TITLE
Add a params v3 page to the specs

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3762]
Overall LGTM. We'll also need to add a params v3 page to the specs and mark the params: `blob.GasPerBlobByte` and `auth.TxSizeCostPerByte` as non governance modifiable on that page. 

Ref: https://github.com/celestiaorg/celestia-app/blob/main/specs/src/specs/parameters_v2.md

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/3735#pullrequestreview-2221789398_

**Comment by rootulp** [comment]
The parameters v3 page isn't visible on https://celestiaorg.github.io/celestia-app/parameters.html. We need to add it to:
- https://github.com/celestiaorg/celestia-app/blob/983385a1abe2361fb7f4a78fdaf86bda8ae9af18/specs/src/SUMMARY.md?plain=1#L24-L26
- https://github.com/celestiaorg/celestia-app/blob/983385a1abe2361fb7f4a78fdaf86bda8ae9af18/specs/src/parameters.md?plain=1#L5-L6
