### ISSUE TITLE
app/init: app is always looking for a user in HOME path through etc/passwd

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#377]
H/t @SweeXordious for helping finding the root cause

If we initialize a celestia-app instance in testground, the app is panicking in not finding the home directory, due to these lines

https://github.com/celestiaorg/celestia-app/blob/d7bb3934e0c13259bf3d666378ea67fda852b6e5/app/app.go#L156-L163

https://github.com/celestiaorg/cosmos-sdk/blob/eee26c3b6763edf8817d47b4e6695aa04c49bf9f/simapp/app.go#L179-L186

Here is the log output of the failure in testground: 
```
May  2 16:36:56.293013	INFO	starting run	{"run_id": "c9o0h7tvqc7pa50kffmg", "plan": "celestia-app", "case": "capp-1", "runner": "local:exec", "instances": 1}
May  2 16:36:56.293516	INFO	starting test case instance	{"plan": "celestia-app", "group": "single", "number": 0, "total": 1}
May  2 16:36:56.855331	INFO	0.5622s      ERROR << single[000] >> panic: $HOME is not defined
May  2 16:36:56.855438	INFO	0.5624s      ERROR << single[000] >>
May  2 16:36:56.855470	INFO	0.5624s      ERROR << single[000] >> goroutine 1 [running]:
May  2 16:36:56.855519	INFO	0.5625s      ERROR << single[000] >> github.com/celestiaorg/celestia-app/app.init.0()
```

Resource: [link](https://unix.stackexchange.com/questions/259791/how-to-change-the-home-directory-of-the-currently-logged-in-user#:~:text=You%20need%20to%20edit%20the,home%20directory%20of%20the%20user)

As a hot-fix/dirty-hack for testground case, we should create a branch where those init funcs are commented out in order for the app to be intialized properly.

**Comment by evan-forbes** [comment]
We might be able to pass a flag that overwrites whatever that initialized `DefaultNodeHome` value is.

**Comment by SweeXordious** [comment]
It would be better if we have a way to initialize celestia-app without having to call:

```golang
os.UserHomeDir()
```

Currently, we can pass `homePath` to:

https://github.com/celestiaorg/celestia-app/blob/d7bb3934e0c13259bf3d666378ea67fda852b6e5/app/app.go#L213-L224 

However, it is still evaluating:

```golang
os.UserHomeDir()
```
Which ends up `panic`ing in the context of a user who doesn't have an explicitly defined home directory.

Possible solutions would be to:
- Add a new flag that is checked before getting the default user home
- using the existing `--home` flag to set the home. And, if not provided, fallback to the user home (shouldn't probably be defined as a default parameter as it will always be evaluated when starting the CLI and end up complaining)

**Comment by SweeXordious** [comment]
> We might be able to pass a flag that overwrites whatever that initialized DefaultNodeHome value is.

That was fast :D  I guess we already have the `--home` flag which can be used for this purpose. Except that we need to change the implementation not to evaluate the user home directory on every run.

**Comment by evan-forbes** [comment]
ahhh I frontran @SweeXordious by 10s lol 

yeah, that DefaultNodeHome was added last second to accomodate a newer version of the cosmos-sdk iirc, there's no reason to keep it.

**Comment by SweeXordious** [comment]
makes sense. And also not to use this function to get it:
https://github.com/celestiaorg/celestia-app/blob/d7bb3934e0c13259bf3d666378ea67fda852b6e5/app/app.go#L156
It would be preferable if everything is inside the `New` function.

**Comment by MSevey** [comment]
Bumping as it came up today :-)

**Comment by rootulp** [comment]
Note: Osmosis uses `init` [here](https://github.com/osmosis-labs/osmosis/blob/ce3fdb5a90095c06f3f543939cab2e0624971293/app/app.go#L143-L151) and a freshly scaffoled ignite CLI app also contains this `init` function. That doesn't mean we shouldn't remove it but we may want to ensure `DefaultNodeHome` is defined in for expected contexts if we set it via a different mechanism.
