### ISSUE TITLE
Document moving of constants to go-square

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#3770]
[discussion] it looks like these constants were moved to go-square. Note to future selves, we should add a line to the v3.0.0 release notes breaking changes section that consumers who imported these constants from `appconsts` can instead get them from go-square. I think we could start a changelog file for release notes like this.

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/3765#discussion_r1709912518_

**Comment by cmwaters** [comment]
I think more broadly it might be beneficial to introduce an `UPGRADING.md` page

**Comment by rootulp** [comment]
Yea an `UPGRADING.md` page works for me 👍

**Comment by rootulp** [comment]
Closing in favor of https://github.com/celestiaorg/celestia-app/issues/3791
