### ISSUE TITLE
Gate authored blobs to v3 if we don't use multi-app

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3771]
in #3765, we added authored blobs, a consensus breaking feature, but didn't gate it like normal due to the ongoing switch to a new upgrade mechanism. 

if we don't end up using that mechanism, we need to make sure that we gate it appropriately.

this issue can be closed upon using the new upgrade mechanism or by adding the gating mechanism and a unit test (preferably also a e2e test) for the upgrade https://github.com/celestiaorg/celestia-app/issues/3772

**Comment by rootulp** [comment]
Slight correction: multi-app doesn't change the upgrade mechanism. The upgrade from v2 -> v3 and onwards will still use signaling.

We need to gate authored blobs to v3 if we don't adopt a refactor to how the celestia-app binary supports multiple state machines. That refactor is sometimes called "multi-app".

**Comment by rootulp** [comment]
This appears closed by https://github.com/celestiaorg/celestia-app/pull/3870. @cmwaters please re-open if I'm mistaken.
