### ISSUE TITLE
Fix gas limit check for `WirePayForData`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#378]
as pointed out here https://github.com/celestiaorg/celestia-node/pull/658/files#r860270919 we should be able to hardcode the gas limit for pay for data transactions. Unfortunately, we cannot as `CheckTx` will reject `WirePayForData` messages as they are significantly larger than the `PayForData` transactions that actually ends up on chain, and the determining factor for gas limit is the size of the transaction. We should find a way to hardcode the gas limit and their checks for `WirePayForData` transactions so that reasonable gas limits can be used and the transaction will still get accepted into the mempool.

**Comment by renaynay** [comment]
Once this is fixed, we also need to change the API for PFD

**Comment by evan-forbes** [comment]
so after discussing this with @liamsi and @musalbas, this is actually a feature and not a bug lol

We want a fee market to include the data being paid for, so we should keep things the way they are and not bypass the size of the WirePFD
