### ISSUE TITLE
Describe lightweight tx indexer in release notes

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3810]
## Context

https://github.com/celestiaorg/celestia-app/releases/tag/v2.1.0 

## Problem

This release contains a lightweight transaction indexer but the release notes don't describe it, how users should use it, what advantages it has over the KV indexer.

## Proposal

Update the release notes.

Tagging @ninabarbakadze @cmwaters for awareness.

**Comment by ninabarbakadze** [comment]
I can work on this, I should also write an ADR

**Comment by ninabarbakadze** [comment]
closing with https://github.com/celestiaorg/celestia-app/releases/tag/v2.1.0
