### ISSUE TITLE
Add computation limits on transactions

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#3820]
### Summary

We want to prevent situations that could lead to excessive computation which could also slow down the network (This could happen if all the transactions in an 8MB block were IBC headers for example). 

### Proposal

We could introduce an upper bound on the amount of txs or we could use the `MaxGas` field in the `ConsensusParams`.

**Comment by cmwaters** [comment]
One of the first steps would be to benchmark the effects of "computationally heavy" transactions on execution by seeing how long it would take to execute 1000 IBC headers or 5000 Send Txs

**Comment by evan-forbes** [comment]
closing as completed 

the decision was to only add a default computation limit for proposer atm. the limit was determined by benchmarking execution of prepare, process proposal, and commit on a cloud vm
