### ISSUE TITLE
Governance proposal to modify ICA host param

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3827]
## Context

https://github.com/celestiaorg/celestia-app/issues/3824

## Problem

Arabica and Mocha have an incorrect ICA host param for AllowMessages because it is the default `[*]`. It should be an explicit allowlist.

## Acceptance Criteria

This guide should help: https://github.com/celestiaorg/celestia-app/pull/3832

### Arabica
- [x] Submit a governance proposal. Josh submitted it on Arabica and it has proposal ID 1
- [x] Get the governance proposal approved. Votes from [validator 2](https://arabica.celenium.io/tx/dac16c9e62c3b953d98e39d91fa55354d5f210b4694f422828bcaa06a0fddbae?tab=messages), [validator 3](https://arabica.celenium.io/tx/089e695587c2cc3b6040cf0997278fbfe2c54c0986a793e758362c7e349d1350?tab=messages), [validator 4](https://arabica.celenium.io/tx/a3792a73badfd1f031988becbd4c1c34864ba46e2ce23c5b0faff04631959981?tab=messages)

### Mocha
- [x] Submit a governance proposal: https://www.mintscan.io/celestia-testnet/proposals/5
- [x] Get the governance proposal approved.

### Mainnet
- [ ] Submit a governance proposal.
- [ ] Get the governance proposal approved.

**Comment by rootulp** [comment]
Blocked on approval from leadership

**Comment by rootulp** [comment]
Got approval from leadership to do this.

**Comment by rootulp** [comment]
Adding Evan b/c he volunteered to help do this on mainnet 🫡

**Comment by rootulp** [comment]
Blocked until Sept 18th.

**Comment by rootulp** [comment]
Unblocked b/c v2 activated on mainnet.

**Comment by evan-forbes** [comment]
closing as completed

**Comment by rootulp** [comment]
Confirmed:

```
$ grpcurl -d '{"subspace": "icahost", "key": "AllowMessages"}' celestia-grpc.publicnode.com:443 cosmos.params.v1beta1.Query/Params
{
  "param": {
    "subspace": "icahost",
    "key": "AllowMessages",
    "value": "[\"/ibc.applications.transfer.v1.MsgTransfer\",\"/cosmos.bank.v1beta1.MsgSend\",\"/cosmos.staking.v1beta1.MsgDelegate\",\"/cosmos.staking.v1beta1.MsgBeginRedelegate\",\"/cosmos.staking.v1beta1.MsgUndelegate\",\"/cosmos.staking.v1beta1.MsgCancelUnbondingDelegation\",\"/cosmos.distribution.v1beta1.MsgSetWithdrawAddress\",\"/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward\",\"/cosmos.distribution.v1beta1.MsgFundCommunityPool\",\"/cosmos.gov.v1.MsgVote\",\"/cosmos.feegrant.v1beta1.MsgGrantAllowance\",\"/cosmos.feegrant.v1beta1.MsgRevokeAllowance\"]"
  }
}
```
