### ISSUE TITLE
Make `icahost.AllowMessages` unmodifiable by governance

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3837]
## Context

https://github.com/celestiaorg/celestia-app/issues/3824

## Problem

Arabica and Mocha have an incorrect ICA host param for AllowMessages because it is the default [*]. It should be an explicit allowlist.

## Proposal

Make `icahost.AllowMessages` unmodifiable by governance. Hard-code it to the explicit allowlist defined in https://github.com/celestiaorg/CIPs/blob/main/cips/cip-14.md

**Comment by rootulp** [comment]
We may not want to do this if we frequently get requests from teams to update the list because making the param unmodifiable by governance means that the list can only be modified via app version upgrades.

**Comment by evan-forbes** [comment]
per sync

it doesn't appear that pfbs can be submitted via ICA, therefore we don't need to block PFBs, and governance can be responsible for picking the values

**Comment by rootulp** [comment]
Related: https://github.com/celestiaorg/celestia-app/issues/3857 we can get more visibility on the error with PFBs if we bump ibc-go

**Comment by rootulp** [comment]
Closing for now as won't do
