### ISSUE TITLE
mocha-4 genesis file does not define an app version 

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3840]
## Context

https://celestia-team.slack.com/archives/C02PFFCGMNW/p1725353291554399?thread_ts=1725273825.398589&cid=C02PFFCGMNW

## Problem

Attempt to sync a v2.1.2 node from genesis with the genesis.json file defined at https://github.com/celestiaorg/networks/blob/master/mocha-4/genesis.json

### Option 1: modify Mocha genesis.json
- Identify if there are any issues with updating the existing genesis.json file.
- Update the mocha-4 genesis file (I checked both celestia and arabica-11 and they have the correct app version in the genesis)
```json
"version": {
   "app_version": "1"
}
```
- Update https://github.com/celestiaorg/networks/blob/master/mocha-4/genesis_hash.txt
- Update the checksum for the download-genesis command so it works with the modified genesis.

### Option 2: modify celestia-app to accomodate mocha-4's lack of app version in genesis.json

**Comment by evan-forbes** [comment]
is it possible to modify the genesis and sync an existing network from scratch? if so, is that a bug? my understanding of the genesis is that its the first block. If that's committed to then changing it without recomputing all of the headers is not possible

**Comment by rootulp** [comment]
As an alternative to this: can celestia-app interpret an `InitGenesis` invocation on a genesis file with an unpopulated app version as `1`?

Did this only surface for DevOps maintained Mocha nodes because it was a regression in v2.x.x?
