### ISSUE TITLE
Request reviews from all core/app engineers

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3850]
## Context

Breakfast discussion w/ @cmwaters @ninabarbakadze 

## Proposal

@cmwaters @ninabarbakadze don't like how the auto PR request reviewer action only requests reviews from two people on core/app. 

I personally don't have a strong opinion for or against this.

## Proposal

They would prefer if the PR request reviewer action requested reviews from all core/app engineers.

**Comment by ninabarbakadze** [comment]
thanks! I think @evan-forbes should have the perms for this

**Comment by evan-forbes** [comment]
we just need to change this line

https://github.com/celestiaorg/celestia-app/blob/main/.github%2Fauto_request_review.yml#L18
