### ISSUE TITLE
Override the `timeout_commit` and `timeout_propose` when switching to v3

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3859]
We should override the timeouts upon the switch to app version v3

**Comment by rootulp** [comment]
Notes from discussion w/ @evan-forbes :

- This issue diverges from ADR-115 because we want to override two params not just one (as proposed in ADR-115).
- This is blocked on experiments for determining what the values are.
    - @evan-forbes hypothesizes that TimeoutCommit = ~4.7 seconds and TimeoutProposal = ~3.5 seconds.
    - @evan-forbes teach @rootulp how to run experiment to determine the correct timeouts. Blocked on @evan-forbes syncing with @sysrex because he's currently using his personal accounts for Congest.

**Comment by staheri14** [comment]
**Question:**
At height X-1 (before upgrade height X), should we suggest timeouts for the current app version (v2) or the upcoming version (v3)?

### **Option 1: Use Timeouts for Next Version (v3)**  
- **Pros:**
  - Fast block production starts immediately at upgrade height (X).
- **Cons:**
  - Inconsistency: Suggested timeouts at height X-1 don’t match the app version in the current block header (v2 vs. v3).

### **Option 2: Use Timeouts for Current Version (v2)**  
- **Pros:**
  - Consistency: Timeouts always align with the app version in the current block header.
- **Cons:**
  - Delayed effect: Timeouts based on v3 will only apply at height X+1 (one height after the upgrade).

**Comment by evan-forbes** [comment]
good question, my understanding of this is that we should only change the timeouts when the app version is changed, so we should do option 2

**Comment by evan-forbes** [comment]
to add more reasoning to the above, we don't know if the upgrade is successful until we produce a block that has that version, therefore that is the soonest we possibly could change.

**Comment by staheri14** [comment]
Thanks, @evan-forbes! That makes sense—I'll go ahead with the second option.

**Comment by evan-forbes** [comment]
either or should be okay if I'm understanding correctly, especially for our existing testnets

we could also just use a default timeouts for the first block, as it shouldn't be super important for us atm
