### ISSUE TITLE
Proposal: Limit the number of txs per block to 5000

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3875]
one option to prevent undue load would be limit the number of transactions to roughly what could be included in 2MB, which is ~5000txs

**Comment by rootulp** [comment]
Related: https://github.com/celestiaorg/celestia-app/issues/3820

**Comment by rootulp** [comment]
This seems close-able b/c we added limits to the # of PFB and non-PFB messages in v3. Please re-open if you think differently.
