### ISSUE TITLE
E2E test for v3

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#3877]
### Summary

We're unable to use gRPC correctly because the paths that knuu creates a reverse proxy for can't be parsed by the gRPC client. We should use ports instead. When this is completed we can write a test which upgrades to v3 using the signalling mechanism and asserts that everything works as expected

**Comment by rootulp** [comment]
I think this can be closed b/c https://github.com/celestiaorg/celestia-app/pull/3910 merged which upgrades to v3 using the signaling mechanism.
