### ISSUE TITLE
ADR: Pay for multiple blobs with a single `MsgPayForBlob`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#388]
Currently, each `MsgPayForData` transaction can only pay for a single message. Ideally, users would be able to pay for multiple messages using a single payment transaction. Not only that, but because this reduces the number of state transitions each full node would have to execute, we would want to incentivize this behavior, by adding some base fee to `PayForData`

**Comment by adlerjohn** [comment]
Are you proposing a consensus-critical change (i.e. having multiple data commitments per PFD), or an application-level standard?

**Comment by evan-forbes** [comment]
Well I mean, it would presumably be implemented here lol

@musalbas and @liamsi were discussing this idea earlier this week, and I just wanted to write it down so we can begin discussing it. It's not something I think would make mainnet imho

**Comment by musalbas** [comment]
More important than this would be to add an overhead cost to MsgPayForData, so that e.g. one MsgPayForData with 10KB of data is cheaper than two MsgPayForData with 5KB of data.

**Comment by adlerjohn** [comment]
Such an overhead doesn't necessarily have to be enforced by the protocol, but can rather be an emergent property of a separate fee market for Celestia-app transactions: https://github.com/celestiaorg/celestia-specs/issues/97

**Comment by evan-forbes** [comment]
This becomes significantly easier after implementing #835

**Comment by evan-forbes** [comment]
I don't think this is useful anymore as it can be done entirely on the rollup's side now that we are only using a single share commitment.

@adlerjohn can you check my logic on this? 

If we want to submit a single transaction that has blobs with different namespaces, then we can after we complete #890 by submitting multiple PFBs in a single sdk.Tx
