### ISSUE TITLE
Ensure fees were deducted when submitting a PayForData in the cli integration test

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#389]
With #380, we started deducting fees based on the size of the message submitted via `MsgWirePayForData`. While we have unit tests to ensure that funds were actually deducted, we should also add the [cli integration test](https://github.com/celestiaorg/celestia-app/blob/b2617e419280061e33feaa12ff4dcdd9cc612113/x/payment/client/testutil/integration_test.go#L152-L158) by querying for the balance of the user after the tx has been successfully submitted.

**blocked** by #379

**Comment by evan-forbes** [comment]
this can be closed as we're testing for this in the block size integration test

**Comment by rootulp** [comment]
Where are we testing for gas consumption in? https://github.com/celestiaorg/celestia-app/blob/8b9c4c9d13fe0ccb6ea936cc26dee3f52b6f6129/app/test/block_size_test.go#L83

**Comment by evan-forbes** [comment]
:eyes: oh shoot! we aren't! I could swear we were. opened #998 as a simple test
