### ISSUE TITLE
Configure mergify to support forward-porting to main

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3917]
## Context

I frequently have a PR that targets a release branch (v1.x or v2.x) that I would like to forward-porting to main.

## Problem

https://github.com/celestiaorg/celestia-app/blob/main/.github/mergify.yml does not support forward-porting to main.

## Proposal

Configure mergify to enable forward-porting to main

**Comment by tusharnagar17** [comment]
Hi team,
I'd like to work on this issue, could you please assign it to me?

**Comment by kobakaku** [comment]
@rootulp 
I've done this issue.
https://github.com/celestiaorg/celestia-app/pull/3922
