### ISSUE TITLE
v2.2.0-mocha Docker image does not exist

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3934]
## Context

https://github.com/celestiaorg/celestia-app/pkgs/container/celestia-app/versions

Reported by @smuu 

## Problem

A docker image for v2.2.0-mocha does not exist

## Proposal

- [x] Create and publish a Docker image for v2.2.0-mocha.
- [x] Make sure CI is fixed and that it will create Docker images in the future. IIRC @MSevey created a few fixes for Docker publishing recently. Fixed via https://github.com/celestiaorg/celestia-app/pull/3939

**Comment by MSevey** [comment]
I know the team uses feature branches a lot. Did all my fixes get applied to the correct feature branches?

**Comment by MSevey** [comment]
If the tag was built off of the `v2.x` branch then the issue is that branch doesn't contain the CI fixes. 

https://github.com/celestiaorg/celestia-app/blob/v2.x/.github/workflows/docker-build-publish.yml

**Comment by rootulp** [comment]
Yes the tag was built off of the v2.x branch. I'll update it to account for your fixes.

**Comment by rootulp** [comment]
Manually triggered https://github.com/celestiaorg/celestia-app/actions/runs/11146831921

**Comment by MSevey** [comment]
You need to select the v2 branch when you manually trigger the action for v2 updates
<img width="935" alt="Screenshot 2024-10-02 at 11 46 37 AM" src="https://github.com/user-attachments/assets/01e5ccba-7ab3-4e58-81ae-fcc374e4f63f">

**Comment by rootulp** [comment]
Manually published https://github.com/celestiaorg/celestia-app/pkgs/container/celestia-app/283797346?tag=v2.2.0-mocha
