### ISSUE TITLE
Manually test state sync on `v3.0.0-arabica`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3946]
## Context

https://github.com/celestiaorg/celestia-app/pull/3936 introduced a more reliable way to state sync.

## Problem

We don't have any state sync integration or end-to-end tests so it's not easy to verify state sync works in all cases.

## Proposal

Manually test state sync after we cut and deploy v3.0.0-arabica

**Comment by rootulp** [comment]
Blocked on v3.0.0-arabica being deployed

**Comment by evan-forbes** [comment]
closing as completed
