### ISSUE TITLE
Document gas usage by `MsgPayForBlobs`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#397]
in #380 we started consuming 1 gas per byte of data posted via `MsgPayForData`, but didn't include this in the documentation. We should add this to the specs package of the payment module, and discuss where else to communicate.

**Comment by musalbas** [comment]
I think we should also document all the other celestia-app transactions, not just PayForData, to see what their pricing is in relation to PayForData.

**Comment by evan-forbes** [comment]
can close with #2132
