### ISSUE TITLE
Decrease voting period on Arabica from 1 week to 1 day

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3976]
## Context

The governance voting period is:

- Arabica => 1 week
- Mocha => 1 day
- Mainnet Beta => 1 week

## Problem

It is counter-intuitive that Arabica is 1 week when Mocha is 1 day

## Proposal

1. Create a governance proposal to decrease the voting period on Arabica from 1 week to 1 day
2. Get the governance proposal passed

**Comment by rootulp** [comment]
## Notes

I'm referencing https://github.com/celestiaorg/celestia-app/blob/main/docs/maintainers/modify-param.md

### Prerequisites 

On arabica consensus node via Lens

```
consensus-full-snapshot-0:~$ celestia-appd query params subspace gov votingparams
key: votingparams
subspace: gov
value: '{"voting_period":"604800000000000"}'
```

which is 7 days. See https://celestiaorg.github.io/celestia-app/parameters_v2.html

### Steps

On arabica validator node via Lens. Create a proposal.json with

```
{
  "title": "Decrease voting period to 1 day",
  "description": "Decrease voting period to 1 day",
  "changes": [
    {
      "subspace": "gov",
      "key": "votingparams",
      "value": {"voting_period":"86400000000000"}
    }
  ],
  "deposit": "10000000000utia"
}
```

Submit the proposal

```
celestia-appd tx gov submit-legacy-proposal param-change proposal.json --from $FROM --fees $FEES --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --yes --home /home/celestia --keyring-backend test
```

The proposal has ID 2.

Vote for the proposal

```
export PROPOSAL_ID=2
6F481CF1EF97A9D4DDC3ADBDC000A971F385DFBA3DAD6D459DF4A4A15673FC47
```

Repeat that process on the other validators.

```
consensus-validator-2-0:~$ celestia-appd tx gov vote 2 yes --from consensus-validator-2-0-arabica-11 --fees 210000utia --gas auto --gas-adjustment 2.0 --yes --home /home/celestia

consensus-validator-3-0:~$ celestia-appd tx gov vote 2 yes --from consensus-validator-3-0-arabica-11 --fees 210000utia --gas auto --gas-adjustment 2.0 --yes --home /home/celestia

consensus-validator-4-0:~$ celestia-appd tx gov vote 2 yes --from consensus-validator-4-0-arabica-11 --fees 210000utia --gas auto --gas-adjustment 2.0 --yes --home /home/celestia
```

**Comment by rootulp** [comment]
Closing as done but this won't manifest on-chain until Oct 22 b/c the current voting period is 1 week.

**Comment by jcstein** [comment]
should all of these be 1 week? or at least Mocha be 1 week, so as to mimic what is on Mainnet Beta?

**Comment by rootulp** [comment]
@evan-forbes decreased Mocha from 1 week to 1 day because we wanted an expedited governance process on testnets
