### ISSUE TITLE
Stop requiring `TestAppUpgradeV3` produce enough blocks to hit the DefaultUpgradeHeightDelay

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3978]
https://github.com/celestiaorg/celestia-app/blob/899ad7c56f62560a5666a604606f550ae1804cb3/app/test/upgrade_test.go#L106-L124

we're currently requiring a test to produce >50,400 block to pass, in order to prevent flakes in the race detector and simply to reduce the amount of time required for this test to pass, we should reduce the number of blocks that this has to take. This could be via build flags, or configuring the testapp specifically to not use the same constant.

**Comment by rootulp** [comment]
This was done in https://github.com/celestiaorg/celestia-app/pull/3980 . I just confirmed by logging the block height in upgrade_test.go after the chain upgrades to v3:

```
block height for v3: 4
```
