### ISSUE TITLE
Version `DefaultUpgradeHeightDelay`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3979]
In order to keep roughly a week delay, we should version the `DefaultUpgradeHeightDelay`. To close this issue, version `DefaultUpgradeHeightDelay`. Ideally, such a change would get into v3 so that when upgrading to v4, the delay would be the same.

**Comment by rootulp** [comment]
This appears to have been done via https://github.com/celestiaorg/celestia-app/pull/3882

Please re-open if I'm mistaken @evan-forbes @staheri14
