### ISSUE TITLE
Revert using a commit in the `MajorUpgradeToV3`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3981]
LGTM

Can we just create a follow up issue to fix the v3 upgrade test such that we don't need a fixed commit tag

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/pull/3882#pullrequestreview-2372557757_

**Comment by rootulp** [comment]
Can close this as a duplicate of https://github.com/celestiaorg/celestia-app/issues/3947
