### ISSUE TITLE
Consider including v2 upgrade heights in binary for common networks

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3995]
## Context

We used a `--v2-upgrade-height` flag on networks

## Problem

If a consensus node is block syncing from genesis, it needs to provide the `--v2-upgrade-height`

## Proposal

Consider hard-coding the `--v2-upgrade-height`s for arabica, mocha, mainnet beta so that node operators don't have to specify it.

**Comment by cmwaters** [comment]
I am for this

**Comment by rootulp** [comment]
Note: this will be cumbersome to test b/c we'll need to block sync on Arabica, Mocha, or Mainnet through the v2 upgrade height.

To make this issue easier, we should build a utility that makes it easier + faster to block sync.
