### ISSUE TITLE
querying empty signal tally causes index panic

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#4007]
Found by using the following command on arabica:

❯ celestia-appd query signal tally 3 --node https://rpc.celestia-arabica-11.com:443
Error: rpc error: code = Unknown desc = runtime error: index out of range [7] with length 7: panic

**Comment by rootulp** [comment]
hmm, I can't repro with that exact command or a few variants of that command:

```
celestia-appd query signal tally 3 --node https://celestia-mainnet-rpc.itrocket.net:443
celestia-appd query signal tally 4 --node https://rpc.celestia-arabica-11.com:443
celestia-appd query signal tally 5 --node https://rpc.celestia-arabica-11.com:443
```

**Comment by rootulp** [comment]
Oh it's possible that this node was the Arabica node that DevOps accidentally downgraded after upgrading to v3.x and submitting the signal message. See [Slack thread](https://celestia-team.slack.com/archives/C07G6UY8YTG/p1730843900203849) for context.

**Comment by rootulp** [comment]
I reproed this by running single-node.sh from https://github.com/celestiaorg/celestia-app/pull/4041 and then ./scripts/upgrade-to-v3.sh

```bash
# Query during app version 1
$ celestia-appd query signal tally 3
Error: rpc error: code = Unknown desc = kv store with key KVStoreKey{0x14001209a90, signal} has not been registered in stores: panic

# Query during app version 2
$ celestia-appd query signal tally 3
threshold_power: "4167"
total_voting_power: "5000"
voting_power: "0"

# Query after running upgrade-to-v3.sh but before v3 activation height
$ celestia-appd query signal tally 3
Error: rpc error: code = Unknown desc = runtime error: index out of range [7] with length 6: panic
```

**Comment by rootulp** [comment]
The upgrade key is getting iterated over when calculating the tally. I added a unit test and fix.
