### ISSUE TITLE
Curls are not working for me.

### ISSUE THREAD

**Issue by shaswatsaloni** [celestiaorg/celestia-app#4032]
curl --location 'http://<serverip>:1317/cosmos/bank/v1beta1/balances/celestia1w73c9lh4hc2s4fgrq3t526ggq0yw467xtf4wps' \
--header 'x-cosmos-block-height: 2767245'

I have a archival celestia consensus node setup. But this doesn't seems to be working for me?

But these are working.

curl --location 'http://10.213.56.73:1317/status'

any help would be appreciated.

Thanks,
Saloni.

**Comment by rootulp** [comment]
The IP address is absent from your first command. Does the following command work? 

```
curl --location 'http://10.213.56.73:1317/cosmos/bank/v1beta1/balances/celestia1w73c9lh4hc2s4fgrq3t526ggq0yw467xtf4wps'
--header 'x-cosmos-block-height: 2767245'
```

**Comment by rootulp** [comment]
Please re-open if this is still an issue.

**Comment by rootulp** [comment]
Can you please provide:
1. more details on the error you're observing?
2. more information on the networking between the place you're invoking `curl` and the archival node?

A variant of your command works if I use a consensus node API endpoint:

```
$ curl --location 'https://celestia-rpc.brightlystake.com/api/cosmos/bank/v1beta1/balances/celestia1w73c9lh4hc2s4fgrq3t526ggq0yw467xtf4wps' --header 'x-cosmos-block-height: 2826293'
{
  "balances": [
    {
      "denom": "utia",
      "amount": "52215"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}%
```
