### ISSUE TITLE
Use the `file` keyring backend as a default

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#405]
In order to simplify keyring use, celestia-node will be using the `file` keyring backend as a default. In order to stay consistent and avoid possible confusion for users, we should investigate exactly what this entails, and then make a decision on switching the backend here as well.

**Comment by rootulp** [comment]
Is this issue coupled to the celestia-node implementation of the same? The celestia-node side isn't implemented yet: https://github.com/celestiaorg/celestia-node/issues/603 and https://github.com/celestiaorg/celestia-node/blob/0c2669574fcbc8478cf9572ae5d36c98901916e8/nodebuilder/state/keyring.go#L25

**Comment by cmwaters** [comment]
Is there a justification anywhere about why `file` over `os`? - is it just to simplify things?

**Comment by evan-forbes** [comment]
cc @renaynay do you remember the exact reason for switching?

**Comment by renaynay** [comment]
`os` is wonky on macos
