### ISSUE TITLE
QGB Orchestrator should stop signing if no longer in the valset

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#406]
Currently, the QGB orchestrator keeps signing attestations even if it  is not part of the valset. These signatures will  be eventually rejected. Thus, the orchestrator should check if it is in the valset before signing attestations.

**Comment by evan-forbes** [comment]
one point to note, is that a validator could potentially fall into and out of the validator set every other block, and ideally the orchestrator would be able to handle this as well, although this might be a premature feature.

**Comment by SweeXordious** [comment]
100% it's still too early for this. Except that I wanted to keep track of all ideas so that after QGB 1.0,  we have a list of improvements we can work on.
Btw, once the IT tests are set, let's go for a call to decide on the set of features we want for QGB 1.0.
