### ISSUE TITLE
Monitor v3 signal

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#4073]
## Context

As of December 2nd, validators are encouraged to upgrade to the latest v3.x.x release (v3.0.2 ATM) and signal for v3

## Proposal

1. Monitor the v3 signal tally
2. [Optional] provide frequent status updates in Slack about it
3. Submit a MsgTryUpgrade so that ideally the upgrade activates between 2-5PM UTC

**Comment by rootulp** [comment]
```
rootulp@rootulp-NUC12WSHv5:~$ celestia-appd query signal tally 3
threshold_power: "584950529"
total_voting_power: "701940634"
voting_power: "241257560"
```

so we're currently at 34% have signalled for v3. We need 83% to signal before we submit a MsgTryUpgrade

**Comment by jcstein** [comment]
getting close!!

```
{"voting_power_out_of_threshold": 85.81, "voting_power_out_of_total": 71.51}
```

**Comment by rootulp** [comment]
Submitted MsgTryUpgrade. The v3 activation height on Mainnet Beta is:

```
$ celestia-appd query signal upgrade --node http://rpc.celestia.pops.one:26657/
An upgrade is pending to app version 3 at height 2993219.
```

https://www.mintscan.io/celestia/block/2993219/ which is estimated at Dec 12th 2024, 11:57:02+00:00
