### ISSUE TITLE
Ensure e2e test uses "test" chain ID

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#4074]
## Context

https://github.com/celestiaorg/celestia-app/pull/4065

## Motivation 

In a call today, we weren't sure if the end-to-end test uses the "test" chain ID

## Proposal

Ensure that the end-to-end test for upgrading to v3 uses the "test" chain ID

**Comment by rootulp** [comment]
There are 4 e2e tests:
1. MinorVersionCompatibility
2. MajorUpgradeToV2
3. MajorUpgradeToV3
4. E2ESimple

We only care about MajorUpgradeToV3 using the `test` chain ID. 

One thing worth noting: each block that the knuu network produces only contains 1 tx so I expect it will take a while for txsim to randomly submit a `MsgSignalUpgrade 3` and then a subsequent `MsgTryUpgrade`

**Comment by evan-forbes** [comment]
> knuu network produces only contains 1 tx

do you know why this is? is it just because we're running one txsim?

**Comment by rootulp** [comment]
Not sure. I expected txsim to submit more than one tx per block but I could be wrong
