### ISSUE TITLE
Support custom `timeout_commit` in testing mode

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#4080]
### Summary

Since v3, timeout commits are now dictated by the application. This has made it difficult in the case of testing, where we and others want to be able to have short timeouts. Both sovereign and eiger have reported this being problematic for them.

### Proposal

Introduce either an environment variable or a flag to force set the timeout commit. We may want to consider this to also set the square size as well. If we're concerned about misuse on a live network we can add chainID checks.

**Comment by cmwaters** [comment]
Furthermore, we might want to, if it's not too breaking, to rename the current timeout_commit and timeout_propose in the config.toml (or at least the go struct) to something else so as to avoid confusion. Most teams may still be setting these values and think it will change the times

**Comment by rootulp** [comment]
> Introduce either an environment variable or a flag to force set the timeout commit. We may want to consider this to also set the square size as well.

We have the `OVERRIDE_MAX_SQUARE_SIZE` env variable which can override the max square size at binary build time so we could add another for overriding `timeout_commit`.

Alternatively, we could override the `timeout_commit` when the chain_id is `test` similar to how we override the upgrade height delay to 3 [here](https://github.com/celestiaorg/celestia-app/blob/e52234f9f0e7f1fb30a5bb0142ecaa214b492f9f/pkg/appconsts/versioned_consts.go#L83-L85).

> Furthermore, we might want to, if it's not too breaking, to rename the current timeout_commit and timeout_propose in the config.toml (or at least the go struct) to something else so as to avoid confusion. Most teams may still be setting these values and think it will change the times

IMO we should deprecate the config `timeout_commit` and `timeout_propose` in v3.x.x and remove them in v4.x.x.

**Comment by rootulp** [comment]
Related: https://github.com/celestiaorg/celestia-app/issues/4023
