### ISSUE TITLE
Upgrade to ledger-go 1.0.0 to fix support for Ledger Nano S+

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#4106]
## Context

https://github.com/osmosis-labs/osmosis/pull/8872

## Problem

There may be an issue with the latest Ledger software.

## Proposal

- [x] Upgrade to the latest Ledger Live application. Upgraded to Ledger Live 2.92.1 
- [x] Upgrade to latest Ledger firmware. Upgraded to Ledger Nano X - OS Version 2.4.0 (previously on 2.2.3)
- [x] Test if it's still possible to use the Cosmos app and send TIA. Confirmed possible: https://www.mintscan.io/celestia-testnet/tx/9CA7A44F1C199383CCB5C2B1AD3285AAE4CA232647F9AC22C6EB92F236622EC1?height=3577088

**Comment by rootulp** [comment]
We use https://github.com/celestiaorg/celestia-app/blob/818026ac446570605d3db582f2d261fb392e1973/go.mod#L258-L260 and the linked PR bumps https://github.com/zondax/ledger-go which we only depend on indirectly https://github.com/celestiaorg/celestia-app/blob/818026ac446570605d3db582f2d261fb392e1973/go.mod#L218

**Comment by rootulp** [comment]
Based on [this comment](https://github.com/osmosis-labs/osmosis/pull/8872#issuecomment-2540134035) the issue may only impact Ledger Nano S+.

Inclined to wait for https://github.com/cosmos/ledger-cosmos-go to cut a new release that bumps their dependency of ledger-go to v1.0.0 so will monitor https://github.com/cosmos/ledger-cosmos-go/pull/70

**Comment by PaddyMc** [comment]
I agree, I'm hoping for a bump in the ledger-cosmos-go app as well, and bump that

**Comment by rootulp** [comment]
https://github.com/cosmos/ledger-cosmos-go/releases/tag/v0.14.0 was released an hour ago so we can bump to that here.
