### ISSUE TITLE
Re-enable IBC

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#412]
during the upgrade to v0.46.0 of the cosmos-sdk in #399, we commented out the ibc module installation into the app, as the ibc module did not have a release that was compatible with v0.46.0. 

When there is a release ready, we should re-install the ibc module by un-commenting out the installation process.

**Comment by liamsi** [comment]
Looks like ibc-go is getting close to be released (with a 0.46 compatible version): https://github.com/cosmos/ibc-go/releases/tag/v6.0.0-rc1

We should sync with the IBC team before using that during the incentivized testnet though.
