### ISSUE TITLE
Query balances for the account is showing null values instead of token amount

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#414]
## Summary of Bug
After creating an account(genesis one or any other) with some amounts of token, querying this account is showing null values instead of the real amount value of it(account)

## Version
d255f0ce461e8cc72f48282593a876cca9cb6c91

## Steps to Reproduce
Checked on running dryrun-1 chain
1. Init chain-id dryrun-1
2. Add genesis account
3. Collect-gentxs
4. Start the chain 
5. Execute cmd `celestia-appd query bank balances $account_adr`

Note: This is also reproducible for accounts created post-genesis
### Log output
```sh
celestia-appd query bank balances celes1eqpxqz6g3vfgvm6l0vju2dx58t49jldj5rd85h
balances: []
pagination:
  next_key: null
  total: "0"
```
---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Bidon15** [comment]
For the record, sending tokens is working as expected. Here is the log output
```sh
celestia-appd tx bank send celes1eqpxqz6g3vfgvm6l0vju2dx58t49jldj5rd85h celes1upzr8d02m3s0g7jhp5hgfvszgznu83tmyhy7ts 100000000uceles --chain-id dryrun-1 --keyring-backend test
{"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"celes1eqpxqz6g3vfgvm6l0vju2dx58t49jldj5rd85h","to_address":"celes1upzr8d02m3s0g7jhp5hgfvszgznu83tmyhy7ts","amount":[{"denom":"uceles","amount":"100000000"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 0
codespace: ""
data: ""
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: 96D666226D373DCC34392ED5208E0975346D1CA010BB2329C815D1B4BAA1B5B7
```

**Comment by evan-forbes** [comment]
@Bidon15 have you claimed any rewards for that account? iirc, we delegated exactly all of our funds, so this would explain why it shows up as null

also, I'm not sure that the tx listed is actually going through, because the broadcast mode was not set to "block" (flag `--broadcast-mode block`). If that's not set, then the tx is always returned. we can check the that tx using `celestia-appd q tx 96D666226D373DCC34392ED5208E0975346D1CA010BB2329C815D1B4BAA1B5B7`?

**Comment by Bidon15** [comment]
Fixed. Thanks for the hints and advices @evan-forbes 🚘
