### ISSUE TITLE
QGB module fatal error: concurrent map writes 

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#421]
Sometimes, when running Celestia-app with the QGB module loaded, it panics with the following error:
https://gist.github.com/SweeXordious/e363cc9f1da00b0c099753a4a68714ac

This needs to be investigated as it didn't happen before adding the module.

One possible track of investigation is the `Query_LastUnbondingHeight_Handler` as the `QueryLastUnbondingHeight` is the only query  that appears in the logs when registering handlers. 
Also, it would be good to find a way to deterministically reproduce this. Currently, it only happens when running integration tests in a docker-compose environment

**Comment by evan-forbes** [comment]
is this still a thing that pops up?

**Comment by SweeXordious** [comment]
Didn't see it lately anymore but I  am not sure it disapeared. I guess we can leave the issue  open for more  months and see.
