### ISSUE TITLE
Charge gas per message share

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#431]
Padding was removed from messages entirely in #419 as it was causing complexity. We can however still pay for padding by increasing the declared size of the message in the `MsgPayForData` and `MsgWirePayForData`. While this will slightly complicate `ValidateBasic`, it is definitely possible.

It's worth noting that paying for padding isn't enforceable. As previously discussed conversations around fee burning, due to tendermint's [deferred execution](https://github.com/tendermint/tendermint/issues/7898) model, enforcing that a message declare the correct padded size is not possible atm. It would be trivial for a block producer to include a `MsgPayForData` transaction that declares the size to be 0 or whatever size they want. This isn't really an issue, as its the same as a block producer including a message with a zero fee. However, adding a check in `ValidateBasic` would stop messages that are not paying for padding from being propagated by nodes running unmodified software.

**Comment by evan-forbes** [comment]
to update from a sync: we still want to include the in message padding when calculating gas costs. This effectively means also including the padding in the last share when calculating gas costs. This means that we will be charging per share used, instead of per byte. 

We will not be including padding from the non-interactive defaults into gas costs.

**Comment by rootulp** [comment]
> we will be charging per share used, instead of per byte

Clarification: I infer this as paying for each byte used by the message shares associated with a PFD (including namespace IDs, info bytes, message length delimiter, and padding). I also infer this as not charging for the amount of transaction shares associated with the PFD.
