### ISSUE TITLE
Change 'microceles' alias in the default genesis

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#440]
This hardcoding of the denomination snuck through

https://github.com/celestiaorg/celestia-app/blob/8e0cf71abce509ceda2786bde6a745e5efddeb2b/app/module.go#L37

we should change it, and preferably in a way that uses `app.BondDenom`

**Comment by iofq** [comment]
After reading through the code, I'm not sure where this Alias is being used, or what we'd replace "microceles" with besides `app.BondDenom` or `app.DisplayDenom`.

**Comment by rootulp** [comment]
> or what we'd replace "microceles" with besides

We could replace it with "microtia" because neither of these constants match what we need

https://github.com/celestiaorg/celestia-app/blob/8e0cf71abce509ceda2786bde6a745e5efddeb2b/app/app.go#L93-L96

**Comment by rootulp** [comment]
Osmosis doesn't define "micro" based on [this search](https://github.com/osmosis-labs/osmosis/search?q=micro&type=code)

[Cosmos Hub docs](https://hub.cosmos.network/main/hub-overview/overview.html) don't describe a "micro" denomination but micro-atom is apparently a thing: https://github.com/cosmos/gaia/blob/main/docs/governance/params-change/Mint.md#mintdenom=

> This is the type of asset (aka coin) that is being minted. The Cosmos Hub produces uatom, or micro-ATOM, where 1,000,000 uatom is equivalent to 1 ATOM.

**Comment by evan-forbes** [comment]
yeah, micro-denomination is simply the long form of `u-denom` (1^10-6). also @iofq this is only used in the [default genesis](https://github.com/celestiaorg/networks/blob/bf123a1287b8ea36e8ddbd8ba72b8f7755017781/mamaki/genesis.json#L346), which we didn't fix in mamaki. Fortunately aliases aren't used by the statemachine iirc, and are purely syntactic sugar.

We should still be consistent tho, and replace it with an accurate label. I agree with @rootulp and we can rename it to microtia
