### ISSUE TITLE
Keys list problem

### ISSUE THREAD

**Issue by Ivan123-ops** [celestiaorg/celestia-app#448]
## Summary of Bug

When inputing `celestia-appd keys list` command, it gives error 

`migrate err: config.info: key not foundmigrate err: data.info: key not foundmigrate err: keyhash.info: key not foundEnter keyring passphrase:`

So there is no way to see the list of added keys. 

## Version

5.0.2

## Steps to Reproduce

Enter in cli `celestia-appd keys list`

**Comment by rootulp** [comment]
@Ivan123-ops can you please share:
1. Which OS are you running? 
2. Are you able to reproduce this error on https://github.com/celestiaorg/celestia-app/commit/ff2d92a98584b5f3f0fef0bdf595e21fdd808a97 ? 

I was able to repro this error on Ubuntu 20.04 on https://github.com/celestiaorg/celestia-app/commit/c8d7cd166cc063ff54438e1b0f650d935bc65cad but upgrading to  https://github.com/celestiaorg/celestia-app/commit/ff2d92a98584b5f3f0fef0bdf595e21fdd808a97  resolved. See https://github.com/celestiaorg/celestia-app/issues/530#issuecomment-1224996082
