### ISSUE TITLE
Successful MsgPayForData isn't consuming gas on mamaki

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#452]
This successful pay for data transaction didn't consume any gas at all, which is really weird and we need to investigate this further

https://celestia.explorers.guru/transaction/AE50126C7A59A4A1AB5167BA1F9CDEC3D37B55F0F73AA58D05EFFD9683F43101

**Comment by evan-forbes** [comment]
and weirder still, some pay for messages are failing due to an incorrect signature, despite this message passing on integration and unit tests, but it indicates that it is using gas

https://celestia.explorers.guru/transaction/0D98FA208FB10AE404B6D3FA3643C8A69E8A6DB0EECD6592BB859826D3B1BE44

**Comment by liamsi** [comment]
As far as I can tell this does not seem to be PfD sepcific. Here is a simply transfer that did not consume any gas:
https://celestia.explorers.guru/transaction/B935F34B8E0E3F4425F3BC6AAAC13B861B749B289191686BC44E0C92DEDF3CEA

Or, relevant part from `query tx`: 
```
gas_used: "0"
gas_wanted: "0"
```

**Comment by evan-forbes** [comment]
Turns out that gas is being consumed, but its not being reported as the values were not being passed via CheckTx and DeliverTx 

https://github.com/celestiaorg/cosmos-sdk/issues/191
https://github.com/celestiaorg/cosmos-sdk/pull/192

**Comment by evan-forbes** [comment]
instead of pathcing this ourselves in https://github.com/celestiaorg/cosmos-sdk/issues/191
https://github.com/celestiaorg/cosmos-sdk/pull/192, this will be fixed in the next hardfork when we update the cosmos-sdk
