### ISSUE TITLE
Message is included in the block even if PayForData transaction fails

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/celestia-app#456]
Even if submit PFD returns error (signature verification error), message/data is included in the block.

Example:
Failed TX: https://celestia.explorers.guru/transaction/F7DABD37A745A32E63BEBADDEACE62FE9D37D521457B64B973C4F956D463497A
Block with data: https://rpc-mamaki.pops.one/block?height=11482

May be related to: #452 (see: https://github.com/celestiaorg/celestia-app/issues/452#issuecomment-1140052535)

**Comment by evan-forbes** [comment]
due to tendermint's deferred execution mechanism, there isn't actually a way avoid this.

**Comment by evan-forbes** [comment]
we might want to consider also checking the PfD signatures when we call CheckTx on a wirePfD, to make it more difficult for this to happen.

**Comment by evan-forbes** [comment]
closing for now @tzdybal but pls feel free to continue the conversation or reopen if you see fit.
