### ISSUE TITLE
Curling for block at height 1 returns back for height 2

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#477]
## Summary of Bug
```
curl ip:26657/block?height=1
```

Is returning the result for the height=2 instead of 1

## Version
v0.5.2 for app
v1.2.2-tm-v0.35.4 for core
v0.3.0-rc1 for node

## Steps to Reproduce
1. Install [testground](https://docs.testground.ai/v/master/getting-started)
2. Checkout this PR that contains app and celestia nodes (https://github.com/celestiaorg/test-infra/pull/23)
3. Run in 1 terminal `testground daemon`
4. Tun in 2 terminal `testground run composition -f composition.toml --wait`
5. Observe results

Node needs the height=1 block's hash in order to work properly. Unfortunately, it receives the 2nd

full logs: https://gist.github.com/Bidon15/efebf75014e674a9d913b7575ccff695
---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
> Is returning the result for the height=2 instead of 1

how do you know? The shared logs do not say anything is wrong. From the screenshot you shared on slack it seems that the bridge / node software interprets the hash of block 2 as the hash of block 1. Which is a bug in node or even simply in the debug output you are using.

**Comment by Bidon15** [comment]
Closing the bug 😒

**Comment by liamsi** [comment]
bug was here: https://github.com/celestiaorg/test-infra/pull/23#discussion_r892363824
