### ISSUE TITLE
QGB orchestrator signing everything before implementing slashing

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#479]
As discussed in https://github.com/celestiaorg/celestia-app/pull/478#discussion_r893744763_, currently, the QGB orchestrator is implemented to sign attestations up to the last unbonding period. This makes sense when we have slashing, as after the unbonding period, if an orchestrator didn't sign it will already be slashed and no need to sign at that point.

However, before implementing slashing, there is no need to stop up to a certain height, as in testnets, we would want to have most attestations signed anyway.

Proposal: when an orchestrator is started, it goes over all the attestations where it was part of the valset  and signs them (without having to worry about the last unbonding period).

**Comment by SweeXordious** [comment]
@evan-forbes What do you think about this?

**Comment by evan-forbes** [comment]
> when an orchestrator is started, it goes over all the attestations where it was part of the valset and signs them (without having to worry about the last unbonding period).

this seems sane. we definitely don't want people to submit pointless signatures. as a side note, this could actually be implemented in a single transaction with many sdk.Msg, to sort of batch sign.

**Comment by SweeXordious** [comment]
> **without having to worry about the last unbonding period**

Do we want this? I guess we decided in our last call to only sign up to the last unbonding period...
I have a question concerning the unbonding period, is it validator specific or for the whole valset?

**Comment by evan-forbes** [comment]
> I have a question concerning the unbonding period, is it validator specific or for the whole valset?

The whole valset, except if the validator was not part of the valset for the entirety of it

**Comment by SweeXordious** [comment]
Okey cool then. Thanks a lot

**Comment by evan-forbes** [comment]
per sync discussion, this issue can be closed due to moving to v2
