### ISSUE TITLE
Fees: actually enforce deducting those

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#48]
As far as I remember, currently no fees are deducted for PayForMessage. Is that right? Or do we actually make use of the default fee-machanism of the SDK?

**Comment by evan-forbes** [comment]
Currently, we are using the default fee mech in the sdk, and they are optional. If a user includes fees in the tx, this is done using a flag in the cli but can also be done manually when building the tx, then fees are deducted. Nothing is currently enforcing that each transaction has fees, or what the min/max fee should be.

**Comment by liamsi** [comment]
Thanks for the prompt reply @evan-forbes 🙏🏼 

IMO, the most minimal fee-mechanism would be to just enforce that the fees are paid according to the existing SDK logic. IMO, this would be sufficient for an incentivized test-net / maybe for mainnet even?
Changed the title of the issue to reflect this.

I'll create another issue about investigating and implementing fee-burning according to the specs. 

cc @adlerjohn

**Comment by evan-forbes** [comment]
> Currently, we are using the default fee mech in the sdk, and they are optional.

To clarify, the fee is optional in the sense that the gas price can be set to zero, and the default sdk app relies on the block producer to determine if they want to include a transaction for free or not. Gas is metered per byte, but that is not counting the message size, only the size of the actual `SignedTxDataPayForMessage`. We will need to include a way to meter per message, the simplest of which would be to include the size of the message in `SignedTxDataPayForMessage`.

**Comment by evan-forbes** [comment]
to update: we are prioritizing fee deduction for message size for testnet

the size of the data is included in the PFD here 
https://github.com/celestiaorg/celestia-app/blob/d7bb3934e0c13259bf3d666378ea67fda852b6e5/proto/payment/tx.proto#L22

and the size of the data is checked here for honest nodes
https://github.com/celestiaorg/celestia-app/blob/d7bb3934e0c13259bf3d666378ea67fda852b6e5/x/payment/types/wirepayfordata.go#L93-L100

The size of the data is checked by 2/3s of the validators during the message inclusion check, by recalculating the commit of the message included in the block and comparing it to the commitment in the respective PFD.

Block producers can still include data in the block for free by submitting an invalid PFD, the only way around this is to have some form of immediate execution, where we would check that a PFD is valid before including its corresponding data in the block (note: by "some form", I mean the validators don't have to vote on an updated AppHash for that block, they could have some hacky solution where the transactions are executed and the state is saved but isn't applied until the block after or thrown away and recalculated during `Commit`)

cc: @musalbas @liamsi @adlerjohn

**Comment by evan-forbes** [comment]
> Block producers can still include data in the block for free by submitting an invalid PFD...

by invalid, I mean that they can submit a PFD from an account with not enough funds to pay for gas, effectively submitting a PFD for free

**Comment by adlerjohn** [comment]
>  the only way around this is to have some form of immediate execution
> they could have some hacky solution where the transactions are executed and the state is saved but isn't applied until the block after or thrown away and recalculated during Commit

This is generally along the lines of what we had discussed way back when, so nothing new.
