### ISSUE TITLE
Question: State machine panic when querying invalid data

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#483]
Currently, in keepers, we have implementations similar to the following:

```golang
func (k Keeper) GetValsetConfirm(
	ctx sdk.Context,
	nonce uint64,
	validator sdk.AccAddress,
) *types.MsgValsetConfirm {
	store := ctx.KVStore(k.storeKey)
	if err := sdk.VerifyAddressFormat(validator); err != nil {
		ctx.Logger().Error("invalid validator address")
		return nil
	}
	entity := store.Get([]byte(types.GetValsetConfirmKey(nonce, validator)))
	if entity == nil {
		return nil
	}
	confirm := types.MsgValsetConfirm{Nonce: nonce}
	k.cdc.MustUnmarshal(entity, &confirm)    // <-- issue
	return &confirm
}
```

This getter runs the `MustUnmarshal` method which panics in case the deserialization failed. 

Questions: 
- Will this stop the node if it happened? Or, is the panic recovered?
- Does that line assume a correctly marshalled data, thus it will never panic?

**Comment by SweeXordious** [comment]
This is needed for https://github.com/celestiaorg/celestia-app/issues/468#issuecomment-1152955936

**Comment by evan-forbes** [comment]
just to make sure we stay up to date here with our synchronous discussions on the topic, where exactly did we land?

ideally we use universal nonces everything including in queries, and if necessary we throw an error. In the above instance, perhaps we could not use `MustMarshal` and instead catch the error?

**Comment by SweeXordious** [comment]
yes, 100%, that's the plan. I'm just keeping this issue open to also check this. We can close it tho.

**Comment by evan-forbes** [comment]
we can definitely keep it open until things are handled, I just forgot to update this issue after we talked, and wanted to make sure we wrote it down

**Comment by evan-forbes** [comment]
closing since #657
