### ISSUE TITLE
QGB E2E scripts retry starting nodes

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#504]
When starting E2E network, the scripts used to boot up the orchestrator, relayer and nodes can fail for various reasons. These failures are sometimes due to an orchestrator/relayer starting before the corresponding node starts. 
Thus, we need to include a retry mechanism in the bash scripts that retries a number of times in case of failures.
This would make the tests less flaky.

**Comment by evan-forbes** [comment]
per sync discussion, this issue is outdated due to the move to QGB 2.0
