### ISSUE TITLE
QGB use interface for Valset/DataCommitment confirms

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#505]
As done in https://github.com/celestiaorg/celestia-app/issues/468#issuecomment-1156887715, we can go  for replacing `ValsetConfirm`s and `DataCommitmentConfirm`s with an `AttestationConfirm`  interface which would simplify the implementation and remove unnecessary redundant code.

**Comment by evan-forbes** [comment]
was this completed?

**Comment by SweeXordious** [comment]
I guess this is no longer relevant as per: https://github.com/celestiaorg/celestia-app/blob/main/docs/architecture/adr-005-qgb-reduce-state-usage.md. What do you think?

**Comment by SweeXordious** [comment]
We can just close it as no longer relevant, no?

**Comment by evan-forbes** [comment]
:+1:
