### ISSUE TITLE
QGB import Any type correctly

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#507]
Currently, in the QGB, we're defining the following query:
https://github.com/celestiaorg/celestia-app/blob/adfdc8574b960cf7fded64722cc0afa887456353/proto/qgb/query.proto#L103-L109

The problem is that the protobuf generated code type expects an implementation of `Any` under the `celestia-app/codec/types`. 
As a simple hack, we're changing the import to use the cosmos-sdk implementation of `Any`:
https://github.com/celestiaorg/celestia-app/blob/adfdc8574b960cf7fded64722cc0afa887456353/x/qgb/types/query.pb.go#L9

However,  we need to find a way to specify that dynamically so that we don't have to copy all the code from cosmos-sdk repo, or make the change manually every time we generate code.

**Comment by rootulp** [comment]
> However, we need to find a way to specify that dynamically so that we don't have to copy all the code from cosmos-sdk repo, or make the change manually every time we generate code.

Do we want a new issue for this? I couldn't find one in https://github.com/celestiaorg/celestia-app/issues/301

If we do create a new issue, then we may want to include a step to delete: https://github.com/celestiaorg/celestia-app/pull/742/files#diff-63113d53e02a4e334ffa1a1ba0c308329c7acd431153571a2c02ce9268af5816R28-R32

**Comment by SweeXordious** [comment]
Sure sounds good. want me to create the issue? or you wanna do it yourself?

**Comment by rootulp** [comment]
Just created https://github.com/celestiaorg/celestia-app/issues/744 and added it as a Nice to have, high priority in the tracking issue.

**Comment by SweeXordious** [comment]
Thanks a lot
