### ISSUE TITLE
testing: Add integration test for tx prioritization

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#513]
When we upgraded to cosmos-sdk v0.46, we gain the ability prioritized txs in the mempool. Since this feature is so critical, we need to test this in an integration test.

**Comment by rootulp** [comment]
Note from synchronous discussion @evan-forbes @musalbas :

- We may want a separate test (not end-to-end) on testground or our testnet that spams transactions and verifies transaction prioritization

**Comment by evan-forbes** [comment]
[comment](https://github.com/celestiaorg/celestia-app/issues/590#issuecomment-1282974687)

[comment](https://github.com/tendermint/tendermint/issues/9388#issuecomment-1247811007)

as discussed in the linked comments, it looks like we should just just the v0 mempool and sort the tx by fee ourselves, or wait and use the default [app side mempool](https://github.com/cosmos/cosmos-sdk/pull/13262) coming in v0.47.0 of the sdk

**Comment by evan-forbes** [comment]
we should still create a test to ensure that we don't accidentally break fee prioritization by default.

**Comment by evan-forbes** [comment]
to update this, we are just planning on using the v1 mempool now. It will not be deprecated until at least v0.38.0 of tendermint. We should have a custom mempool by then anyway. 

We can leave this open as its a nice to have, but having a test for the prioritized mempool is a bit redundant so its not a priority
