### ISSUE TITLE
QGB e2e use signaling channel to notify

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#522]
Currently, the QGB is using context extensively to communicate. This can be improved via the use of a signaling channel. 
This PR is an example of how to do it: https://github.com/celestiaorg/celestia-app/pull/512 in here:
https://github.com/celestiaorg/celestia-app/blob/7169d9a9aff9a3460454e1697afc385bf23f65f9/x/qgb/orchestrator/orchestrator_command.go#L77-L86

**Comment by evan-forbes** [comment]
> Currently, the QGB is using context extensively to communicate. 

mind elaborating on this a bit? is this referencing our reliance on ctx.Done()?

**Comment by SweeXordious** [comment]
Yes, exactly. We have multiple functions waiting for a signal to stop processing. Currently, we're forced to use context timeouts and cancells in a complex way to notify all threads. However, we can use an easier mechanism using a special notify channel that can be used to trap any error or exit signal and notify everything to stop.
