### ISSUE TITLE
Default-backend keys not added properly

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#530]
## Summary of Bug

Adding a key with the default backend doesn't actually add it.

## Version

Commit: c8d7cd166cc063ff54438e1b0f650d935bc65cad

OS: Ubuntu 20.04

## Steps to Reproduce

```console
$ celestia-appd keys add foo
$ celestia-appd keys list
[]

```

**Comment by adlerjohn** [comment]
Yes. Additionally, running

```console
$ celestia-appd keys delete foo 
Error: foo.info: key not found
```

**Comment by liamsi** [comment]
By explicitly stating the backend I mean using `--keyring-backend os`. Does it still show "key not found in that case?

**Comment by adlerjohn** [comment]
> Yes.

Yes.

**Comment by rootulp** [comment]
OS | c8d7cd166cc063ff54438e1b0f650d935bc65cad | ff2d92a98584b5f3f0fef0bdf595e21fdd808a97
--- | --- | ---
macOS Monterey version 12.4 | ✅  | ✅ 
Ubuntu 22.04 x64 |  ✅  | ✅ 
Ubuntu 20.04 x64 | ❌  | ✅ 

✅: works as expected
❌: does not work 

Nothing in Cosmos SDK [docs](https://docs.cosmos.network/v0.46/run-node/keyring.html) say that Ubuntu 20.4 isn't supported.
 
## Desired Behavior (output from macOS)

```shell
$ celestia-appd keys add foo

- address: celestia1k4k3d2m2k7gckz2z75czgdhnyqsgauzdf9c9z5
  name: foo
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A7bP2v+7zMC1bPzZEYIpOFsShQBdOdGWkYONPs+TTY7l"}'
  type: local

$ celestia-appd keys list
- address: celestia1k4k3d2m2k7gckz2z75czgdhnyqsgauzdf9c9z5
  name: foo
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A7bP2v+7zMC1bPzZEYIpOFsShQBdOdGWkYONPs+TTY7l"}'
  type: local
```

## Actual Behavior (output from c8d7cd166cc063ff54438e1b0f650d935bc65cad on Ubuntu 20.04)

```shell
root@rootulp-ubuntu-20:~/celestia-app# celestia-appd keys list
migrate err: config.info: key not foundmigrate err: data.info: key not foundError: read /root/.celestia-app/config: is a directory

root@rootulp-ubuntu-20:~/celestia-app# celestia-appd keys add foo
Enter keyring passphrase:
Re-enter keyring passphrase:

- address: celestia10f5556j9swam8tj8d2ugfw95vf9e3jve5z0z9s
  name: foo
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A1aQvKbQiyNV0Y6b3N/bsuGrxGPe8iZFhoLq6ovj7cKW"}'
  type: local

root@rootulp-ubuntu-20:~/celestia-app# celestia-appd keys list
migrate err: config.info: key not foundmigrate err: data.info: key not foundEnter keyring passphrase:
migrate err: keyhash.info: key not foundError: read /root/.celestia-app/config: is a directory
```

**Comment by rootulp** [comment]
- https://github.com/celestiaorg/celestia-app/commit/c8d7cd166cc063ff54438e1b0f650d935bc65cad is based on https://github.com/celestiaorg/cosmos-sdk/releases/tag/v1.1.1-sdk-v0.46.0
- https://github.com/celestiaorg/celestia-app/commit/ff2d92a98584b5f3f0fef0bdf595e21fdd808a97 is based on https://github.com/celestiaorg/cosmos-sdk/releases/tag/v1.2.0-sdk-v0.46.0

It's not clear to me which change fixed this particular issue but these look relevant:
- https://github.com/cosmos/cosmos-sdk/issues/12093
- https://github.com/cosmos/cosmos-sdk/pull/12122 

even though they were included in https://github.com/cosmos/cosmos-sdk/blob/main/CHANGELOG.md#v0452---2022-04-05 so both these commits should have this fix.

@adlerjohn are you able to repro on https://github.com/celestiaorg/celestia-app/commit/ff2d92a98584b5f3f0fef0bdf595e21fdd808a97 ? If not, is it safe to resolve this issue?

**Comment by adlerjohn** [comment]
Amazing investiation
