### ISSUE TITLE
Decide on using gofumpt and adding a CI job check for  it

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#534]
> Yeah I agree with John about using CI. gofumpt is backwards compatible and doesn't do any harm, but whatever linter we choose, we should be consistent instead of one off fixes. 
>
> I'm also in favor of of adding stricter restrictions to golangci, as that's what tendermint and the sdk (and the app currently) use, so that's one less tool contributors have to install.
>
> I think we have an issue for that, so I'm okay with merging this as is, provided we don't make this a habit
>
_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/issues/519#issuecomment-1179872937_

**Comment by evan-forbes** [comment]
ideally we will be able to do this before we merge the qgb, so that we don't have a bunch of non-qgb-related conflicts in the rest of the repo
