### ISSUE TITLE
Repo and command-line tool name

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#54]
Currently, the binary that runs lazyledger is called `lazyledger-appd`. We should probably rename this to `lazyledger` or `lazyledgerd`?

Also, the repo name could just be `lazyledger` or `lazyledger-rsm` (replicated state machine) or some other name we should settle on.

There was also the suggestion to rename the tendermint binaries in lazyledger-core. IMO, their name can just stay the same. The consensus is in fact tendermint consensus and the user-facing binaries are in here.

Also, another name to consider is the one chosen for modules (currently there is only one): https://github.com/lazyledger/lazyledger-app/tree/master/x/lazyledgerapp

cc @musalbas @adlerjohn

**Comment by adlerjohn** [comment]
I like the `d` at the end fwiw

**Comment by marbar3778** [comment]
def a fan of naming the repo merely Celestia and the executable celestiad

**Comment by musalbas** [comment]
I think celestia-node should be the real celestiad

**Comment by marbar3778** [comment]
makes sense. is there a plan to merge both executables?

**Comment by liamsi** [comment]
> I think celestia-node should be the real celestiad

And what should we call celestia-app then?

>  is there a plan to merge both executables?

maybe: 
https://github.com/celestiaorg/celestia-node/issues/275

**Comment by marbar3778** [comment]
keeping them as two different repos but one executable is possible. It would be this pr in the other repo then the app commands could be under celestiad app and celestiad node for node. Would simplify having multiple locations to download things.

**Comment by liamsi** [comment]
cc @Wondertan @renaynay

**Comment by renaynay** [comment]
can't we call celestia app just `app`? 100% let's keep the repos separate, but fine with making it one executable in the future.
