### ISSUE TITLE
QGB implement synchronous orchestrator

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#546]
Currently, the QGB is using multiple go routines to enqueue attestations and process them. We can further simplify this by following a design similar to the relayer and simply the codebase further.
 
_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/526#discussion_r919984921_

**Comment by evan-forbes** [comment]
per sync discussion, this issue can be closed due to moving to v2
