### ISSUE TITLE
QGB investigate indexing attestation confirms in multiple ways

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#552]
As discussed https://github.com/celestiaorg/celestia-app/pull/550#discussion_r926474209, we can investigate the use of multiple keys to index valset/data commitment confirms in the store so that we don't have to iterate over all of it to find elements.

**Comment by evan-forbes** [comment]
if there are any obvious improvements that we can do, we should do those, but if the changes are larger, we might just want to wait for the even less stateful QGB 2.0

**Comment by evan-forbes** [comment]
can close since ADR005 #657
