### ISSUE TITLE
celestia-appd version doesn't display version

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#581]
### Summary of Bug

Originally reported by @sysrex in Slack. Reproed by @Wondertan 

### Version

[v0.6.0](https://github.com/celestiaorg/celestia-app/releases/tag/v0.6.0)

### Steps to Reproduce

> I did not clone and checkout, I strictly downloaded the release and built from there

It sounds like `make build` was run and `make install` was not

**Comment by Wondertan** [comment]
It's reproducible for me if the binary is built via plain `go build`. However, that is not really an issue. In the celestia-node the sam would happen if one builds a node without `make build`

**Comment by sysrex** [comment]
Whenever you build tag v0.6.0 with just `make build` the version returns empty, this was tested on several debian-based distros and mac m1 platforms.

**Comment by rootulp** [comment]
Reproduced on an M1 Mac with:

```shell
cd celestia-app
git checkout v0.6.0
make build
./build/celestia-appd version 
```
Observe no version displayed 

## Screenshot
<img width="524" alt="Screen Shot 2022-07-29 at 9 34 49 AM" src="https://user-images.githubusercontent.com/3699047/181771604-cdbeafdb-6fb2-4f51-aff4-a605da7ac5e5.png">

**Comment by rootulp** [comment]
https://github.com/celestiaorg/celestia-app/pull/360 fixed this for `make install`
https://github.com/celestiaorg/celestia-app/pull/582 will fix this for `make build`
