### ISSUE TITLE
config: Review and define default params for *.toml files

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#585]
Introduction ✌🏻
---
Found during testing with testground, we haven't predefined what default values are specific and crucial for celestia-app validators
In order to fix this, we need to review each section of the `*.toml` and conclude with what value should we opt per each setting. 

As an example, `rpc.timeout_broadcast_tx_commit` located in `config.toml` is equal to 10 seconds, which is fine considering that `consensus.timeout_commit` in vanilla tendermint is 6 seconds. 

However, this(10 seconds timeout for tx broadcast) is not ok for `celestia-app` as we have timeout commit of 30 seconds, hence the user will usually see errors like :
`RPC error -32603 - Internal error: timed out waiting for tx to be included in a block`

What files 🧐 
---
There are 3 files that needs our rigorous attention: 

1. `config.toml` -> this one is the heaviest of all 3, so breaking it down to smaller issues makes more sense, imho 
2. `app.toml`
3. `client.toml`

Ref: #413

**Comment by evan-forbes** [comment]
while most of these changes could be done by changing the defaults in tendermint, this will cause many tests to break, which will increase the diff between core and tendermint. We might want to get a bit more creative in how we change them. We've changed defaults previously by intercepting the config when it is being loaded by the cli, and then making the changes there. While that solution is not as clean, it does avoid creating a larger diff.

**Comment by evan-forbes** [comment]
closing this issue as it is redundant to the rest of the parameter picking issues, which are more specific, pls feel free to reopen if we think otherwise
