### ISSUE TITLE
Recover from the panic when pushing a message with namespace `consts.ParitySharesNamespaceID`

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#596]
### Summary of Bug

Currently, if we manually add a message with namespace ID: `consts.ParitySharesNamespaceID` to a block and propagate it, the application panics during `ProcessProposal` as this latter is higher than the maximum allowed namespace.
This panic should be recovered from, as a malicious block proposer could propose an invalid block containing such a message, and halt the chain.

Panic message:
```
panic: pushed data has to be lexicographically ordered by namespace IDs: last namespace: ffffffffffffffff, pushed: fffffffffffffffe [recovered]
	panic: pushed data has to be lexicographically ordered by namespace IDs: last namespace: ffffffffffffffff, pushed: fffffffffffffffe
```

### Version

f5a07435f5969bb558b72f4189611db9ff1eefad

### Steps to Reproduce

Uncomment the following test:
https://github.com/celestiaorg/celestia-app/pull/592/files#r938092524

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
I think #595 covers this and is a tad bit more general? wdyt?

**Comment by evan-forbes** [comment]
also, what if the parity namespace is placed exactly at the last share of the original square, won't those shares still be in order and therefore we won't see a panic?

**Comment by SweeXordious** [comment]
That is actually true. In fact, I was checking process proposal and I guess even for a block which has a message whose namespace is of the parity shares, the node will not panic, because, it will be caught before.
Currently, process proposal starts by sanitizing the messages. And then, it proceeds to calculate the data availability root. This latter is the one that panics when receiving a message that has a wrong namespace. But, in our case, it will never be reached.

**Comment by evan-forbes** [comment]
yeah, that's a great point, after #592, this specific panic isn't actually reachable.
