### ISSUE TITLE
Implement tooling for creating QGB compatible inclusion proofs to data

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#609]
We need to provide tooling for creating inclusion proofs that are ready to be verified by the qgb contacts. While at first we just write this in go, we might also want to consider writing this logic in other languages as well in order to cater to many projects.

**Comment by SweeXordious** [comment]
Closing as currently we have the `verify` command that creates the proofs and sends them to a QGB contract for verification. That code can be used to create the proofs.
If there are other needs, then we will open new issues with more specific tasks.
