### ISSUE TITLE
Refactor logs to take up fewer lines

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#610]
### Summary

Multi-line log lines are difficult to read.

### Problem Definition

> as a side note, all of the logs there take up so many lines of code that is makes the function difficult to read. If we get a tad creative, we should be to refactor all of those lines into much few lines, while also including the proposer in the error message.

See https://github.com/celestiaorg/celestia-app/blob/main/app/process_proposal.go

Originally reported in https://github.com/celestiaorg/celestia-core/pull/827#pullrequestreview-1070366326

### Proposal

One approach I can think of (but don't advocate) is extracting functions per log. In other words:

### Old
```go
		if err := types.ValidateMessageNamespaceID(msg.NamespaceId); err != nil {
			app.Logger().Error(
				rejectedPropBlockLog,
				"reason",
				"found a message that uses an invalid namespace id",
				"error",
				err.Error(),
			)
			return abci.ResponseProcessProposal{
				Result: abci.ResponseProcessProposal_REJECT,
			}
		}
```

### New

```go
		if err := types.ValidateMessageNamespaceID(msg.NamespaceId); err != nil {
			logInvalidNamespaceId(app, err)
			return abci.ResponseProcessProposal{
				Result: abci.ResponseProcessProposal_REJECT,
			}
		}
...

func logInvalidNamespaceID(app *App, err error) {
	app.Logger().Error(
		rejectedPropBlockLog,
		"reason",
		"found a message that uses an invalid namespace id",
		"error",
		err.Error(),
	)
}
```

but this much indirection seems unnecessary. Any other ideas @evan-forbes ?

### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
perhaps
```go
func logInvalidNamespaceID(l Logger, h Header, msg string, err error) {
	l.Error(
		rejectedPropBlockLog,
		"reason",
		msg,
		"error",
		err.Error(),
		"proposer",
		h.ProposerAddress,
	)
}
```
or perhaps we could just put the "reason" as constants so they take up less space and we can fit more on one line
