### ISSUE TITLE
Use nmt wrapper when creating commitments for PayForData transactions

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#617]
currently, we're not using the nmt wrapper when generating commitments for pfd transactions. This is problematic because the wrapper is used when creating the data commitments, so when we modify the message inclusion check to actually use subtree roots, it won't be able to find them.

Also, we need the payment module to be more or less stable so that the audit process can begin.

**Comment by distractedm1nd** [comment]
An ErrInvalidShareCommit (11116) is thrown occasionally when a node running an earlier app version (v0.7.0-rc-1) submits a pfd to an app with #618.
