### ISSUE TITLE
New share format

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#619]
### Summary

We're considering changing the format of a share. See: https://celestiaorg.github.io/celestia-specs/latest/specs/data_structures.html#share

### Problem Definition

// TODO

### Proposal

Add the following fields to share:
- share length
- start bit (that's on if the share is the start of a message)
- version byte

This likely needs:
1. An ADR in this repo
2. A PR to update the spec
3. A PR to update the all share logic in this repo

Questions:
1. Does this have downstream consequences in celestia-node?

### For Admin Use

- [X] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
closing in favor of https://github.com/celestiaorg/celestia-core/issues/839
