### ISSUE TITLE
Broken docker build ci

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#626]
we recently moved the dockerfile in #625 and I think it might have broken the build 

https://github.com/celestiaorg/celestia-app/runs/7884067922?check_suite_focus=true

**Comment by rootulp** [comment]
Thanks for flagging! The error message makes me think this is a transient network issue

```
#1 32.10 fatal: unable to access 'https://github.com/celestiaorg/celestia-app.git/': The requested URL returned error: 500
------
error: failed to solve: failed to read dockerfile: failed to fetch remote https://github.com/celestiaorg/celestia-app.git: exit status 128
Error: buildx failed with: error: failed to solve: failed to read dockerfile: failed to fetch remote https://github.com/celestiaorg/celestia-app.git: exit status 128
```

so retrying the failed job.
Ref: https://github.com/celestiaorg/celestia-app/runs/7884067922?check_suite_focus=true#step:8:134

**Comment by rootulp** [comment]
Closing as won't fix b/c transient network issue. Will re-open and invest time in fixing if reoccurs.

**Comment by evan-forbes** [comment]
thanks! yeah sorry my smooth brain should have retried it first!
