### ISSUE TITLE
Recreate the manual testing of share encoding

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#630]
Why is this test commented?

_Originally posted by @SweeXordious in https://github.com/celestiaorg/celestia-app/pull/627#discussion_r948585018_

When moving share encoding and decoding logic to the app, we had to comment out a test because it was designed around some tendermint logic, like creating votes and using methods instead of functions to encode shares. We should recreate this test by changing those requirements.

**Comment by evan-forbes** [comment]
we have since added quite a few manual tests, and I'm not sure of the value that we would get from this anymore. I guess the manual tests would act as a forcing function to notify reviewers if anything changes the encoding, but that's about it.

Leaving this as a stretch issue for the epic, but I am also okay with closing this as unplanned. Will defer to @rootulp

**Comment by rootulp** [comment]
This issue refers to the `TestMakeShares` test which was commented out and eventually removed. It appears to have tested

```
// 			got := tt.args.data.SplitIntoShares()
```

which no longer exists but it resembles https://github.com/celestiaorg/celestia-app/blob/0b85a0fabf07ff02bf03e9205638c6cd5462afba/pkg/shares/share_splitting.go#L25 which doesn't have unit tests so I think we can update this issue to add unit tests to that function.

**Comment by rootulp** [comment]
That file has been migrated to the go-square repo: https://github.com/celestiaorg/go-square/blob/main/shares/share_splitting.go

SplitTxs has tests but SplitBlobs doesn't: https://github.com/celestiaorg/go-square/blob/main/shares/share_splitting_test.go
