### ISSUE TITLE
EPIC: Add an official spec for the app

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#650]
While archived, the [specs](https://github.com/celestiaorg/celestia-specs) contain a lot of really important and critical designs that are effectively cannon. We should move as much as we can over from them, while refactoring, modifying, and updating to match the current implementation.

some special love is needed for our the encoding section, as its much more difficult to decipher the share splitting/merging implementation

- [x] #688
- [x] #727
- [x] #728
- [x] #729
- [x] #730
- [x] #732
- [x] #733
- [x] #792
- [x] #866

# Pure specs

- [ ] #735
- [ ] #736
- [ ] #737
- [x] #743
- [x] #751
- [x] #784
- [x] #883
- [x] #995
- [ ] #1007
- [x] #1063
- [ ] #1066
- [x] #1067
- [x] #1349
- [x] #1435
- [x] #1437
- [x] #1440 
- [x] #1453
- [ ] #1459
- [x] #1488
- [x] #1532

# Needs implementation

- [x] #431
- [x] #731
- [x] #734
- [x] #739
- [ ] #795 (blocked by #835)
- [x] #940
- [x] #1487

**Comment by rootulp** [comment]
One alternative approach is to unarchive the specs repo and remove the outdated specs.

**Comment by adlerjohn** [comment]
Per-repo specs will be easier to maintain, as each team can update spec in tandem with implementation changes.

**Comment by evan-forbes** [comment]
I'm going to use this comment to continually add reminders as I think of them. Others should feel free to edit this comment or post their own comment as well.

we introduced a new validity rule here for `MsgPayForData` and `MsgWirePayForData`.
https://github.com/celestiaorg/celestia-app/pull/666

**Comment by rootulp** [comment]
Relevant: https://github.com/celestiaorg/celestia-specs/issues/213

**Comment by evan-forbes** [comment]
nice!! I didn't see that

**Comment by adlerjohn** [comment]
Can we turn this into a tracking issues @evan-forbes

**Comment by rootulp** [comment]
The **Pure Specs** issues are blocking the merge of `specs-staging` into `main`.

**Comment by evan-forbes** [comment]
referencing a comment with changes that are likely a good idea to include above 

https://github.com/celestiaorg/celestia-app/pull/796#issuecomment-1467871463

**Comment by evan-forbes** [comment]
here's an list from a recent sync on overhauling the spec. Some of these are duplicates from the main comment in this issue :pray: 

- [ ] #1067
- [ ] x/paramfilter
- [ ] #1854 
- [ ] #1855
- [ ] #1267
- [ ] x/upgrade
- [ ] x/qgb
- [ ] #743 
- [ ] #1063

**Comment by evan-forbes** [comment]
are there still issues that we think are worth blocking here or can we finally close this issue? 

imo I think if we want to do another round of spec refactors/updates/additions we should reevaluate and create another epic

I'll close this issue without further feedback at the end of the week
