### ISSUE TITLE
Celestia PoA testnet proposal

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#652]
## Summary

At the current stage of development, we will need to deploy a PoA Celestia testnet that follows the fast-paced development environment of Celestia-app and, optionally, the Quantum Gravity Bridge.
This testnet will be long-lived and will enable external teams to tinker with the latest changes and have a taste of what the upcoming stable upgrades would look like.

## Detailed proposal

Currently, we have a public testnet called Mamaki. It is an upgraded version of the now-retired Devnet, featuring many new enhancements and bug fixes, more details in [here](https://blog.celestia.org/celestia-testnet-introduces-alpha-data-availability-api). This latter focuses more on stability, reliability and provides external projects with a stable environment they can use to build their applications.

The proposed PoA chain will take all the features proposed by Mamaki, and extend them to include all the latest developments. This means that it will be upgraded in a faster rate, hard forked regularly and more prone to bugs. Thus, it is more suitable for experimentation and testing.

For the validator set, it will most likely be internal to avoid the overhead of coordinating hard forks and protocol upgrades. However, we will provide publicly exposed RPCs, which can be used by the external projects for experimentation. 

#### Optional : Quantum Gravity Bridge

We can think of deploying the [Quantum Gravity Bridge](https://blog.celestia.org/celestiums/) v1.0 on an EVM testnet and relay attestations from the proposed PoA testnet. This means that validators will need to run an extra binary called the orchestrator. This latter will sign attestations that will later be relayed to the target EVM testnets.

## Action items

- [ ] We still need to decide on the parameters used in this chain such as, block time, block size, etc.
- [ ] We will need to prepare automated scripts to simplify the tasks https://github.com/celestiaorg/celestia-app/issues/653.

Credits to @evan-forbes.

**Comment by evan-forbes** [comment]
one of the goals (possibly done later) is having deep introspection into what happened to the nodes on the network. We might even want to go beyond the metrics typically logged via prometheus to test for specific things. Such as logging all rejected proposal blocks and the data that composes them.

**Comment by evan-forbes** [comment]
can this be closed? if not it might need to go in a different repo unless we plan on keeping the infra to spin up robusta/arabica here

**Comment by SweeXordious** [comment]
we can close it, thanks for reminding me
