### ISSUE TITLE
Automated deployment scripts for testnets

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#653]
As mentioned in https://github.com/celestiaorg/celestia-app/issues/652, we will need to create deployment scripts to ease the process of deploying a new tesnet and forking it.
These can be written in Ansible, Terraform, or other similar technologies.

**Comment by evan-forbes** [comment]
I believe this is already completed @SweeXordious ? can we link them here?

**Comment by SweeXordious** [comment]
They are still in a private repository... not sure when we should make them public or if @sysrex will prefer to share the scripts he used instead, as what I currently have is the foundations he based his work on

**Comment by evan-forbes** [comment]
any update to this, can we close?

**Comment by SweeXordious** [comment]
Yes
