### ISSUE TITLE
Investigate and finalize resource pricing 

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#658]
We need to investigate and decide on resource pricing. While we should easily be able to change the default gas configs found in tendermint and the sdk, its unclear how specific we can get as to adding multipliers to specific types of sdk txs.

**Comment by liamsi** [comment]
My understanding is that for PayForData we want to measure account for the bytes but ideally we also want to add a constant cost per PfD s.t. batching is encouraged in the future. I do think this is possible and not difficult in the SDK.

For the other Txs types (sdk messages) I guess we rather want clarity on how exactly they are priced and if we want to change any of that default behaviour? One message type that comes to mind are the IBC related txs (so this issue/comment is kinda related here: https://github.com/celestiaorg/celestia-app/issues/235#issuecomment-1190439900).

**Comment by evan-forbes** [comment]
The goal of this issue to is to document the formula used for each transaction type, so that we have a concrete understanding of how gas is deducted.

**Comment by evan-forbes** [comment]
in #1029 , we're creating a script to run standard cosmos-sdk transactions on an inprocess network that has the ability to change genesis params and monitor gas. This should help us investigate gas params.

**Comment by evan-forbes** [comment]
listing this as incentivized testnet stretch milestone, as we can change parameters and add docs at any time after the feature freeze without breaking anything. We also have a good idea of how much gas roughly a PFB takes up relative to other tx types, and we have code to trace the gas consumption of any transaction in any scenario should we need more precise data for a given situation.

**Comment by evan-forbes** [comment]
referencing a comment where we discuss the gas costs of IBC. Notably, following the defaults of IBC, we are not charging gas per signature verified when updating the client.

https://github.com/celestiaorg/celestia-app/issues/1125#issuecomment-1354812142

**Comment by evan-forbes** [comment]
can close imo since we have the above analysis and have set the default min gas price to .1utia
