### ISSUE TITLE
Wrong bech32 format with a newly  generated wallet

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-app#678]
### Summary of Bug

so i have a 2nd user now with wrong bech32 format error, which in the first case i thought its because a user tried to use his old wallet address, but it seems its not the case, see the info:

```
root@vmi561079:~/celestia-app# celestia-appd keys add secondary_wallet
root@vmi561079:~/celestia-app# celestia-appd version
0.6.0
root@vmi561079:~/celestia-app# celestia-appd tx staking delegate celestiavaloper1q3v5cugc8cdpud87u4zwy0a74uxkk6u43cv6hd 500000utia  --from=celestia1zx6ctp0lk4u3r6r0yxnmcyrcwyapfr4gp3la5k --chain-id=mamaki --fees 200utia --keyring-backend test
**Error: decoding bech32 failed: invalid checksum (expected q4gx4p got 3cv6hd)**
root@vmi561079:~/celestia-app#
```

note that the exact same message appeared in the other case too, and i saw one other in russian channel: **(expected q4gx4p got 3cv6hd)**

For the first case i run into, asking the user to import wallet with seed seems to have worked, but that was when i thought he wasnt using a new address, so not sure how this can really happen.

### Version

0.6.0

### Steps to Reproduce

1. install 0.6.0
2. create wallet
3. try to delegate

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
I can't find `celestiavaloper1q3v5cugc8cdpud87u4zwy0a74uxkk6u43cv6hd` on https://celestia.explorers.guru/ so I don't think it is a valid validator address.

I did find `celestiavaloper1q3v5cugc8cdpud87u4zwy0a74uxkk6u4q4gx4p` here: https://celestia.explorers.guru/validator/celestiavaloper1q3v5cugc8cdpud87u4zwy0a74uxkk6u4q4gx4p

Given the prefix of the address is the same, I expect this is a copy + paste error and the user intended on using the latter address.

**Comment by rootulp** [comment]
Based on [Discord](https://discord.com/channels/638338779505229824/920642717057421393/1014657759507128410) I think the user intended on delegating to Nodes.Guru. Based on https://celestia.explorers.guru/validator/celestiavaloper1kg5njpnn494gnek8p7ug6juqrzwq3c3gxrdj5s I think they can try delegating to the address `celestiavaloper1kg5njpnn494gnek8p7ug6juqrzwq3c3gxrdj5s`.

**Comment by rootulp** [comment]
Resolved over Discord, this issue was user error.
