### ISSUE TITLE
Limit validators' set for the PoA network

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#685]
As per discussions with the leadership team, we want to limit the validator set to 4 
This can be done in the genesis.json file and I assume that we are hardcoding it for deployment

For the beginning, we assign all tokens to 1 account/validator

Ref: 

- https://github.com/celestiaorg/networks/pull/49
- https://github.com/celestiaorg/celestia-app/issues/653
- https://github.com/celestiaorg/celestia-app/issues/652
- https://github.com/celestiaorg/devops/issues/33

**Comment by adlerjohn** [comment]
Is this being tracked for implementation @evan-forbes?

**Comment by evan-forbes** [comment]
it is not currently, but we can in #514  

Its unclear to me what needs to be done here. One way this can be handled by created a new stake denom, different from the token used to pay fees, and giving some tokens only to that to predetermined account/gentx accounts. Do we want a specific go script just for that, or will we do that by hand?

**Comment by evan-forbes** [comment]
closing this, as this should likely just be done using a config.

pls reopen if this is not the case
