### ISSUE TITLE
Create an API for calculating the number bytes and shares used by compact and sparse data

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#700]
As pointed out in this [comment](https://github.com/celestiaorg/celestia-app/pull/692#discussion_r967369561) and this [comment](https://github.com/celestiaorg/celestia-app/pull/692#discussion_r967387967), it will be easier to maintain and modify share encoding code if we also have a canonical API for calculating the number bytes and shares that compact and sparse share use. There are many different uses of this estimation logic, so getting a perfect API or modifying the existing code to use such an API could take a few PRs. We should track them here.

**Comment by rootulp** [comment]
We now have the following exported functions which handle the number of shares usecase: 

https://github.com/celestiaorg/celestia-app/blob/0b447adf776689cc8f14823c6ef925b8f8249b5a/pkg/shares/share_sequence.go#L101-L103 https://github.com/celestiaorg/celestia-app/blob/0b447adf776689cc8f14823c6ef925b8f8249b5a/pkg/shares/share_sequence.go#L80-L83

I don't see an immediate need for a separate API that returns number of bytes but it would be easy to implement (number of shares needed * share size) so proposal to mark this as resolved for now? @evan-forbes
