### ISSUE TITLE
Increase share size to 512 bytes

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#711]
I like big blocks and I cannot lie.

Change `ShareSize` to `512`: https://github.com/celestiaorg/celestia-core/blob/c193de698f889a3c78565ac4a73899326a23d544/pkg/consts/consts.go#L15

This will also require a change to the reserved bytes to `2`: https://github.com/celestiaorg/celestia-core/blob/c193de698f889a3c78565ac4a73899326a23d544/pkg/consts/consts.go#L21

**Comment by rootulp** [comment]
We want to do this as a fast follow after https://github.com/celestiaorg/celestia-app/issues/659

**Comment by rootulp** [comment]
Based on synchronous discussion, this issue needs investigation to determine what the share size should be.

**Comment by evan-forbes** [comment]
to help figure out what breaks, we are doing https://github.com/celestiaorg/celestia-app/issues/825 first, which could potentially be merged and close this issue

**Comment by musalbas** [comment]
| ODS | 256 byte shares | 512 byte shares | 1024 byte shares |
| - | - | - | - |
| 4 | 53 MB/s | 95 MB/s | 169 MB/s
| 8 | 116 MB/s | 203 MB/s | 297 MB/s
| 16 | 208 MB/s | 367 MB/s | 540 MB/s
| 32 | 265 MB/s | 478 MB/s | 697 MB/s
| 64 | 300 MB/s | 540 MB/s | 745 MB/s
| 128 | 305 MB/s | 534 MB/s | 695 MB/s
| 256 | 293 MB/s | 496 MB/s | 634 MB/s
| 512 | 276 MB/s | 458 MB/s | 612 MB/s

**Comment by rootulp** [comment]
https://github.com/celestiaorg/celestia-app/pull/850 merged so this issue seems close-able. In the spirit of:

> I like big blocks and I cannot lie.

if we can increase share size to 1024 bytes then can we please create a new issue to tackle that?
