### ISSUE TITLE
Define a `ParseShares` API

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#723]
## Context

celestia-node currently parses shares depending on the type of share (see [here](https://github.com/celestiaorg/celestia-node/blob/d051a94bce1cf8a6b72be03a9484abdb9a6983a3/service/share/share_test.go#L264)). Universal share encoding should enable us to expose one API where any type of share can be parsed. As a result, it may be possible to stop exporting 
https://github.com/celestiaorg/celestia-app/blob/f67bb6ba30e1d4886c5248efef12df5a7b6d5173/pkg/shares/share_merging.go#L125

https://github.com/celestiaorg/celestia-app/blob/f67bb6ba30e1d4886c5248efef12df5a7b6d5173/pkg/shares/share_merging.go#L78

https://github.com/celestiaorg/celestia-app/blob/f67bb6ba30e1d4886c5248efef12df5a7b6d5173/pkg/shares/share_merging.go#L95

**Comment by evan-forbes** [comment]
I still think we will need to export these functions, but also expose a `ParseShares` api. Perhaps something like this.

```go
type ShareSet [][]byte

func ParseShares(shares [][]byte) []ShareSet
```

then we can parse depending on namespace

**Comment by rootulp** [comment]
1. Does this proposal imply an additional mechanism to convert from `[]ShareSet` => `coretypes.Messages`, `coretypes.Txs`, or `coretypes.EvidenceData`? 
2. Is the type `ShareSet` meant to describe that shares in this set are of a particular type. In other words, all share in this ShareSet are `coretypes.Txs`?

One alternative proposal that comes to mind:

```golang
func ParseShares(shares [][]byte) (coretypes.Messages, coretypes.Txs, coretypes.EvidenceData, error)
```

However this has the disadvantage that the return signature must be updated if/when we introduce more types.

**Comment by evan-forbes** [comment]
ParseShares should perform only the universal shares parsing logic, which means splitting up some set of data using only the namespace and the message start byte. 

Now we have some universal and purposefully ambiguous (potentially called a `ShareSet`) data that we can do something with. If we're celestia-node, and we just want to serve some complete set of shares, then we can do that, if we actually want to parse the shares into a data structure, then we can do that using the namespace and the version portion of the info byte.

**Comment by evan-forbes** [comment]
If we are wanting to parse the entire square into block data, then we already have the `Merge` function to do that.

**Comment by rootulp** [comment]
> ParseShares should perform only the universal shares parsing logic, which means splitting up some set of data using only the namespace and the message start byte.

Agreed. How about?

```golang
// ShareSequence represents a contiguous sequence of shares that are part of the
// same namespace and message. For compact shares, one share set exists per
// reserved namespace. For sparse shares, one share sequence exists per PFD.
type ShareSequence struct {
	ID     namespace.ID
	Shares []NamespacedShare
}

func ParseShares(shares [][]byte) []ShareSequence {
	// TODO
	return []ShareSequence{}
}
```

**Comment by evan-forbes** [comment]
I don't have any qualms with using word sequence over set, but why use NamespacedShares and namespace.ID? isn't one of our goals to get rid of NamespaceShares? #721 

In the past this has just felt like fighting the type system with middleware.

**Comment by rootulp** [comment]
> sequence over set

Sounds good. I opted for sequence to indicate that the order of the shares in this struct are important and I think set conveys lack of ordering.

> isn't one of our goals to get rid of NamespaceShares?

Sorry I forgot about #721 but just commented there. I'm not strongly opinionated on keeping vs removing the `NamespaceShares` type. If we remove, we can definitely remove `NamespaceShares` from the `ShareSequence` struct and use `[]Share` instead.

**Comment by rootulp** [comment]
Opted to remove the `NamespaceShares` type so I updated the proposed API in https://github.com/celestiaorg/celestia-app/issues/723#issuecomment-1252518254

The implementation of this API should split the provided shares into sequences based on the last bit in the info byte (a.k.a the message start indicator). Note: its possible to rename message start indicator to sequence start indicator given this API is public and "sequence start" is more precise given this applies to non-message shares.
