### ISSUE TITLE
Encode data length varint into first compact share

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#725]
## Context

https://github.com/celestiaorg/celestia-app/pull/660 introduces a `data length (varint 1 to 10 bytes)` to the first compact share in a reserved namespace where `data length (varint 1 to 10 bytes)` is the sum of lengths of all units in that namespace. 

For example, in the transaction namespace `data length` is the sum of all transaction lengths. Note this is distinct from the varint prefix to each individual transaction.

## Proposal

Modify the files below to account for the new varint. Note the varint is dependent on all data in the namespace so it is only determinable in the [`Export`](https://github.com/celestiaorg/celestia-app/blob/main/pkg/shares/split_compact_shares.go#L115-L116) function. However, it must be prefixed to the first share which will modify the subsequent share lengths and therefore force a rewrite of a subsequent shares.
- https://github.com/celestiaorg/celestia-app/blob/main/pkg/shares/parse_compact_shares.go
- https://github.com/celestiaorg/celestia-app/blob/main/pkg/shares/split_compact_shares.go

**Comment by evan-forbes** [comment]
yeah, I've ran into similar issues a lot with the non-interactive defaults. 

perhaps we can simply put the varint at the end instead of the beginning. This would allow us to continue to lazily write the compactShareSplitter, while also not having to fill in all of the reserved bytes afterwords.

**Comment by rootulp** [comment]
> perhaps we can create a second version to use in the info byte, and continue to not use a varint for compact shares

Is you proposal as follows?

**version 0**:
- compact share does not contain data length varint
- sparse share does contain data length varint

**version 1**: 
- compact share does contain data length varint
- sparse share does contain data length varint

where we implement **version 0** now and punt **version 1** to a later date?

**Comment by rootulp** [comment]
We want to implement this ASAP because it is share format breaking. Two clarifying notes:
1. The data length for the transaction reserved namespace includes the length all transactions, and the length delimiters prefix to each transaction. It does not include the universal prefix (namespace, info byte), or reserved byte in each share or the total length in the first share. 
2. We may be able to reserve N bytes in the first compact share for the data length varint and write it to in the export function without rewriting all subsequent shares if we overestimate the # of bytes needed for the data length.
