### ISSUE TITLE
specs: identify inconsistencies in implementation

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#730]
Discussed offline with @evan-forbes and we need to do a pass of existing specs, identify inconsistencies, fix them, and then migrate specs to individual repos.

## Inconsistencies
- https://github.com/celestiaorg/celestia-specs/issues/211
- https://github.com/celestiaorg/celestia-app/issues/728
- https://github.com/celestiaorg/celestia-app/issues/883

**Comment by rootulp** [comment]
Since we're going with **Option B** we no longer need this issue to identify inconsistencies.

**Comment by evan-forbes** [comment]
> Since we're going with Option B we no longer need this issue to identify inconsistencies.

? I think we might afaiu. I believe @adlerjohn will copy over the portions of the spec that are relevant to the app sometime soon, and then we can identify and fix inconsistencies.

> Identify and fix inconsistencies in the PRs that move specs

what about step 2?

**Comment by evan-forbes** [comment]
option C was only discussed in slack, but

- copy over the relevant specs
- identify and fix portions of the spec as we find them

we still get atomic PRs

**Comment by rootulp** [comment]
I should've included **Option C** above but yes I'm on-board because then we still get atomic PRs in individual repos to fix specs. Given **Option C**, we'll likely want a unique "Identify inconsistencies between specs and implementation" issue per repo where specs are migrated to.

**Comment by evan-forbes** [comment]
> I'm leaning towards option B since it's a forcing function. In the current repo, there aren't enough eyes paid to the specs since it's one step removed.

I'll still obvi defer to the author on this. Regardless of what we pick, we'll likely be doing C forever anywho

**Comment by adlerjohn** [comment]
Subsumbed by #650
