### ISSUE TITLE
Specify max block size and other parameters

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#731]
The specification must include all system-wide parameters. Client side parameters should also be specified in the sense that there should be a recommendation for defaults and where applicable it should specify which ranges do make sense.

ref: celestiaorg/celestia-app#732

**Comment by evan-forbes** [comment]
ref #183

**Comment by rootulp** [comment]
I think this is close-able via https://github.com/celestiaorg/celestia-app/pull/2416
