### ISSUE TITLE
Potentially increase share size

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#732]
We currently set the share size (rather arbitrarily) to 256 bytes. IMO this should be increased to maybe 1KB or more. Independent of what I think there must be a rationale document for the parameter choice explaining pros/cons and why we settled on whatever value.

**Comment by evan-forbes** [comment]
ref #711

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/850
