### ISSUE TITLE
Add reserved namespace ID for padding

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#733]
Taking some inspiration from [this post](https://ethresear.ch/t/suggested-format-for-shard-blob-header/9996)'s suggestion of

> Application ID 0 is interpreted as an empty entry and can be inserted anywhere by the block producers; it might be required for padding. Any application ID 0 fields should be ignored by clients.

We could use the application ID `0x0000000000000000` to denote any padding shares, then modify the rules of the NMT to simply ignore such shares when computing the min and max namespace IDs of a subtree. Note that the NMT [already has special rules to handle tail padding](https://github.com/celestiaorg/celestia-specs/blob/1b8c98d5f5e51e07acab02118dd8aa0c26f572fa/src/specs/data_structures.md#namespace-merkle-tree), though since tail padding has the maximum namespace ID it is guaranteed to be lexicographically sorted. These padding shares with a zero namespace ID would _not_ be.

The intuitions around why this should be possible is that there is no need to use the lexicographic-less-than binary relation specifically. The binary relation used for ordering namespace IDs does not necessarily need to be transitive or antisymmetric for its entire domain. As such, we can simply define a new one that ignores the zero namespace ID (i.e. is `true` if one or more of the inputs to the relation is the zero namespace ID).

The reason this would be useful is that currently padding between messages cannot be distinguished from messages. This means applications must potentially download a bunch of extra data that isn't useful for them. If padding has a distinct namespace ID, then it can be distinguished and simply not downloaded.

**Comment by evan-forbes** [comment]
see https://github.com/celestiaorg/celestia-app/issues/577#issuecomment-1227793901

**Comment by evan-forbes** [comment]
> Allowing for padding shares with non-zero namespace ID also enables for perverse things, such as storing (quite a bit of) data in the namespace ID that isn't paid for by anyone.

this is currently an implicit block validity rule as honest nodes will recompute the DAH and fill in empty shares with tail padding. It could still be done with a dishonest majority currently. Do we need a fraud proof for this? @adlerjohn

**Comment by adlerjohn** [comment]
Can you clarify the attack? I'm not understanding it.
