### ISSUE TITLE
specs: Document support for native multisigs

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#736]
Currently, we only support externally-owned accounts (EOAs), i.e. accounts that are controlled by a single secret key.

We would like to natively support multisigs, i.e. accounts that are controlled by more than one secret key, since this offers more security for users and validators (similar to 2FA). A downside of supporting native multisigs is increase in state transition complexity.

**Comment by evan-forbes** [comment]
while we inherit native [multisig functionality](https://github.com/cosmos/cosmos-sdk/tree/main/crypto/keys/multisig) in the sdk, we should still document the current status and functionality of this implementation.

**Comment by rootulp** [comment]
We can just link to Cosmos SDK docs on multisig

**Comment by liamsi** [comment]
Additionally, later adding a few links for different frontends would be cool. 

Dropping some links here:
- https://www.figment.io/resources/how-to-multi-sig-on-cosmos
- https://safe.serenity.aura.network/ or https://github.com/aura-nw/Aura-Safe
- https://github.com/informalsystems/multisig

By the time we actually document this there might be more or other options than the above.
