### ISSUE TITLE
Bound shares used for transactions

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#738]
The number of shares used for transactions, intermediate state roots, evidence, etc. should be bounded by some parameter. Otherwise, a malicious validator could create a maximum-size block filled with only transactions, and all full node would be required to fully download and process the block to compute the state.

**Comment by evan-forbes** [comment]
This was implemented when we added a max square size, and will be further expanded when we do #183

**Comment by evan-forbes** [comment]
I think I read this too quickly originally, we still need to implement this

**Comment by adlerjohn** [comment]
Hmmm. Fee markets don't necessarily have to be played out entirely in-protocol. Ultimately, it's up to the block producers how they calculate priority.

**Comment by evan-forbes** [comment]
This can be closed now that the square is deterministic
