### ISSUE TITLE
Define genesis block

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-app#739]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200392411185755/1200392755538284) by [Unito](https://www.unito.io)

**Comment by evan-forbes** [comment]
ref https://github.com/celestiaorg/celestia-app/issues/669

**Comment by liamsi** [comment]
Closing in favour of https://github.com/celestiaorg/celestia-app/issues/169 and https://github.com/celestiaorg/celestia-app/issues/669 as these are more specific and actionable. Genesis params + using the cosmos sdk sufficiently define the  genesis block. We can open a more specification-related issue that covers a bit more about which parts of the statemachine should be speced out / documented (including the genesis block).
