### ISSUE TITLE
specs: Precisely describe all block validity rules in `ProcessProposal`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#743]
A large portion of the responsibilities of the application is to define the block validity rules that are checked by validators during consensus (`ProcessProposal`), and enforced by creating fraud proofs for each rule. Things like namespaces must be ordered lexicographically, all messages must have a corresponding PFD transaction with a commitment that consists only of subtree roots, tail padding shares must consist of zeroed data, etc

We should define each of these rules in the specs.

**Comment by rootulp** [comment]
In addition to the rules specified above: all namespaces must be valid (i.e. use a supported namespace version and ID)
