### ISSUE TITLE
Remove temporary import hack for protobuf any

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#744]
## Context
- https://github.com/celestiaorg/celestia-app/issues/507#issue-1284883031
- https://github.com/celestiaorg/celestia-app/pull/554

## Problem
We want to remove the temporary import hack in https://github.com/celestiaorg/celestia-app/pull/742/files#diff-63113d53e02a4e334ffa1a1ba0c308329c7acd431153571a2c02ce9268af5816R28-R32

**Comment by evan-forbes** [comment]
is this still a thing @SweeXordious ?

**Comment by SweeXordious** [comment]
it's still here: https://github.com/celestiaorg/celestia-app/blob/b8168ac2a29e8dda5ac895b540f3ff328933b490/scripts/protocgen.sh#L26-L29
not sure if it's worth fixing tho

**Comment by rootulp** [comment]
I think this issue is worth fixing. Ideally we remove the lines that perform the hack b/c it looks like they modify the generated `query.pb.go` file and the top of that file says:

https://github.com/celestiaorg/celestia-app/blob/b75c7e3b80f91efae1164e8889bed9dd2c96414f/x/mint/types/query.pb.go#L1
