### ISSUE TITLE
Linter for error message strings

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#750]
## Problem
We currently don't have a linter that checks for the guidelines in https://github.com/golang/go/wiki/CodeReviewComments#error-strings

1. Error strings should not be capitalized
2. Error string should not end with punctuation

This leads to iteration cycles on nits in PR reviews.

## Proposal
We should investigate if there exists a linter that can enforce these checks. If there is, we should enable it to remove nits in PR reviews.

**Comment by rootulp** [comment]
[revive#error-strings](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings) seems well suited for this.

**Comment by rootulp** [comment]
It only works for trailing punctuation in error strings not capitalization of the first character: https://github.com/mgechev/revive/issues/733

Also it only works in error strings not panic strings.

**Comment by chavacava** [comment]
> It only works for trailing punctuation in error strings not capitalization of the first character: [mgechev/revive#733](https://github.com/mgechev/revive/issues/733)
> 
> Also it only works in error strings not panic strings.

revive's string literal analysis could be applied to any parameter of any function. Please check [the documentation](https://github.com/mgechev/revive/blob/feature/762/RULES_DESCRIPTIONS.md#string-format)
