### ISSUE TITLE
QGB add validator edit test cases

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#768]
If a validator edits their orchestrator/ethereum address, the state machine must react to that.
Currently:
- if they change their orchestrator address, then it's alright, nothing will change
- If they change their Ethereum address, they will be treated like a new validator and a new valset will be emitted and submitted to the target EVM chain.

We need to have tests for this.

**Comment by evan-forbes** [comment]
note from sync: we need to think about this more, specifically we need to know for certain that the validator set changes in the endblocker if this occurs and how that relates slashing

**Comment by SweeXordious** [comment]
> how that relates slashing

I guess in the case of editing the validator orch address, we will still be able to identify them as a malicious validator. Because, from the QGB perspective, we identify validators by their EVM addresses. 

However, if they edit their EVM address, it becomes harder to catch them.  So, a potential attack vector would be equivocating then changing the EVM address.

On the other hand, on the state machine, we keep track of previous valsets. Thus, we should be able to identify the malicious validator, even if they change their EVM address, via checking `valset.nonce = nonce - 1`, or even the ones before, until the last unbonding height, and slash them accordingly.

So, editing a validator shouldn't be an issue for slashing.

Let me know what you think.
