### ISSUE TITLE
Upgrade to Go 1.19

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#769]
## Problem

This repo currently uses Go 1.18 ([ref](https://github.com/celestiaorg/celestia-app/blob/d53f66b67946d20af5a24487c2f79da4ebb1b171/go.mod#L3)). Go [1.19](https://go.dev/blog/go1.19) was released.

The celestia-node repo has already upgraded to Go 1.19. For developers that are working across multiple Celestia repos there is a slight overhead involved in managing multiple Go versions locally. We can eliminate this overhead and get the benefits of Go 1.19 by upgrading. See [Go 1.19 Release Notes](https://go.dev/doc/go1.19) for more details.

## Proposal

Upgrade to Go 1.19

**Comment by evan-forbes** [comment]
before we upgrade, we should probably upgrade our fork of the cosmos-sdk, as upstream sdk has yet to upgrade. While upgrading will likely not cause any issues, there is a chance that upgrading causes a weird bug in some of the state machine logic that we import.

**Comment by rootulp** [comment]
I'm not opposed to holding off on upgrading celestia-app to Go 1.19 until cosmos/cosmos-sdk upgrades to Go 1.19

If we hold off, that also helps reduce the diff between celestiaorg/cosmos-sdk and cosmos/cosmos-sdk

**Comment by rootulp** [comment]
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.2 still uses Go 1.18 [here](https://github.com/cosmos/cosmos-sdk/blob/26786a07bb02d89a0e491120bfead03975c4ef5c/go.mod#L1)

**Comment by rootulp** [comment]
Update: Go [1.20[(https://go.dev/blog/go1.20) was released.

**Comment by smuu** [comment]
Go 1.18 is end of life and is not supported anymore. See [here](https://endoflife.date/go).
This is a security issue, and we should move to a supported Go version as soon as possible.

cosmos-sdk v0.46.11 uses Go 1.19. See [here](https://github.com/cosmos/cosmos-sdk/blob/v0.46.11/go.mod#L1).

Let's start updating cosmos-sdk from v0.46.7 to v0.46.11 to improve the security of our software :rocket:

**Comment by rootulp** [comment]
Blocked on https://github.com/celestiaorg/cosmos-sdk/issues/305

**Comment by rootulp** [comment]
Per in-person meeting, we're going to decouple from the Go version specified by cosmos-sdk so this is no longer blocked

cc: @evan-forbes @cmwaters
