### ISSUE TITLE
Manually test hardware wallet support

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#771]
As far as I know, we've never actually tested hardware wallet support, we've always just relied on the cosmos-sdk. We need to test hardware wallet support and better understand if there's anything we can do to support it. 

Ideally, hardware wallets would also be able to support signing PFDs, but that might be weird or not possible since we have to sign multiple versions of the protobuf encoded transactions.

**Comment by rootulp** [comment]
I verified that it is possible to add a key from Ledger (see https://github.com/celestiaorg/celestia-app/pull/2014#issuecomment-1646383354). I will test that it is possible to submit a PFB with a ledger. I expect it to work b/c now a user only needs to sign one transaction (no more multiple square sizes). Additionally the blob module has legacy Amino codec support which is needed for Ledger.

**Comment by liamsi** [comment]
I think, besides manual testing, we should also add a very minimalistic test in CI. IIRC, ledger also can be mocked away s.t. you can emulate a plugged in ledger in docker. (I think the manual tests are mainnet blocking, the CI tests are not though).

**Comment by rootulp** [comment]
> I think the manual tests are mainnet blocking, the CI tests are not though

Agreed. CI tests would help us catch regressions so I think we should add.

**Comment by rootulp** [comment]
It works! Steps documented in [this gist](https://gist.github.com/rootulp/0d16d76814a6169c38ac0e9cca86cc58) in case anyone wants to try it.
