### ISSUE TITLE
Use a consistent name for  `message_namespace_id`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#773]
## Problem

In the same proto definition file, we use two slightly different names for the same field

https://github.com/celestiaorg/celestia-app/blob/53d688eac87c4b5cc8798e822226f4589a59f346/proto/payment/tx.proto#L21

https://github.com/celestiaorg/celestia-app/blob/53d688eac87c4b5cc8798e822226f4589a59f346/proto/payment/tx.proto#L46

## Proposal

Use `message_namespace_id` in both locations

**Comment by nicoelzer** [comment]
Hey @rootulp would love to take care of it :)

**Comment by rootulp** [comment]
Sorry @nicoelzer this was done in #775 but we appreciate your interest in contributing! Are you interested in any other issues with the label https://github.com/celestiaorg/celestia-app/labels/good%20first%20issue ?
