### ISSUE TITLE
CompactShareSplitter `Count()` doesn't implement its doc comment

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#777]
## Problem
CompactShareSplitter claims to return the current number of shares that will be made if exporting but it actually returns one less than the number of shares that would be created if the pending share has any bytes written to it.

## Link

https://github.com/celestiaorg/celestia-app/blob/907da5f587cee1cbabae4549db7ada0df35e122b/pkg/shares/split_compact_shares.go#L156-L165

## Proposal

1. Fix either the doc comment or the implementation depending on which one is incorrect
3. [Optional but preferred] write unit tests for the behavior of this function

**Comment by evan-forbes** [comment]
Originally this was used for the mechanism to arrange a square during prepare proposal, although its no longer used for that. In that implementation, we needed the counter and the available bytes, but now we don't so we could change this function to follow what the comment says.
