### ISSUE TITLE
Stop forcing the last reserved byte to 0 for compact shares

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#779]
## Question

Why is reserved byte of last compact share forced to zero? This behavior seems undesirable if the last compact share contains a new transaction.

## Context
- https://github.com/celestiaorg/celestia-core/pull/637#issuecomment-1091461481
- https://github.com/celestiaorg/celestia-core/pull/637#issuecomment-1092278815
- https://github.com/celestiaorg/celestia-core/pull/637#issuecomment-1092585704

## Link

https://github.com/celestiaorg/celestia-app/blob/907da5f587cee1cbabae4549db7ada0df35e122b/pkg/shares/split_compact_shares.go#L141-L145

**Comment by evan-forbes** [comment]
I'm confused by this as well.

> As such, the reserved bytes should use the well-defined zero value to indicate a termination of the transaction stream.

@adlerjohn ?

perhaps we should rethink this now that we are adding the length delimiter to compact shares (formerly contiguous shares)

**Comment by rootulp** [comment]
Based on synchronous discussion, it seems like the last transaction share _shouldn't_ force the reserve byte to zero.
