### ISSUE TITLE
Use permalinks to any links to the specs (or otherwise)

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#780]
There are a few places in function docs where we references the specs with non-perma links to the specs, this was fixed in https://github.com/celestiaorg/celestia-app/pull/673/commits/185e1574c1f746d8bd2067f165170e1275f0d364 for the ADR, but not for the actual implementation.

https://github.com/celestiaorg/celestia-app/blob/dca08d75b26f3cf95efade58c2d0913e3d447243/pkg/shares/non_interactive_defaults.go#L6

**Comment by nicoelzer** [comment]
Hey @evan-forbes, would love to take care of it

**Comment by rootulp** [comment]
I think we can close this as won't do b/c we have markdown link checker which should fail if we break a link. At that time we can update the link to use a permalink.
