### ISSUE TITLE
specs: document namespaced padded shares between messages

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#784]
With the non-interactive defaults, we introduced padding between messages. Per the original specs [`Caveats`](https://github.com/celestiaorg/celestia-specs/blob/e59efd63a2165866584833e91e1cb8a6ed8c8203/src/rationale/message_block_layout.md#caveats) section of Message Layout Rational, these are described as 

> [Namespaced padded shares] have a value of zero and a namespace ID equal to the preceding message's. Since their value is known, they can be omitted from NMT proofs of all shares of a given namespace ID.

We need to make sure that we include these in the share encoding portion of the specs, and update with any implementation modifications.

tracked in #650 
blocked by (or should be updated after) #783

**Comment by rootulp** [comment]
Oops I created a duplicate issue https://github.com/celestiaorg/celestia-app/issues/1247
