### ISSUE TITLE
Implement API for parsing out of context shares with explicit tests for reserved bytes

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#802]
We don't actually use the reserved bytes for anything at the moment, and we don't have a way to use them to parse out of context shares. We should create an api that parses compact shares without the context of starting at the beginning of the namespace/message. We might even want to refactor the existing ParseTxs (or whatever compact shares) to use this implementation under the hood. Having this API should help us test reserved bytes to ensure their integrity.

**Comment by evan-forbes** [comment]
we will likely have to implement this in a different repo, because if optimint is to use it, then it cannot require including celestia-core/celestia-app/our fork of the sdk in the dependency tree.

**Comment by rootulp** [comment]
We can implement this API inside celestia-app (potentially the shares package). This issue includes corresponding unit tests.
