### ISSUE TITLE
Consolidate network testing code

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#829]
With the introduction of our own network tests, we should replace our usage of the old cosmos-sdk network tests for our integration tests. 

This will involve:
- [ ] Adding cli execution functionality for the new testnode
- [ ] Refactor existing integration tests to use new testnode

we should also expect a decrease in integration test times, since the new testnode can produce sub 1s blocks.

**Comment by rootulp** [comment]
Resolving this issue will likely also resolve https://github.com/celestiaorg/celestia-app/issues/574

**Comment by rahulghangas** [comment]
Picking this up

**Comment by evan-forbes** [comment]
in #1474, we are introducing the ibctesting framework for testing the ibc token filter. This seems like a good solution imo considering the amount of work we'd have to do replicate the same functionality. However, I'll ref it here to have a more exhaustive list

**Comment by rootulp** [comment]
I think the original post refers to the two test networks:
1. https://github.com/celestiaorg/celestia-app/blob/be3acf0a79849af0dafda5eecb0644cfc08c58b0/test/util/network/network.go#L27
2. https://github.com/celestiaorg/celestia-app/blob/be3acf0a79849af0dafda5eecb0644cfc08c58b0/test/util/testnode/full_node.go#L69

where 1 should be deleted and usage of 1 should be replaced with 2.
