### ISSUE TITLE
Test: verify that modifications to share sequence indicator in reserved namespace result in different DataHash

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#831]
### Problem
https://github.com/celestiaorg/celestia-app/issues/659 introduced an info byte that contains a sequence start indicator. The indicator must be `1` for the first share in a reserved namespace and `0` for continuation shares in that reserved namespace.

It is currently possible for a block proposer to construct a block with shares that don't conform to this rule (i.e. two share sequences in the transactions namespace).

### Proposal
Introduce a block validity rule that ensures all shares in a reserved namespace belong to one share sequence

**Comment by evan-forbes** [comment]
this sounds reasonable to me. If its a new block validity rule, then we should also consider if light clients gain anything by having a fraud proof for it.

**Comment by rootulp** [comment]
>  if light clients gain anything by having a fraud proof for it.

Good point. Currently light clients can't verify adherence to this rule without sampling all reserved namespace shares so it seems necessary to provide fraud proofs.

I think the priority of implementing such a fraud proof should consider if malicious block proposers have an incentive to propose a block that violates this rule. Since share parsing code assumes all shares in a reserved namespace belong to one share sequence, I could see a scenario where light clients fail to parse subsequent share sequences in a reserved namespace.

**Comment by rootulp** [comment]
Similar to https://github.com/celestiaorg/celestia-app/issues/830#issuecomment-1267381239 I don't think this can be a block validity rule because the info byte isn't in the block.

It can be a check in https://github.com/rootulp/celestia-app/blob/f1a671a9af56e9a0272f7b390376c293b098ff6b/pkg/shares/share_merging.go#L146 or https://github.com/rootulp/celestia-app/blob/f1a671a9af56e9a0272f7b390376c293b098ff6b/pkg/shares/share_merging.go#L16

**Comment by evan-forbes** [comment]
> I don't think this can be a block validity rule because the info byte isn't in the block. It can be a check in [ParseShares](https://github.com/rootulp/celestia-app/blob/f1a671a9af56e9a0272f7b390376c293b098ff6b/pkg/shares/share_merging.go#L146) or [Merge](https://github.com/rootulp/celestia-app/blob/f1a671a9af56e9a0272f7b390376c293b098ff6b/pkg/shares/share_merging.go#L16).

what's the status of this @rootulp ? what is needed to close this issue?
