### ISSUE TITLE
Un-export shares.Merge

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#840]
Where is this actually called? I found it being used in `func Merge(eds...)`, but I don't see this latter being used anywhere

_Originally posted by @SweeXordious in https://github.com/celestiaorg/celestia-app/pull/837#discussion_r987355330_

**Comment by evan-forbes** [comment]
Round-trip testing the ability to encode and decode block data is an important thing to test given that each piece of that process is vital to the network. While we might not need to decode an entire block in a single call, we will always need to decode each portion. 

Therefore, while we might be able to un-export this function and only use it as a testing helper func, but imo removing it entirely is not a good idea.

**Comment by evan-forbes** [comment]
is there an action item remaining here? cc @SweeXordious 

I'm fine with unexporting the function if that is deemed valuable

**Comment by SweeXordious** [comment]
> Round-trip testing the ability to encode and decode block data is an important thing to test given that each piece of that process is vital to the network

So, it is being used in tests, right? 

> is there an action item remaining here? 

Nope, the issue was just to know if this could be deleted, since we didn't see it being used anywhere.

**Comment by evan-forbes** [comment]
yes it is part of some of the tests for share encoding, can we close this issue then?

**Comment by SweeXordious** [comment]
Thanks for the help, I don't think any action is required for this
