### ISSUE TITLE
testnode: Perform checks on squareSize argument in `FillSquare` method

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#867]
per the TODO in the method description introduced in #866:
`TODO: perform checks (is a power of 2 and is > 2) on
// the passed squaresize arg`

**Comment by vidhanarya** [comment]
Working on this. @evan-forbes  What's the expected error here? Would a general error "Unsupported squareSize: <squareSize>" work or do we have any other suggestion?

**Comment by rootulp** [comment]
An error like "unsupported squareSize: %d" sounds reasonable to me. Thanks for working on this @vidhanarya
