### ISSUE TITLE
specs: increase number of reserved bytes to two

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#883]
## Problem
https://github.com/celestiaorg/celestia-app/pull/850 increased the share size and the number of reserved bytes from 1 to 2: https://github.com/celestiaorg/celestia-app/blob/45353941dc365630b42b096fb587044ab6fa36f2/pkg/appconsts/appconsts.go#L28-L30

so the specs are now inaccurate https://github.com/celestiaorg/celestia-app/blob/2cc65da4e2663b4ba94e8be7861fe81f2be5d09c/specs/src/specs/consensus.md?plain=1#L58

## Proposal
1. Update the share size constant from `256` to `512` bytes
1. Update the num reserved bytes constant from `1` to `2`
2. Update the diagrams and text in the Share section

**Comment by evan-forbes** [comment]
closed by #939
