### ISSUE TITLE
.github: remove stale.yml workflow 

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/celestia-app#885]
> can we also delete https://github.com/celestiaorg/celestia-app/blob/sevey/ci-release/.github/workflows/stale.yml?

I will onces https://github.com/celestiaorg/.github/pull/3 is merged.

_Originally posted by @MSevey in https://github.com/celestiaorg/celestia-app/issues/884#issuecomment-1284072615_

**Comment by MSevey** [comment]
This should be coupled into the housekeeping workflow updates https://github.com/celestiaorg/.github/issues/11

**Comment by rootulp** [comment]
Note we still have a stale workflow: https://github.com/celestiaorg/celestia-app/blob/main/.github/workflows/stale.yml

I suppose we could migrate to https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_stale.yml but I don't see a strong reason to do so so closing as won't do.
