### ISSUE TITLE
Proposal: Require that messages in the same namespace be ordered by fee

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#889]
Currently, we do not require any specific ordering for messages in the same namespace. Adding a block validity rule that would require that messages with a higher fee be ordered first would have at least two potentially important consequences:
- allow for rollup block producers to mitigate the damage of a [woods attack](https://forum.celestia.org/t/woods-attack-on-celestia/59)
- allow for an auction based leader selection (assuming no censorship from the celestia validator)

The implementation itself would be fairly easy to implement, as we simply add a sorting step during `PrepareProposal` and an equivalent sorting check during `ProcessProposal`, for namespaces with more than one message.

**Comment by rootulp** [comment]
There is a distinction between making "ordering messages by fee" a validity rule and making it a default. The team has alignment on making this rule a default but not a validity rule.

**Comment by evan-forbes** [comment]
> Are there other reasons we may want this validity rule?

I'm not sure, as this was just written down after some slack conversion. 

to summarize the above/sync discussion, the important thing is that this would leak MEV from the rollup to the base layer, which is something that we don't want.

I feel comfortable closing this issue
