### ISSUE TITLE
Proposal: Implement the option to exclude the message in a PFD if the message is not first in a namespace

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#891]
It was proposed to add an extra field in PFDs that would indicate to the block producer to exclude the message that is paid for if the message is not the first one in a namespace.

Along with the implementation of #889, this feature would allow rollup leader selection mechanisms that rely on auctions.

Its important to note here that, afaiu, we still need to charge some gas for this to prevent spamming the network, but we obviously do not want to charge the same amount of gas as a PFD that has a message included. Also, message inclusion proofs would have to also check this new boolean value.

**Comment by rootulp** [comment]
Synchronous discussion: 
- this makes fraud proofs more complicated
- wait for more teams to request this feature

**Comment by evan-forbes** [comment]
I feel comfortable closing this issue after the sync discussion we had where we elaborated on how this proposal would leak MEV to the base layer
