### ISSUE TITLE
node server does not suppot linux-x86?

### ISSUE THREAD

**Issue by signalxu** [celestiaorg/celestia-app#906]
### Summary of Bug

there is a mistake during installing celestia-app 

### Version

version:v 0.8.0
server:aws linux-x86

### Steps to Reproduce

 Installing celestia-appd
# github.com/ethereum/go-ethereum/crypto/secp256k1
In file included from ././libsecp256k1/src/util.h:14,
                 from ././libsecp256k1/src/secp256k1.c:9,
                 from ../go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.17/crypto/secp256
k1/secp256.go:29:
/usr/include/stdlib.h:25:10: fatal error: bits/libc-header-start.h: No such file or directo
ry
   25 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
# github.com/ethereum/go-ethereum/rpc
../go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.17/rpc/constants_unix.go:23:10: fatal e
rror: sys/un.h: No such file or directory
   23 | #include <sys/un.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:40: install] Error 2

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mindstyle85** [comment]
Hello!

this to me looks like you dont have the appropriate GO version installed by the looks of it, and also make sure you installed all the library packages needed (its all in the docs)

**Comment by rootulp** [comment]
Thanks for creating an issue @signalxu ! Just clarifying, have you performed the [install dependencies](https://docs.celestia.org/developers/environment#install-dependencies) step prior to installing celestia-app? If yes, it's possible there are more dependencies we need to add to this prerequisite step.

```error
25 | #include <bits/libc-header-start.h>
| ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Based on https://github.com/sirfz/tesserocr/issues/130#issuecomment-403857751 it is possible `sudo apt-get install gcc-multilib g++-multilib` may resolve
