### ISSUE TITLE
TestFuzzPrepareProcessProposal: makeslice: len out of range

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#913]
### Summary of Bug

We're observing instances where a fuzz test has uncovered a bug. See CI run: https://github.com/celestiaorg/celestia-app/actions/runs/3318414871/jobs/5482354309#step:6:149

### Version

https://github.com/celestiaorg/celestia-app/commit/26eeca4d35588991ccec7dcaf2defd4d63854e82 and `main`

### Steps to Reproduce

@evan-forbes ran fuzz test locally long enough to reproduce the error: https://gist.github.com/rootulp/86c4a7a80e95f64bafdd4f968c0f131a

**Comment by evan-forbes** [comment]
Hopefully we can fix this when we refactor/remove estimation to use square size independent commitments

cc @rootulp
