### ISSUE TITLE
celestia-app start error

### ISSUE THREAD

**Issue by signalxu** [celestiaorg/celestia-app#914]
### Summary of Bug

systemctl start celestia-appd

### Version

version:latest
server:ubuntu 20.04

### Steps to Reproduce

Oct 25 07:48:35 ip-172-31-12-196 systemd[1]: celestia-appd.service: Failed with result 'exit-code'.
Oct 25 07:48:38 ip-172-31-12-196 systemd[1]: celestia-appd.service: Scheduled restart job, restart counter is at 125.
Oct 25 07:48:38 ip-172-31-12-196 systemd[1]: Stopped celestia-appd Cosmos daemon.
Oct 25 07:48:38 ip-172-31-12-196 systemd[1]: Started celestia-appd Cosmos daemon.
Oct 25 07:48:39 ip-172-31-12-196 celestia-appd[26974]: 7:48AM INF starting node with ABCI Tendermint in-process
Oct 25 07:48:39 ip-172-31-12-196 celestia-appd[26974]: Error: error reading GenesisDoc at /home/ubuntu/.celestia-app/config/genesis.json: block.TimeIotaMs must be greater than 0. Got 0
Oct 25 07:48:39 ip-172-31-12-196 systemd[1]: celestia-appd.service: Main process exited, code=exited, status=1/FAILURE
Oct 25 07:48:39 ip-172-31-12-196 systemd[1]: celestia-appd.service: Failed with result 'exit-code'.
Oct 25 07:48:42 ip-172-31-12-196 systemd[1]: celestia-appd.service: Scheduled restart job, restart counter is at 126.
Oct 25 07:48:42 ip-172-31-12-196 systemd[1]: Stopped celestia-appd Cosmos daemon.
Oct 25 07:48:42 ip-172-31-12-196 systemd[1]: Started celestia-appd Cosmos daemon.
Oct 25 07:48:42 ip-172-31-12-196 celestia-appd[26982]: 7:48AM INF starting node with ABCI Tendermint in-process
Oct 25 07:48:42 ip-172-31-12-196 celestia-appd[26982]: Error: error reading GenesisDoc at /home/ubuntu/.celestia-app/config/genesis.json: block.TimeIotaMs must be greater than 0. Got 0
Oct 25 07:48:42 ip-172-31-12-196 systemd[1]: celestia-appd.service: Main process exited, code=exited, status=1/FAILURE
Oct 25 07:48:42 ip-172-31-12-196 systemd[1]: celestia-appd.service: Failed with result 'exit-code'.

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Thanks for creating an issue @signalxu . Can you please include **Steps to Reproduce** in addition to the error pasted above? A few questions to help populate that section:
1. Where was your `genesis.json` sourced from? 
2. Are you following the steps at: https://docs.celestia.org/developers/instantiate-testnet/#creating-the-genesis-json-file or are you trying to join an existing testnet like Mamaki per the steps at: https://docs.celestia.org/nodes/mamaki-testnet/#setup-p2p-network?

**Comment by mindstyle85** [comment]
@signalxu i think you are using celestia-appd version 0.8.0 which doesnt work for Mamaki, please checkout and build the v0.6.0 version, then it should work

**Comment by signalxu** [comment]
> @signalxu i think you are using celestia-appd version 0.8.0 which doesnt work for Mamaki, please checkout and build the v0.6.0 version, then it should work

ok thx

**Comment by 1991wangliang** [comment]
```
cd $HOME
rm -rf celestia-app
git clone https://github.com/celestiaorg/celestia-app.git
cd celestia-app/
APP_VERSION=v0.6.0
git checkout tags/$APP_VERSION -b $APP_VERSION
make install
```
