### ISSUE TITLE
Replace Max/MinSquareSize params with Max/MinBlockSize

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#925]
Using the square size as a param certainly works, but as discussed synchronously, we should use the block size instead. The reasoning was that using a specific blocksize is more precise, and accounts for share size as well. For example, we could have any value between 4MB and 8MB instead of only 8MB. We can enforce this value by calculating the number of non-tail padding shares in the square, instead of only relying on square size max of 128.

**Comment by rootulp** [comment]
Note: this proposal is for parameters to the payment module

**Comment by rootulp** [comment]
IIUC this parameter doesn't constrain the minimum or maximum size of a block because the block includes information that won't be bound by parameters to the payment module. For example, the block can contain 1MB of evidence which the payment module is unaware of. I think these parameters specifically constrain the amount of non tail padding shares in the data square.

**Comment by evan-forbes** [comment]
> IIUC this parameter doesn't constrain the minimum or maximum size of a block because the block includes information that won't be bound by parameters to the payment module. For example, the block can contain 1MB of evidence which the payment module is unaware of.

just to clarify, this is entirely dependent on #950. if we keep evidence in the block data, then this param would be aware of that data. 

I don't have any strong opinions on names

**Comment by rootulp** [comment]
Thanks for commenting.

> if we keep evidence in the block data, then this param would be aware of that data.

Then these params are no longer strictly applicable to the payment module. If we want to constraint the minimum / maximum size of [`blockData`](https://github.com/celestiaorg/celestia-app/blob/6f3b3ae437b2a70d72ff6be2741abb8b5378caa0/app/prepare_proposal.go#L44-L49) perhaps these params should exist outside the payment module (i.e. `appconsts.go`)? There may be a rationale to including them as payment module params that I'm not considering (potentially ability to upgrade via governance).

**Comment by evan-forbes** [comment]
it will have to be in _a_ module, but I like your point that its not payment (now blob) module specific. Due to the cosmos-sdk tho, having another module would add a lot of code. So I guess the question is if we want to have an entire separate module dedicated to this new param. 

I don't have any strong opinions on names

**Comment by rootulp** [comment]
I may be too pedantic on the name but if these params don't constrain the entire [Block](https://github.com/celestiaorg/celestia-core/blob/b7a7c1ab37fde91f9687b5c1c4766119e7b71db5/types/block.go#L45) but do constrain the Block's [Data](https://github.com/celestiaorg/celestia-core/blob/b7a7c1ab37fde91f9687b5c1c4766119e7b71db5/types/block.go#L1008): proposal to use `MaxBlockDataSize` / `MinBlockDataSize`.

Agreed with putting them in blob (f.k.a. payment) module to reduce boilerplate.

**Comment by evan-forbes** [comment]
Updating from a sync discussion, we need to ensure that there is still a manual size limit, ie the governance cannot increase the size to 2000x2000

**Comment by evan-forbes** [comment]
not planned, as we are using the standard block size param in tendermint instead
