### ISSUE TITLE
When delegate to a validator steps throws an error with key not found

### ISSUE THREAD

**Issue by 1991wangliang** [celestiaorg/celestia-app#933]
### Summary of Bug

execute commands:
```
root@ubuntu:~/.celestia-app/keyring-test# celestia-appd keys show $VALIDATOR_WALLET --bech val -a
celestiavaloper1cuaaqlv649zljtqfnlhp97djl20axwe9hkfrd3
root@ubuntu:~/.celestia-app/keyring-test# celestia-appd tx staking delegate celestiavaloper1cuaaqlv649zljtqfnlhp97djl20axwe9hkfrd3 1000000utia --from=$VALIDATOR_WALLET --chain-id=mamaki
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account celestia1cuaaqlv649zljtqfnlhp97djl20axwe9jft6mh not found: key not found
root@ubuntu:~/.celestia-app/keyring-test# ll
total 16
drwx------ 2 root root 4096 Oct 29 11:37 ./
drwxr-xr-x 5 root root 4096 Oct 29 11:29 ../
-rw------- 1 root root  540 Oct 29 11:28 c73bd07d9aa945f92c099fee12f9b2fa9fd33b25.address
-rw------- 1 root root  766 Oct 29 11:28 validator.info
root@ubuntu:~/.celestia-app/keyring-test#
```

### Version

0.6.0

### Steps to Reproduce

Delegate to a validator
https://docs.celestia.org/nodes/mamaki-testnet#delegate-to-a-validator

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by 1991wangliang** [comment]
oh, that my address  account need had amount. but why error was key not found ?

**Comment by mindstyle85** [comment]
Hello! There is no bug here, your celestia-appd node has to run and be in sync in order to be able to delegate. Alternatively you can use the —node flag and choose one of the RPC endpoints mentioned in the doc

**Comment by 1991wangliang** [comment]
my local server was running. that question was error message is key not found .i try celestia-faucet get some amount then to run was success.so if account was no amount that can't to execute ?

**Comment by mindstyle85** [comment]
Check on the explorer if it does and check if your node is in sync, it has to be at around 272k height or so

**Comment by 1991wangliang** [comment]
i was solved that question. thanks
