### ISSUE TITLE
Add support for arm64 vps

### ISSUE THREAD

**Issue by gsweeh** [celestiaorg/celestia-app#938]
### Summary

Add support for arm64 vps

### Problem Definition

Add support for arm64 vps it helpfull to us to stared with node

### Proposal

Add support for arm64 vps it helpfull to us to stared with node

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
mind adding more details @gsweeh? what would be needed to finish this issue?

**Comment by rootulp** [comment]
Now celestia-app creates prebuilt binaries for arm64. See the assets section under latest release: https://github.com/celestiaorg/celestia-app/releases/tag/v1.6.0 

So I'm pretty confident this does compile on arm64. Please re-open if there's something we're missing.
