### ISSUE TITLE
Reach final decision on ADR 008

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#941]
## Description

We created a feature branch: `feat/square-size-independent-commitments` because we haven't reach a final decision on whether to adopt ADR 008. 

## Proposal
If we choose to adopt it, let's:
1. merge the feature branch to `main`
2. update the ADR to reflect that it was implemented

If we reject it, let's:
1. delete the feature branch
2. update the ADR to reflect that it was rejected / closed

**Comment by musalbas** [comment]
Before ADR 008 is implemented, ADR 008 needs an analysis of message inclusion proofs (for super light clients that only download the data root, and light clients), pre- vs post-ADR 008.

For example, ADR 008 proposes to change the non-interactive defaults (https://github.com/nashqueue/celestia-app/blob/518d7241f04f0a36358f8eab0f8da1d0744e541d/docs/architecture/adr-008-square-size-independent-message-commitments.md#positive-core-app-changes), but I do not believe that this is feasible without increasing the size of message inclusion proofs to O(sqrt(n)).

**Comment by rootulp** [comment]
Fair enough, as you pointed out message inclusion proofs do increase if we adopt the new non-interactive default rules. @nashqueue has prepared an analysis of message inclusion proof sizes that will be added to the ADR 008 (or a new ADR).

If the point of debate is strictly for old vs new non-interactive defaults and there are no objections to square-size independent commitments, then we can:
1. mark this issue as resolved
2. merge the feature branch `feat/square-size-independent-commitments` to `main`
3. continue the discussion on ADR 008 regarding old vs new non-interactive defaults which we haven't implemented yet

**Comment by musalbas** [comment]
It might however be better if we make a decision about the non-interactive default rules first, so that we don't have to change the how the commitment works twice in `main`

**Comment by rootulp** [comment]
If I understand correctly, square size independent commitments are a prerequisite to new non-interactive default rules but they aren't strictly coupled. We can adopt square size independent commitments without adopting new non-interactive default rules.

Is there a reason you think we'd have to revert how the commitment is generated?

**Comment by musalbas** [comment]
I'm not talking about reverting how the commitment is generated - I'm talking about merging ADR 008, and changing the non-interactive defaults in two steps. Both of these steps will impact how rollups should expect to verify inclusion of their data in Celestia, and thus each step involves a breaking change to rollups, so it may be better to do it one step to have only one breaking change.

**Comment by musalbas** [comment]
Though I suppose technically rollups can use ADR 008 without any changes in core, so maybe only changing the non-interactive default is a breaking change for rollups.

**Comment by rootulp** [comment]
> Both of these steps will impact how rollups should expect to verify inclusion of their data in Celestia, and thus each step involves a breaking change to rollups

Do we expect rollups to verify the inclusion of their message in a block via [`TxInclusion`](https://github.com/celestiaorg/celestia-app/blob/3473000a9ff04fccfbba83929711fe11643b782c/pkg/prove/proof.go#L15-L19)? If so, I don't see why adopting ADR 008 is a user facing breaking change assuming `TxInclusion` works pre/post ADR adoption.

> so that we don't have to change the how the commitment works twice in `main`

I still don't understand why the commitment would need to be changed twice in `main`. The implementation for square size independent commitments will change the commitment once. New non-interactive default rules won't change the commitment. So the commitment would only change twice on `main` if we had to revert the square size independent commitment implementation. If we don't expect to revert the decision on square size independent commitments then I don't see why we want to hold off on merging the feature branch.

>  so it may be better to do it one step to have only one breaking change.

We can hold off on cutting a release until implementation for new non-interactive default rules is implemented to minimize the number of breaking releases.

**Comment by musalbas** [comment]
>Do we expect rollups to verify the inclusion of their message in a block via [TxInclusion](https://github.com/celestiaorg/celestia-app/blob/3473000a9ff04fccfbba83929711fe11643b782c/pkg/prove/proof.go#L15-L19)? If so, I don't see why adopting ADR 008 is a user facing breaking change assuming TxInclusion works pre/post ADR adoption.

Just because the API abstracted doesn't mean it's not a breaking change; the rollup still has to update its dependencies, and it would break verification of historical rollup blocks, etc.

**Comment by rootulp** [comment]
Based on the syncronous discussion we had in core-app retro, this issue seems resolvable. We agreed to merge the feature branch as-is.

`TxInclusion` doesn't appear to use the message share commitment so I'm not convinced that the feature branchis a breaking change to `TxInclusion`. The feature branch is a breaking change regardless so we can still hold-off on cutting a celestia-app release if minimizing breaking releases is desired.

**Comment by rootulp** [comment]
Will mark as closed when feature branch merges.
