### ISSUE TITLE
Reduce complexity and document retrieval of malleated transacions

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#942]
Currently, there are three different hashes for a malleated tx:
- The original hash of the tx that the user submitted
- The hash of the malleated tx itself (a `MsgPayForData`)
- The hash of the wrapped malleated tx that is in the block

This is very confusing and has not been documented well enough, particularly what hash is used when. We need to formalize and document when each hash is used, and see if we can refactor tx indexing to simplify this further.

**Comment by evan-forbes** [comment]
blocked by implementing #835

**Comment by rootulp** [comment]
Potentially obsolete if we can remove transaction hash tracking from celestia-core

**Comment by evan-forbes** [comment]
we've since removed malleation as mentioned by Rootul, so closing
