### ISSUE TITLE
Error after run app - block.TimeIotaMs must be greater than 0

### ISSUE THREAD

**Issue by kamiloski88** [celestiaorg/celestia-app#943]
### Summary of Bug

Error after run app - Error: error reading GenesisDoc at /home/celestia/.celestia-app/config/genesis.json: block.TimeIotaMs must be greater than 0. Got 0. 
on verision 0.9.0. **After run app on 0.6.0 works fine**

### Version

0.9.0

### Steps to Reproduce

Pull v 0.9.0 run app

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
@kamiloski88 thanks for bringing this up. While this is not documented well, this is actually expected behavior. In order to run v0.9.0 on a network, it must have the appropriate consensus parameters. This means that we will not be able to until we hardfork, although local devnets work as expected.

If this makes sense, do you mind closing this issue? :slightly_smiling_face:

**Comment by kamiloski88** [comment]
Thanks for fast reply:) ok, I’m understand but I have question. I want to run validator on testnet, so should I run on 0.6.0 or hold my horses and wait for some updates?

> @kamiloski88 thanks for bringing this up. While this is not documented well, this is actually expected behavior. In order to run v0.9.0 on a network, it must have the appropriate consensus parameters. This means that we will not be able to until we hardfork, although local devnets work as expected.
> 
> Like other blockchains, the latest versions of code will rarely work on an existing network. We should (and will!) do a better job of communicating this in future.
> 
> If this makes sense, do you mind closing this issue? 🙂

Thanks for fast reply:) ok, I’m understand but I have question. I want to run validator on testnet, so should I run on 0.6.0 or hold my horses and wait for some updates?

**Comment by evan-forbes** [comment]
Yes, currently we need to run v0.6.0 on mamaki

**Comment by kamiloski88** [comment]
Ok thanks:)

**Comment by kamiloski88** [comment]
Thanks
