### ISSUE TITLE
Extract `GasPerMsgByte` as a parameter to payment module

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#949]
We should add a parameter to the `x/payment` module that describes the `GasPerMsgByte`. https://github.com/celestiaorg/celestia-app/pull/893 may be used for inspiration on how to implement parameters to the payment module. We likely also want to update the `x/payment/README.md` to describe this parameter.

**Comment by evan-forbes** [comment]
does #965 close this? do we have any other work needed to complete this task @rahulghangas?

**Comment by rahulghangas** [comment]
I think the original issue asks for the readme to be updated as well
The implementation side is closed by #965

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/965
