### ISSUE TITLE
Consider renaming `x/payment`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#961]
## Context

During an onsite meeting, @liamsi proposed renaming the `x/payment` module to something else prior to the v1.0.0 release because this type of rename would be a breaking change. We should align on if we want a rename and what the new name should be.

## Proposals

- `x/da`
- `x/blob`

**Comment by evan-forbes** [comment]
the `/da` module will presumably be for something that would check for data availability (ie via vote extensions and read only IBC) imo, so I'm in favor of blob

**Comment by evan-forbes** [comment]
whatever we choose, we should do soon, as renaming a module is super breaking and it will be easiest to do so before hardforking mocha
