### ISSUE TITLE
Consider renaming `PayForData` => `PayForBlob`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#962]
## Context

See https://github.com/celestiaorg/celestia-app/issues/269

During an onsite meeting, we discussed renaming `PayForData` (commonly referred to as PFD) to something else because people still use "message" when describing the contents of a `PayForData`. It seems like data was chosen to replace message to disambiguate a roll-up block's data from a Cosmos SDK [message](https://docs.cosmos.network/main/building-modules/messages-and-queries.html#messages). However, people still use the term "message" when describing PFDs because data is vague. 

## Proposals
- `PayForBlob` (see [Slack vote](https://celestia-team.slack.com/archives/C02PFFCGMNW/p1667473915363899))
- `PayForPayload`

**Comment by evan-forbes** [comment]
I think @rootulp also suggested `MsgSubmitBlob` which I'm in favor of

**Comment by rootulp** [comment]
IFF the module was renamed `blob` then instead of the current CLI command
```shell
celestia-appd tx payment payForData [hexNamespace] [hexMessage] [flags]
```
I propose something like

```shell
celestia-appd tx blob submit [hexNamespace] [hexMessage] [flags]
```

I'm currently unopinionated on the struct names.

**Comment by evan-forbes** [comment]
we could change the cli name, but the standard for the sdk is to name it directly after the sdk.Msg type. Fortunately, it is unlikely that people will use the cli to submit PFBs beyond just testing or trying out the functionality
