### ISSUE TITLE
Update permalinks and ADRs to new code

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#991]
we're in a chicken and egg situation because the permalink https://github.com/celestiaorg/celestia-app/blob/6f3b3ae437b2a70d72ff6be2741abb8b5378caa0/x/payment/types/tx.pb.go#L32-L40 still points to the old name. Super minor but after this PR merges, we can update the permalinks to reference the lines of code with the new name

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/978#discussion_r1016807260_

we should update the permalinks after we merge the name changes to blob instead of payment/pay

**Comment by rootulp** [comment]
The instance cited in the comment was resolved in https://github.com/celestiaorg/celestia-app/commit/f67acced1d0de28c6d8d0b583390dcdf70ba91d5. Some of the other permalinks in ADR 008 link to old code but those references are still valid (i.e. `CreateCommitment`)
