### ISSUE TITLE
Move default values for blob params to appconsts module

### ISSUE THREAD

**Issue by rahulghangas** [celestiaorg/celestia-app#993]
### Summary

Default values for blob params are currently hardcoded and should be moved to `appconsts` module

**Comment by rootulp** [comment]
Naive question but why do we want to define these default parameters in the `appconsts` module if the associated parameter is configured in the `blob` module?

I assume the end-goal is that the defaults are only used to set the initial value of the parameter in the blob module and after that the parameters are subject to modification through governance. The value that should be used throughout the application is therefore the parameter in the blob module not the default in `appconsts`.

**Comment by rahulghangas** [comment]
This was done because I wanted to do the changes incrementally (since it's going to break app in a few different places). PR resolving #1032 will replace all usages of default values to `paramstore` reads

**Comment by evan-forbes** [comment]
I'm fine with moving these, but I also definitely see the reasoning behind keeping them in the blob module since that's where we're planning on keeping these params
