### ISSUE TITLE
refactor: VerifySig and add unit tests

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#996]
[non-blocking] If I understand this correctly,  you could also write it like so:
```suggestion
	if err != nil {
		valid = false
	}

	return valid, err
```

Which begs the question, shouldn't that be handled by `VerifySig`? It feels like a bug if `VerifySig` is returning `valid == true` with `err != nil`.  So we should probably just verify that the unit test for `VerifySig` handles that and then this can just be:
```suggestion
	return VerifySig(signerData, txConfig, pfbTx)
```

_Originally posted by @MSevey in https://github.com/celestiaorg/celestia-app/pull/984#discussion_r1019618934_

**Comment by evan-forbes** [comment]
imo, after implementing #951, we should just delete the verify sig code as we will no longer be doing any weird frankenstein sdk.Tx malleation.
