### ISSUE TITLE
Verify gas consumption of PFD

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#997]
### Summary of Bug

>  having ran a few rollmint chains submitting PFDs and submitting PFDs manually, I've never actually seen my balance change

Source @jcstein 

### Version

Arabica

### Steps to Reproduce

1. Submit a PFD
2. Verify that balance does / does not change

### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
I couldn't easily acquire Arabica tokens but I was able to repro on a local devnet

```shell
$ celestia-appd query account celestia1g5n0ma5k3sqswfdge4k32525gdpcmcr8gqvh6z
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "0"
address: celestia1g5n0ma5k3sqswfdge4k32525gdpcmcr8gqvh6z
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: A5GDXc2/suE5N2biyVplRXg3vYzizF6+lCdyS0PNI1RM
sequence: "1"

$ celestia-appd query bank balances celestia1g5n0ma5k3sqswfdge4k32525gdpcmcr8gqvh6z
balances:
- amount: "999995000000000"
  denom: utia
pagination:
  next_key: null
  total: "0"

$ celestia-appd tx blob payForData 0101010101010101 0101010101010101 --from validator --keyring-backend test
// trimmed output
```

wait a few blocks

```shell
$ celestia-appd query account celestia1g5n0ma5k3sqswfdge4k32525gdpcmcr8gqvh6z
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "0"
address: celestia1g5n0ma5k3sqswfdge4k32525gdpcmcr8gqvh6z
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: A5GDXc2/suE5N2biyVplRXg3vYzizF6+lCdyS0PNI1RM
sequence: "2"

$ celestia-appd query bank balances celestia1g5n0ma5k3sqswfdge4k32525gdpcmcr8gqvh6z
balances:
- amount: "999995000000000"
  denom: utia
pagination:
  next_key: null
  total: "0"
```

**Comment by evan-forbes** [comment]
I think the fee is set to zero by default, and unless the node has changed their app.toml config, then fee free txs will be allowed to be submitted and included in a block. 

This could still be a bug tho, we should verify after specifying a fee

**Comment by rootulp** [comment]
Cosmos SDK docs on [Main Gas Meter](https://docs.cosmos.network/main/basics/gas-fees#main-gas-meter):

> Gas consumption can be done manually, generally by the module developer in the [BeginBlocker, EndBlocker](https://docs.cosmos.network/main/building-modules/beginblock-endblock) or [Msg service](https://docs.cosmos.network/main/building-modules/msg-services), but most of the time it is done automatically whenever there is a read or write to the store. This automatic gas consumption logic is implemented in a special store called [GasKv](https://docs.cosmos.network/main/core/store#gaskv-store).

Even though keeper isn't explicitly listed as a location to do gas consumption, it seems possible per [x/authz/keeper/keeper.go](https://github.com/cosmos/cosmos-sdk/blob/4ff588d08483fcdc41e896bcd6f2c15a6c716d32/x/authz/keeper/keeper.go#L356). If keeper isn't a valid location to do gas consumption, I think we could use the Msg service.

**Comment by evan-forbes** [comment]
> Even though keeper isn't explicitly listed as a location to do gas consumption, it seems possible

I'm confused, are we not consuming gas in the same way [here](https://github.com/celestiaorg/celestia-app/blob/8b9c4c9d13fe0ccb6ea936cc26dee3f52b6f6129/x/blob/keeper/keeper.go#L62)?

**Comment by rootulp** [comment]
> I'm confused, are we not consuming gas in the same way [here](https://github.com/celestiaorg/celestia-app/blob/8b9c4c9d13fe0ccb6ea936cc26dee3f52b6f6129/x/blob/keeper/keeper.go#L62)?

Right we do. I was under the impression that this line wasn't working as expected but it does appear working and valid so we don't need to change it.

**Comment by evan-forbes** [comment]
phew, ok I was panicking there a bit :sweat_smile: 

we have 
> Undecided
default minimum fee in app.toml

https://github.com/celestiaorg/celestia-app/issues/669#issuecomment-1299045728 fwiw, which would require some fee by default. We will definitely have some value there other than zero, but not sure what yet. It kinda depends on the token price

**Comment by rootulp** [comment]
> phew, ok I was panicking there a bit 😅

Same

> We will definitely have some value there other than zero

Thanks for the link. Agreed on some non-zero value. Out of curiosity, where would we define something like:

```
minimum-gas-prices = "1utia"
```

such that it ends up in the `app.toml`?

**Comment by evan-forbes** [comment]
we should just be able to change this iirc
https://github.com/celestiaorg/celestia-app/blob/18c9caba25b878f0d924f555ffe216de7172fedc/cmd/celestia-appd/cmd/root.go#L111

**Comment by evan-forbes** [comment]
can we close this issue?

**Comment by jcstein** [comment]
thank you for clearing this up 🙏
